"""CID 3617 ValveFlows
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


PULMONARY_VALVE_FLOW = CodedConcept(
    value="R-0035D",
    meaning="Pulmonary Valve Flow",
    scheme_designator="SRT"
)

MITRAL_VALVE_FLOW = CodedConcept(
    value="R-0032D",
    meaning="Mitral Valve Flow",
    scheme_designator="SRT"
)

DERIVED_FLOW_NONVALVE = CodedConcept(
    value="R-00394",
    meaning="Derived Flow, Non-Valve",
    scheme_designator="SRT"
)

AORTIC_VALVE_FLOW = CodedConcept(
    value="R-002D3",
    meaning="Aortic Valve Flow",
    scheme_designator="SRT"
)

TRICUSPID_VALVE_FLOW = CodedConcept(
    value="R-00385",
    meaning="Tricuspid Valve Flow",
    scheme_designator="SRT"
)

