"""CID 12246 CardiacUltrasoundIndicationforStudy
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


CORONARY_ARTERY_DISEASE = CodedConcept(
    value="D3-13040",
    meaning="Coronary Artery Disease",
    scheme_designator="SRT"
)

DYSPNEA = CodedConcept(
    value="F-201B3",
    meaning="Dyspnea",
    scheme_designator="SRT"
)

HEMOPTYSIS = CodedConcept(
    value="F-24210",
    meaning="Hemoptysis",
    scheme_designator="SRT"
)

ANGINA_PECTORIS = CodedConcept(
    value="D3-13012",
    meaning="Angina pectoris",
    scheme_designator="SRT"
)

IMAGING_GUIDANCE = CodedConcept(
    value="P0-05DA0",
    meaning="Imaging guidance",
    scheme_designator="SRT"
)

MURMUR = CodedConcept(
    value="R-00302",
    meaning="Murmur",
    scheme_designator="SRT"
)

CONGENITAL_HEART_DISEASE = CodedConcept(
    value="D4-31000",
    meaning="Congenital heart disease",
    scheme_designator="SRT"
)

HEART_DISEASE_RISK_FACTORS = CodedConcept(
    value="F-03C97",
    meaning="Heart disease risk factors",
    scheme_designator="SRT"
)

HYPERTENSION = CodedConcept(
    value="D3-02000",
    meaning="Hypertension",
    scheme_designator="SRT"
)

PALPITATIONS = CodedConcept(
    value="F-37150",
    meaning="Palpitations",
    scheme_designator="SRT"
)

VALVULAR_HEART_DISEASE = CodedConcept(
    value="D3-10800",
    meaning="Valvular heart disease",
    scheme_designator="SRT"
)

ABNORMAL_ECG = CodedConcept(
    value="F-38002",
    meaning="Abnormal ECG",
    scheme_designator="SRT"
)

ARRHYTHMIA = CodedConcept(
    value="D3-30000",
    meaning="Arrhythmia",
    scheme_designator="SRT"
)

SYNCOPE = CodedConcept(
    value="D3-00006",
    meaning="Syncope",
    scheme_designator="SRT"
)

LEFT_BUNDLE_BRANCH_BLOCK = CodedConcept(
    value="D3-33120",
    meaning="Left bundle branch block",
    scheme_designator="SRT"
)

FEVER = CodedConcept(
    value="F-0A44A",
    meaning="Fever",
    scheme_designator="SRT"
)

SUPRAVENTRICULAR_TACHYCARDIA = CodedConcept(
    value="D3-31290",
    meaning="Supraventricular tachycardia",
    scheme_designator="SRT"
)

CHEST_PAIN = CodedConcept(
    value="F-37000",
    meaning="Chest Pain",
    scheme_designator="SRT"
)

