"""CID 7220 RTDoseDerivation
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


COMPOSED_FROM_PRIOR_DOSES = CodedConcept(
    value="121370",
    meaning="Composed from prior doses",
    scheme_designator="DCM"
)

COMPOSED_FROM_PRIOR_DOSES_AND_CURRENT_PLAN = CodedConcept(
    value="121371",
    meaning="Composed from prior doses and current plan",
    scheme_designator="DCM"
)

