"""CID 67 ImagingAgentAdministrationCompletionStatus
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


TERMINATED_DUE_TO_FLOW_RATE_ABOVE_TERMINATION_LIMIT = CodedConcept(
    value="130157",
    meaning="Terminated due to flow rate above termination limit",
    scheme_designator="DCM"
)

TERMINATED_DUE_TO_CONSUMABLE_REMOVAL = CodedConcept(
    value="130179",
    meaning="Terminated due to consumable removal",
    scheme_designator="DCM"
)

TERMINATED_DUE_TO_PRESSURE_ABOVE_TERMINATION_LIMIT = CodedConcept(
    value="130156",
    meaning="Terminated due to pressure above termination limit",
    scheme_designator="DCM"
)

TERMINATED_DUE_TO_CRITICAL_BATTERY_LEVEL = CodedConcept(
    value="130178",
    meaning="Terminated due to critical battery level",
    scheme_designator="DCM"
)

TERMINATED_BY_SCANNER = CodedConcept(
    value="130177",
    meaning="Terminated by scanner",
    scheme_designator="DCM"
)

TERMINATED_DUE_TO_AIR_DETECTED = CodedConcept(
    value="130176",
    meaning="Terminated due to air detected",
    scheme_designator="DCM"
)

TERMINATED_DUE_TO_REQUEST_FROM_OPERATOR = CodedConcept(
    value="130154",
    meaning="Terminated due to request from operator",
    scheme_designator="DCM"
)

TERMINATED_DUE_TO_INJECTOR_COMMUNICATION_LOSS = CodedConcept(
    value="130159",
    meaning="Terminated due to injector communication loss",
    scheme_designator="DCM"
)

TERMINATED_DUE_TO_EXCESSIVE_DURATION_PAUSE = CodedConcept(
    value="130158",
    meaning="Terminated due to excessive duration pause",
    scheme_designator="DCM"
)

TERMINATED_DUE_TO_UNSPECIFIED_INJECTOR_FAILURE = CodedConcept(
    value="130160",
    meaning="Terminated due to unspecified injector failure",
    scheme_designator="DCM"
)

COMPLETE = CodedConcept(
    value="R-404F1",
    meaning="Complete",
    scheme_designator="SRT"
)

