"""CID 12112 AbdominalArteries(Unilateral)
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


COMMON_HEPATIC_ARTERY = CodedConcept(
    value="T-46421",
    meaning="Common Hepatic Artery",
    scheme_designator="SRT"
)

INFERIOR_MESENTERIC_ARTERY = CodedConcept(
    value="T-46520",
    meaning="Inferior Mesenteric Artery",
    scheme_designator="SRT"
)

LUMBAR_ARTERY = CodedConcept(
    value="T-46960",
    meaning="Lumbar Artery",
    scheme_designator="SRT"
)

CELIAC_AXIS = CodedConcept(
    value="T-46400",
    meaning="Celiac Axis",
    scheme_designator="SRT"
)

PROPER_HEPATIC_ARTERY = CodedConcept(
    value="T-46422",
    meaning="Proper Hepatic Artery",
    scheme_designator="SRT"
)

SUPERIOR_MESENTERIC_ARTERY = CodedConcept(
    value="T-46510",
    meaning="Superior Mesenteric Artery",
    scheme_designator="SRT"
)

RIGHT_BRANCH_OF_HEPATIC_ARTERY = CodedConcept(
    value="T-46423",
    meaning="Right Branch of Hepatic Artery",
    scheme_designator="SRT"
)

SPLENIC_ARTERY = CodedConcept(
    value="T-46460",
    meaning="Splenic Artery",
    scheme_designator="SRT"
)

AORTA = CodedConcept(
    value="T-42000",
    meaning="Aorta",
    scheme_designator="SRT"
)

GASTRODUODENAL_ARTERY = CodedConcept(
    value="T-46440",
    meaning="Gastroduodenal Artery",
    scheme_designator="SRT"
)

SUPRARENAL_AORTA = CodedConcept(
    value="T-42510",
    meaning="Supra-renal Aorta",
    scheme_designator="SRT"
)

INFRARENAL_AORTA = CodedConcept(
    value="T-42520",
    meaning="Infra-renal Aorta",
    scheme_designator="SRT"
)

COMMON_ILIAC_ARTERY = CodedConcept(
    value="T-46710",
    meaning="Common Iliac Artery",
    scheme_designator="SRT"
)

LEFT_BRANCH_OF_HEPATIC_ARTERY = CodedConcept(
    value="T-46427",
    meaning="Left Branch of Hepatic Artery",
    scheme_designator="SRT"
)

