"""CID 228 EquationorTable
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


TABLE_OF_VALUES = CodedConcept(
    value="121424",
    meaning="Table of Values",
    scheme_designator="DCM"
)

TABLE_OF_VALUES_CITATION = CodedConcept(
    value="121422",
    meaning="Table of Values Citation",
    scheme_designator="DCM"
)

METHOD_CITATION = CodedConcept(
    value="121423",
    meaning="Method Citation",
    scheme_designator="DCM"
)

EQUATION = CodedConcept(
    value="121420",
    meaning="Equation",
    scheme_designator="DCM"
)

EQUATION_CITATION = CodedConcept(
    value="121421",
    meaning="Equation Citation",
    scheme_designator="DCM"
)

