"""CID 12034 UltrasoundTransducerBeamSteering
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


PHASED_BEAM_STEERING = CodedConcept(
    value="125259",
    meaning="Phased beam steering",
    scheme_designator="DCM"
)

MECHANICAL_BEAM_STEERING = CodedConcept(
    value="125258",
    meaning="Mechanical beam steering",
    scheme_designator="DCM"
)

FIXED_BEAM_DIRECTION = CodedConcept(
    value="125257",
    meaning="Fixed beam direction",
    scheme_designator="DCM"
)

