"""CID 7467 GrayLevelCooccurrenceMatrixMeasurements
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


ROOT_ANGULAR_SECOND_MOMENT_OF_GLCM = CodedConcept(
    value="126061",
    meaning="Root Angular Second Moment of GLCM",
    scheme_designator="DCM"
)

