"""CID 1002 AnatomicalReferenceBasisHead
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


NASION = CodedConcept(
    value="264779",
    meaning="Nasion",
    scheme_designator="FMA"
)

FRONTAL_SINUS = CodedConcept(
    value="T-22200",
    meaning="Frontal sinus",
    scheme_designator="SRT"
)

MAXILLARY_SINUS = CodedConcept(
    value="T-22100",
    meaning="Maxillary sinus",
    scheme_designator="SRT"
)

EXTERNAL_AUDITORY_MEATUS = CodedConcept(
    value="T-AB200",
    meaning="External Auditory Meatus",
    scheme_designator="SRT"
)

MANDIBLE = CodedConcept(
    value="T-11180",
    meaning="Mandible",
    scheme_designator="SRT"
)

CAROTID_ARTERY = CodedConcept(
    value="T-45010",
    meaning="Carotid Artery",
    scheme_designator="SRT"
)

TEMPORAL_BONE = CodedConcept(
    value="T-11130",
    meaning="Temporal Bone",
    scheme_designator="SRT"
)

ORBITAL_STRUCTURE = CodedConcept(
    value="T-D14AE",
    meaning="Orbital structure",
    scheme_designator="SRT"
)

MASTOID_BONE = CodedConcept(
    value="T-11133",
    meaning="Mastoid bone",
    scheme_designator="SRT"
)

SKULL = CodedConcept(
    value="T-11100",
    meaning="Skull",
    scheme_designator="SRT"
)

INTERNAL_AUDITORY_MEATUS = CodedConcept(
    value="T-11134",
    meaning="Internal Auditory Meatus",
    scheme_designator="SRT"
)

PITUITARY_FOSSA = CodedConcept(
    value="T-D1460",
    meaning="Pituitary Fossa",
    scheme_designator="SRT"
)

VERTEX_OF_HEAD = CodedConcept(
    value="T-D1120",
    meaning="Vertex of Head",
    scheme_designator="SRT"
)

FORAMEN_MAGNUM = CodedConcept(
    value="T-11106",
    meaning="Foramen Magnum",
    scheme_designator="SRT"
)

MASTOID_CELLS_AND_ANTRA = CodedConcept(
    value="T-AB500",
    meaning="Mastoid cells and antra",
    scheme_designator="SRT"
)

LATERAL_CANTHUS = CodedConcept(
    value="T-AA813",
    meaning="Lateral Canthus",
    scheme_designator="SRT"
)

