"""CID 6070 BloomRichardsonHistologicGrade
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


GRADE_1_WELL_DIFFERENTIATED = CodedConcept(
    value="G-F211",
    meaning="Grade 1: well differentiated",
    scheme_designator="SRT"
)

GRADE_2_MODERATELY_DIFFERENTIATED = CodedConcept(
    value="G-F212",
    meaning="Grade 2: moderately differentiated",
    scheme_designator="SRT"
)

GRADE_3_POORLY_DIFFERENTIATED = CodedConcept(
    value="G-F213",
    meaning="Grade 3: poorly differentiated",
    scheme_designator="SRT"
)

GRADE_4_UNDIFFERENTIATED = CodedConcept(
    value="R-41DC5",
    meaning="Grade 4: undifferentiated",
    scheme_designator="SRT"
)

