"""CID 10024 WaterEquivalentDiameterMethod
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


AAPM_220 = CodedConcept(
    value="113987",
    meaning="AAPM 220",
    scheme_designator="DCM"
)

