"""CID 3452 CalibrationMethods
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


GEOMETRIC_NONISOCENTER = CodedConcept(
    value="122487",
    meaning="Geometric Non-Isocenter",
    scheme_designator="DCM"
)

CALIBRATION_OBJECT_USED = CodedConcept(
    value="122488",
    meaning="Calibration Object Used",
    scheme_designator="DCM"
)

GEOMETRIC_ISOCENTER = CodedConcept(
    value="122486",
    meaning="Geometric Isocenter",
    scheme_designator="DCM"
)

