"""CID 12239 CardiacOutputProperties
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


CARDIAC_OUTPUT = CodedConcept(
    value="F-32100",
    meaning="Cardiac Output",
    scheme_designator="SRT"
)

STROKE_INDEX = CodedConcept(
    value="F-00078",
    meaning="Stroke Index",
    scheme_designator="SRT"
)

CARDIAC_INDEX = CodedConcept(
    value="F-32110",
    meaning="Cardiac Index",
    scheme_designator="SRT"
)

STROKE_VOLUME = CodedConcept(
    value="F-32120",
    meaning="Stroke Volume",
    scheme_designator="SRT"
)

