"""CID 3680 ECGLeadNoiseDescriptions
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


MODERATE_NOISE = CodedConcept(
    value="10:11216",
    meaning="Moderate noise",
    scheme_designator="MDC"
)

SEVERE_NOISE = CodedConcept(
    value="10:11232",
    meaning="Severe noise",
    scheme_designator="MDC"
)

NO_NOISE = CodedConcept(
    value="10:11200",
    meaning="No noise",
    scheme_designator="MDC"
)

NO_SIGNAL = CodedConcept(
    value="10:11248",
    meaning="No signal",
    scheme_designator="MDC"
)

