"""CID 252 SMLSizeDescriptor
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


SMALL = CodedConcept(
    value="R-404A8",
    meaning="Small",
    scheme_designator="SRT"
)

MEDIUM = CodedConcept(
    value="R-404A9",
    meaning="Medium",
    scheme_designator="SRT"
)

LARGE = CodedConcept(
    value="R-404AA",
    meaning="Large",
    scheme_designator="SRT"
)

