"""CID 3406 NoncoronaryTranscatheterInterventions
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


VASCULAR_INTERVENTION = CodedConcept(
    value="122056",
    meaning="Vascular Intervention",
    scheme_designator="DCM"
)

MYOCARDIAL_BIOPSY = CodedConcept(
    value="122057",
    meaning="Myocardial biopsy",
    scheme_designator="DCM"
)

AORTIC_INTERVENTION = CodedConcept(
    value="122054",
    meaning="Aortic Intervention",
    scheme_designator="DCM"
)

SEPTAL_DEFECT_INTERVENTION = CodedConcept(
    value="122055",
    meaning="Septal Defect Intervention",
    scheme_designator="DCM"
)

VALVULAR_INTERVENTION = CodedConcept(
    value="122053",
    meaning="Valvular Intervention",
    scheme_designator="DCM"
)

