"""CID 8132 MagnificationSelection
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


X_10 = CodedConcept(
    value="112716",
    meaning="10X",
    scheme_designator="DCM"
)

X_20 = CodedConcept(
    value="112717",
    meaning="20X",
    scheme_designator="DCM"
)

X_40 = CodedConcept(
    value="112718",
    meaning="40X",
    scheme_designator="DCM"
)

X_5 = CodedConcept(
    value="112715",
    meaning="5X",
    scheme_designator="DCM"
)

