"""CID 637 ExogenousSubstanceTypes
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


TUMOR_GRAFT = CodedConcept(
    value="127460",
    meaning="Tumor Graft",
    scheme_designator="DCM"
)

CYTOKINE = CodedConcept(
    value="F-CB250",
    meaning="Cytokine",
    scheme_designator="SRT"
)

FIBRIL = CodedConcept(
    value="T-1A080",
    meaning="Fibril",
    scheme_designator="SRT"
)

TOXIN = CodedConcept(
    value="C-00224",
    meaning="Toxin",
    scheme_designator="SRT"
)

VIRUS = CodedConcept(
    value="L-30000",
    meaning="Virus",
    scheme_designator="SRT"
)

GRAFT_MATERIAL = CodedConcept(
    value="G-C1F9",
    meaning="Graft material",
    scheme_designator="SRT"
)

