"""CID 3641 HemodynamicAssessments
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


PULMONARY_VASCULAR_RESISTANCE = CodedConcept(
    value="F-03E86",
    meaning="Pulmonary Vascular Resistance",
    scheme_designator="SRT"
)

RIGHT_VENTRICULAR_SYSTOLIC_PRESSURE = CodedConcept(
    value="F-03DFE",
    meaning="Right Ventricular Systolic Pressure",
    scheme_designator="SRT"
)

PULMONARY_ARTERY_PRESSURE = CodedConcept(
    value="F-0212C",
    meaning="Pulmonary Artery Pressure",
    scheme_designator="SRT"
)

PULMONARY_CAPILLARY_WEDGE_PRESSURE = CodedConcept(
    value="F-31146",
    meaning="Pulmonary Capillary Wedge Pressure",
    scheme_designator="SRT"
)

LEFT_VENTRICULAR_SYSTOLIC_PRESSURE = CodedConcept(
    value="F-03E0D",
    meaning="Left Ventricular Systolic Pressure",
    scheme_designator="SRT"
)

LEFT_VENTRICULAR_ENDDIASTOLIC_PRESSURE = CodedConcept(
    value="F-03E0E",
    meaning="Left Ventricular End-Diastolic Pressure",
    scheme_designator="SRT"
)

RIGHT_VENTRICULAR_ENDDIASTOLIC_PRESSURE = CodedConcept(
    value="F-03E02",
    meaning="Right Ventricular End-Diastolic Pressure",
    scheme_designator="SRT"
)

VASCULAR_RESISTANCE = CodedConcept(
    value="F-39790",
    meaning="Vascular Resistance",
    scheme_designator="SRT"
)

RIGHT_ATRIAL_PRESSURE = CodedConcept(
    value="F-03DE9",
    meaning="Right Atrial Pressure",
    scheme_designator="SRT"
)

DIASTOLIC_PRESSURE = CodedConcept(
    value="F-008ED",
    meaning="Diastolic Pressure",
    scheme_designator="SRT"
)

