"""CID 6064 UltrasoundFindingsforBreast
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


COMPLEX_CYST = CodedConcept(
    value="111460",
    meaning="Complex cyst",
    scheme_designator="DCM"
)

COMPLICATED_CYST = CodedConcept(
    value="111130",
    meaning="Complicated cyst",
    scheme_designator="DCM"
)

INTRACYSTIC_LESION = CodedConcept(
    value="111461",
    meaning="Intracystic lesion",
    scheme_designator="DCM"
)

SOLID_MASS = CodedConcept(
    value="111462",
    meaning="Solid mass",
    scheme_designator="DCM"
)

CLUSTERED_MICROCYSTS = CodedConcept(
    value="111129",
    meaning="Clustered microcysts",
    scheme_designator="DCM"
)

LYMPH_NODE = CodedConcept(
    value="T-C4000",
    meaning="Lymph node",
    scheme_designator="SRT"
)

ULTRASOUND_SCAN_NORMAL = CodedConcept(
    value="F-01BF8",
    meaning="Ultrasound scan normal",
    scheme_designator="SRT"
)

SEBACEOUS_CYST_OF_SKIN_OF_BREAST = CodedConcept(
    value="D7-90382",
    meaning="Sebaceous cyst of skin of breast",
    scheme_designator="SRT"
)

MAMMARY_DUCT_ECTASIA = CodedConcept(
    value="D7-90370",
    meaning="Mammary duct ectasia",
    scheme_designator="SRT"
)

FOREIGN_BODY = CodedConcept(
    value="M-30400",
    meaning="Foreign body",
    scheme_designator="SRT"
)

CYST_OF_BREAST = CodedConcept(
    value="D7-90035",
    meaning="Cyst of breast",
    scheme_designator="SRT"
)

