"""CID 3777 ImplantedDevices
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


CARDIAC_PACEMAKER = CodedConcept(
    value="A-11100",
    meaning="Cardiac pacemaker",
    scheme_designator="SRT"
)

INSULIN_PUMP = CodedConcept(
    value="A-28040",
    meaning="Insulin pump",
    scheme_designator="SRT"
)

IMPLANTABLE_DEFIBRILLATOR = CodedConcept(
    value="A-11206",
    meaning="Implantable defibrillator",
    scheme_designator="SRT"
)

LEFT_VENTRICULAR_ASSIST_DEVICE = CodedConcept(
    value="A-11FCD",
    meaning="Left ventricular assist device",
    scheme_designator="SRT"
)

