"""CID 9243 RadiotherapyRegistrationWorkitemDefinition
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


RT_PATIENT_POSITION_REGISTRATION_SINGLE_PLANE = CodedConcept(
    value="121712",
    meaning="RT Patient Position Registration, single plane",
    scheme_designator="DCM"
)

RT_PATIENT_POSITION_REGISTRATION_DUAL_PLANE = CodedConcept(
    value="121713",
    meaning="RT Patient Position Registration, dual plane",
    scheme_designator="DCM"
)

RT_PATIENT_POSITION_REGISTRATION_SPATIAL_FIDUCIALS = CodedConcept(
    value="121721",
    meaning="RT Patient Position Registration, Spatial Fiducials",
    scheme_designator="DCM"
)

RT_PATIENT_POSITION_REGISTRATION_ULTRASOUND = CodedConcept(
    value="121720",
    meaning="RT Patient Position Registration, Ultrasound",
    scheme_designator="DCM"
)

RT_PATIENT_POSITION_REGISTRATION_2D_ON_3D_REFERENCE = CodedConcept(
    value="121718",
    meaning="RT Patient Position Registration, 2D on 3D reference",
    scheme_designator="DCM"
)

RT_PATIENT_POSITION_REGISTRATION_OPTICAL = CodedConcept(
    value="121719",
    meaning="RT Patient Position Registration, Optical",
    scheme_designator="DCM"
)

RT_PATIENT_POSITION_REGISTRATION_3D_CT_VOLUMEBASED = CodedConcept(
    value="121716",
    meaning="RT Patient Position Registration, 3D CT volume-based",
    scheme_designator="DCM"
)

RT_PATIENT_POSITION_REGISTRATION_3D_ON_2D_REFERENCE = CodedConcept(
    value="121717",
    meaning="RT Patient Position Registration, 3D on 2D reference",
    scheme_designator="DCM"
)

RT_PATIENT_POSITION_REGISTRATION_3D_CT_GENERAL = CodedConcept(
    value="121714",
    meaning="RT Patient Position Registration, 3D CT general",
    scheme_designator="DCM"
)

RT_PATIENT_POSITION_REGISTRATION_3D_CT_MARKERBASED = CodedConcept(
    value="121715",
    meaning="RT Patient Position Registration, 3D CT marker-based",
    scheme_designator="DCM"
)

