"""CID 635 HeatingMethod
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


HEATED_WATER_BLANKET = CodedConcept(
    value="127253",
    meaning="Heated water blanket",
    scheme_designator="DCM"
)

PREHEATED_PAD = CodedConcept(
    value="127254",
    meaning="Pre-heated pad",
    scheme_designator="DCM"
)

UNHEATED = CodedConcept(
    value="127255",
    meaning="Unheated",
    scheme_designator="DCM"
)

FORCED_AIR_HEATER = CodedConcept(
    value="127250",
    meaning="Forced air heater",
    scheme_designator="DCM"
)

HEATED_IMAGING_DEVICE = CodedConcept(
    value="127251",
    meaning="Heated imaging device",
    scheme_designator="DCM"
)

HEATED_PATIENT_SUPPORT = CodedConcept(
    value="127252",
    meaning="Heated patient support",
    scheme_designator="DCM"
)

ELECTRIC_BLANKET = CodedConcept(
    value="A-18041",
    meaning="Electric blanket",
    scheme_designator="SRT"
)

AIR_HEATING_PAD = CodedConcept(
    value="R-FDB79",
    meaning="Air heating pad",
    scheme_designator="SRT"
)

ELECTRIC_HEATING_PAD = CodedConcept(
    value="A-2C140",
    meaning="Electric heating pad",
    scheme_designator="SRT"
)

NONELECTRIC_HEATING_PAD = CodedConcept(
    value="A-2C141",
    meaning="Non-electric heating pad",
    scheme_designator="SRT"
)

WARMING_BLANKET = CodedConcept(
    value="A-17452",
    meaning="Warming blanket",
    scheme_designator="SRT"
)

FORCED_AIR_WARMING_BLANKET = CodedConcept(
    value="A-17454",
    meaning="Forced air warming blanket",
    scheme_designator="SRT"
)

WARMER_DEVICE = CodedConcept(
    value="A-17450",
    meaning="Warmer device",
    scheme_designator="SRT"
)

HEAT_LAMP = CodedConcept(
    value="C0181514",
    meaning="Heat lamp",
    scheme_designator="UMLS"
)

