"""CID 6053 BreastImagingReportElements
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


PROCEDURE_REPORTED = CodedConcept(
    value="121058",
    meaning="Procedure reported",
    scheme_designator="DCM"
)

CONCLUSION = CodedConcept(
    value="121077",
    meaning="Conclusion",
    scheme_designator="DCM"
)

PHYSICAL_EXAMINATION_RESULTS = CodedConcept(
    value="111423",
    meaning="Physical Examination Results",
    scheme_designator="DCM"
)

RECOMMENDATION = CodedConcept(
    value="121075",
    meaning="Recommendation",
    scheme_designator="DCM"
)

REASON_FOR_PROCEDURE = CodedConcept(
    value="111401",
    meaning="Reason for procedure",
    scheme_designator="DCM"
)

COMPARISON_TO_PREVIOUS_EXAMS = CodedConcept(
    value="111424",
    meaning="Comparison to previous exams",
    scheme_designator="DCM"
)

OVERALL_ASSESSMENT = CodedConcept(
    value="111413",
    meaning="Overall Assessment",
    scheme_designator="DCM"
)

IMPRESSION = CodedConcept(
    value="121073",
    meaning="Impression",
    scheme_designator="DCM"
)

FINDING = CodedConcept(
    value="121071",
    meaning="Finding",
    scheme_designator="DCM"
)

BREAST_COMPOSITION = CodedConcept(
    value="F-01710",
    meaning="Breast composition",
    scheme_designator="SRT"
)

