"""CID 3001 ECGLeads
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


FRANK_LEAD_C = CodedConcept(
    value="2:26",
    meaning="Frank Lead C",
    scheme_designator="MDC"
)

FRANK_LEAD_A = CodedConcept(
    value="2:27",
    meaning="Frank Lead A",
    scheme_designator="MDC"
)

FRANK_LEAD_M = CodedConcept(
    value="2:28",
    meaning="Frank Lead M",
    scheme_designator="MDC"
)

FRANK_LEAD_F = CodedConcept(
    value="2:29",
    meaning="Frank Lead F",
    scheme_designator="MDC"
)

CHESTMANUBRIUM_LEAD_PER_V5_PLACEMENT = CodedConcept(
    value="2:20",
    meaning="Chest-manubrium lead per V5 placement",
    scheme_designator="MDC"
)

LEFT_ARM_LEAD = CodedConcept(
    value="2:21",
    meaning="Left Arm Lead",
    scheme_designator="MDC"
)

CANINE_SIXTH_LEFT_INTERCOSTAL_SPACE_AT_COSTOCHONDRAL_JUNCTION = CodedConcept(
    value="2:150",
    meaning="Canine, sixth left intercostal space at costochondral junction",
    scheme_designator="MDC"
)

RIGHT_ARM_LEAD = CodedConcept(
    value="2:22",
    meaning="Right Arm Lead",
    scheme_designator="MDC"
)

LEFT_LEG_LEAD = CodedConcept(
    value="2:23",
    meaning="Left Leg Lead",
    scheme_designator="MDC"
)

CANINE_OVER_DORSAL_SPINOUS_PROCESS_OF_7TH_THORACIC_VERTEBRA = CodedConcept(
    value="2:151",
    meaning="Canine, over dorsal spinous process of 7th thoracic vertebra",
    scheme_designator="MDC"
)

FRANK_LEAD_I = CodedConcept(
    value="2:24",
    meaning="Frank Lead I",
    scheme_designator="MDC"
)

FRANK_LEAD_E = CodedConcept(
    value="2:25",
    meaning="Frank Lead E",
    scheme_designator="MDC"
)

DERIVED_LEAD_V5 = CodedConcept(
    value="2:37",
    meaning="Derived Lead V5",
    scheme_designator="MDC"
)

DERIVED_LEAD_V6 = CodedConcept(
    value="2:38",
    meaning="Derived Lead V6",
    scheme_designator="MDC"
)

FRANK_LEAD_H = CodedConcept(
    value="2:30",
    meaning="Frank Lead H",
    scheme_designator="MDC"
)

DERIVED_LEAD_I = CodedConcept(
    value="2:31",
    meaning="Derived Lead I",
    scheme_designator="MDC"
)

DERIVED_LEAD_II = CodedConcept(
    value="2:32",
    meaning="Derived Lead II",
    scheme_designator="MDC"
)

DERIVED_LEAD_V1 = CodedConcept(
    value="2:33",
    meaning="Derived Lead V1",
    scheme_designator="MDC"
)

DERIVED_LEAD_V2 = CodedConcept(
    value="2:34",
    meaning="Derived Lead V2",
    scheme_designator="MDC"
)

DERIVED_LEAD_V3 = CodedConcept(
    value="2:35",
    meaning="Derived Lead V3",
    scheme_designator="MDC"
)

DERIVED_LEAD_V4 = CodedConcept(
    value="2:36",
    meaning="Derived Lead V4",
    scheme_designator="MDC"
)

EASI_LEAD_AS = CodedConcept(
    value="2:132",
    meaning="EASI Lead AS",
    scheme_designator="MDC"
)

EASI_LEAD_AI = CodedConcept(
    value="2:133",
    meaning="EASI Lead AI",
    scheme_designator="MDC"
)

EASI_UPPER_STERNUM_LEAD = CodedConcept(
    value="2:134",
    meaning="EASI upper sternum lead",
    scheme_designator="MDC"
)

AUXILIARY_BIPOLAR_LEAD_4 = CodedConcept(
    value="2:130",
    meaning="Auxiliary bipolar lead 4",
    scheme_designator="MDC"
)

EASI_LEAD_ES = CodedConcept(
    value="2:131",
    meaning="EASI Lead ES",
    scheme_designator="MDC"
)

RIGHT_LEG_LEAD = CodedConcept(
    value="2:147",
    meaning="Right Leg Lead",
    scheme_designator="MDC"
)

CANINE_FIFTH_RIGHT_INTERCOSTAL_SPACE_NEAR_EDGE_OF_STERNUM = CodedConcept(
    value="2:148",
    meaning="Canine, fifth right intercostal space near edge of sternum",
    scheme_designator="MDC"
)

CANINE_SIXTH_LEFT_INTERCOSTAL_SPACE_NEAR_EDGE_OF_STERNUM = CodedConcept(
    value="2:149",
    meaning="Canine, sixth left intercostal space near edge of sternum",
    scheme_designator="MDC"
)

LEAD_I = CodedConcept(
    value="2:1",
    meaning="Lead I",
    scheme_designator="MDC"
)

UNSPECIFIED_LEAD = CodedConcept(
    value="2:0",
    meaning="Unspecified lead",
    scheme_designator="MDC"
)

LEAD_V1 = CodedConcept(
    value="2:3",
    meaning="Lead V1",
    scheme_designator="MDC"
)

LEAD_II = CodedConcept(
    value="2:2",
    meaning="Lead II",
    scheme_designator="MDC"
)

LEAD_V3 = CodedConcept(
    value="2:5",
    meaning="Lead V3",
    scheme_designator="MDC"
)

LEAD_V2 = CodedConcept(
    value="2:4",
    meaning="Lead V2",
    scheme_designator="MDC"
)

LEAD_V5 = CodedConcept(
    value="2:7",
    meaning="Lead V5",
    scheme_designator="MDC"
)

LEAD_V4 = CodedConcept(
    value="2:6",
    meaning="Lead V4",
    scheme_designator="MDC"
)

LEAD_V7 = CodedConcept(
    value="2:9",
    meaning="Lead V7",
    scheme_designator="MDC"
)

LEAD_V6 = CodedConcept(
    value="2:8",
    meaning="Lead V6",
    scheme_designator="MDC"
)

DERIVED_LEAD_AVF = CodedConcept(
    value="2:114",
    meaning="Derived Lead aVF",
    scheme_designator="MDC"
)

AVR_AUGMENTED_VOLTAGE_RIGHT = CodedConcept(
    value="2:62",
    meaning="aVR, augmented voltage, right",
    scheme_designator="MDC"
)

CHESTMANUBRIUM_LEAD_PER_V6_PLACEMENT = CodedConcept(
    value="2:110",
    meaning="Chest-manubrium lead per V6 placement",
    scheme_designator="MDC"
)

AVL_AUGMENTED_VOLTAGE_LEFT = CodedConcept(
    value="2:63",
    meaning="aVL, augmented voltage, left",
    scheme_designator="MDC"
)

DERIVED_LEAD_III = CodedConcept(
    value="2:111",
    meaning="Derived Lead III",
    scheme_designator="MDC"
)

AVF_AUGMENTED_VOLTAGE_FOOT = CodedConcept(
    value="2:64",
    meaning="aVF, augmented voltage, foot",
    scheme_designator="MDC"
)

DERIVED_LEAD_AVR = CodedConcept(
    value="2:112",
    meaning="Derived Lead aVR",
    scheme_designator="MDC"
)

_AVR = CodedConcept(
    value="2:65",
    meaning="−aVR",
    scheme_designator="MDC"
)

DERIVED_LEAD_AVL = CodedConcept(
    value="2:113",
    meaning="Derived Lead aVL",
    scheme_designator="MDC"
)

LEAD_V8 = CodedConcept(
    value="2:66",
    meaning="Lead V8",
    scheme_designator="MDC"
)

LEAD_V9 = CodedConcept(
    value="2:67",
    meaning="Lead V9",
    scheme_designator="MDC"
)

LEAD_V8R = CodedConcept(
    value="2:68",
    meaning="Lead V8R",
    scheme_designator="MDC"
)

LEAD_V9R = CodedConcept(
    value="2:69",
    meaning="Lead V9R",
    scheme_designator="MDC"
)

LEAD_III = CodedConcept(
    value="2:61",
    meaning="Lead III",
    scheme_designator="MDC"
)

AUXILIARY_BIPOLAR_LEAD_3 = CodedConcept(
    value="2:129",
    meaning="Auxiliary bipolar lead 3",
    scheme_designator="MDC"
)

LEAD_CR5 = CodedConcept(
    value="2:125",
    meaning="Lead CR5",
    scheme_designator="MDC"
)

MODIFIED_LIMB_LEAD = CodedConcept(
    value="2:126",
    meaning="Modified limb lead",
    scheme_designator="MDC"
)

AUXILIARY_BIPOLAR_LEAD_1 = CodedConcept(
    value="2:127",
    meaning="Auxiliary bipolar lead 1",
    scheme_designator="MDC"
)

AUXILIARY_BIPOLAR_LEAD_2 = CodedConcept(
    value="2:128",
    meaning="Auxiliary bipolar lead 2",
    scheme_designator="MDC"
)

CHESTMANUBRIUM_LEAD_PER_V7_PLACEMENT = CodedConcept(
    value="2:121",
    meaning="Chest-manubrium lead per V7 placement",
    scheme_designator="MDC"
)

DEFIBRILLATOR_LEAD_ANTERIORLATERAL = CodedConcept(
    value="2:73",
    meaning="Defibrillator lead: anterior-lateral",
    scheme_designator="MDC"
)

LEAD_CH5 = CodedConcept(
    value="2:122",
    meaning="Lead CH5",
    scheme_designator="MDC"
)

EXTERNAL_PACING_LEAD_ANTERIORPOSTERIOR = CodedConcept(
    value="2:74",
    meaning="External pacing lead: anterior-posterior",
    scheme_designator="MDC"
)

AUXILIARY_UNIPOLAR_LEAD_1 = CodedConcept(
    value="2:75",
    meaning="Auxiliary unipolar lead 1",
    scheme_designator="MDC"
)

NEGATIVE_RIGHT_INFRACLAVICULAR_FOSSA = CodedConcept(
    value="2:123",
    meaning="negative: right infraclavicular fossa",
    scheme_designator="MDC"
)

AUXILIARY_UNIPOLAR_LEAD_2 = CodedConcept(
    value="2:76",
    meaning="Auxiliary unipolar lead 2",
    scheme_designator="MDC"
)

NEGATIVE_LOW_RIGHT_SCAPULA_LEAD = CodedConcept(
    value="2:124",
    meaning="negative: low right scapula Lead",
    scheme_designator="MDC"
)

AUXILIARY_UNIPOLAR_LEAD_3 = CodedConcept(
    value="2:77",
    meaning="Auxiliary unipolar lead 3",
    scheme_designator="MDC"
)

AUXILIARY_UNIPOLAR_LEAD_4 = CodedConcept(
    value="2:78",
    meaning="Auxiliary unipolar lead 4",
    scheme_designator="MDC"
)

LEAD_D_NEHB_DORSAL_ = CodedConcept(
    value="2:70",
    meaning="Lead D (Nehb - Dorsal)",
    scheme_designator="MDC"
)

LEAD_A_NEHB_ANTERIOR_ = CodedConcept(
    value="2:71",
    meaning="Lead A (Nehb - Anterior)",
    scheme_designator="MDC"
)

LEAD_J_NEHB_INFERIOR_ = CodedConcept(
    value="2:72",
    meaning="Lead J (Nehb - Inferior)",
    scheme_designator="MDC"
)

CHEST_LEAD = CodedConcept(
    value="2:86",
    meaning="Chest lead",
    scheme_designator="MDC"
)

PRECORDIAL_LEAD = CodedConcept(
    value="2:87",
    meaning="Precordial lead",
    scheme_designator="MDC"
)

LEAD_VR_NONAUGMENTED_VOLTAGE_VECTOR_OF_RA = CodedConcept(
    value="2:88",
    meaning="Lead VR, nonaugmented voltage, vector of RA",
    scheme_designator="MDC"
)

LEAD_VL_NONAUGMENTED_VOLTAGE_VECTOR_OF_LA = CodedConcept(
    value="2:89",
    meaning="Lead VL, nonaugmented voltage, vector of LA",
    scheme_designator="MDC"
)

CHESTMANUBRIUM_LEAD_PER_V2_PLACEMENT = CodedConcept(
    value="2:107",
    meaning="Chest-manubrium lead per V2 placement",
    scheme_designator="MDC"
)

LEAD_V7R = CodedConcept(
    value="2:15",
    meaning="Lead V7R",
    scheme_designator="MDC"
)

CHESTMANUBRIUM_LEAD_PER_V3_PLACEMENT = CodedConcept(
    value="2:108",
    meaning="Chest-manubrium lead per V3 placement",
    scheme_designator="MDC"
)

LEAD_X = CodedConcept(
    value="2:16",
    meaning="Lead X",
    scheme_designator="MDC"
)

CHESTMANUBRIUM_LEAD_PER_V4_PLACEMENT = CodedConcept(
    value="2:109",
    meaning="Chest-manubrium lead per V4 placement",
    scheme_designator="MDC"
)

LEAD_Y = CodedConcept(
    value="2:17",
    meaning="Lead Y",
    scheme_designator="MDC"
)

LEAD_Z = CodedConcept(
    value="2:18",
    meaning="Lead Z",
    scheme_designator="MDC"
)

CHEST_LEAD_PER_V5_AND_V5R_PLACEMENT = CodedConcept(
    value="2:19",
    meaning="Chest lead per V5 and V5R placement",
    scheme_designator="MDC"
)

CHEST_LEAD_PER_V6_AND_V6R_PLACEMENT = CodedConcept(
    value="2:103",
    meaning="Chest lead per V6 and V6R placement",
    scheme_designator="MDC"
)

CHEST_LEAD_PER_V7_AND_V8R_PLACEMENT = CodedConcept(
    value="2:104",
    meaning="Chest lead per V7 and V8R placement",
    scheme_designator="MDC"
)

CHESTMANUBRIUM_LEAD = CodedConcept(
    value="2:105",
    meaning="Chest-manubrium lead",
    scheme_designator="MDC"
)

CHESTMANUBRIUM_LEAD_PER_V1_PLACEMENT = CodedConcept(
    value="2:106",
    meaning="Chest-manubrium lead per V1 placement",
    scheme_designator="MDC"
)

MODIFIED_CHEST_LEAD_PER_V4_PLACEMENT = CodedConcept(
    value="2:95",
    meaning="Modified chest lead per V4 placement",
    scheme_designator="MDC"
)

CHEST_LEAD_PER_V2_AND_V2R_PLACEMENT = CodedConcept(
    value="2:100",
    meaning="Chest lead per V2 and V2R placement",
    scheme_designator="MDC"
)

MODIFIED_CHEST_LEAD_PER_V5_PLACEMENT = CodedConcept(
    value="2:96",
    meaning="Modified chest lead per V5 placement",
    scheme_designator="MDC"
)

CHEST_LEAD_PER_V3_AND_V3R_PLACEMENT = CodedConcept(
    value="2:101",
    meaning="Chest lead per V3 and V3R placement",
    scheme_designator="MDC"
)

MODIFIED_CHEST_LEAD_PER_V6_PLACEMENT = CodedConcept(
    value="2:97",
    meaning="Modified chest lead per V6 placement",
    scheme_designator="MDC"
)

CHEST_LEAD_SYMMETRIC_PLACEMENT_ = CodedConcept(
    value="2:98",
    meaning="Chest lead (symmetric placement)",
    scheme_designator="MDC"
)

CHEST_LEAD_PER_V4_AND_V4R_PLACEMENT = CodedConcept(
    value="2:102",
    meaning="Chest lead per V4 and V4R placement",
    scheme_designator="MDC"
)

LEAD_V2R = CodedConcept(
    value="2:10",
    meaning="Lead V2R",
    scheme_designator="MDC"
)

CHEST_LEAD_PER_V1_AND_V1R_PLACEMENT = CodedConcept(
    value="2:99",
    meaning="Chest lead per V1 and V1R placement",
    scheme_designator="MDC"
)

LEAD_V3R = CodedConcept(
    value="2:11",
    meaning="Lead V3R",
    scheme_designator="MDC"
)

LEAD_V4R = CodedConcept(
    value="2:12",
    meaning="Lead V4R",
    scheme_designator="MDC"
)

LEAD_V5R = CodedConcept(
    value="2:13",
    meaning="Lead V5R",
    scheme_designator="MDC"
)

LEAD_V6R = CodedConcept(
    value="2:14",
    meaning="Lead V6R",
    scheme_designator="MDC"
)

LEAD_VF_NONAUGMENTED_VOLTAGE_VECTOR_OF_LL = CodedConcept(
    value="2:90",
    meaning="Lead VF, nonaugmented voltage, vector of LL",
    scheme_designator="MDC"
)

MODIFIED_CHEST_LEAD_LEFT_ARM_INDIFFERENT_ = CodedConcept(
    value="2:91",
    meaning="Modified chest lead (left arm indifferent)",
    scheme_designator="MDC"
)

MODIFIED_CHEST_LEAD_PER_V1_PLACEMENT = CodedConcept(
    value="2:92",
    meaning="Modified chest lead per V1 placement",
    scheme_designator="MDC"
)

MODIFIED_CHEST_LEAD_PER_V2_PLACEMENT = CodedConcept(
    value="2:93",
    meaning="Modified chest lead per V2 placement",
    scheme_designator="MDC"
)

MODIFIED_CHEST_LEAD_PER_V3_PLACEMENT = CodedConcept(
    value="2:94",
    meaning="Modified chest lead per V3 placement",
    scheme_designator="MDC"
)

