"""CID 3813 StentFindings
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


STENT_FRACTURE = CodedConcept(
    value="122683",
    meaning="stent fracture",
    scheme_designator="DCM"
)

STENT_DISINTEGRATION = CodedConcept(
    value="122684",
    meaning="stent disintegration",
    scheme_designator="DCM"
)

ENDOLEAK = CodedConcept(
    value="122680",
    meaning="endoleak",
    scheme_designator="DCM"
)

HYPOPLASIA = CodedConcept(
    value="M-75300",
    meaning="hypoplasia",
    scheme_designator="SRT"
)

MIGRATION_OF_IMPLANT_OR_INTERNAL_DEVICE = CodedConcept(
    value="DD-661D2",
    meaning="migration of implant or internal device",
    scheme_designator="SRT"
)

STENOSIS = CodedConcept(
    value="M-3400A",
    meaning="stenosis",
    scheme_designator="SRT"
)

