"""CID 626 PremedicationAgentsforSmallAnimalAnesthesia
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


CHLORPROMAZINE = CodedConcept(
    value="F-61A7F",
    meaning="Chlorpromazine",
    scheme_designator="SRT"
)

ACEPROMAZINE = CodedConcept(
    value="C-62960",
    meaning="Acepromazine",
    scheme_designator="SRT"
)

