"""CID 9502 RTSegmentAnnotationCategories
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


EXTERNAL_BODY_MODEL = CodedConcept(
    value="130047",
    meaning="External Body Model",
    scheme_designator="DCM"
)

NONSPECIFIC_VOLUME = CodedConcept(
    value="130046",
    meaning="Non-specific Volume",
    scheme_designator="DCM"
)

BRACHYTHERAPY_DEVICE = CodedConcept(
    value="130045",
    meaning="Brachytherapy Device",
    scheme_designator="DCM"
)

FIXATION_OR_POSITIONING_DEVICE = CodedConcept(
    value="130044",
    meaning="Fixation or Positioning Device",
    scheme_designator="DCM"
)

RT_GEOMETRIC_INFORMATION = CodedConcept(
    value="130043",
    meaning="RT Geometric Information",
    scheme_designator="DCM"
)

RT_DOSE_CALCULATION_STRUCTURE = CodedConcept(
    value="130042",
    meaning="RT Dose Calculation Structure",
    scheme_designator="DCM"
)

RT_TARGET = CodedConcept(
    value="130041",
    meaning="RT Target",
    scheme_designator="DCM"
)

PHYSICAL_OBJECT = CodedConcept(
    value="A-00004",
    meaning="Physical object",
    scheme_designator="SRT"
)

