"""CID 6115 OsseousAnatomyModifiers
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


RIB_SCALENE_TUBERCLE = CodedConcept(
    value="112096",
    meaning="Rib Scalene Tubercle",
    scheme_designator="DCM"
)

VERTEBRAL_INTERVERTEBRAL_NOTCH = CodedConcept(
    value="112097",
    meaning="Vertebral Intervertebral Notch",
    scheme_designator="DCM"
)

SUBSCAPULAR_FOSSA = CodedConcept(
    value="112098",
    meaning="Subscapular Fossa",
    scheme_designator="DCM"
)

SCAPULAR_SPINE = CodedConcept(
    value="112099",
    meaning="Scapular Spine",
    scheme_designator="DCM"
)

SCAPULAR_SUPRASPINATUS_FOSSA = CodedConcept(
    value="112100",
    meaning="Scapular Supraspinatus Fossa",
    scheme_designator="DCM"
)

SCAPULAR_INFRASPINATUS_FOSSA = CodedConcept(
    value="112101",
    meaning="Scapular Infraspinatus Fossa",
    scheme_designator="DCM"
)

SUPERIOR_ARTICULAR_PROCESS_OF_VERTEBRA = CodedConcept(
    value="T-1153E",
    meaning="Superior articular process of vertebra",
    scheme_designator="SRT"
)

INFERIOR_ARTICULAR_PROCESS_OF_VERTEBRA = CodedConcept(
    value="T-1153F",
    meaning="Inferior articular process of vertebra",
    scheme_designator="SRT"
)

VERTEBRAL_CANAL = CodedConcept(
    value="T-1151F",
    meaning="Vertebral canal",
    scheme_designator="SRT"
)

BODY_OF_STERNUM = CodedConcept(
    value="T-11220",
    meaning="Body of sternum",
    scheme_designator="SRT"
)

STERNAL_ANGLE = CodedConcept(
    value="T-11221",
    meaning="Sternal angle",
    scheme_designator="SRT"
)

HEAD_OF_RIB = CodedConcept(
    value="T-11301",
    meaning="Head of rib",
    scheme_designator="SRT"
)

NECK_OF_RIB = CodedConcept(
    value="T-11303",
    meaning="Neck of rib",
    scheme_designator="SRT"
)

TUBERCLE_OF_RIB = CodedConcept(
    value="T-11304",
    meaning="Tubercle of rib",
    scheme_designator="SRT"
)

XIPHOID_PROCESS_OF_STERNUM = CodedConcept(
    value="T-11227",
    meaning="Xiphoid process of sternum",
    scheme_designator="SRT"
)

ANGLE_OF_RIB = CodedConcept(
    value="T-11307",
    meaning="Angle of rib",
    scheme_designator="SRT"
)

COSTAL_GROOVE = CodedConcept(
    value="T-11308",
    meaning="Costal groove",
    scheme_designator="SRT"
)

SHAFT_OF_RIB = CodedConcept(
    value="T-11309",
    meaning="Shaft of rib",
    scheme_designator="SRT"
)

ACROMION_PROCESS_OF_SCAPULA = CodedConcept(
    value="T-12281",
    meaning="Acromion process of scapula",
    scheme_designator="SRT"
)

CORACOID_PROCESS_OF_SCAPULA = CodedConcept(
    value="T-12282",
    meaning="Coracoid process of scapula",
    scheme_designator="SRT"
)

DORSAL_ASPECT_OF_SCAPULA = CodedConcept(
    value="T-12287",
    meaning="Dorsal aspect of scapula",
    scheme_designator="SRT"
)

PECTORAL_GIRDLE = CodedConcept(
    value="T-12200",
    meaning="Pectoral girdle",
    scheme_designator="SRT"
)

MANUBRIUM_OF_STERNUM = CodedConcept(
    value="T-11211",
    meaning="Manubrium of sternum",
    scheme_designator="SRT"
)

VERTEBRAL_FORAMEN = CodedConcept(
    value="T-11531",
    meaning="Vertebral foramen",
    scheme_designator="SRT"
)

ARCH_OF_VERTEBRA = CodedConcept(
    value="T-11511",
    meaning="Arch of vertebra",
    scheme_designator="SRT"
)

SPINOUS_PROCESS_OF_VERTEBRA = CodedConcept(
    value="T-11512",
    meaning="Spinous process of vertebra",
    scheme_designator="SRT"
)

SUPERIOR_ARTICULAR_FACET_OF_AXIS = CodedConcept(
    value="T-116EE",
    meaning="Superior articular facet of axis",
    scheme_designator="SRT"
)

INFERIOR_ARTICULAR_FACET_OF_AXIS = CodedConcept(
    value="T-116EF",
    meaning="Inferior articular facet of axis",
    scheme_designator="SRT"
)

TRANSVERSE_PROCESS_OR_VERTEBRA = CodedConcept(
    value="T-11513",
    meaning="Transverse process or vertebra",
    scheme_designator="SRT"
)

LAMINA_OF_VERTEBRA = CodedConcept(
    value="T-11514",
    meaning="Lamina of vertebra",
    scheme_designator="SRT"
)

PEDICLE_OF_VERTEBRA = CodedConcept(
    value="T-11515",
    meaning="Pedicle of vertebra",
    scheme_designator="SRT"
)

SUPRASTERNAL_NOTCH = CodedConcept(
    value="T-11218",
    meaning="Suprasternal notch",
    scheme_designator="SRT"
)

CLAVICULAR_NOTCH_OF_STERNUM = CodedConcept(
    value="T-11219",
    meaning="Clavicular notch of sternum",
    scheme_designator="SRT"
)

GLENOID_CAVITY_OF_SCAPULA = CodedConcept(
    value="T-1228A",
    meaning="Glenoid cavity of scapula",
    scheme_designator="SRT"
)

