"""CID 3770 ProblemStatus
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


PROBLEM_RESOLVED = CodedConcept(
    value="F-04B88",
    meaning="Problem resolved",
    scheme_designator="SRT"
)

WELL_CONTROLLED = CodedConcept(
    value="P0-30450",
    meaning="Well controlled",
    scheme_designator="SRT"
)

CHRONIC = CodedConcept(
    value="G-A270",
    meaning="Chronic",
    scheme_designator="SRT"
)

RECURRENT = CodedConcept(
    value="G-A39A",
    meaning="Recurrent",
    scheme_designator="SRT"
)

SUSPECTED = CodedConcept(
    value="G-A47B",
    meaning="Suspected",
    scheme_designator="SRT"
)

INTERMITTENT = CodedConcept(
    value="G-A397",
    meaning="Intermittent",
    scheme_designator="SRT"
)

KNOWN_ABSENT = CodedConcept(
    value="G-A46B",
    meaning="Known absent",
    scheme_designator="SRT"
)

ACTIVE_PROBLEM = CodedConcept(
    value="R-42501",
    meaning="Active problem",
    scheme_designator="SRT"
)

INACTIVE_PROBLEM = CodedConcept(
    value="R-42502",
    meaning="Inactive problem",
    scheme_designator="SRT"
)

