"""CID 7156 VascularSegmentationTypes
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


INTIMA = CodedConcept(
    value="T-1A170",
    meaning="Intima",
    scheme_designator="SRT"
)

MEDIA = CodedConcept(
    value="T-1A180",
    meaning="Media",
    scheme_designator="SRT"
)

ADVENTITIA = CodedConcept(
    value="T-1A190",
    meaning="Adventitia",
    scheme_designator="SRT"
)

CARDIOVASCULAR_SYSTEM = CodedConcept(
    value="T-30000",
    meaning="Cardiovascular system",
    scheme_designator="SRT"
)

LUMEN = CodedConcept(
    value="T-40230",
    meaning="Lumen",
    scheme_designator="SRT"
)

SYSTEMIC_ARTERY = CodedConcept(
    value="T-4105E",
    meaning="Systemic artery",
    scheme_designator="SRT"
)

THROMBUS = CodedConcept(
    value="M-35001",
    meaning="Thrombus",
    scheme_designator="SRT"
)

VASCULAR_SCLEROSIS = CodedConcept(
    value="M-520F8",
    meaning="Vascular sclerosis",
    scheme_designator="SRT"
)

SYSTEMIC_VEIN = CodedConcept(
    value="T-48081",
    meaning="Systemic vein",
    scheme_designator="SRT"
)

