"""CID 3620 HemodynamicRatios
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


DIASTOLIC_SYSTOLIC_VELOCITY_RATIO = CodedConcept(
    value="122218",
    meaning="Diastolic/Systolic velocity ratio",
    scheme_designator="DCM"
)

HYPEREMIC_RATIO = CodedConcept(
    value="122219",
    meaning="Hyperemic ratio",
    scheme_designator="DCM"
)

CORONARY_FLOW_RESERVE = CodedConcept(
    value="122217",
    meaning="Coronary Flow reserve",
    scheme_designator="DCM"
)

HEMODYNAMIC_RESISTANCE_INDEX = CodedConcept(
    value="122220",
    meaning="Hemodynamic Resistance Index",
    scheme_designator="DCM"
)

TIBIAL_BRACHIAL_INDEX = CodedConcept(
    value="8581-1",
    meaning="Tibial/brachial index",
    scheme_designator="LN"
)

FRACTIONAL_FLOW_RESERVE_USING_INTRACORONARY_BOLUS = CodedConcept(
    value="R-00308",
    meaning="Fractional Flow Reserve using intracoronary bolus",
    scheme_designator="SRT"
)

FRACTIONAL_FLOW_RESERVE = CodedConcept(
    value="R-00307",
    meaning="Fractional flow reserve",
    scheme_designator="SRT"
)

PULMONARY_SYSTEMIC_FLOW_RATIO = CodedConcept(
    value="F-0238B",
    meaning="Pulmonary/Systemic Flow Ratio",
    scheme_designator="SRT"
)

FRACTIONAL_FLOW_RESERVE_USING_INTRAVENOUS_INFUSION = CodedConcept(
    value="R-00309",
    meaning="Fractional Flow Reserve using intravenous infusion",
    scheme_designator="SRT"
)

PULSATILITY_INDEX = CodedConcept(
    value="F-031A2",
    meaning="Pulsatility Index",
    scheme_designator="SRT"
)

