"""CID 66 MedicationforImagingAgentAdministration
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


REMIFENTANIL = CodedConcept(
    value="386839004",
    meaning="Remifentanil",
    scheme_designator="SCT"
)

SUFENTANIL = CodedConcept(
    value="49998007",
    meaning="Sufentanil",
    scheme_designator="SCT"
)

MIDAZOLAM = CodedConcept(
    value="F-6183C",
    meaning="Midazolam",
    scheme_designator="SRT"
)

PROPOFOL = CodedConcept(
    value="F-61B48",
    meaning="Propofol",
    scheme_designator="SRT"
)

ALFENTANIL = CodedConcept(
    value="F-61C65",
    meaning="Alfentanil",
    scheme_designator="SRT"
)

