"""CID 3410 NumericParametersofDrugs/Contrast
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


UNDILUTED_DOSE_ADMINISTERED = CodedConcept(
    value="122092",
    meaning="Undiluted dose administered",
    scheme_designator="DCM"
)

CONCENTRATION = CodedConcept(
    value="122093",
    meaning="Concentration",
    scheme_designator="DCM"
)

VOLUME_ADMINISTERED = CodedConcept(
    value="122091",
    meaning="Volume administered",
    scheme_designator="DCM"
)

MASS_ADMINISTERED = CodedConcept(
    value="121383",
    meaning="Mass administered",
    scheme_designator="DCM"
)

VOLUME_UNADMINISTERED_OR_DISCARDED = CodedConcept(
    value="122096",
    meaning="Volume unadministered or discarded",
    scheme_designator="DCM"
)

QUANTITY_ADMINISTERED = CodedConcept(
    value="121382",
    meaning="Quantity administered",
    scheme_designator="DCM"
)

RATE_OF_ADMINISTRATION = CodedConcept(
    value="122094",
    meaning="Rate of administration",
    scheme_designator="DCM"
)

DURATION_OF_ADMINISTRATION = CodedConcept(
    value="122095",
    meaning="Duration of administration",
    scheme_designator="DCM"
)

