"""CID 3115 StressImagingQualityIssues
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


BREAST_ATTENUATION = CodedConcept(
    value="122744",
    meaning="Breast attenuation",
    scheme_designator="DCM"
)

DIAPHRAGMATIC_ATTENUATION = CodedConcept(
    value="122745",
    meaning="Diaphragmatic attenuation",
    scheme_designator="DCM"
)

BODY_HABITUS_ATTENUATION = CodedConcept(
    value="122743",
    meaning="Body habitus attenuation",
    scheme_designator="DCM"
)

MOTION_BLUR = CodedConcept(
    value="111210",
    meaning="Motion blur",
    scheme_designator="DCM"
)

SUBDIAPHRAGMATIC_UPTAKE = CodedConcept(
    value="F-04FD3",
    meaning="Subdiaphragmatic uptake",
    scheme_designator="SRT"
)

