"""CID 6043 TypesofMammographyCADAnalysis
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


INDIVIDUAL_IMPRESSION_RECOMMENDATION_ANALYSIS = CodedConcept(
    value="111233",
    meaning="Individual Impression / Recommendation Analysis",
    scheme_designator="DCM"
)

OVERALL_IMPRESSION_RECOMMENDATION_ANALYSIS = CodedConcept(
    value="111234",
    meaning="Overall Impression / Recommendation Analysis",
    scheme_designator="DCM"
)

FOCAL_ASYMMETRIC_DENSITY_ANALYSIS = CodedConcept(
    value="P5-B3410",
    meaning="Focal asymmetric density analysis",
    scheme_designator="SRT"
)

IMAGE_QUALITY_ANALYSIS = CodedConcept(
    value="P5-B3408",
    meaning="Image quality analysis",
    scheme_designator="SRT"
)

SPATIAL_PROXIMITY_ANALYSIS = CodedConcept(
    value="P5-B3404",
    meaning="Spatial proximity analysis",
    scheme_designator="SRT"
)

TEMPORAL_CORRELATION = CodedConcept(
    value="P5-B3406",
    meaning="Temporal correlation",
    scheme_designator="SRT"
)

ASYMMETRIC_BREAST_TISSUE_ANALYSIS = CodedConcept(
    value="P5-B3412",
    meaning="Asymmetric breast tissue analysis",
    scheme_designator="SRT"
)

BREAST_COMPOSITION_ANALYSIS = CodedConcept(
    value="P5-B3414",
    meaning="Breast composition analysis",
    scheme_designator="SRT"
)

SPATIAL_COLLOCATION_ANALYSIS = CodedConcept(
    value="P5-B3402",
    meaning="Spatial collocation analysis",
    scheme_designator="SRT"
)

