"""CID 10043 IntravenousExtravasationSymptoms
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


EXTRAVASATION_VISIBLE_IN_IMAGE = CodedConcept(
    value="113568",
    meaning="Extravasation visible in image",
    scheme_designator="DCM"
)

INJECTION_SITE_STERILE_ABSCESS = CodedConcept(
    value="D0-B0326",
    meaning="Injection site sterile abscess",
    scheme_designator="SRT"
)

INJECTION_SITE_ABSCESS = CodedConcept(
    value="D0-B0324",
    meaning="Injection site abscess",
    scheme_designator="SRT"
)

INJECTION_SITE_NERVE_DAMAGE = CodedConcept(
    value="D0-B0346",
    meaning="Injection site nerve damage",
    scheme_designator="SRT"
)

INJECTION_SITE_DISORDER = CodedConcept(
    value="D0-B0300",
    meaning="Injection site disorder",
    scheme_designator="SRT"
)

INJECTION_SITE_BURNING = CodedConcept(
    value="D0-B0342",
    meaning="Injection site burning",
    scheme_designator="SRT"
)

INJECTION_SITE_CYST = CodedConcept(
    value="D0-B0364",
    meaning="Injection site cyst",
    scheme_designator="SRT"
)

INJECTION_SITE_INFECTION = CodedConcept(
    value="D0-B0320",
    meaning="Injection site infection",
    scheme_designator="SRT"
)

INJECTION_SITE_PAIN = CodedConcept(
    value="D0-B0340",
    meaning="Injection site pain",
    scheme_designator="SRT"
)

INJECTION_SITE_MASS = CodedConcept(
    value="D0-B0360",
    meaning="Injection site mass",
    scheme_designator="SRT"
)

INJECTION_SITE_PARESTHESIA = CodedConcept(
    value="D0-B0382",
    meaning="Injection site paresthesia",
    scheme_designator="SRT"
)

INJECTION_SITE_ANESTHESIA = CodedConcept(
    value="D0-B0380",
    meaning="Injection site anesthesia",
    scheme_designator="SRT"
)

INJECTION_SITE_MALABSORPTION = CodedConcept(
    value="D0-B0339",
    meaning="Injection site malabsorption",
    scheme_designator="SRT"
)

INJECTION_SITE_GRANULOMA = CodedConcept(
    value="M-44150",
    meaning="Injection site granuloma",
    scheme_designator="SRT"
)

INJECTION_SITE_THROMBOSIS = CodedConcept(
    value="D0-B0338",
    meaning="Injection site thrombosis",
    scheme_designator="SRT"
)

INJECTION_SITE_PIGMENTATION_CHANGE = CodedConcept(
    value="D0-B0314",
    meaning="Injection site pigmentation change",
    scheme_designator="SRT"
)

INJECTION_SITE_HEMORRHAGE = CodedConcept(
    value="D0-B0334",
    meaning="Injection site hemorrhage",
    scheme_designator="SRT"
)

INJECTION_SITE_IRRITATION = CodedConcept(
    value="D0-B0312",
    meaning="Injection site irritation",
    scheme_designator="SRT"
)

INJECTION_SITE_URTICARIA = CodedConcept(
    value="D0-B0356",
    meaning="Injection site urticaria",
    scheme_designator="SRT"
)

INJECTION_SITE_HYPERSENSITIVITY = CodedConcept(
    value="D0-B0311",
    meaning="Injection site hypersensitivity",
    scheme_designator="SRT"
)

INJECTION_SITE_DERMATITIS = CodedConcept(
    value="D0-B0354",
    meaning="Injection site dermatitis",
    scheme_designator="SRT"
)

INJECTION_SITE_REACTION = CodedConcept(
    value="D0-B0310",
    meaning="Injection site reaction",
    scheme_designator="SRT"
)

INJECTION_SITE_SCAR = CodedConcept(
    value="M-78066",
    meaning="Injection site scar",
    scheme_designator="SRT"
)

INJECTION_SITE_EDEMA = CodedConcept(
    value="D0-B0352",
    meaning="Injection site edema",
    scheme_designator="SRT"
)

INJECTION_SITE_BRUISING = CodedConcept(
    value="D0-B0394",
    meaning="Injection site bruising",
    scheme_designator="SRT"
)

INJECTION_SITE_INFLAMMATION = CodedConcept(
    value="D0-B0350",
    meaning="Injection site inflammation",
    scheme_designator="SRT"
)

INJECTION_SITE_NECROSIS = CodedConcept(
    value="D0-B0370",
    meaning="Injection site necrosis",
    scheme_designator="SRT"
)

INJECTION_SITE_ULCER = CodedConcept(
    value="D0-B0390",
    meaning="Injection site ulcer",
    scheme_designator="SRT"
)

INJECTION_SITE_ATROPHY = CodedConcept(
    value="D0-B03A4",
    meaning="Injection site atrophy",
    scheme_designator="SRT"
)

INJECTION_SITE_FIBROSIS = CodedConcept(
    value="D0-B03A2",
    meaning="Injection site fibrosis",
    scheme_designator="SRT"
)

INJECTION_SITE_INDURATION = CodedConcept(
    value="D0-B03A0",
    meaning="Injection site induration",
    scheme_designator="SRT"
)

