"""CID 9521 RadiotherapyTreatmentEnergyUnit
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


KILOVOLT = CodedConcept(
    value="kV",
    meaning="Kilovolt",
    scheme_designator="UCUM"
)

MEGAVOLT = CodedConcept(
    value="MV",
    meaning="Megavolt",
    scheme_designator="UCUM"
)

MEGAELECTRONVOLT = CodedConcept(
    value="MeV",
    meaning="Megaelectronvolt",
    scheme_designator="UCUM"
)

