"""CID 3721 CardiovascularSurgeries
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


ABLATION_OPERATION_FOR_ARRHYTHMIA = CodedConcept(
    value="P1-31C03",
    meaning="Ablation operation for arrhythmia",
    scheme_designator="SRT"
)

IMPLANTATION_OF_CARDIAC_PACEMAKER = CodedConcept(
    value="P0-004BA",
    meaning="Implantation of cardiac pacemaker",
    scheme_designator="SRT"
)

CORONARY_ARTERY_BYPASS_GRAFT = CodedConcept(
    value="P1-3301A",
    meaning="Coronary artery bypass graft",
    scheme_designator="SRT"
)

OPERATION_ON_HEART_VALVE = CodedConcept(
    value="P1-32000",
    meaning="Operation on heart valve",
    scheme_designator="SRT"
)

CORRECTION_OF_CONGENITAL_CARDIOVASCULAR_DEFORMITY = CodedConcept(
    value="P1-080B4",
    meaning="Correction of congenital cardiovascular deformity",
    scheme_designator="SRT"
)

PERCUTANEOUS_CORONARY_INTERVENTION = CodedConcept(
    value="R-102B4",
    meaning="Percutaneous coronary intervention",
    scheme_designator="SRT"
)

IMPLANTATION_OF_AUTOMATIC_CARDIAC_DEFIBRILLATOR = CodedConcept(
    value="P1-3157D",
    meaning="Implantation of automatic cardiac defibrillator",
    scheme_designator="SRT"
)

ABDOMINAL_AORTIC_ANEURYSM_STENTING = CodedConcept(
    value="P1-0555A",
    meaning="Abdominal aortic aneurysm stenting",
    scheme_designator="SRT"
)

HEART_TRANSPLANT = CodedConcept(
    value="P1-31D00",
    meaning="Heart transplant",
    scheme_designator="SRT"
)

