"""CID 9504 RTGeometricInformation
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


PATIENT_SETUP_POINT = CodedConcept(
    value="130069",
    meaning="Patient Setup Point",
    scheme_designator="DCM"
)

REFERENCE_ACQUISITION_POINT = CodedConcept(
    value="130072",
    meaning="Reference Acquisition Point",
    scheme_designator="DCM"
)

MOVEABLE_LASER_PATIENT_SETUP_POINT = CodedConcept(
    value="130071",
    meaning="Moveable Laser Patient Setup Point",
    scheme_designator="DCM"
)

ROOM_LASER_PATIENT_SETUP_POINT = CodedConcept(
    value="130070",
    meaning="Room Laser Patient Setup Point",
    scheme_designator="DCM"
)

ISOCENTRIC_TREATMENT_LOCATION_POINT = CodedConcept(
    value="130073",
    meaning="Isocentric Treatment Location Point",
    scheme_designator="DCM"
)

