"""CID 8109 SpecimenCollectionProcedure
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


BIOPSY = CodedConcept(
    value="P1-03100",
    meaning="Biopsy",
    scheme_designator="SRT"
)

EXCISION = CodedConcept(
    value="P1-03000",
    meaning="Excision",
    scheme_designator="SRT"
)

SCRAPING = CodedConcept(
    value="P1-03154",
    meaning="Scraping",
    scheme_designator="SRT"
)

REMOVAL_OF_DEVICE = CodedConcept(
    value="P1-03021",
    meaning="Removal of device",
    scheme_designator="SRT"
)

ASPIRATION = CodedConcept(
    value="P1-03130",
    meaning="Aspiration",
    scheme_designator="SRT"
)

VENIPUNCTURE = CodedConcept(
    value="P1-38200",
    meaning="Venipuncture",
    scheme_designator="SRT"
)

HARVESTING_OF_TISSUE = CodedConcept(
    value="P1-0D300",
    meaning="Harvesting of tissue",
    scheme_designator="SRT"
)

TAKING_OF_SWAB = CodedConcept(
    value="P0-00593",
    meaning="Taking of swab",
    scheme_designator="SRT"
)

SPECIMEN_COLLECTION = CodedConcept(
    value="P3-02000",
    meaning="Specimen collection",
    scheme_designator="SRT"
)

