"""CID 7023 RTProcessOutput
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


RT_PLANNING_RESULT = CodedConcept(
    value="128189",
    meaning="RT Planning Result",
    scheme_designator="DCM"
)

RT_TREATMENT_SIMULATION_RESULT = CodedConcept(
    value="128188",
    meaning="RT Treatment Simulation Result",
    scheme_designator="DCM"
)

DOSIMETRIC_RESULT = CodedConcept(
    value="128190",
    meaning="Dosimetric Result",
    scheme_designator="DCM"
)

RT_TREATMENT_SESSION_RESULT = CodedConcept(
    value="128192",
    meaning="RT Treatment Session Result",
    scheme_designator="DCM"
)

PATIENT_SETUP_VERIFICATION_RESULT = CodedConcept(
    value="128191",
    meaning="Patient Setup Verification Result",
    scheme_designator="DCM"
)

RT_TREATMENT_QA_RESULT = CodedConcept(
    value="128194",
    meaning="RT Treatment QA Result",
    scheme_designator="DCM"
)

RT_TREATMENT_COURSE_SUMMARY = CodedConcept(
    value="128193",
    meaning="RT Treatment Course Summary",
    scheme_designator="DCM"
)

RT_PRESCRIPTION_RESULT = CodedConcept(
    value="128185",
    meaning="RT Prescription Result",
    scheme_designator="DCM"
)

PREPLANNING_RESULT = CodedConcept(
    value="128184",
    meaning="Pre-Planning Result",
    scheme_designator="DCM"
)

COORDINATE_ALIGNMENT_IMAGE_SERIES = CodedConcept(
    value="128187",
    meaning="Coordinate Alignment Image Series",
    scheme_designator="DCM"
)

DOSE_CALCULATION_IMAGE_SERIES = CodedConcept(
    value="128186",
    meaning="Dose Calculation Image Series",
    scheme_designator="DCM"
)

