"""CID 638 ExogenousSubstance
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


HUMAN_ALPHA_SYNUCLEIN_PREFORMED_FIBRILS = CodedConcept(
    value="127851",
    meaning="Human alpha synuclein preformed fibrils",
    scheme_designator="DCM"
)

MOUSE_ALPHA_SYNUCLEIN_PREFORMED_FIBRILS = CodedConcept(
    value="127852",
    meaning="Mouse alpha synuclein preformed fibrils",
    scheme_designator="DCM"
)

HUMAN_TAU_PREFORMED_FIBRILS = CodedConcept(
    value="127853",
    meaning="Human Tau preformed fibrils",
    scheme_designator="DCM"
)

MOUSE_TAU_PREFORMED_FIBRILS = CodedConcept(
    value="127854",
    meaning="Mouse Tau preformed fibrils",
    scheme_designator="DCM"
)

BRONCHIOLOALVEOLAR_ADENOCARCINOMA = CodedConcept(
    value="C2923",
    meaning="Bronchioloalveolar adenocarcinoma",
    scheme_designator="NCIt"
)

HYDROXYDOPAMINE_6 = CodedConcept(
    value="4624",
    meaning="6-hydroxydopamine",
    scheme_designator="PUBCHEM_CID"
)

VASCULAR_ENDOTHELIAL_GROWTH_FACTOR = CodedConcept(
    value="F-CB902",
    meaning="Vascular endothelial growth factor",
    scheme_designator="SRT"
)

ADENOCARCINOMA = CodedConcept(
    value="M-81403",
    meaning="Adenocarcinoma",
    scheme_designator="SRT"
)

SMALL_CELL_CARCINOMA = CodedConcept(
    value="M-80413",
    meaning="Small cell carcinoma",
    scheme_designator="SRT"
)

TUMOR_NECROSIS_FACTOR_ALPHA = CodedConcept(
    value="F-CB962",
    meaning="Tumor necrosis factor alpha",
    scheme_designator="SRT"
)

RENAL_CELL_CARCINOMA = CodedConcept(
    value="R-FB83F",
    meaning="Renal cell carcinoma",
    scheme_designator="SRT"
)

ASTROCYTOMA = CodedConcept(
    value="M-94003",
    meaning="Astrocytoma",
    scheme_designator="SRT"
)

MELANOMA = CodedConcept(
    value="M-87203",
    meaning="Melanoma",
    scheme_designator="SRT"
)

LYSOPHOSPHATIDYLCHOLINE = CodedConcept(
    value="F-63750",
    meaning="Lysophosphatidylcholine",
    scheme_designator="SRT"
)

MESOTHELIOMA = CodedConcept(
    value="M-90503",
    meaning="Mesothelioma",
    scheme_designator="SRT"
)

CARCINOSARCOMA = CodedConcept(
    value="M-89803",
    meaning="Carcinosarcoma",
    scheme_designator="SRT"
)

INTERFERON_GAMMA = CodedConcept(
    value="F-C0101",
    meaning="Interferon gamma",
    scheme_designator="SRT"
)

AMELANOTIC_MELANOMA = CodedConcept(
    value="M-87303",
    meaning="Amelanotic melanoma",
    scheme_designator="SRT"
)

GLIOBLASTOMA = CodedConcept(
    value="M-94403",
    meaning="Glioblastoma",
    scheme_designator="SRT"
)

THEILER_S_MURINE_ENCEPHALOMYELITIS_VIRUS = CodedConcept(
    value="L-30606",
    meaning="Theiler's murine encephalomyelitis virus",
    scheme_designator="SRT"
)

MIXED_SMALL_CELL_CARCINOMA = CodedConcept(
    value="M-80453",
    meaning="Mixed small cell carcinoma",
    scheme_designator="SRT"
)

SQUAMOUS_CELL_CARCINOMA = CodedConcept(
    value="M-80703",
    meaning="Squamous cell carcinoma",
    scheme_designator="SRT"
)

LEUKEMIA = CodedConcept(
    value="DC-F4113",
    meaning="Leukemia",
    scheme_designator="SRT"
)

CARCINOMA = CodedConcept(
    value="M-80103",
    meaning="Carcinoma",
    scheme_designator="SRT"
)

SPINDLE_CELL_CARCINOMA = CodedConcept(
    value="M-80323",
    meaning="Spindle cell carcinoma",
    scheme_designator="SRT"
)

CYSTADENOCARCINOMA = CodedConcept(
    value="M-84403",
    meaning="Cystadenocarcinoma",
    scheme_designator="SRT"
)

ADENOASSOCIATED_VIRUS_GROUP = CodedConcept(
    value="L-35500",
    meaning="Adeno-associated virus group",
    scheme_designator="SRT"
)

LIPOPOLYSACCHARIDE = CodedConcept(
    value="F-63390",
    meaning="Lipopolysaccharide",
    scheme_designator="SRT"
)

SARCOMA = CodedConcept(
    value="M-88003",
    meaning="Sarcoma",
    scheme_designator="SRT"
)

INFILTRATING_DUCTAL_CARCINOMA_OF_BREAST = CodedConcept(
    value="D0-F0369",
    meaning="Infiltrating ductal carcinoma of breast",
    scheme_designator="SRT"
)

NONSMALL_CELL_CARCINOMA = CodedConcept(
    value="M-80463",
    meaning="Non-small cell carcinoma",
    scheme_designator="SRT"
)

LARGE_CELL_CARCINOMA = CodedConcept(
    value="M-80123",
    meaning="Large cell carcinoma",
    scheme_designator="SRT"
)

OSTEOSARCOMA = CodedConcept(
    value="M-91803",
    meaning="Osteosarcoma",
    scheme_designator="SRT"
)

ETHIDIUM_BROMIDE = CodedConcept(
    value="C0019873",
    meaning="Ethidium Bromide",
    scheme_designator="UMLS"
)

