"""CID 12012 OBEquationsandTables
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


FWP_BY_GA_CAMPBELL_1991 = CodedConcept(
    value="128040",
    meaning="FWP by GA, Campbell, 1991",
    scheme_designator="DCM"
)

FWP_BY_GA_HADLOCK_1991 = CodedConcept(
    value="128041",
    meaning="FWP by GA, Hadlock, 1991",
    scheme_designator="DCM"
)

AC_JEANTY_1984 = CodedConcept(
    value="11893-5",
    meaning="AC, Jeanty 1984",
    scheme_designator="LN"
)

CRL_BY_GA_REMPEN1991 = CodedConcept(
    value="33160-3",
    meaning="CRL by GA, Rempen1991",
    scheme_designator="LN"
)

AC_JEANTY_1982 = CodedConcept(
    value="33537-2",
    meaning="AC, Jeanty 1982",
    scheme_designator="LN"
)

OFD_ASUM_2000 = CodedConcept(
    value="33119-9",
    meaning="OFD, ASUM 2000",
    scheme_designator="LN"
)

FIBULA_BY_GA_JEANTY_1983 = CodedConcept(
    value="33164-5",
    meaning="Fibula by GA, Jeanty 1983",
    scheme_designator="LN"
)

CRL_HANSMANN_1985 = CodedConcept(
    value="11911-5",
    meaning="CRL, Hansmann 1985",
    scheme_designator="LN"
)

FEMALE_SINGLETON_BWP_BY_GA_ARBUCKLE_1993 = CodedConcept(
    value="33187-6",
    meaning="Female Singleton BWP by GA, Arbuckle 1993",
    scheme_designator="LN"
)

FETAL_TRUNK_CROSSSECTIONAL_AREA_OSAKA_1989 = CodedConcept(
    value="33138-9",
    meaning="Fetal Trunk Cross-Sectional Area, Osaka 1989",
    scheme_designator="LN"
)

BPD_MERTZ_1988 = CodedConcept(
    value="33081-1",
    meaning="BPD, Mertz 1988",
    scheme_designator="LN"
)

HC_JEANTY_1984 = CodedConcept(
    value="11934-7",
    meaning="HC, Jeanty 1984",
    scheme_designator="LN"
)

EFW_BY_AC_FL_HC_HADLOCK_1985 = CodedConcept(
    value="11746-5",
    meaning="EFW by AC, FL, HC, Hadlock 1985",
    scheme_designator="LN"
)

FL_BY_GA_JEANTY_1982 = CodedConcept(
    value="33168-6",
    meaning="FL by GA, Jeanty 1982",
    scheme_designator="LN"
)

HC_MERZ_1988 = CodedConcept(
    value="33115-7",
    meaning="HC Merz, 1988",
    scheme_designator="LN"
)

RADIUS_JEANTY_1983 = CodedConcept(
    value="33126-4",
    meaning="Radius, Jeanty 1983",
    scheme_designator="LN"
)

CEPHALIC_INDEX_BY_GA_CHITTY_1994 = CodedConcept(
    value="33157-9",
    meaning="Cephalic Index by GA, Chitty 1994",
    scheme_designator="LN"
)

FL_TOKYO_1986 = CodedConcept(
    value="33103-3",
    meaning="FL, Tokyo 1986",
    scheme_designator="LN"
)

EFW_BY_AC_BPD_FL_HADLOCK_1984 = CodedConcept(
    value="11734-1",
    meaning="EFW by AC, BPD, FL, Hadlock 1984",
    scheme_designator="LN"
)

CRL_HANSMANN_1986 = CodedConcept(
    value="33540-6",
    meaning="CRL, Hansmann 1986",
    scheme_designator="LN"
)

AC_BY_GA_ASUM_2000 = CodedConcept(
    value="33145-4",
    meaning="AC by GA, ASUM 2000",
    scheme_designator="LN"
)

BPD_TOKYO_1986 = CodedConcept(
    value="33085-2",
    meaning="BPD, Tokyo 1986",
    scheme_designator="LN"
)

IOD_MAYDEN_1982 = CodedConcept(
    value="33122-3",
    meaning="IOD, Mayden 1982",
    scheme_designator="LN"
)

TIBIA_JEANTY_1984 = CodedConcept(
    value="11941-2",
    meaning="Tibia, Jeanty 1984",
    scheme_designator="LN"
)

CRL_ASUM_1991 = CodedConcept(
    value="33089-4",
    meaning="CRL, ASUM 1991",
    scheme_designator="LN"
)

EFW1_BY_SHINOZUKA_1996 = CodedConcept(
    value="33141-3",
    meaning="EFW1 by Shinozuka 1996",
    scheme_designator="LN"
)

GESTATIONAL_AGE_BY_LMP = CodedConcept(
    value="11885-1",
    meaning="Gestational Age by LMP",
    scheme_designator="LN"
)

MALE_TWINS_BWP_BY_GA_ARBUCKLE_1993 = CodedConcept(
    value="33199-1",
    meaning="Male Twins BWP by GA, Arbuckle 1993",
    scheme_designator="LN"
)

BD_JEANTY_1982 = CodedConcept(
    value="33545-5",
    meaning="BD, Jeanty 1982",
    scheme_designator="LN"
)

HC_BY_GA_ASUM_2000 = CodedConcept(
    value="33172-8",
    meaning="HC by GA, ASUM 2000",
    scheme_designator="LN"
)

BPD_BY_GA_JEANTY_1982 = CodedConcept(
    value="33153-8",
    meaning="BPD by GA, Jeanty 1982",
    scheme_designator="LN"
)

BPD_DOUBILET_1993 = CodedConcept(
    value="11900-8",
    meaning="BPD, Doubilet 1993",
    scheme_designator="LN"
)

GS_TOKYO_1986 = CodedConcept(
    value="33108-2",
    meaning="GS, Tokyo 1986",
    scheme_designator="LN"
)

EFW_BY_AC_BPD_HADLOCK_1984 = CodedConcept(
    value="11738-2",
    meaning="EFW by AC, BPD, Hadlock 1984",
    scheme_designator="LN"
)

HC_BY_GA_MERZ_1988 = CodedConcept(
    value="33176-9",
    meaning="HC by GA, Merz 1988",
    scheme_designator="LN"
)

TCD_HILL_1990 = CodedConcept(
    value="33134-8",
    meaning="TCD, Hill 1990",
    scheme_designator="LN"
)

CRL_OSAKA_1989 = CodedConcept(
    value="33093-6",
    meaning="CRL, Osaka 1989",
    scheme_designator="LN"
)

HC_DERIVED_CHITTY_1997 = CodedConcept(
    value="33111-6",
    meaning="HC derived, Chitty 1997",
    scheme_designator="LN"
)

BPD_OUTERINNER_BY_GA_CHITTY_1994 = CodedConcept(
    value="33556-2",
    meaning="BPD outer-inner by GA, Chitty 1994",
    scheme_designator="LN"
)

TAD_TOKYO_1986 = CodedConcept(
    value="33130-6",
    meaning="TAD, Tokyo 1986",
    scheme_designator="LN"
)

AC_LESSOWAY_1998 = CodedConcept(
    value="33074-6",
    meaning="AC, Lessoway 1998",
    scheme_designator="LN"
)

AXT_SHINOZUKA_1996 = CodedConcept(
    value="33078-7",
    meaning="AxT, Shinozuka 1996",
    scheme_designator="LN"
)

FIBULA_JEANTY_1983 = CodedConcept(
    value="33097-7",
    meaning="Fibula, Jeanty 1983",
    scheme_designator="LN"
)

RADIUS_MERZ_1987 = CodedConcept(
    value="11939-6",
    meaning="Radius, Merz 1987",
    scheme_designator="LN"
)

HC_AC_BY_GA_CAMPBELL_1977 = CodedConcept(
    value="33182-7",
    meaning="HC/AC by GA, Campbell 1977",
    scheme_designator="LN"
)

EFW_BY_GA_HANSMANN_1986 = CodedConcept(
    value="33163-7",
    meaning="EFW by GA, Hansmann 1986",
    scheme_designator="LN"
)

MALE_SINGLETON_BWP_BY_GA_ARBUCKLE_1993 = CodedConcept(
    value="33186-8",
    meaning="Male Singleton BWP by GA, Arbuckle 1993",
    scheme_designator="LN"
)

FL_BY_GA_CHITTY_1994 = CodedConcept(
    value="33167-8",
    meaning="FL by GA, Chitty 1994",
    scheme_designator="LN"
)

OOD_TROUT_1994 = CodedConcept(
    value="33125-6",
    meaning="OOD, Trout 1994",
    scheme_designator="LN"
)

EFW_BY_AC_FL_HADLOCK_1984 = CodedConcept(
    value="11750-7",
    meaning="EFW by AC, FL, Hadlock 1984",
    scheme_designator="LN"
)

EFW_BY_BPD_APAD_TAD_FL_TOKYO_1987 = CodedConcept(
    value="33144-7",
    meaning="EFW by BPD, APAD, TAD, FL, Tokyo 1987",
    scheme_designator="LN"
)

BPD_LESSOWAY_1998 = CodedConcept(
    value="33080-3",
    meaning="BPD, Lessoway 1998",
    scheme_designator="LN"
)

FL_HANSMANN_1986 = CodedConcept(
    value="33541-4",
    meaning="FL, Hansmann 1986",
    scheme_designator="LN"
)

FL_SHINOZUKA_1996 = CodedConcept(
    value="33102-5",
    meaning="FL, Shinozuka 1996",
    scheme_designator="LN"
)

OFD_LESSOWAY_1998 = CodedConcept(
    value="33121-5",
    meaning="OFD, Lessoway 1998",
    scheme_designator="LN"
)

BPD_SHINOZUKA_1996 = CodedConcept(
    value="33084-5",
    meaning="BPD, Shinozuka 1996",
    scheme_designator="LN"
)

FL_JEANTY_1984 = CodedConcept(
    value="11923-0",
    meaning="FL, Jeanty 1984",
    scheme_designator="LN"
)

CLAVICLE_LENGTH_YARKONI_1985 = CodedConcept(
    value="33088-6",
    meaning="Clavicle length, Yarkoni 1985",
    scheme_designator="LN"
)

EFW_BY_BPD_FTA_FL_OSAKA_1990 = CodedConcept(
    value="33140-5",
    meaning="EFW by BPD, FTA, FL, Osaka 1990",
    scheme_designator="LN"
)

FL_MERZ_1987 = CodedConcept(
    value="11924-8",
    meaning="FL, Merz 1987",
    scheme_designator="LN"
)

GS_BY_GA_REMPEN_1991 = CodedConcept(
    value="33171-0",
    meaning="GS by GA, Rempen 1991",
    scheme_designator="LN"
)

BPD_JEANTY_1984 = CodedConcept(
    value="11905-7",
    meaning="BPD, Jeanty 1984",
    scheme_designator="LN"
)

BPD_OUTEROUTER_BY_GA_CHITTY_1994 = CodedConcept(
    value="33152-0",
    meaning="BPD outer-outer by GA, Chitty 1994",
    scheme_designator="LN"
)

GS_HELLMAN_1969 = CodedConcept(
    value="11928-9",
    meaning="GS, Hellman 1969",
    scheme_designator="LN"
)

HC_BY_GA_JEANTY_1982 = CodedConcept(
    value="33175-1",
    meaning="HC by GA, Jeanty 1982",
    scheme_designator="LN"
)

BPD_BY_GA_SHINOZUKA_1996 = CodedConcept(
    value="33156-1",
    meaning="BPD by GA, Shinozuka 1996",
    scheme_designator="LN"
)

BPD_BY_GA_HADLOCK_1984 = CodedConcept(
    value="33198-3",
    meaning="BPD by GA, Hadlock 1984",
    scheme_designator="LN"
)

OFD_BY_GA_CHITTY_1994 = CodedConcept(
    value="33179-3",
    meaning="OFD by GA, Chitty 1994",
    scheme_designator="LN"
)

EFW_BY_AC_HC_HADLOCK_1984 = CodedConcept(
    value="11754-9",
    meaning="EFW by AC, HC Hadlock 1984",
    scheme_designator="LN"
)

FL_HADLOCK_1984 = CodedConcept(
    value="11920-6",
    meaning="FL, Hadlock 1984",
    scheme_designator="LN"
)

EFW_BY_AC_BPD_FL_HADLOCK_1985 = CodedConcept(
    value="11735-8",
    meaning="EFW by AC, BPD, FL, Hadlock 1985",
    scheme_designator="LN"
)

BPDA_HADLOCK_1982 = CodedConcept(
    value="11901-6",
    meaning="BPDa, Hadlock 1982",
    scheme_designator="LN"
)

AC_BY_GA_SHINOZUKA_1996 = CodedConcept(
    value="33149-6",
    meaning="AC by GA, Shinozuka 1996",
    scheme_designator="LN"
)

GS_NYBERG_1992 = CodedConcept(
    value="33107-4",
    meaning="GS, Nyberg 1992",
    scheme_designator="LN"
)

EFW_BY_AC_AND_BPD_SHEPARD_1982 = CodedConcept(
    value="11739-0",
    meaning="EFW by AC and BPD, Shepard 1982",
    scheme_designator="LN"
)

LENGTH_OF_VERTEBRA_TOKYO_1986 = CodedConcept(
    value="33118-1",
    meaning="Length of Vertebra, Tokyo 1986",
    scheme_designator="LN"
)

CRL_JEANTY_1982 = CodedConcept(
    value="33092-8",
    meaning="CRL, Jeanty 1982",
    scheme_designator="LN"
)

HC_MEASURED_CHITTY_1997 = CodedConcept(
    value="33110-8",
    meaning="HC measured, Chitty 1997",
    scheme_designator="LN"
)

TRANSVERSE_THORACIC_DIAMETER_LESSOWAY_1998 = CodedConcept(
    value="33137-1",
    meaning="Transverse Thoracic Diameter, Lessoway 1998",
    scheme_designator="LN"
)

HC_LESSOWAY_1998 = CodedConcept(
    value="33114-0",
    meaning="HC, Lessoway 1998",
    scheme_designator="LN"
)

BPD_HANSMANN_1986 = CodedConcept(
    value="33538-0",
    meaning="BPD, Hansmann 1986",
    scheme_designator="LN"
)

TCD_GOLDSTEIN_1987 = CodedConcept(
    value="33133-0",
    meaning="TCD, Goldstein 1987",
    scheme_designator="LN"
)

AC_HANSMANN1985 = CodedConcept(
    value="33073-8",
    meaning="AC, Hansmann1985",
    scheme_designator="LN"
)

AP_ABDOMINAL_DIAMETER_LESSOWAY_1998 = CodedConcept(
    value="33077-9",
    meaning="A-P Abdominal Diameter, Lessoway 1998",
    scheme_designator="LN"
)

CRL_TOKYO_1986 = CodedConcept(
    value="33096-9",
    meaning="CRL, Tokyo 1986",
    scheme_designator="LN"
)

FWP_BY_GA_HADLOCK_1985 = CodedConcept(
    value="33190-0",
    meaning="FWP by GA, Hadlock 1985",
    scheme_designator="LN"
)

FWP_BY_GA_ALEXANDER_1996 = CodedConcept(
    value="33185-0",
    meaning="FWP by GA, Alexander, 1996",
    scheme_designator="LN"
)

FL_BY_GA_HADLOCK_1984 = CodedConcept(
    value="33166-0",
    meaning="FL by GA, Hadlock 1984",
    scheme_designator="LN"
)

CRL_NELSON_1981 = CodedConcept(
    value="11913-1",
    meaning="CRL, Nelson 1981",
    scheme_designator="LN"
)

FWP_BY_GA_BRENNER_1976 = CodedConcept(
    value="33189-2",
    meaning="FWP by GA, Brenner 1976",
    scheme_designator="LN"
)

HUMERUS_JEANTY_1984 = CodedConcept(
    value="11936-2",
    meaning="Humerus, Jeanty 1984",
    scheme_designator="LN"
)

TCD_BY_GA_GOLDSTEIN_1987 = CodedConcept(
    value="33181-9",
    meaning="TCD by GA Goldstein 1987",
    scheme_designator="LN"
)

EFW_BY_GA_HADLOCK_1991 = CodedConcept(
    value="33162-9",
    meaning="EFW by GA, Hadlock 1991",
    scheme_designator="LN"
)

BPD_JEANTY_1982 = CodedConcept(
    value="33539-8",
    meaning="BPD, Jeanty 1982",
    scheme_designator="LN"
)

CRL_JEANTY_1984 = CodedConcept(
    value="11917-2",
    meaning="CRL, Jeanty 1984",
    scheme_designator="LN"
)

FL_OSAKA_1989 = CodedConcept(
    value="33101-7",
    meaning="FL, Osaka 1989",
    scheme_designator="LN"
)

HC_ASUM_2000 = CodedConcept(
    value="33109-0",
    meaning="HC, ASUM 2000",
    scheme_designator="LN"
)

EFW3_BY_SHINOZUKA_1996 = CodedConcept(
    value="33143-9",
    meaning="EFW3 by Shinozuka 1996",
    scheme_designator="LN"
)

FL_MERZ_1988 = CodedConcept(
    value="33542-2",
    meaning="FL, Merz 1988",
    scheme_designator="LN"
)

TAD_ERIKSEN_1985 = CodedConcept(
    value="33128-0",
    meaning="TAD, Eriksen 1985",
    scheme_designator="LN"
)

EFW_BY_AC_FL_HADLOCK_1985 = CodedConcept(
    value="11751-5",
    meaning="EFW by AC, FL, Hadlock 1985",
    scheme_designator="LN"
)

BPD_REMPEN_1991 = CodedConcept(
    value="33083-7",
    meaning="BPD, Rempen 1991",
    scheme_designator="LN"
)

OFD_HANSMANN_1986 = CodedConcept(
    value="33120-7",
    meaning="OFD, Hansmann 1986",
    scheme_designator="LN"
)

AC_MEASURED_BY_GA_CHITTY_1994 = CodedConcept(
    value="33147-0",
    meaning="AC (measured) by GA, Chitty 1994",
    scheme_designator="LN"
)

AC_DERIVED_BY_GA_CHITTY_1994 = CodedConcept(
    value="33546-3",
    meaning="AC (derived) by GA, Chitty 1994",
    scheme_designator="LN"
)

BPDOO_CHITTY_1997 = CodedConcept(
    value="33087-8",
    meaning="BPD-oo, Chitty 1997",
    scheme_designator="LN"
)

FL_BY_GA_SHINOZUKA_1996 = CodedConcept(
    value="33170-2",
    meaning="FL by GA, Shinozuka 1996",
    scheme_designator="LN"
)

BPD_KURTZ_1980 = CodedConcept(
    value="11906-5",
    meaning="BPD, Kurtz 1980",
    scheme_designator="LN"
)

BPD_BY_GA_ASUM_2000 = CodedConcept(
    value="33151-2",
    meaning="BPD by GA, ASUM 2000",
    scheme_designator="LN"
)

GS_REMPEN_1991 = CodedConcept(
    value="11929-7",
    meaning="GS, Rempen 1991",
    scheme_designator="LN"
)

HC_DERIVED_BY_GA_CHITTY_1994 = CodedConcept(
    value="33174-4",
    meaning="HC derived by GA, Chitty 1994",
    scheme_designator="LN"
)

FL_HANSMANN_1985 = CodedConcept(
    value="11921-4",
    meaning="FL, Hansmann 1985",
    scheme_designator="LN"
)

CRL_DAYA_1993 = CodedConcept(
    value="33091-0",
    meaning="CRL, Daya 1993",
    scheme_designator="LN"
)

BPD_BY_GA_REMPEN_1991 = CodedConcept(
    value="33155-3",
    meaning="BPD by GA, Rempen 1991",
    scheme_designator="LN"
)

TAD_HANSMANN_1979 = CodedConcept(
    value="33129-8",
    meaning="TAD Hansmann, 1979",
    scheme_designator="LN"
)

BPD_HADLOCK_1984 = CodedConcept(
    value="11902-4",
    meaning="BPD, Hadlock 1984",
    scheme_designator="LN"
)

GS_HANSMANN_1982 = CodedConcept(
    value="33106-6",
    meaning="GS, Hansmann 1982",
    scheme_designator="LN"
)

AC_BY_GA_MERZ_1988 = CodedConcept(
    value="33148-8",
    meaning="AC by GA, Merz 1988",
    scheme_designator="LN"
)

OFD_BY_GA_ASUM_2000 = CodedConcept(
    value="33178-5",
    meaning="OFD by GA, ASUM 2000",
    scheme_designator="LN"
)

EFW_BY_AC_BPD_FL_HC_HADLOCK_1985 = CodedConcept(
    value="11732-5",
    meaning="EFW by AC, BPD, FL, HC, Hadlock 1985",
    scheme_designator="LN"
)

ULNA_JEANTY_1984 = CodedConcept(
    value="11944-6",
    meaning="Ulna, Jeanty 1984",
    scheme_designator="LN"
)

CRL_BY_GA_ASUM_2000 = CodedConcept(
    value="33159-5",
    meaning="CRL by GA ASUM 2000",
    scheme_designator="LN"
)

HUMERUS_LENGTH_OSAKA_1989 = CodedConcept(
    value="33117-3",
    meaning="Humerus Length, Osaka 1989",
    scheme_designator="LN"
)

AC_ASUM_2000 = CodedConcept(
    value="33072-0",
    meaning="AC, ASUM 2000",
    scheme_designator="LN"
)

TRANSVERSE_THORACIC_DIAMETER_HANSMANN_1985 = CodedConcept(
    value="33136-3",
    meaning="Transverse Thoracic Diameter, Hansmann 1985",
    scheme_designator="LN"
)

HC_HADLOCK_1984 = CodedConcept(
    value="11932-1",
    meaning="HC, Hadlock 1984",
    scheme_designator="LN"
)

HC_JEANTY_1982 = CodedConcept(
    value="33113-2",
    meaning="HC, Jeanty 1982",
    scheme_designator="LN"
)

AC_SHINOZUKA_1996 = CodedConcept(
    value="33076-1",
    meaning="AC, Shinozuka 1996",
    scheme_designator="LN"
)

CRL_SHINOZUKA_1996 = CodedConcept(
    value="33095-1",
    meaning="CRL, Shinozuka 1996",
    scheme_designator="LN"
)

TCD_CHITTY_1994 = CodedConcept(
    value="33132-2",
    meaning="TCD, Chitty 1994",
    scheme_designator="LN"
)

FL_JEANTY_1982 = CodedConcept(
    value="33099-3",
    meaning="FL, Jeanty 1982",
    scheme_designator="LN"
)

CRL_BY_GA_SHINOZUKA_1996 = CodedConcept(
    value="33161-1",
    meaning="CRL by GA, Shinozuka 1996",
    scheme_designator="LN"
)

AC_HADLOCK_1984 = CodedConcept(
    value="11892-7",
    meaning="AC, Hadlock 1984",
    scheme_designator="LN"
)

CRL_ROBINSON_1975 = CodedConcept(
    value="11914-9",
    meaning="CRL, Robinson 1975",
    scheme_designator="LN"
)

FWP_BY_GA_WILLIAMS_1982 = CodedConcept(
    value="33184-3",
    meaning="FWP by GA, Williams, 1982",
    scheme_designator="LN"
)

FL_BY_GA_ASUM_2000 = CodedConcept(
    value="33165-2",
    meaning="FL by GA, ASUM 2000",
    scheme_designator="LN"
)

HUMERUS_MERZ_1987 = CodedConcept(
    value="11937-0",
    meaning="Humerus, Merz 1987",
    scheme_designator="LN"
)

FEMALE_TWINS_BWP_BY_GA_ARBUCKLE_1993 = CodedConcept(
    value="33188-4",
    meaning="Female Twins BWP by GA, Arbuckle 1993",
    scheme_designator="LN"
)

FIBULA_MERZ_1987 = CodedConcept(
    value="11918-0",
    meaning="Fibula, Merz 1987",
    scheme_designator="LN"
)

EFW_BY_BPD_TTD_HANSMANN_1986 = CodedConcept(
    value="33139-7",
    meaning="EFW by BPD, TTD, Hansmann 1986",
    scheme_designator="LN"
)

CRL_HADLOCK_1992 = CodedConcept(
    value="11910-7",
    meaning="CRL, Hadlock 1992",
    scheme_designator="LN"
)

FL_BY_GA_MERZ_1988 = CodedConcept(
    value="33169-4",
    meaning="FL by GA, Merz 1988",
    scheme_designator="LN"
)

HUMERUS_LENGTH_ASUM_2000 = CodedConcept(
    value="33116-5",
    meaning="Humerus Length, ASUM 2000",
    scheme_designator="LN"
)

BPDOI_CHITTY_1997 = CodedConcept(
    value="33086-0",
    meaning="BPD-oi, Chitty 1997",
    scheme_designator="LN"
)

CEPHALIC_INDEX_BY_GA_HADLOCK_1981 = CodedConcept(
    value="33158-7",
    meaning="Cephalic Index by GA, Hadlock 1981",
    scheme_designator="LN"
)

FL_LESSOWAY_1998 = CodedConcept(
    value="33100-9",
    meaning="FL, Lessoway 1998",
    scheme_designator="LN"
)

HC_HANSMANN_1986 = CodedConcept(
    value="33543-0",
    meaning="HC, Hansmann 1986",
    scheme_designator="LN"
)

SPINE_LENGTH_TOKYO_1989 = CodedConcept(
    value="33127-2",
    meaning="Spine Length, Tokyo, 1989",
    scheme_designator="LN"
)

GS_DAYA_1991 = CodedConcept(
    value="33104-1",
    meaning="GS, Daya 1991",
    scheme_designator="LN"
)

AC_BY_GA_HADLOCK_1984 = CodedConcept(
    value="33146-2",
    meaning="AC by GA, Hadlock 1984",
    scheme_designator="LN"
)

IOD_TROUT_1994 = CodedConcept(
    value="33123-1",
    meaning="IOD, Trout 1994",
    scheme_designator="LN"
)

EFW2_BY_SHINOZUKA_1996 = CodedConcept(
    value="33142-1",
    meaning="EFW2 by Shinozuka 1996",
    scheme_designator="LN"
)

BPD_OSAKA_1989 = CodedConcept(
    value="33082-9",
    meaning="BPD, Osaka 1989",
    scheme_designator="LN"
)

RADIUS_BY_GA_JEANTY_1983 = CodedConcept(
    value="33180-1",
    meaning="Radius by GA, Jeanty 1983",
    scheme_designator="LN"
)

AC_CAMPBELL_1975 = CodedConcept(
    value="11889-3",
    meaning="AC, Campbell 1975",
    scheme_designator="LN"
)

BPD_SABBAGHA_1978 = CodedConcept(
    value="11907-3",
    meaning="BPD, Sabbagha 1978",
    scheme_designator="LN"
)

AVERAGE_ULTRASOUND_AGE = CodedConcept(
    value="11884-4",
    meaning="Average Ultrasound Age",
    scheme_designator="LN"
)

AXT_BY_GA_SHINOZUKA_1996 = CodedConcept(
    value="33150-4",
    meaning="AxT by GA, Shinozuka 1996",
    scheme_designator="LN"
)

ULNA_MERZ_1987 = CodedConcept(
    value="11945-3",
    meaning="Ulna, Merz 1987",
    scheme_designator="LN"
)

FL_HOHLER_1982 = CodedConcept(
    value="11922-2",
    meaning="FL, Hohler 1982",
    scheme_designator="LN"
)

HC_BY_GA_HADLOCK_1984 = CodedConcept(
    value="33173-6",
    meaning="HC by GA, Hadlock 1984",
    scheme_designator="LN"
)

CRL_ASUM_2000 = CodedConcept(
    value="33090-2",
    meaning="CRL, ASUM 2000",
    scheme_designator="LN"
)

OFD_HANSMANN_1985 = CodedConcept(
    value="33544-8",
    meaning="OFD, Hansmann 1985",
    scheme_designator="LN"
)

BPD_HANSMANN_1985 = CodedConcept(
    value="11903-2",
    meaning="BPD, Hansmann 1985",
    scheme_designator="LN"
)

BPD_BY_GA_MERZ_1988 = CodedConcept(
    value="33154-6",
    meaning="BPD by GA, Merz 1988",
    scheme_designator="LN"
)

FOOT_LENGTH_MERCER_1987 = CodedConcept(
    value="11926-3",
    meaning="Foot Length, Mercer 1987",
    scheme_designator="LN"
)

HUMERUS_LENGTH_BY_GA_ASUM_2000 = CodedConcept(
    value="33177-7",
    meaning="Humerus Length by GA, ASUM 2000",
    scheme_designator="LN"
)

GS_HANSMANN_1979 = CodedConcept(
    value="33105-8",
    meaning="GS, Hansmann 1979",
    scheme_designator="LN"
)

OOD_MAYDEN_1982 = CodedConcept(
    value="33124-9",
    meaning="OOD, Mayden, 1982",
    scheme_designator="LN"
)

EFW_BY_AC_CAMPBELL_1975 = CodedConcept(
    value="11756-4",
    meaning="EFW by AC, Campbell 1975",
    scheme_designator="LN"
)

CRL_REMPEN_1991 = CodedConcept(
    value="33094-4",
    meaning="CRL, Rempen 1991",
    scheme_designator="LN"
)

TCD_NIMROD_1986 = CodedConcept(
    value="33135-5",
    meaning="TCD, Nimrod 1986",
    scheme_designator="LN"
)

AC_MERTZ_1988 = CodedConcept(
    value="33075-3",
    meaning="AC, Mertz 1988",
    scheme_designator="LN"
)

HC_HANSMANN_1985 = CodedConcept(
    value="33112-4",
    meaning="HC, Hansmann 1985",
    scheme_designator="LN"
)

THC_CHITKARA_1987 = CodedConcept(
    value="33131-4",
    meaning="ThC, Chitkara 1987",
    scheme_designator="LN"
)

FL_CHITTY_1997 = CodedConcept(
    value="33098-5",
    meaning="FL, Chitty 1997",
    scheme_designator="LN"
)

BPD_ASUM_1989 = CodedConcept(
    value="33079-5",
    meaning="BPD, ASUM 1989",
    scheme_designator="LN"
)

