"""CID 644 ExogenousSubstanceAdministrationSites
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


MOUSE_MAMMARY_FAT_PAD = CodedConcept(
    value="C22550",
    meaning="Mouse mammary fat pad",
    scheme_designator="NCIt"
)

BONE_MARROW = CodedConcept(
    value="T-C1000",
    meaning="Bone Marrow",
    scheme_designator="SRT"
)

LIVER = CodedConcept(
    value="T-62000",
    meaning="Liver",
    scheme_designator="SRT"
)

FLANK = CodedConcept(
    value="T-D2310",
    meaning="Flank",
    scheme_designator="SRT"
)

TUMOR = CodedConcept(
    value="M-8FFFF",
    meaning="Tumor",
    scheme_designator="SRT"
)

BRAIN = CodedConcept(
    value="T-A0100",
    meaning="Brain",
    scheme_designator="SRT"
)

