"""CID 6003 ChangeSinceLastMammogramorPriorSurgeryfromBIRADS®
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


MORE_DEFINED = CodedConcept(
    value="F-01729",
    meaning="More defined",
    scheme_designator="SRT"
)

INCREASE_IN_SIZE = CodedConcept(
    value="M-02520",
    meaning="Increase in size",
    scheme_designator="SRT"
)

LESS_DEFINED = CodedConcept(
    value="F-01728",
    meaning="Less defined",
    scheme_designator="SRT"
)

DECREASE_IN_SIZE = CodedConcept(
    value="M-02530",
    meaning="Decrease in size",
    scheme_designator="SRT"
)

DECREASE_IN_NUMBER_OF_CALCIFICATIONS = CodedConcept(
    value="F-01727",
    meaning="Decrease in number of calcifications",
    scheme_designator="SRT"
)

INCREASE_IN_NUMBER_OF_CALCIFICATIONS = CodedConcept(
    value="F-01726",
    meaning="Increase in number of calcifications",
    scheme_designator="SRT"
)

NEW_FINDING = CodedConcept(
    value="F-01721",
    meaning="New finding",
    scheme_designator="SRT"
)

REMOVAL_OF_IMPLANT_SINCE_PREVIOUS_MAMMOGRAM = CodedConcept(
    value="F-0172A",
    meaning="Removal of implant since previous mammogram",
    scheme_designator="SRT"
)

NO_SIGNIFICANT_CHANGES_IN_THE_FINDING = CodedConcept(
    value="F-01723",
    meaning="No significant changes in the finding",
    scheme_designator="SRT"
)

FINDING_PARTIALLY_REMOVED = CodedConcept(
    value="F-01722",
    meaning="Finding partially removed",
    scheme_designator="SRT"
)

IMPLANT_REVISED_SINCE_PREVIOUS_MAMMOGRAM = CodedConcept(
    value="F-0172B",
    meaning="Implant revised since previous mammogram",
    scheme_designator="SRT"
)

