"""CID 10047 GFRMeasurementMethods
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


COCKROFTGAULT_FORMULA_ESTIMATION_OF_GFR = CodedConcept(
    value="113570",
    meaning="Cockroft-Gault Formula estimation of GFR",
    scheme_designator="DCM"
)

CKDEPI_FORMULA_ESTIMATION_OF_GFR = CodedConcept(
    value="113571",
    meaning="CKD-EPI Formula estimation of GFR",
    scheme_designator="DCM"
)

GLOMERULAR_FILTRATION_RATE_MDRD_ = CodedConcept(
    value="113572",
    meaning="Glomerular Filtration Rate (MDRD)",
    scheme_designator="DCM"
)

GLOMERULAR_FILTRATION_RATE_NONBLACK_MDRD_ = CodedConcept(
    value="113573",
    meaning="Glomerular Filtration Rate non-black (MDRD)",
    scheme_designator="DCM"
)

GLOMERULAR_FILTRATION_RATE_BLACK_MDRD_ = CodedConcept(
    value="113574",
    meaning="Glomerular Filtration Rate black (MDRD)",
    scheme_designator="DCM"
)

GLOMERULAR_FILTRATION_RATE_FEMALE_MDRD_ = CodedConcept(
    value="113575",
    meaning="Glomerular Filtration Rate female (MDRD)",
    scheme_designator="DCM"
)

GLOMERULAR_FILTRATION_RATE_CYSTATINBASED_FORMULA = CodedConcept(
    value="113576",
    meaning="Glomerular Filtration Rate Cystatin-based formula",
    scheme_designator="DCM"
)

GLOMERULAR_FILTRATION_RATE_CREATININEBASED_FORMULA_SCHWARTZ_ = CodedConcept(
    value="113577",
    meaning="Glomerular Filtration Rate Creatinine-based formula (Schwartz)",
    scheme_designator="DCM"
)

