"""CID 3426 ConsumablesParameters
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


LOT_IDENTIFIER = CodedConcept(
    value="121149",
    meaning="Lot Identifier",
    scheme_designator="DCM"
)

UNIT_SERIAL_IDENTIFIER = CodedConcept(
    value="121148",
    meaning="Unit Serial Identifier",
    scheme_designator="DCM"
)

DESCRIPTION_OF_MATERIAL = CodedConcept(
    value="121145",
    meaning="Description of Material",
    scheme_designator="DCM"
)

