"""CID 6125 GeneralChestLocation
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


PERIPHERAL = CodedConcept(
    value="G-A111",
    meaning="Peripheral",
    scheme_designator="SRT"
)

APICAL = CodedConcept(
    value="G-A122",
    meaning="Apical",
    scheme_designator="SRT"
)

CENTRAL = CodedConcept(
    value="G-A110",
    meaning="Central",
    scheme_designator="SRT"
)

BASAL = CodedConcept(
    value="G-A123",
    meaning="Basal",
    scheme_designator="SRT"
)

