"""CID 7 UltrasoundBeamPath
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


TRANSPANCREATIC = CodedConcept(
    value="G-A1A6",
    meaning="Trans-pancreatic",
    scheme_designator="SRT"
)

TRANSESOPHAGEAL = CodedConcept(
    value="G-D033",
    meaning="Trans-esophageal",
    scheme_designator="SRT"
)

TRANSORBITAL = CodedConcept(
    value="G-D065",
    meaning="Trans-orbital",
    scheme_designator="SRT"
)

TRANSTEMPORAL = CodedConcept(
    value="G-D032",
    meaning="Trans-temporal",
    scheme_designator="SRT"
)

TRANSVAGINAL_ENDOVAGINAL_ = CodedConcept(
    value="G-D002",
    meaning="Trans-vaginal (endovaginal)",
    scheme_designator="SRT"
)

TRANSABDOMINAL = CodedConcept(
    value="G-D001",
    meaning="Trans-abdominal",
    scheme_designator="SRT"
)

TRANSHEPATIC = CodedConcept(
    value="G-D027",
    meaning="Trans-hepatic",
    scheme_designator="SRT"
)

TRANSGASTRIC = CodedConcept(
    value="G-A1B2",
    meaning="Trans-gastric",
    scheme_designator="SRT"
)

TRANSVESICAL = CodedConcept(
    value="G-A1A1",
    meaning="Trans-vesical",
    scheme_designator="SRT"
)

TRANSSPLENIC = CodedConcept(
    value="G-A1A3",
    meaning="Trans-splenic",
    scheme_designator="SRT"
)

TRANSMURAL = CodedConcept(
    value="G-A1B3",
    meaning="Trans-mural",
    scheme_designator="SRT"
)

TRANSTHECAL = CodedConcept(
    value="G-A1A2",
    meaning="Trans-thecal",
    scheme_designator="SRT"
)

TRANSPLEURAL = CodedConcept(
    value="G-A1A5",
    meaning="Trans-pleural",
    scheme_designator="SRT"
)

TRANSRENAL = CodedConcept(
    value="G-A1A4",
    meaning="Trans-renal",
    scheme_designator="SRT"
)

