"""CID 7036 ImageQualityAssessment
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


NONDIAGNOSTIC_QUALITY = CodedConcept(
    value="RID14",
    meaning="Non-diagnostic quality",
    scheme_designator="RADLEX"
)

LIMITED_QUALITY = CodedConcept(
    value="RID13",
    meaning="Limited quality",
    scheme_designator="RADLEX"
)

DIAGNOSTIC_QUALITY = CodedConcept(
    value="RID12",
    meaning="Diagnostic quality",
    scheme_designator="RADLEX"
)

