"""CID 3203 ExerciserDevice
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


ARM_ERGOMETER = CodedConcept(
    value="A-1002A",
    meaning="Arm ergometer",
    scheme_designator="SRT"
)

TREADMILL = CodedConcept(
    value="A-17222",
    meaning="Treadmill",
    scheme_designator="SRT"
)

BICYCLE_ERGOMETER = CodedConcept(
    value="A-17230",
    meaning="Bicycle ergometer",
    scheme_designator="SRT"
)

