"""CID 7015 ExportDelayReasons
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


DELAY_EXPORT_UNTIL_PATIENT_DIES = CodedConcept(
    value="128721",
    meaning="Delay export until patient dies",
    scheme_designator="DCM"
)

DELAY_EXPORT_UNTIL_PATIENT_IS_DISCHARGED = CodedConcept(
    value="128720",
    meaning="Delay export until patient is discharged",
    scheme_designator="DCM"
)

DELAY_EXPORT_UNTIL_EXPERT_REVIEW_IS_AVAILABLE = CodedConcept(
    value="128722",
    meaning="Delay export until expert review is available",
    scheme_designator="DCM"
)

DELAY_EXPORT_UNTIL_CLINICAL_INFORMATION_IS_AVAILABLE = CodedConcept(
    value="128716",
    meaning="Delay export until clinical information is available",
    scheme_designator="DCM"
)

DELAY_EXPORT_UNTIL_FINAL_REPORT_IS_AVAILABLE = CodedConcept(
    value="128715",
    meaning="Delay export until final report is available",
    scheme_designator="DCM"
)

DELAY_EXPORT_UNTIL_HISTOPATHOLOGY_IS_AVAILABLE = CodedConcept(
    value="128718",
    meaning="Delay export until histopathology is available",
    scheme_designator="DCM"
)

DELAY_EXPORT_UNTIL_CONFIRMATION_OF_DIAGNOSIS_IS_AVAILABLE = CodedConcept(
    value="128717",
    meaning="Delay export until confirmation of diagnosis is available",
    scheme_designator="DCM"
)

DELAY_EXPORT_UNTIL_OTHER_LABORATORY_RESULTS_ARE_AVAILABLE = CodedConcept(
    value="128719",
    meaning="Delay export until other laboratory results are available",
    scheme_designator="DCM"
)

