"""CID 70 Flush
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


SALINE = CodedConcept(
    value="C-70841",
    meaning="Saline",
    scheme_designator="SRT"
)

LACTATED_RINGER_S = CodedConcept(
    value="C-70434",
    meaning="Lactated Ringer's",
    scheme_designator="SRT"
)

DEXTRAN = CodedConcept(
    value="C-A7220",
    meaning="Dextran",
    scheme_designator="SRT"
)

