"""CID 611 AnesthesiaCategoryCodeTypeforSmallAnimalAnesthesia
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


LOCAL_ANESTHESIA = CodedConcept(
    value="P1-C0038",
    meaning="Local anesthesia",
    scheme_designator="SRT"
)

TOPICAL_LOCAL_ANESTHESIA = CodedConcept(
    value="P1-C0037",
    meaning="Topical local anesthesia",
    scheme_designator="SRT"
)

SPINAL_ANESTHESIA = CodedConcept(
    value="P1-C0208",
    meaning="Spinal anesthesia",
    scheme_designator="SRT"
)

GENERAL_ANESTHESIA = CodedConcept(
    value="P1-C0010",
    meaning="General anesthesia",
    scheme_designator="SRT"
)

EPIDURAL_ANESTHESIA = CodedConcept(
    value="P1-C0220",
    meaning="Epidural anesthesia",
    scheme_designator="SRT"
)

SEDATION = CodedConcept(
    value="P1-C0B00",
    meaning="Sedation",
    scheme_designator="SRT"
)

REGIONAL_ANESTHESIA = CodedConcept(
    value="P1-C0200",
    meaning="Regional anesthesia",
    scheme_designator="SRT"
)

MONITORED_ANESTHESIA_CARE_MAC_ = CodedConcept(
    value="P1-0512E",
    meaning="Monitored Anesthesia Care (MAC)",
    scheme_designator="SRT"
)

