"""CID 3704 MyocardiumWallMorphologyFindings
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


SCARRED_MYOCARDIUM = CodedConcept(
    value="122113",
    meaning="Scarred Myocardium",
    scheme_designator="DCM"
)

THINNING_MYOCARDIUM = CodedConcept(
    value="122114",
    meaning="Thinning Myocardium",
    scheme_designator="DCM"
)

NORMAL_MYOCARDIUM = CodedConcept(
    value="122112",
    meaning="Normal Myocardium",
    scheme_designator="DCM"
)

VENTRICULAR_ANEURYSM = CodedConcept(
    value="D3-10510",
    meaning="Ventricular Aneurysm",
    scheme_designator="SRT"
)

