"""CID 6071 HistologicGradingMethod
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


BLOOMRICHARDSON_GRADE = CodedConcept(
    value="111502",
    meaning="Bloom-Richardson Grade",
    scheme_designator="DCM"
)

NOTTINGHAM_COMBINED_GRADE = CodedConcept(
    value="R-00288",
    meaning="Nottingham Combined Grade",
    scheme_designator="SRT"
)

