"""CID 7701 FiberTractsInBrainstem
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


LATERAL_LEMNISCUS = CodedConcept(
    value="T-A5272",
    meaning="lateral lemniscus",
    scheme_designator="SRT"
)

MEDIAL_LONGITUDINAL_FASCICULUS = CodedConcept(
    value="T-A5250",
    meaning="medial longitudinal fasciculus",
    scheme_designator="SRT"
)

MEDIAL_LEMNISCUS = CodedConcept(
    value="T-A5271",
    meaning="medial lemniscus",
    scheme_designator="SRT"
)

CORTICOSPINAL_TRACT_IN_BRAINSTEM = CodedConcept(
    value="T-D07EA",
    meaning="corticospinal tract in brainstem",
    scheme_designator="SRT"
)

INFERIOR_CEREBELLAR_PEDUNCLE = CodedConcept(
    value="T-A6640",
    meaning="inferior cerebellar peduncle",
    scheme_designator="SRT"
)

MIDDLE_CEREBELLAR_PEDUNCLE = CodedConcept(
    value="T-A6630",
    meaning="middle cerebellar peduncle",
    scheme_designator="SRT"
)

SUPERIOR_CEREBELLAR_PEDUNCLE = CodedConcept(
    value="T-A6620",
    meaning="superior cerebellar peduncle",
    scheme_designator="SRT"
)

