"""CID 3469 ESVolume
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


LEFT_ATRIAL_ES_VOLUME = CodedConcept(
    value="122408",
    meaning="Left Atrial ES Volume",
    scheme_designator="DCM"
)

RIGHT_VENTRICULAR_ES_VOLUME = CodedConcept(
    value="8824-5",
    meaning="Right Ventricular ES Volume",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_ES_VOLUME = CodedConcept(
    value="8823-7",
    meaning="Left Ventricular ES Volume",
    scheme_designator="LN"
)

