"""CID 10034 ReasonforRepeatingAcquisition
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


SUBOPTIMAL_CONTRAST_TIMING = CodedConcept(
    value="128554",
    meaning="Suboptimal contrast timing",
    scheme_designator="DCM"
)

PATIENT_MOTION = CodedConcept(
    value="128553",
    meaning="Patient motion",
    scheme_designator="DCM"
)

