"""CID 7449 ReaderSpecialty
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


ONCOLOGIC_IMAGING_SPECIALTY = CodedConcept(
    value="128013",
    meaning="Oncologic Imaging Specialty",
    scheme_designator="DCM"
)

OB_GYN_IMAGING_SPECIALTY = CodedConcept(
    value="128012",
    meaning="OB/Gyn Imaging Specialty",
    scheme_designator="DCM"
)

THORACIC_IMAGING_SPECIALTY = CodedConcept(
    value="128015",
    meaning="Thoracic Imaging Specialty",
    scheme_designator="DCM"
)

ONCOLOGY_SPECIALTY = CodedConcept(
    value="128014",
    meaning="Oncology Specialty",
    scheme_designator="DCM"
)

ABDOMINAL_IMAGING_SPECIALTY = CodedConcept(
    value="128006",
    meaning="Abdominal Imaging Specialty",
    scheme_designator="DCM"
)

VASCULAR_IMAGING_SPECIALTY = CodedConcept(
    value="128017",
    meaning="Vascular Imaging Specialty",
    scheme_designator="DCM"
)

PEDIATRIC_IMAGING_SPECIALTY = CodedConcept(
    value="128016",
    meaning="Pediatric Imaging Specialty",
    scheme_designator="DCM"
)

HEAD_AND_NECK_IMAGING_SPECIALTY = CodedConcept(
    value="128008",
    meaning="Head and Neck Imaging Specialty",
    scheme_designator="DCM"
)

CARDIAC_IMAGING_SPECIALTY = CodedConcept(
    value="128007",
    meaning="Cardiac Imaging Specialty",
    scheme_designator="DCM"
)

MUSCULOSKELETAL_IMAGING_SPECIALTY = CodedConcept(
    value="128009",
    meaning="Musculoskeletal Imaging Specialty",
    scheme_designator="DCM"
)

NEURORADIOLOGY_IMAGING_SPECIALTY = CodedConcept(
    value="128011",
    meaning="Neuroradiology Imaging Specialty",
    scheme_designator="DCM"
)

NEUROLOGY_SPECIALTY = CodedConcept(
    value="128010",
    meaning="Neurology Specialty",
    scheme_designator="DCM"
)

