"""CID 3414 ProcedureUrgency
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


EMERGENT_PROCEDURE = CodedConcept(
    value="G-D209",
    meaning="Emergent Procedure",
    scheme_designator="SRT"
)

SALVAGE_PROCEDURE = CodedConcept(
    value="R-41C8D",
    meaning="Salvage Procedure",
    scheme_designator="SRT"
)

ELECTIVE_PROCEDURE = CodedConcept(
    value="G-D210",
    meaning="Elective Procedure",
    scheme_designator="SRT"
)

URGENT_PROCEDURE = CodedConcept(
    value="G-D216",
    meaning="Urgent Procedure",
    scheme_designator="SRT"
)

