"""CID 621 TypeofMedicationforSmallAnimalAnesthesia
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


CARRIER_GAS = CodedConcept(
    value="127330",
    meaning="Carrier gas",
    scheme_designator="DCM"
)

BETABLOCKER = CodedConcept(
    value="F-61814",
    meaning="Beta-blocker",
    scheme_designator="SRT"
)

SKELETAL_MUSCLE_RELAXANT = CodedConcept(
    value="F-61899",
    meaning="Skeletal muscle relaxant",
    scheme_designator="SRT"
)

ANTIBIOTIC = CodedConcept(
    value="C-5008C",
    meaning="Antibiotic",
    scheme_designator="SRT"
)

BLOOD_PRODUCT = CodedConcept(
    value="R-005B3",
    meaning="Blood product",
    scheme_designator="SRT"
)

NSAID = CodedConcept(
    value="F-61898",
    meaning="NSAID",
    scheme_designator="SRT"
)

OXYTOCIC = CodedConcept(
    value="F-61E2A",
    meaning="Oxytocic",
    scheme_designator="SRT"
)

BRONCHODILATOR = CodedConcept(
    value="F-616EB",
    meaning="Bronchodilator",
    scheme_designator="SRT"
)

POTASSIUM = CodedConcept(
    value="C-13500",
    meaning="Potassium",
    scheme_designator="SRT"
)

AMINOGLYCOSIDE_ANTIBIOTIC = CodedConcept(
    value="C-52500",
    meaning="Aminoglycoside antibiotic",
    scheme_designator="SRT"
)

BARBITURATE = CodedConcept(
    value="R-F2B23",
    meaning="Barbiturate",
    scheme_designator="SRT"
)

NEUROMUSCULAR_BLOCKING_NMB_DEPOLARIZING = CodedConcept(
    value="F-6180F",
    meaning="NeuroMuscular Blocking (NMB) - depolarizing",
    scheme_designator="SRT"
)

THYROID_HORMONE = CodedConcept(
    value="F-B3000",
    meaning="Thyroid hormone",
    scheme_designator="SRT"
)

ANTIHYPERTENSIVE = CodedConcept(
    value="C-81100",
    meaning="Antihypertensive",
    scheme_designator="SRT"
)

BETALACTAM_ANTIBIOTIC = CodedConcept(
    value="C-00231",
    meaning="Beta-Lactam antibiotic",
    scheme_designator="SRT"
)

ANTICONVULSANT = CodedConcept(
    value="R-F1216",
    meaning="Anticonvulsant",
    scheme_designator="SRT"
)

BENZODIAZEPINE = CodedConcept(
    value="R-F2B1D",
    meaning="Benzodiazepine",
    scheme_designator="SRT"
)

DIURETIC = CodedConcept(
    value="F-618AF",
    meaning="Diuretic",
    scheme_designator="SRT"
)

ANTIHEPARIN_AGENT = CodedConcept(
    value="F-618BA",
    meaning="Anti-heparin agent",
    scheme_designator="SRT"
)

METRONIDAZOLE_ANTIBIOTIC = CodedConcept(
    value="F-616FE",
    meaning="Metronidazole antibiotic",
    scheme_designator="SRT"
)

LINCOMYCIN_ANTIBIOTIC = CodedConcept(
    value="C-0023B",
    meaning="Lincomycin antibiotic",
    scheme_designator="SRT"
)

NASAL_DECONGESTANT = CodedConcept(
    value="C-97302",
    meaning="Nasal decongestant",
    scheme_designator="SRT"
)

DRUG_DILUENT = CodedConcept(
    value="C-50013",
    meaning="Drug diluent",
    scheme_designator="SRT"
)

ESTROGEN = CodedConcept(
    value="F-B2700",
    meaning="Estrogen",
    scheme_designator="SRT"
)

ANTIDIURETIC_HORMONE = CodedConcept(
    value="F-B1810",
    meaning="Antidiuretic hormone",
    scheme_designator="SRT"
)

ANALGESIC = CodedConcept(
    value="F-6181F",
    meaning="Analgesic",
    scheme_designator="SRT"
)

LOW_MOLECULAR_WEIGHT_HEPARIN = CodedConcept(
    value="F-6186F",
    meaning="Low Molecular Weight Heparin",
    scheme_designator="SRT"
)

GENERAL_ANESTHETIC = CodedConcept(
    value="F-6186A",
    meaning="General anesthetic",
    scheme_designator="SRT"
)

INOTROPIC_AGENT = CodedConcept(
    value="C-80120",
    meaning="Inotropic agent",
    scheme_designator="SRT"
)

LINEZOLID_ANTIBIOTIC = CodedConcept(
    value="C-00286",
    meaning="Linezolid antibiotic",
    scheme_designator="SRT"
)

VASODILATOR = CodedConcept(
    value="F-61957",
    meaning="Vasodilator",
    scheme_designator="SRT"
)

BENZODIAZEPINE_ANTAGONIST = CodedConcept(
    value="F-619EF",
    meaning="Benzodiazepine antagonist",
    scheme_designator="SRT"
)

HYPOGLYCEMIC = CodedConcept(
    value="C-50309",
    meaning="Hypoglycemic",
    scheme_designator="SRT"
)

CALCIUM_CHANNEL_BLOCKER = CodedConcept(
    value="F-61878",
    meaning="Calcium channel blocker",
    scheme_designator="SRT"
)

VASOCONSTRICTOR = CodedConcept(
    value="F-619AA",
    meaning="Vasoconstrictor",
    scheme_designator="SRT"
)

ANTIFUNGAL = CodedConcept(
    value="F-617EF",
    meaning="Antifungal",
    scheme_designator="SRT"
)

VANCOMYCIN_ANTIBIOTIC = CodedConcept(
    value="C-0024E",
    meaning="Vancomycin antibiotic",
    scheme_designator="SRT"
)

QUINOLONE_ANTIBIOTIC = CodedConcept(
    value="C-0024C",
    meaning="Quinolone antibiotic",
    scheme_designator="SRT"
)

STEROID = CodedConcept(
    value="C-10098",
    meaning="Steroid",
    scheme_designator="SRT"
)

CALORIC_AGENT = CodedConcept(
    value="F-618D8",
    meaning="Caloric agent",
    scheme_designator="SRT"
)

LOCAL_ANESTHETIC = CodedConcept(
    value="F-6183D",
    meaning="Local anesthetic",
    scheme_designator="SRT"
)

MAGNESIUM = CodedConcept(
    value="C-14800",
    meaning="Magnesium",
    scheme_designator="SRT"
)

SULFONAMIDE_ANTIBIOTIC = CodedConcept(
    value="C-00257",
    meaning="Sulfonamide antibiotic",
    scheme_designator="SRT"
)

CHOLINERGIC_AGENT = CodedConcept(
    value="F-620E8",
    meaning="Cholinergic agent",
    scheme_designator="SRT"
)

MACROLIDE_ANTIBIOTIC = CodedConcept(
    value="C-00211",
    meaning="Macrolide antibiotic",
    scheme_designator="SRT"
)

ANTICOAGULANT = CodedConcept(
    value="F-6199A",
    meaning="Anticoagulant",
    scheme_designator="SRT"
)

ANTIEMETIC = CodedConcept(
    value="C-85800",
    meaning="Antiemetic",
    scheme_designator="SRT"
)

NEUROMUSCULAR_BLOCKING_NMB_NON_DEPOLARIZING = CodedConcept(
    value="F-61959",
    meaning="NeuroMuscular Blocking (NMB) - non depolarizing",
    scheme_designator="SRT"
)

OCULAR_LUBRICANT = CodedConcept(
    value="F-61D70",
    meaning="Ocular Lubricant",
    scheme_designator="SRT"
)

ANTIHISTAMINE = CodedConcept(
    value="F-61969",
    meaning="Antihistamine",
    scheme_designator="SRT"
)

TETRACYCLINE_ANTIBIOTIC = CodedConcept(
    value="C-00216",
    meaning="Tetracycline antibiotic",
    scheme_designator="SRT"
)

ADRENERGIC_AGENT = CodedConcept(
    value="C-68000",
    meaning="Adrenergic agent",
    scheme_designator="SRT"
)

CEPHALOSPORIN_ANTIBIOTIC = CodedConcept(
    value="C-0021C",
    meaning="Cephalosporin antibiotic",
    scheme_designator="SRT"
)

CARBAPENEM_ANTIBIOTIC = CodedConcept(
    value="C-002B1",
    meaning="Carbapenem antibiotic",
    scheme_designator="SRT"
)

CALCIUM = CodedConcept(
    value="C-14300",
    meaning="Calcium",
    scheme_designator="SRT"
)

HEMOSTATIC_AGENT = CodedConcept(
    value="F-618A5",
    meaning="Hemostatic agent",
    scheme_designator="SRT"
)

ANTICHOLINERGIC = CodedConcept(
    value="F-6180B",
    meaning="Anticholinergic",
    scheme_designator="SRT"
)

GASTROINTESTINAL_PROKINETIC = CodedConcept(
    value="C-84989",
    meaning="Gastrointestinal prokinetic",
    scheme_designator="SRT"
)

ANTIARRHYTHMIC = CodedConcept(
    value="F-6196E",
    meaning="Antiarrhythmic",
    scheme_designator="SRT"
)

PLASMA_EXPANDER = CodedConcept(
    value="F-616E7",
    meaning="Plasma Expander",
    scheme_designator="SRT"
)

NARCOTIC_OPIATE_ANTAGONIST = CodedConcept(
    value="F-6188F",
    meaning="Narcotic (opiate) antagonist",
    scheme_designator="SRT"
)

PENICILLIN_ANTIBIOTIC = CodedConcept(
    value="C-0021D",
    meaning="Penicillin antibiotic",
    scheme_designator="SRT"
)

RESPIRATORY_STIMULANT = CodedConcept(
    value="F-6205D",
    meaning="Respiratory stimulant",
    scheme_designator="SRT"
)

VITAMIN = CodedConcept(
    value="F-BB000",
    meaning="Vitamin",
    scheme_designator="SRT"
)

H2_ANTAGONIST = CodedConcept(
    value="C0019593",
    meaning="H2 antagonist",
    scheme_designator="UMLS"
)

NARCOTIC_ANALGESIC = CodedConcept(
    value="C0027409",
    meaning="Narcotic analgesic",
    scheme_designator="UMLS"
)

ANTIHYPOGLYCEMIC = CodedConcept(
    value="C1579431",
    meaning="Antihypoglycemic",
    scheme_designator="UMLS"
)

