"""CID 3520 BloodSourceType
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


PULMONARY_VEIN_BLOOD = CodedConcept(
    value="R-0035E",
    meaning="Pulmonary Vein Blood",
    scheme_designator="SRT"
)

SYSTEMIC_ARTERY_BLOOD = CodedConcept(
    value="R-00376",
    meaning="Systemic Artery Blood",
    scheme_designator="SRT"
)

MIXED_VENOUS_BLOOD = CodedConcept(
    value="T-C2007",
    meaning="Mixed Venous Blood",
    scheme_designator="SRT"
)

PULMONARY_ARTERY_BLOOD = CodedConcept(
    value="R-0035B",
    meaning="Pulmonary Artery Blood",
    scheme_designator="SRT"
)

