"""CID 10045 RadiopharmaceuticalPatientState
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


CARDIAC_STRESS_STATE = CodedConcept(
    value="109091",
    meaning="Cardiac Stress State",
    scheme_designator="DCM"
)

ACUTE_UNILATERAL_RENAL_BLOCKAGE = CodedConcept(
    value="113560",
    meaning="Acute unilateral renal blockage",
    scheme_designator="DCM"
)

LOW_THYROID_UPTAKE = CodedConcept(
    value="113561",
    meaning="Low Thyroid Uptake",
    scheme_designator="DCM"
)

HIGH_THYROID_UPTAKE = CodedConcept(
    value="113562",
    meaning="High Thyroid Uptake",
    scheme_designator="DCM"
)

SEVERELY_JAUNDICED = CodedConcept(
    value="113563",
    meaning="Severely Jaundiced",
    scheme_designator="DCM"
)

ABNORMAL_RENAL_FUNCTION = CodedConcept(
    value="F-70102",
    meaning="Abnormal Renal Function",
    scheme_designator="SRT"
)

RESTING_STATE = CodedConcept(
    value="F-01604",
    meaning="Resting State",
    scheme_designator="SRT"
)

