"""CID 7153 CNSSegmentationTypes
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


ARCUATE_FASCICULUS = CodedConcept(
    value="276650",
    meaning="Arcuate Fasciculus",
    scheme_designator="FMA"
)

SUBARACHNOID_SPACE = CodedConcept(
    value="T-A1500",
    meaning="Subarachnoid space",
    scheme_designator="SRT"
)

UNCINATE_FASCICULUS = CodedConcept(
    value="T-A2830",
    meaning="Uncinate fasciculus",
    scheme_designator="SRT"
)

FOURTH_VENTRICLE = CodedConcept(
    value="T-A1820",
    meaning="Fourth ventricle",
    scheme_designator="SRT"
)

CEREBELLAR_WHITE_MATTER = CodedConcept(
    value="T-A6080",
    meaning="Cerebellar white matter",
    scheme_designator="SRT"
)

OPTIC_TRACT = CodedConcept(
    value="T-A8060",
    meaning="Optic tract",
    scheme_designator="SRT"
)

PINEAL_GLAND = CodedConcept(
    value="T-B2000",
    meaning="Pineal Gland",
    scheme_designator="SRT"
)

SPINAL_CORD = CodedConcept(
    value="T-A7010",
    meaning="Spinal cord",
    scheme_designator="SRT"
)

LATERAL_CORTICOSPINAL_TRACT = CodedConcept(
    value="T-A7093",
    meaning="Lateral corticospinal tract",
    scheme_designator="SRT"
)

MEDIAL_LEMNISCUS = CodedConcept(
    value="T-A5271",
    meaning="Medial Lemniscus",
    scheme_designator="SRT"
)

OPTIC_RADIATION = CodedConcept(
    value="T-A2880",
    meaning="Optic radiation",
    scheme_designator="SRT"
)

CINGULUM = CodedConcept(
    value="T-A2840",
    meaning="Cingulum",
    scheme_designator="SRT"
)

INFERIOR_CEREBELLAR_PEDUNCLE = CodedConcept(
    value="T-A6640",
    meaning="Inferior cerebellar peduncle",
    scheme_designator="SRT"
)

MENINGES = CodedConcept(
    value="T-A1110",
    meaning="Meninges",
    scheme_designator="SRT"
)

OCCIPITAL_LOBE = CodedConcept(
    value="T-A2400",
    meaning="Occipital lobe",
    scheme_designator="SRT"
)

BRAIN = CodedConcept(
    value="T-A0100",
    meaning="Brain",
    scheme_designator="SRT"
)

FRONTAL_LOBE = CodedConcept(
    value="T-A2200",
    meaning="Frontal lobe",
    scheme_designator="SRT"
)

TELENCEPHALON = CodedConcept(
    value="T-A0103",
    meaning="Telencephalon",
    scheme_designator="SRT"
)

DIENCEPHALON = CodedConcept(
    value="T-A0102",
    meaning="Diencephalon",
    scheme_designator="SRT"
)

NUCLEUS_ACCUMBENS = CodedConcept(
    value="T-A0149",
    meaning="Nucleus accumbens",
    scheme_designator="SRT"
)

POSTERIOR_CEREBRAL_COMMISSURE = CodedConcept(
    value="T-A4904",
    meaning="Posterior cerebral commissure",
    scheme_designator="SRT"
)

BRAIN_CEREBROSPINAL_FLUID_PATHWAY = CodedConcept(
    value="T-A0109",
    meaning="Brain cerebrospinal fluid pathway",
    scheme_designator="SRT"
)

NEUROHYPOPHYSIS = CodedConcept(
    value="T-B1200",
    meaning="Neurohypophysis",
    scheme_designator="SRT"
)

SPINAL_CORD_GRAY_MATTER = CodedConcept(
    value="T-A7020",
    meaning="Spinal cord gray matter",
    scheme_designator="SRT"
)

SUBSTANTIA_NIGRA = CodedConcept(
    value="T-A5160",
    meaning="Substantia nigra",
    scheme_designator="SRT"
)

PITUITARY = CodedConcept(
    value="T-B1000",
    meaning="Pituitary",
    scheme_designator="SRT"
)

PIA_MATER = CodedConcept(
    value="T-A1280",
    meaning="Pia mater",
    scheme_designator="SRT"
)

CORPUS_STRIATUM = CodedConcept(
    value="T-A3100",
    meaning="Corpus striatum",
    scheme_designator="SRT"
)

DURA_MATER = CodedConcept(
    value="T-A1120",
    meaning="Dura mater",
    scheme_designator="SRT"
)

HIPPOCAMPUS = CodedConcept(
    value="T-A2570",
    meaning="Hippocampus",
    scheme_designator="SRT"
)

INFERIOR_LONGITUDINAL_FASCICULUS = CodedConcept(
    value="T-A2850",
    meaning="Inferior longitudinal fasciculus",
    scheme_designator="SRT"
)

CEREBROSPINAL_FLUID = CodedConcept(
    value="T-A1000",
    meaning="Cerebrospinal Fluid",
    scheme_designator="SRT"
)

GLOBUS_PALLIDUS = CodedConcept(
    value="T-A3500",
    meaning="Globus pallidus",
    scheme_designator="SRT"
)

CEREBRAL_FORNIX = CodedConcept(
    value="T-A2970",
    meaning="Cerebral fornix",
    scheme_designator="SRT"
)

LIMBIC_LOBE = CodedConcept(
    value="T-A0036",
    meaning="Limbic lobe",
    scheme_designator="SRT"
)

INSULA = CodedConcept(
    value="T-A2610",
    meaning="Insula",
    scheme_designator="SRT"
)

BRAIN_VENTRICLE = CodedConcept(
    value="T-A1600",
    meaning="Brain ventricle",
    scheme_designator="SRT"
)

CEREBRAL_AQUEDUCT = CodedConcept(
    value="T-A1800",
    meaning="Cerebral aqueduct",
    scheme_designator="SRT"
)

SPINAL_CORD_WHITE_MATTER = CodedConcept(
    value="T-A7070",
    meaning="Spinal cord white matter",
    scheme_designator="SRT"
)

SPINAL_CEREBROSPINAL_FLUID_PATHWAY = CodedConcept(
    value="T-D0721",
    meaning="Spinal cerebrospinal fluid pathway",
    scheme_designator="SRT"
)

THALAMUS = CodedConcept(
    value="T-A4000",
    meaning="Thalamus",
    scheme_designator="SRT"
)

AMYGDALA = CodedConcept(
    value="T-A3230",
    meaning="Amygdala",
    scheme_designator="SRT"
)

CEREBRAL_CORTEX = CodedConcept(
    value="T-A2020",
    meaning="Cerebral cortex",
    scheme_designator="SRT"
)

LATERAL_VENTRICLE = CodedConcept(
    value="T-A1650",
    meaning="Lateral ventricle",
    scheme_designator="SRT"
)

PARIETAL_LOBE = CodedConcept(
    value="T-A2300",
    meaning="Parietal lobe",
    scheme_designator="SRT"
)

SUPERIOR_CEREBELLAR_PEDUNCLE = CodedConcept(
    value="T-A6620",
    meaning="Superior cerebellar peduncle",
    scheme_designator="SRT"
)

CORPUS_CALLOSUM = CodedConcept(
    value="T-A2700",
    meaning="Corpus callosum",
    scheme_designator="SRT"
)

TEMPORAL_LOBE = CodedConcept(
    value="T-A2500",
    meaning="Temporal lobe",
    scheme_designator="SRT"
)

BRAIN_STEM = CodedConcept(
    value="T-D0558",
    meaning="Brain stem",
    scheme_designator="SRT"
)

OPTIC_CHIASM = CodedConcept(
    value="T-A800B",
    meaning="Optic chiasm",
    scheme_designator="SRT"
)

SUPERIOR_LONGITUDINAL_FASCICULUS = CodedConcept(
    value="T-A2820",
    meaning="Superior longitudinal fasciculus",
    scheme_designator="SRT"
)

ADENOHYPOPHYSIS = CodedConcept(
    value="T-B1100",
    meaning="Adenohypophysis",
    scheme_designator="SRT"
)

CENTRAL_NERVOUS_SYSTEM = CodedConcept(
    value="T-A0090",
    meaning="Central nervous system",
    scheme_designator="SRT"
)

WHITE_MATTER = CodedConcept(
    value="T-A0095",
    meaning="White Matter",
    scheme_designator="SRT"
)

ENTORHINAL_CORTEX = CodedConcept(
    value="T-A2594",
    meaning="Entorhinal Cortex",
    scheme_designator="SRT"
)

CEREBRAL_WHITE_MATTER = CodedConcept(
    value="T-A2030",
    meaning="Cerebral White Matter",
    scheme_designator="SRT"
)

MIDBRAIN = CodedConcept(
    value="T-A5100",
    meaning="Midbrain",
    scheme_designator="SRT"
)

GRAY_MATTER = CodedConcept(
    value="T-A0096",
    meaning="Gray Matter",
    scheme_designator="SRT"
)

PUTAMEN = CodedConcept(
    value="T-A3400",
    meaning="Putamen",
    scheme_designator="SRT"
)

ARACHNOID = CodedConcept(
    value="T-A1220",
    meaning="Arachnoid",
    scheme_designator="SRT"
)

CAUDATE_NUCLEUS = CodedConcept(
    value="T-A3200",
    meaning="Caudate nucleus",
    scheme_designator="SRT"
)

MIDDLE_CEREBELLAR_PEDUNCLE = CodedConcept(
    value="T-A6630",
    meaning="Middle cerebellar peduncle",
    scheme_designator="SRT"
)

THIRD_VENTRICLE = CodedConcept(
    value="T-A1740",
    meaning="Third ventricle",
    scheme_designator="SRT"
)

