"""CID 6136 ChestTypesofQualityControlStandard
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


PERFORMANCE_OF_PEDIATRIC_AND_ADULT_THORACIC_CT = CodedConcept(
    value="112184",
    meaning="Performance of Pediatric and Adult Thoracic CT",
    scheme_designator="DCM"
)

PERFORMANCE_OF_CT_FOR_DETECTION_OF_PULMONARY_EMBOLISM_IN_ADULTS = CodedConcept(
    value="112185",
    meaning="Performance of CT for Detection of Pulmonary Embolism in Adults",
    scheme_designator="DCM"
)

INSTITUTIONALLY_DEFINED_QUALITY_CONTROL_STANDARD = CodedConcept(
    value="111240",
    meaning="Institutionally defined quality control standard",
    scheme_designator="DCM"
)

PERFORMANCE_OF_HIGHRESOLUTION_CT_OF_THE_LUNGS_IN_ADULTS = CodedConcept(
    value="112186",
    meaning="Performance of High-Resolution CT of the Lungs in Adults",
    scheme_designator="DCM"
)

PERFORMANCE_OF_PEDIATRIC_AND_ADULT_CHEST_RADIOGRAPHY_ACR = CodedConcept(
    value="112035",
    meaning="Performance of Pediatric and Adult Chest Radiography, ACR",
    scheme_designator="DCM"
)

ACR_POSITION_STATEMENT = CodedConcept(
    value="112036",
    meaning="ACR Position Statement",
    scheme_designator="DCM"
)

