"""CID 3827 VesselSegments
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


MARGINAL_CORONARY_ARTERY_LATERALS_1ST = CodedConcept(
    value="20A",
    meaning="1st Marginal Coronary Artery Laterals",
    scheme_designator="BARI"
)

MARGINAL_CORONARY_ARTERY_LATERALS_2ND = CodedConcept(
    value="21A",
    meaning="2nd Marginal Coronary Artery Laterals",
    scheme_designator="BARI"
)

MARGINAL_CORONARY_ARTERY_LATERALS_3RD = CodedConcept(
    value="22A",
    meaning="3rd Marginal Coronary Artery Laterals",
    scheme_designator="BARI"
)

POSTERIOR_DESCENDING_SEPTAL_PERFORATORS = CodedConcept(
    value="9",
    meaning="Posterior descending septal perforators",
    scheme_designator="BARI"
)

DIAGONAL_CORONARY_ARTERY_LATERALS_1ST = CodedConcept(
    value="15A",
    meaning="1st Diagonal Coronary Artery Laterals",
    scheme_designator="BARI"
)

DIAGONAL_CORONARY_ARTERY_LATERALS_2ND = CodedConcept(
    value="16A",
    meaning="2nd Diagonal Coronary Artery Laterals",
    scheme_designator="BARI"
)

RAMUS_LATERALS = CodedConcept(
    value="28A",
    meaning="Ramus Laterals",
    scheme_designator="BARI"
)

DIAGONAL_CORONARY_ARTERY_LATERALS_3RD = CodedConcept(
    value="29A",
    meaning="3rd Diagonal Coronary Artery Laterals",
    scheme_designator="BARI"
)

ANTERIOR_CARDIAC_VEIN = CodedConcept(
    value="T-48403",
    meaning="Anterior Cardiac Vein",
    scheme_designator="SRT"
)

SPLENIC_ARTERY = CodedConcept(
    value="T-46460",
    meaning="Splenic Artery",
    scheme_designator="SRT"
)

INFERIOR_RIGHT_PULMONARY_VEIN = CodedConcept(
    value="T-48520",
    meaning="Inferior Right Pulmonary Vein",
    scheme_designator="SRT"
)

SUBCLAVIAN_ARTERY = CodedConcept(
    value="T-46100",
    meaning="Subclavian Artery",
    scheme_designator="SRT"
)

ILEAL_VEIN = CodedConcept(
    value="G-0370",
    meaning="Ileal vein",
    scheme_designator="SRT"
)

SOLEAL_VEIN = CodedConcept(
    value="G-036B",
    meaning="Soleal vein",
    scheme_designator="SRT"
)

TRANSJUGULAR_INTRAHEPATIC_PORTOSYSTEMIC_SHUNT = CodedConcept(
    value="G-036C",
    meaning="Transjugular Intrahepatic Portosystemic Shunt",
    scheme_designator="SRT"
)

GIACOMINI_VEIN = CodedConcept(
    value="G-036F",
    meaning="Giacomini vein",
    scheme_designator="SRT"
)

INFERIOR_RIGHT_HEPATIC_VEIN = CodedConcept(
    value="G-036D",
    meaning="Inferior Right Hepatic Vein",
    scheme_designator="SRT"
)

POSTERIOR_ARCH_VEIN = CodedConcept(
    value="G-036E",
    meaning="Posterior arch vein",
    scheme_designator="SRT"
)

ANTERIORMIDDLE_CEREBRAL_ARTERY_BIFURCATION = CodedConcept(
    value="G-0368",
    meaning="Anterior-Middle Cerebral Artery Bifurcation",
    scheme_designator="SRT"
)

ANTERIORPOSTERIOR_CEREBRAL_ARTERY_BIFURCATION = CodedConcept(
    value="G-0369",
    meaning="Anterior-Posterior Cerebral Artery Bifurcation",
    scheme_designator="SRT"
)

SMALLEST_CARDIAC_VEIN = CodedConcept(
    value="T-48405",
    meaning="Smallest Cardiac Vein",
    scheme_designator="SRT"
)

VENTRICULAR_VEIN = CodedConcept(
    value="T-48404",
    meaning="Ventricular Vein",
    scheme_designator="SRT"
)

ATRIOVENTRICULAR_VEIN = CodedConcept(
    value="T-48407",
    meaning="Atrioventricular Vein",
    scheme_designator="SRT"
)

ATRIAL_VEIN = CodedConcept(
    value="T-48406",
    meaning="Atrial Vein",
    scheme_designator="SRT"
)

FIFTH_LUMBAR_ARTERY = CodedConcept(
    value="G-0362",
    meaning="Fifth Lumbar Artery",
    scheme_designator="SRT"
)

SIXTH_LUMBAR_ARTERY = CodedConcept(
    value="G-0363",
    meaning="Sixth Lumbar Artery",
    scheme_designator="SRT"
)

THIRD_LUMBAR_ARTERY = CodedConcept(
    value="G-0360",
    meaning="Third Lumbar Artery",
    scheme_designator="SRT"
)

FOURTH_LUMBAR_ARTERY = CodedConcept(
    value="G-0361",
    meaning="Fourth Lumbar Artery",
    scheme_designator="SRT"
)

SAPHENOFEMORAL_JUNCTION = CodedConcept(
    value="T-D930A",
    meaning="Saphenofemoral Junction",
    scheme_designator="SRT"
)

PROFUNDA_FEMORIS_ARTERY = CodedConcept(
    value="T-47440",
    meaning="Profunda Femoris Artery",
    scheme_designator="SRT"
)

POSTERIOR_TIBIAL_VEIN = CodedConcept(
    value="T-49620",
    meaning="Posterior Tibial Vein",
    scheme_designator="SRT"
)

TESTICULAR_VEIN = CodedConcept(
    value="T-48770",
    meaning="Testicular Vein",
    scheme_designator="SRT"
)

CORONARY_SINUS = CodedConcept(
    value="T-48410",
    meaning="Coronary Sinus",
    scheme_designator="SRT"
)

ULNAR_ARTERY = CodedConcept(
    value="T-47200",
    meaning="Ulnar Artery",
    scheme_designator="SRT"
)

SUPERIOR_LEFT_PULMONARY_VEIN = CodedConcept(
    value="T-48530",
    meaning="Superior Left Pulmonary Vein",
    scheme_designator="SRT"
)

SPLENIC_VEIN = CodedConcept(
    value="T-48890",
    meaning="Splenic Vein",
    scheme_designator="SRT"
)

SUPERFICIAL_FEMORAL_VEIN = CodedConcept(
    value="G-035A",
    meaning="Superficial Femoral Vein",
    scheme_designator="SRT"
)

COMMON_FEMORAL_VEIN = CodedConcept(
    value="G-035B",
    meaning="Common Femoral Vein",
    scheme_designator="SRT"
)

FIRST_LUMBAR_ARTERY = CodedConcept(
    value="G-035E",
    meaning="First Lumbar Artery",
    scheme_designator="SRT"
)

SECOND_LUMBAR_ARTERY = CodedConcept(
    value="G-035F",
    meaning="Second Lumbar Artery",
    scheme_designator="SRT"
)

HILAR_ARTERY = CodedConcept(
    value="G-035C",
    meaning="Hilar Artery",
    scheme_designator="SRT"
)

EXTERNAL_ILIAC_ARTERY = CodedConcept(
    value="T-46910",
    meaning="External Iliac Artery",
    scheme_designator="SRT"
)

VERTEBRAL_ARTERY = CodedConcept(
    value="T-45700",
    meaning="Vertebral Artery",
    scheme_designator="SRT"
)

INNOMINATE_VEIN = CodedConcept(
    value="T-48620",
    meaning="Innominate vein",
    scheme_designator="SRT"
)

LEFT_PULMONARY_VEIN = CodedConcept(
    value="T-48502",
    meaning="Left Pulmonary Vein",
    scheme_designator="SRT"
)

RIGHT_PULMONARY_VEIN = CodedConcept(
    value="T-48501",
    meaning="Right Pulmonary Vein",
    scheme_designator="SRT"
)

GASTRODUODENAL_ARTERY = CodedConcept(
    value="T-46440",
    meaning="Gastroduodenal Artery",
    scheme_designator="SRT"
)

RENAL_VEIN = CodedConcept(
    value="T-48740",
    meaning="Renal Vein",
    scheme_designator="SRT"
)

ARCUATE_ARTERY_OF_THE_KIDNEY = CodedConcept(
    value="T-4668A",
    meaning="Arcuate Artery of the Kidney",
    scheme_designator="SRT"
)

INFRARENAL_AORTA = CodedConcept(
    value="T-42520",
    meaning="Infra-renal Aorta",
    scheme_designator="SRT"
)

SUPERIOR_RIGHT_PULMONARY_VEIN = CodedConcept(
    value="T-48510",
    meaning="Superior Right Pulmonary Vein",
    scheme_designator="SRT"
)

RADIAL_ARTERY = CodedConcept(
    value="T-47300",
    meaning="Radial Artery",
    scheme_designator="SRT"
)

BASILAR_ARTERY = CodedConcept(
    value="T-45800",
    meaning="Basilar Artery",
    scheme_designator="SRT"
)

POPLITEAL_VEIN = CodedConcept(
    value="T-49650",
    meaning="Popliteal Vein",
    scheme_designator="SRT"
)

GREAT_SAPHENOUS_VEIN = CodedConcept(
    value="T-49530",
    meaning="Great Saphenous Vein",
    scheme_designator="SRT"
)

CAROTID_BULB = CodedConcept(
    value="T-45170",
    meaning="Carotid Bulb",
    scheme_designator="SRT"
)

SAPHENOPOPLITEAL_JUNCTION = CodedConcept(
    value="T-4941A",
    meaning="Saphenopopliteal junction",
    scheme_designator="SRT"
)

UTERINE_ARTERY = CodedConcept(
    value="T-46820",
    meaning="Uterine Artery",
    scheme_designator="SRT"
)

UMBILICAL_ARTERY = CodedConcept(
    value="T-F1810",
    meaning="Umbilical Artery",
    scheme_designator="SRT"
)

COCKETT_S_PERFORATING_VEIN = CodedConcept(
    value="T-49426",
    meaning="Cockett's perforating vein",
    scheme_designator="SRT"
)

BOYD_S_PERFORATING_VEIN = CodedConcept(
    value="T-49424",
    meaning="Boyd's perforating vein",
    scheme_designator="SRT"
)

RIGHT_CORONARY_ARTERY = CodedConcept(
    value="T-43200",
    meaning="Right Coronary Artery",
    scheme_designator="SRT"
)

SUBCLAVIAN_VEIN = CodedConcept(
    value="T-48330",
    meaning="Subclavian vein",
    scheme_designator="SRT"
)

PROFUNDA_FEMORIS_VEIN = CodedConcept(
    value="T-49660",
    meaning="Profunda Femoris Vein",
    scheme_designator="SRT"
)

SUPERFICIAL_PALMAR_ARCH = CodedConcept(
    value="T-47240",
    meaning="Superficial Palmar Arch",
    scheme_designator="SRT"
)

MID_RIGHT_CORONARY_ARTERY = CodedConcept(
    value="T-D6515",
    meaning="Mid Right Coronary Artery",
    scheme_designator="SRT"
)

GASTROCNEMIUS_VEIN = CodedConcept(
    value="T-4942D",
    meaning="Gastrocnemius vein",
    scheme_designator="SRT"
)

HUNTERIAN_PERFORATING_VEIN = CodedConcept(
    value="T-4942A",
    meaning="Hunterian perforating vein",
    scheme_designator="SRT"
)

DISTAL_RIGHT_CORONARY_ARTERY = CodedConcept(
    value="T-43202",
    meaning="Distal Right Coronary Artery",
    scheme_designator="SRT"
)

PROXIMAL_RIGHT_CORONARY_ARTERY = CodedConcept(
    value="T-43201",
    meaning="Proximal Right Coronary Artery",
    scheme_designator="SRT"
)

COMMON_ILIAC_ARTERY = CodedConcept(
    value="T-46710",
    meaning="Common Iliac Artery",
    scheme_designator="SRT"
)

RIGHT_CORONARY_ARTERY_OSTIUM = CodedConcept(
    value="T-43205",
    meaning="Right Coronary Artery Ostium",
    scheme_designator="SRT"
)

ANTERIOR_TIBIAL_VEIN = CodedConcept(
    value="T-49630",
    meaning="Anterior Tibial Vein",
    scheme_designator="SRT"
)

INFERIOR_LEFT_PULMONARY_VEIN = CodedConcept(
    value="T-48540",
    meaning="Inferior Left Pulmonary Vein",
    scheme_designator="SRT"
)

GREAT_CARDIAC_VEIN = CodedConcept(
    value="T-48420",
    meaning="Great Cardiac Vein",
    scheme_designator="SRT"
)

OVARIAN_VEIN = CodedConcept(
    value="T-48780",
    meaning="Ovarian vein",
    scheme_designator="SRT"
)

PLANTAR_ARTERIAL_ARCH = CodedConcept(
    value="T-47690",
    meaning="Plantar Arterial Arch",
    scheme_designator="SRT"
)

SMALL_CARDIAC_VEIN = CodedConcept(
    value="T-48435",
    meaning="Small Cardiac Vein",
    scheme_designator="SRT"
)

MIDDLE_CARDIAC_VEIN = CodedConcept(
    value="T-48430",
    meaning="Middle Cardiac Vein",
    scheme_designator="SRT"
)

DEEP_PALMAR_ARCH_OF_RADIAL_ARTERY = CodedConcept(
    value="T-47340",
    meaning="Deep Palmar Arch of Radial Artery",
    scheme_designator="SRT"
)

INNOMINATE_ARTERY = CodedConcept(
    value="T-46010",
    meaning="Innominate Artery",
    scheme_designator="SRT"
)

PERONEAL_VEIN = CodedConcept(
    value="T-49640",
    meaning="Peroneal Vein",
    scheme_designator="SRT"
)

AXILLARY_ARTERY = CodedConcept(
    value="T-47100",
    meaning="Axillary Artery",
    scheme_designator="SRT"
)

CAROTID_BIFURCATION = CodedConcept(
    value="T-45160",
    meaning="Carotid Bifurcation",
    scheme_designator="SRT"
)

SAPHENOUS_VEIN = CodedConcept(
    value="T-4940B",
    meaning="Saphenous vein",
    scheme_designator="SRT"
)

MIDDLE_CEREBRAL_ARTERY = CodedConcept(
    value="T-45600",
    meaning="Middle Cerebral Artery",
    scheme_designator="SRT"
)

INTERNAL_ILIAC_ARTERY = CodedConcept(
    value="T-46740",
    meaning="Internal Iliac Artery",
    scheme_designator="SRT"
)

SUPERFICIAL_PALMAR_VENOUS_ARCH = CodedConcept(
    value="T-49217",
    meaning="Superficial Palmar Venous Arch",
    scheme_designator="SRT"
)

ANTERIOR_COMMUNICATING_ARTERY = CodedConcept(
    value="T-45530",
    meaning="Anterior Communicating Artery",
    scheme_designator="SRT"
)

COMMON_ILIAC_VEIN = CodedConcept(
    value="T-48920",
    meaning="Common Iliac Vein",
    scheme_designator="SRT"
)

DISTAL_LEFT_ANTERIOR_DESCENDING_CORONARY_ARTERY = CodedConcept(
    value="T-43112",
    meaning="Distal Left Anterior Descending Coronary Artery",
    scheme_designator="SRT"
)

PROXIMAL_LEFT_ANTERIOR_DESCENDING_CORONARY_ARTERY = CodedConcept(
    value="T-43111",
    meaning="Proximal Left Anterior Descending Coronary Artery",
    scheme_designator="SRT"
)

LEFT_ANTERIOR_DESCENDING_CORONARY_ARTERY = CodedConcept(
    value="T-43110",
    meaning="Left Anterior Descending Coronary Artery",
    scheme_designator="SRT"
)

MARGINAL_CORONARY_ARTERY = CodedConcept(
    value="T-43230",
    meaning="Marginal Coronary Artery",
    scheme_designator="SRT"
)

OVARIAN_ARTERY = CodedConcept(
    value="T-46980",
    meaning="Ovarian Artery",
    scheme_designator="SRT"
)

ULNAR_VEIN = CodedConcept(
    value="T-49330",
    meaning="Ulnar vein",
    scheme_designator="SRT"
)

MIDDLE_CEREBRAL_ARTERY_M1_SEGMENT = CodedConcept(
    value="R-1024F",
    meaning="Middle Cerebral Artery M1 Segment",
    scheme_designator="SRT"
)

MID_LEFT_ANTERIOR_DESCENDING_CORONARY_ARTERY = CodedConcept(
    value="T-43115",
    meaning="Mid Left Anterior Descending Coronary Artery",
    scheme_designator="SRT"
)

DIAGONAL_CORONARY_ARTERY_3RD = CodedConcept(
    value="T-43119",
    meaning="3rd diagonal Coronary Artery",
    scheme_designator="SRT"
)

DEEP_PALMAR_VENOUS_ARCH = CodedConcept(
    value="T-49218",
    meaning="Deep Palmar Venous Arch",
    scheme_designator="SRT"
)

DIAGONAL_CORONARY_ARTERY_2ND = CodedConcept(
    value="T-43118",
    meaning="2nd Diagonal Coronary Artery",
    scheme_designator="SRT"
)

DIAGONAL_CORONARY_ARTERY_1ST = CodedConcept(
    value="T-43117",
    meaning="1st Diagonal Coronary Artery",
    scheme_designator="SRT"
)

ANTERIOR_CEREBRAL_ARTERY = CodedConcept(
    value="T-45540",
    meaning="Anterior Cerebral Artery",
    scheme_designator="SRT"
)

GREAT_SAPHENOUS_VEIN_OF_THIGH = CodedConcept(
    value="R-10259",
    meaning="Great Saphenous Vein of Thigh",
    scheme_designator="SRT"
)

POSTERIOR_TIBIAL_ARTERY = CodedConcept(
    value="T-47600",
    meaning="Posterior Tibial Artery",
    scheme_designator="SRT"
)

SUPERIOR_MESENTERIC_ARTERY = CodedConcept(
    value="T-46510",
    meaning="Superior Mesenteric Artery",
    scheme_designator="SRT"
)

PORTAL_VEIN = CodedConcept(
    value="T-48810",
    meaning="Portal Vein",
    scheme_designator="SRT"
)

INTERNAL_CAROTID_ARTERY = CodedConcept(
    value="T-45300",
    meaning="Internal Carotid Artery",
    scheme_designator="SRT"
)

EXTERNAL_ILIAC_VEIN = CodedConcept(
    value="T-48930",
    meaning="External Iliac Vein",
    scheme_designator="SRT"
)

COMMON_ILIAC_ARTERY_BIFURCATION = CodedConcept(
    value="R-10258",
    meaning="Common Iliac Artery Bifurcation",
    scheme_designator="SRT"
)

CORONARY_ARTERY_GRAFT = CodedConcept(
    value="T-41065",
    meaning="Coronary Artery Graft",
    scheme_designator="SRT"
)

SEPTAL_CORONARY_ARTERY_1ST = CodedConcept(
    value="T-43002",
    meaning="1st Septal Coronary Artery",
    scheme_designator="SRT"
)

DISTAL_CIRCUMFLEX_CORONARY_ARTERY = CodedConcept(
    value="T-43122",
    meaning="Distal Circumflex Coronary Artery",
    scheme_designator="SRT"
)

PROXIMAL_CIRCUMFLEX_CORONARY_ARTERY = CodedConcept(
    value="T-43121",
    meaning="Proximal Circumflex Coronary Artery",
    scheme_designator="SRT"
)

CIRCUMFLEX_CORONARY_ARTERY = CodedConcept(
    value="T-43120",
    meaning="Circumflex Coronary Artery",
    scheme_designator="SRT"
)

RADIAL_VEIN = CodedConcept(
    value="T-49340",
    meaning="Radial vein",
    scheme_designator="SRT"
)

BRACHIAL_ARTERY = CodedConcept(
    value="T-47160",
    meaning="Brachial Artery",
    scheme_designator="SRT"
)

GREAT_SAPHENOUS_VEIN_OF_CALF = CodedConcept(
    value="R-1025A",
    meaning="Great Saphenous Vein of Calf",
    scheme_designator="SRT"
)

LEFT_POSTEROLATERAL_CORONARY_ARTERY_2ND = CodedConcept(
    value="T-4312C",
    meaning="2nd Left Posterolateral Coronary Artery",
    scheme_designator="SRT"
)

LEFT_POSTEROLATERAL_CORONARY_ARTERY_1ST = CodedConcept(
    value="T-4312B",
    meaning="1st Left Posterolateral Coronary Artery",
    scheme_designator="SRT"
)

MARGINAL_CORONARY_ARTERY_3RD = CodedConcept(
    value="T-4312A",
    meaning="3rd Marginal Coronary Artery",
    scheme_designator="SRT"
)

MID_CIRCUMFLEX_CORONARY_ARTERY = CodedConcept(
    value="T-43127",
    meaning="Mid Circumflex Coronary Artery",
    scheme_designator="SRT"
)

POSTERIOR_CEREBRAL_ARTERY_P1_SEGMENT = CodedConcept(
    value="R-10253",
    meaning="Posterior Cerebral Artery P1 Segment",
    scheme_designator="SRT"
)

LEFT_POSTEROLATERAL_CIRCUMFLEX_CORONARY_ARTERY = CodedConcept(
    value="T-43125",
    meaning="Left Posterolateral Circumflex Coronary Artery",
    scheme_designator="SRT"
)

CAROTID_SIPHON = CodedConcept(
    value="T-45308",
    meaning="Carotid Siphon",
    scheme_designator="SRT"
)

MIDDLE_CEREBRAL_ARTERY_M2_SEGMENT = CodedConcept(
    value="R-10251",
    meaning="Middle Cerebral Artery M2 Segment",
    scheme_designator="SRT"
)

AV_GROOVE_CONTINUATION_OF_CIRCUMFLEX_ARTERY = CodedConcept(
    value="T-43124",
    meaning="AV groove continuation of Circumflex Artery",
    scheme_designator="SRT"
)

INTERMEDIATE_ARTERY_RAMUS_ = CodedConcept(
    value="T-43003",
    meaning="Intermediate Artery (Ramus)",
    scheme_designator="SRT"
)

MARGINAL_CORONARY_ARTERY_2ND = CodedConcept(
    value="T-43129",
    meaning="2nd Marginal Coronary Artery",
    scheme_designator="SRT"
)

LEFT_MAIN_BRANCH_OF_PORTAL_VEIN = CodedConcept(
    value="T-48814",
    meaning="Left Main Branch of Portal Vein",
    scheme_designator="SRT"
)

POSTERIOR_CEREBRAL_ARTERY_P2_SEGMENT = CodedConcept(
    value="R-10255",
    meaning="Posterior Cerebral Artery P2 Segment",
    scheme_designator="SRT"
)

MARGINAL_CORONARY_ARTERY_1ST = CodedConcept(
    value="T-43128",
    meaning="1st Marginal Coronary Artery",
    scheme_designator="SRT"
)

RIGHT_MAIN_BRANCH_OF_PORTAL_VEIN = CodedConcept(
    value="T-48813",
    meaning="Right Main Branch of Portal Vein",
    scheme_designator="SRT"
)

LUMBAR_ARTERY = CodedConcept(
    value="T-46960",
    meaning="Lumbar Artery",
    scheme_designator="SRT"
)

POSTERIOR_DESCENDING_RIGHT_CORONARY_ARTERY = CodedConcept(
    value="T-43210",
    meaning="Posterior Descending Right Coronary Artery",
    scheme_designator="SRT"
)

AORTA = CodedConcept(
    value="T-42000",
    meaning="Aorta",
    scheme_designator="SRT"
)

LESSER_SAPHENOUS_VEIN = CodedConcept(
    value="T-49550",
    meaning="Lesser Saphenous Vein",
    scheme_designator="SRT"
)

AZYGOS_VEIN = CodedConcept(
    value="T-48340",
    meaning="Azygos Vein",
    scheme_designator="SRT"
)

THIGH_PERFORATOR = CodedConcept(
    value="T-F6713",
    meaning="Thigh perforator",
    scheme_designator="SRT"
)

PULMONARY_VEIN = CodedConcept(
    value="T-4858F",
    meaning="Pulmonary Vein",
    scheme_designator="SRT"
)

RIGHT_POSTEROLATERAL_CORONARY_ARTERY_3RD = CodedConcept(
    value="T-43215",
    meaning="3rd Right posterolateral Coronary Artery",
    scheme_designator="SRT"
)

RIGHT_POSTEROLATERAL_CORONARY_ARTERY_2ND = CodedConcept(
    value="T-43214",
    meaning="2nd Right posterolateral Coronary Artery",
    scheme_designator="SRT"
)

RIGHT_POSTEROLATERAL_CORONARY_ARTERY_1ST = CodedConcept(
    value="T-43213",
    meaning="1st Right posterolateral Coronary Artery",
    scheme_designator="SRT"
)

RIGHT_POSTERIOR_AV_CORONARY_ARTERY = CodedConcept(
    value="T-43212",
    meaning="Right posterior AV Coronary Artery",
    scheme_designator="SRT"
)

TERMINAL_INTERNAL_CAROTID_ARTERY = CodedConcept(
    value="R-102BD",
    meaning="Terminal internal carotid artery",
    scheme_designator="SRT"
)

RENAL_ARTERY = CodedConcept(
    value="T-46600",
    meaning="Renal Artery",
    scheme_designator="SRT"
)

INTERNAL_CAROTID_ARTERY_C5_SEGMENT = CodedConcept(
    value="R-102BB",
    meaning="Internal Carotid Artery C5 segment",
    scheme_designator="SRT"
)

TESTICULAR_ARTERY = CodedConcept(
    value="T-46970",
    meaning="Testicular Artery",
    scheme_designator="SRT"
)

OPHTHALMIC_ARTERY = CodedConcept(
    value="T-45400",
    meaning="Ophthalmic Artery",
    scheme_designator="SRT"
)

DIGITAL_ARTERY_OF_HAND = CodedConcept(
    value="T-47260",
    meaning="Digital artery of hand",
    scheme_designator="SRT"
)

LATERAL_CALF_PERFORATOR = CodedConcept(
    value="T-F6724",
    meaning="Lateral calf perforator",
    scheme_designator="SRT"
)

LEFT_MAIN_CORONARY_ARTERY_OSTIUM = CodedConcept(
    value="T-43105",
    meaning="Left Main Coronary Artery Ostium",
    scheme_designator="SRT"
)

ANTERIOR_TIBIAL_ARTERY = CodedConcept(
    value="T-47700",
    meaning="Anterior Tibial Artery",
    scheme_designator="SRT"
)

INFERIOR_MESENTERIC_VEIN = CodedConcept(
    value="T-48910",
    meaning="Inferior Mesenteric Vein",
    scheme_designator="SRT"
)

LEFT_MAIN_CORONARY_ARTERY = CodedConcept(
    value="T-43107",
    meaning="Left Main Coronary Artery",
    scheme_designator="SRT"
)

HEPATIC_VEIN = CodedConcept(
    value="T-48720",
    meaning="Hepatic Vein",
    scheme_designator="SRT"
)

PERONEAL_ARTERY = CodedConcept(
    value="T-47630",
    meaning="Peroneal Artery",
    scheme_designator="SRT"
)

COMMON_HEPATIC_ARTERY = CodedConcept(
    value="T-46421",
    meaning="Common Hepatic Artery",
    scheme_designator="SRT"
)

SUPERIOR_MESENTERIC_VEIN = CodedConcept(
    value="T-48840",
    meaning="Superior Mesenteric Vein",
    scheme_designator="SRT"
)

PROPER_HEPATIC_ARTERY = CodedConcept(
    value="T-46422",
    meaning="Proper Hepatic Artery",
    scheme_designator="SRT"
)

RIGHT_BRANCH_OF_HEPATIC_ARTERY = CodedConcept(
    value="T-46423",
    meaning="Right Branch of Hepatic Artery",
    scheme_designator="SRT"
)

CENTRAL_RETINAL_VEIN = CodedConcept(
    value="T-48286",
    meaning="Central Retinal Vein",
    scheme_designator="SRT"
)

MEDIAN_CUBITAL_VEIN = CodedConcept(
    value="T-49250",
    meaning="Median Cubital vein",
    scheme_designator="SRT"
)

LEFT_HEPATIC_VEIN = CodedConcept(
    value="T-48727",
    meaning="Left Hepatic Vein",
    scheme_designator="SRT"
)

MIDDLE_HEPATIC_VEIN = CodedConcept(
    value="T-48726",
    meaning="Middle Hepatic Vein",
    scheme_designator="SRT"
)

PERFORATING_ARTERY_OF_KIDNEY = CodedConcept(
    value="T-46668",
    meaning="Perforating Artery of Kidney",
    scheme_designator="SRT"
)

LEFT_BRANCH_OF_HEPATIC_ARTERY = CodedConcept(
    value="T-46427",
    meaning="Left Branch of Hepatic Artery",
    scheme_designator="SRT"
)

RIGHT_HEPATIC_VEIN = CodedConcept(
    value="T-48725",
    meaning="Right Hepatic Vein",
    scheme_designator="SRT"
)

SUPERIOR_VENA_CAVA = CodedConcept(
    value="T-48610",
    meaning="Superior Vena Cava",
    scheme_designator="SRT"
)

COMMON_CAROTID_ARTERY = CodedConcept(
    value="T-45100",
    meaning="Common Carotid Artery",
    scheme_designator="SRT"
)

COMMON_FEMORAL_ARTERY = CodedConcept(
    value="T-47402",
    meaning="Common Femoral Artery",
    scheme_designator="SRT"
)

INTERNAL_JUGULAR_VEIN = CodedConcept(
    value="T-48170",
    meaning="Internal Jugular vein",
    scheme_designator="SRT"
)

LOBAR_ARTERY = CodedConcept(
    value="T-4667C",
    meaning="Lobar Artery",
    scheme_designator="SRT"
)

INTERLOBAR_ARTERY_OF_KIDNEY = CodedConcept(
    value="T-4667D",
    meaning="Interlobar Artery of Kidney",
    scheme_designator="SRT"
)

POSTERIOR_CEREBRAL_ARTERY = CodedConcept(
    value="T-45900",
    meaning="Posterior Cerebral Artery",
    scheme_designator="SRT"
)

SUPRARENAL_AORTA = CodedConcept(
    value="T-42510",
    meaning="Supra-renal Aorta",
    scheme_designator="SRT"
)

SUPERFICIAL_FEMORAL_ARTERY = CodedConcept(
    value="T-47403",
    meaning="Superficial Femoral Artery",
    scheme_designator="SRT"
)

INTERNAL_ILIAC_VEIN = CodedConcept(
    value="T-48940",
    meaning="Internal iliac vein",
    scheme_designator="SRT"
)

ACCESSORY_RENAL_ARTERY = CodedConcept(
    value="T-46640",
    meaning="Accessory Renal Artery",
    scheme_designator="SRT"
)

CENTRAL_RETINAL_ARTERY = CodedConcept(
    value="T-45430",
    meaning="Central Retinal Artery",
    scheme_designator="SRT"
)

INFERIOR_MESENTERIC_ARTERY = CodedConcept(
    value="T-46520",
    meaning="Inferior Mesenteric Artery",
    scheme_designator="SRT"
)

CELIAC_AXIS = CodedConcept(
    value="T-46400",
    meaning="Celiac Axis",
    scheme_designator="SRT"
)

GASTRIC_VEIN = CodedConcept(
    value="T-48820",
    meaning="Gastric vein",
    scheme_designator="SRT"
)

BASILIC_VEIN = CodedConcept(
    value="T-49230",
    meaning="Basilic vein",
    scheme_designator="SRT"
)

AXILLARY_VEIN = CodedConcept(
    value="T-49110",
    meaning="Axillary vein",
    scheme_designator="SRT"
)

LEFT_POSTERIOR_DESCENDING_CIRCUMFLEX_CORONARY_ARTERY = CodedConcept(
    value="T-4312E",
    meaning="Left Posterior Descending Circumflex Coronary Artery",
    scheme_designator="SRT"
)

BRACHIAL_VEIN = CodedConcept(
    value="T-49350",
    meaning="Brachial vein",
    scheme_designator="SRT"
)

LEFT_POSTEROLATERAL_CORONARY_ARTERY_3RD = CodedConcept(
    value="T-4312D",
    meaning="3rd Left Posterolateral Coronary Artery",
    scheme_designator="SRT"
)

POSTERIOR_COMMUNICATING_ARTERY = CodedConcept(
    value="T-45320",
    meaning="Posterior Communicating Artery",
    scheme_designator="SRT"
)

DORSALIS_PEDIS_ARTERY = CodedConcept(
    value="T-47740",
    meaning="Dorsalis Pedis Artery",
    scheme_designator="SRT"
)

GASTRIC_ARTERY = CodedConcept(
    value="T-46410",
    meaning="Gastric Artery",
    scheme_designator="SRT"
)

EXTERNAL_CAROTID_ARTERY = CodedConcept(
    value="T-45200",
    meaning="External Carotid Artery",
    scheme_designator="SRT"
)

UMBILICAL_VEIN = CodedConcept(
    value="T-48832",
    meaning="Umbilical Vein",
    scheme_designator="SRT"
)

POPLITEAL_ARTERY = CodedConcept(
    value="T-47500",
    meaning="Popliteal Artery",
    scheme_designator="SRT"
)

INFERIOR_VENA_CAVA = CodedConcept(
    value="T-48710",
    meaning="Inferior Vena Cava",
    scheme_designator="SRT"
)

CEPHALIC_VEIN = CodedConcept(
    value="T-49240",
    meaning="Cephalic vein",
    scheme_designator="SRT"
)

INTERNAL_CAROTID_ARTERY_C6_SEGMENT = CodedConcept(
    value="R-FAED1",
    meaning="Internal Carotid Artery C6 segment",
    scheme_designator="SRT"
)

SEGMENTAL_ARTERY = CodedConcept(
    value="T-46659",
    meaning="Segmental Artery",
    scheme_designator="SRT"
)

