"""CID 6207 ColonQuantitativeTemporalDifferenceType
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


DIFFERENCE_IN_LOCATION = CodedConcept(
    value="F-05179",
    meaning="Difference in location",
    scheme_designator="SRT"
)

DIFFERENCE_IN_ATTENUATION = CodedConcept(
    value="F-0516E",
    meaning="Difference in attenuation",
    scheme_designator="SRT"
)

DIFFERENCE_IN_SIZE = CodedConcept(
    value="F-05173",
    meaning="Difference in size",
    scheme_designator="SRT"
)

