"""CID 12216 EchocardiographyHepaticVeins
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


HEPATIC_VEIN_ATRIAL_CONTRACTION_REVERSAL_PEAK_VELOCITY = CodedConcept(
    value="29474-4",
    meaning="Hepatic Vein Atrial Contraction Reversal Peak Velocity",
    scheme_designator="LN"
)

HEPATIC_VEIN_SYSTOLIC_TO_DIASTOLIC_RATIO = CodedConcept(
    value="29473-6",
    meaning="Hepatic Vein Systolic to Diastolic Ratio",
    scheme_designator="LN"
)

HEPATIC_VEIN_DIASTOLIC_PEAK_VELOCITY = CodedConcept(
    value="29472-8",
    meaning="Hepatic Vein Diastolic Peak Velocity",
    scheme_designator="LN"
)

HEART_RATE = CodedConcept(
    value="8867-4",
    meaning="Heart rate",
    scheme_designator="LN"
)

HEPATIC_VEIN_SYSTOLIC_PEAK_VELOCITY = CodedConcept(
    value="29471-0",
    meaning="Hepatic Vein Systolic Peak Velocity",
    scheme_designator="LN"
)

