"""CID 4230 OphthalmicUltrasoundAxialMeasurementsType
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


ULTRASOUND_CONTACT = CodedConcept(
    value="111750",
    meaning="Ultrasound Contact",
    scheme_designator="DCM"
)

ULTRASOUND_IMMERSION = CodedConcept(
    value="111751",
    meaning="Ultrasound Immersion",
    scheme_designator="DCM"
)

