"""CID 10062 EquivalentRadiationDoseTypes
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


MEDIAN_EQUIVALENT_RADIATION_DOSE = CodedConcept(
    value="128540",
    meaning="Median Equivalent Radiation Dose",
    scheme_designator="DCM"
)

MINIMUM_EQUIVALENT_RADIATION_DOSE = CodedConcept(
    value="128536",
    meaning="Minimum Equivalent Radiation Dose",
    scheme_designator="DCM"
)

MAXIMUM_EQUIVALENT_RADIATION_DOSE = CodedConcept(
    value="128535",
    meaning="Maximum Equivalent Radiation Dose",
    scheme_designator="DCM"
)

MODE_EQUIVALENT_RADIATION_DOSE = CodedConcept(
    value="128538",
    meaning="Mode Equivalent Radiation Dose",
    scheme_designator="DCM"
)

MEAN_EQUIVALENT_RADIATION_DOSE = CodedConcept(
    value="128537",
    meaning="Mean Equivalent Radiation Dose",
    scheme_designator="DCM"
)

