"""CID 4252 VisualFieldStaticPerimetryScreeningTestModes
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


AGE_CORRECTED = CodedConcept(
    value="111838",
    meaning="Age corrected",
    scheme_designator="DCM"
)

THRESHOLD_RELATED = CodedConcept(
    value="111839",
    meaning="Threshold related",
    scheme_designator="DCM"
)

USER_CHOSEN_VALUE = CodedConcept(
    value="121410",
    meaning="User chosen value",
    scheme_designator="DCM"
)

SINGLE_LUMINANCE = CodedConcept(
    value="111840",
    meaning="Single luminance",
    scheme_designator="DCM"
)

FOVEAL_SENSITIVITY_RELATED = CodedConcept(
    value="111841",
    meaning="Foveal sensitivity related",
    scheme_designator="DCM"
)

RELATED_TO_NON_MACULAR_SENSITIVITY = CodedConcept(
    value="111842",
    meaning="Related to non macular sensitivity",
    scheme_designator="DCM"
)

