"""CID 4244 OphthalmicAgentConcentrationUnits
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


PERCENT = CodedConcept(
    value="%",
    meaning="Percent",
    scheme_designator="UCUM"
)

MG_ML = CodedConcept(
    value="mg/ml",
    meaning="mg/ml",
    scheme_designator="UCUM"
)

