"""CID 221 MeasurementRangeConcepts
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


PERCENTILE_RANKING_OF_MEASUREMENT = CodedConcept(
    value="121415",
    meaning="Percentile Ranking of measurement",
    scheme_designator="DCM"
)

ZSCORE_OF_MEASUREMENT = CodedConcept(
    value="121416",
    meaning="Z-Score of measurement",
    scheme_designator="DCM"
)

STANDARD_DEVIATION_OF_POPULATION = CodedConcept(
    value="121414",
    meaning="Standard deviation of population",
    scheme_designator="DCM"
)

SIGMA_DEVIATION_OF_POPULATION_2 = CodedConcept(
    value="121417",
    meaning="2 Sigma deviation of population",
    scheme_designator="DCM"
)

PERCENTILE_VALUE_OF_POPULATION_10TH = CodedConcept(
    value="R-00377",
    meaning="10th Percentile Value of population",
    scheme_designator="SRT"
)

SIGMA_LOWER_VALUE_OF_POPULATION_2 = CodedConcept(
    value="R-00388",
    meaning="2 Sigma Lower Value of population",
    scheme_designator="SRT"
)

SIGMA_UPPER_VALUE_OF_POPULATION_2 = CodedConcept(
    value="R-00387",
    meaning="2 Sigma Upper Value of population",
    scheme_designator="SRT"
)

SIGMA_UPPER_VALUE_OF_POPULATION_1 = CodedConcept(
    value="R-00346",
    meaning="1 Sigma Upper Value of population",
    scheme_designator="SRT"
)

PERCENTILE_VALUE_OF_POPULATION_5TH = CodedConcept(
    value="R-00397",
    meaning="5th Percentile Value of population",
    scheme_designator="SRT"
)

MEDIAN_VALUE_OF_POPULATION = CodedConcept(
    value="R-00319",
    meaning="Median Value of population",
    scheme_designator="SRT"
)

PERCENTILE_VALUE_OF_POPULATION_95TH = CodedConcept(
    value="R-00337",
    meaning="95th Percentile Value of population",
    scheme_designator="SRT"
)

SIGMA_LOWER_VALUE_OF_POPULATION_1 = CodedConcept(
    value="R-00347",
    meaning="1 Sigma Lower Value of population",
    scheme_designator="SRT"
)

MEAN_VALUE_OF_POPULATION = CodedConcept(
    value="R-00317",
    meaning="Mean Value of population",
    scheme_designator="SRT"
)

PERCENTILE_VALUE_OF_POPULATION_90TH = CodedConcept(
    value="R-00338",
    meaning="90th Percentile Value of population",
    scheme_designator="SRT"
)

