"""CID 6038 MammographyQualitativeTemporalDifferenceType
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


DIFFERENCE_IN_SYMMETRY = CodedConcept(
    value="F-017B8",
    meaning="Difference in symmetry",
    scheme_designator="SRT"
)

DIFFERENCE_IN_MARGIN = CodedConcept(
    value="F-017B7",
    meaning="Difference in margin",
    scheme_designator="SRT"
)

DIFFERENCE_IN_SHAPE = CodedConcept(
    value="F-017B6",
    meaning="Difference in shape",
    scheme_designator="SRT"
)

