"""CID 7472 VolumeMeasurements
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


VOLUME_ESTIMATED_FROM_THREE_OR_MORE_NONCOPLANAR_2D_REGIONS = CodedConcept(
    value="121217",
    meaning="Volume estimated from three or more non-coplanar 2D regions",
    scheme_designator="DCM"
)

VOLUME_ESTIMATED_FROM_TWO_NONCOPLANAR_2D_REGIONS = CodedConcept(
    value="121218",
    meaning="Volume estimated from two non-coplanar 2D regions",
    scheme_designator="DCM"
)

VOLUME_ESTIMATED_FROM_SINGLE_2D_REGION = CodedConcept(
    value="121216",
    meaning="Volume estimated from single 2D region",
    scheme_designator="DCM"
)

VOLUME_OF_SPHERE = CodedConcept(
    value="121222",
    meaning="Volume of sphere",
    scheme_designator="DCM"
)

VOLUME_OF_CIRCUMSCRIBED_SPHERE = CodedConcept(
    value="121220",
    meaning="Volume of circumscribed sphere",
    scheme_designator="DCM"
)

VOLUME_OF_ELLIPSOID = CodedConcept(
    value="121221",
    meaning="Volume of ellipsoid",
    scheme_designator="DCM"
)

VOLUME_OF_BOUNDING_THREE_DIMENSIONAL_REGION = CodedConcept(
    value="121219",
    meaning="Volume of bounding three dimensional region",
    scheme_designator="DCM"
)

VOLUME = CodedConcept(
    value="G-D705",
    meaning="Volume",
    scheme_designator="SRT"
)

