"""CID 6164 TimeIntervals
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


_3_MONTHS_AGO = CodedConcept(
    value="111396",
    meaning="< 3 months ago",
    scheme_designator="DCM"
)

MONTHS_TO_1_YEAR_AGO_4 = CodedConcept(
    value="111397",
    meaning="4 months to 1 year ago",
    scheme_designator="DCM"
)

_1_YEAR_AGO = CodedConcept(
    value="111398",
    meaning="> 1 year ago",
    scheme_designator="DCM"
)

NOT_SURE = CodedConcept(
    value="111399",
    meaning="Not sure",
    scheme_designator="DCM"
)

