"""CID 6130 SeverityDescriptor
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


HYPERACUTE = CodedConcept(
    value="112159",
    meaning="Hyper-acute",
    scheme_designator="DCM"
)

MILD = CodedConcept(
    value="R-404FA",
    meaning="Mild",
    scheme_designator="SRT"
)

CHRONIC = CodedConcept(
    value="G-A270",
    meaning="Chronic",
    scheme_designator="SRT"
)

SUBACUTE = CodedConcept(
    value="G-A561",
    meaning="Subacute",
    scheme_designator="SRT"
)

SEVERE = CodedConcept(
    value="G-A003",
    meaning="Severe",
    scheme_designator="SRT"
)

MODERATE = CodedConcept(
    value="G-A002",
    meaning="Moderate",
    scheme_designator="SRT"
)

ACUTE_ONSET = CodedConcept(
    value="R-424BE",
    meaning="Acute onset",
    scheme_designator="SRT"
)

