"""CID 6095 NumericPropertiesofProcedures
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


NEEDLE_GAUGE = CodedConcept(
    value="111465",
    meaning="Needle Gauge",
    scheme_designator="DCM"
)

NEEDLE_LENGTH = CodedConcept(
    value="111467",
    meaning="Needle Length",
    scheme_designator="DCM"
)

