"""CID 3430 DateTimeQualifiers
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


DATETIME_UNSYNCHRONIZED = CodedConcept(
    value="121136",
    meaning="DateTime Unsynchronized",
    scheme_designator="DCM"
)

DATETIME_ESTIMATED = CodedConcept(
    value="121137",
    meaning="DateTime Estimated",
    scheme_designator="DCM"
)

