"""CID 7484 DXViewforAnimals
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


CAUDAL_10_DEGREE_DISTALCRANIOPROXIMAL_OBLIQUE = CodedConcept(
    value="123019",
    meaning="Caudal 10 degree distal-cranioproximal oblique",
    scheme_designator="DCM"
)

RIGHT_30_DEGREE_CAUDALLEFT_ROSTRAL_OBLIQUE = CodedConcept(
    value="R-40ACA",
    meaning="Right 30 degree caudal-left rostral oblique",
    scheme_designator="SRT"
)

RIGHT_DORSALLEFT_VENTRAL_OBLIQUE = CodedConcept(
    value="R-40ACC",
    meaning="Right dorsal-left ventral oblique",
    scheme_designator="SRT"
)

DORSAL_35_DEGREE_LATERALPLANTAROMEDIAL_OBLIQUE = CodedConcept(
    value="R-40ACB",
    meaning="Dorsal 35 degree lateral-plantaromedial oblique",
    scheme_designator="SRT"
)

CAUDODISTALCRANIOPROXIMAL_OBLIQUE = CodedConcept(
    value="R-40AC9",
    meaning="Caudodistal-cranioproximal oblique",
    scheme_designator="SRT"
)

PLANTAR_75_DEGREE_PROXIMALDORSODISTAL_OBLIQUE = CodedConcept(
    value="R-40AC8",
    meaning="Plantar 75 degree proximal-dorsodistal oblique",
    scheme_designator="SRT"
)

DORSAL_45_DEGREE_MEDIALPLANTAROLATERAL_OBLIQUE = CodedConcept(
    value="R-40AC5",
    meaning="Dorsal 45 degree medial-plantarolateral oblique",
    scheme_designator="SRT"
)

LEFT_45_DEGREE_VENTRALRIGHT_DORSAL_OBLIQUE = CodedConcept(
    value="R-40AC4",
    meaning="Left 45 degree ventral-right dorsal oblique",
    scheme_designator="SRT"
)

DORSAL_60_DEGREE_MEDIALPALMAROLATERAL_OBLIQUE = CodedConcept(
    value="R-40AC7",
    meaning="Dorsal 60 degree medial-palmarolateral oblique",
    scheme_designator="SRT"
)

DORSAL_60_DEGREE_LATERALPLANTAROMEDIAL_OBLIQUE = CodedConcept(
    value="R-40AC6",
    meaning="Dorsal 60 degree lateral-plantaromedial oblique",
    scheme_designator="SRT"
)

LEFT_30_DEGREE_CAUDALRIGHT_ROSTRAL_OBLIQUE = CodedConcept(
    value="R-40AC1",
    meaning="Left 30 degree caudal-right rostral oblique",
    scheme_designator="SRT"
)

RIGHT_VENTRALLEFT_DORSAL_OBLIQUE = CodedConcept(
    value="R-40AC0",
    meaning="Right ventral-left dorsal oblique",
    scheme_designator="SRT"
)

LEFT_45_DEGREE_DORSALRIGHT_VENTRAL_OBLIQUE = CodedConcept(
    value="R-40AC3",
    meaning="Left 45 degree dorsal-right ventral oblique",
    scheme_designator="SRT"
)

DORSAL_45_DEGREE_LATERALPALMAROMEDIAL_OBLIQUE = CodedConcept(
    value="R-40AC2",
    meaning="Dorsal 45 degree lateral-palmaromedial oblique",
    scheme_designator="SRT"
)

DORSOPROXIMALPLANTARODISTAL_OBLIQUE = CodedConcept(
    value="R-40ABD",
    meaning="Dorsoproximal-plantarodistal oblique",
    scheme_designator="SRT"
)

PALMAR_75_DEGREE_PROXIMALDORSODISTAL_OBLIQUE = CodedConcept(
    value="R-40ABC",
    meaning="Palmar 75 degree proximal-dorsodistal oblique",
    scheme_designator="SRT"
)

CAUDOCRANIAL = CodedConcept(
    value="R-10244",
    meaning="Caudocranial",
    scheme_designator="SRT"
)

RIGHT_ROSTRALLEFT_CAUDAL_OBLIQUE = CodedConcept(
    value="R-40AFD",
    meaning="Right rostral-left caudal oblique",
    scheme_designator="SRT"
)

DORSAL_35_DEGREE_LATERALPALMAROMEDIAL_OBLIQUE = CodedConcept(
    value="R-40AFC",
    meaning="Dorsal 35 degree lateral-palmaromedial oblique",
    scheme_designator="SRT"
)

VENTRAL_LEFTDORSAL_RIGHT_OBLIQUE = CodedConcept(
    value="R-40ABB",
    meaning="Ventral left-dorsal right oblique",
    scheme_designator="SRT"
)

LEFT_20_DEGREE_DORSALRIGHT_VENTRAL_OBLIQUE = CodedConcept(
    value="R-40AFE",
    meaning="Left 20 degree dorsal-right ventral oblique",
    scheme_designator="SRT"
)

VENTRAL_30_DEGREE_LEFTDORSAL_RIGHT_OBLIQUE = CodedConcept(
    value="R-40ABA",
    meaning="Ventral 30 degree left-dorsal right oblique",
    scheme_designator="SRT"
)

DORSAL_20_DEGREE_ROSTRALVENTROCAUDAL_OBLIQUE = CodedConcept(
    value="R-40AFB",
    meaning="Dorsal 20 degree rostral-ventrocaudal oblique",
    scheme_designator="SRT"
)

DORSOPROXIMALPALMARODISTAL_OBLIQUE = CodedConcept(
    value="R-40AFA",
    meaning="Dorsoproximal-palmarodistal oblique",
    scheme_designator="SRT"
)

VENTRAL_30_DEGREE_RIGHTDORSAL_LEFT_OBLIQUE = CodedConcept(
    value="R-40AB8",
    meaning="Ventral 30 degree right-dorsal left oblique",
    scheme_designator="SRT"
)

ROSTROVENTRALCAUDODORSAL = CodedConcept(
    value="R-40AB7",
    meaning="Rostroventral-caudodorsal",
    scheme_designator="SRT"
)

ROSTRAL_30_DEGREE_VENTRALCAUDODORSAL = CodedConcept(
    value="R-40AB9",
    meaning="Rostral 30 degree ventral-caudodorsal",
    scheme_designator="SRT"
)

LATERAL_45_DEG_DORSAL_50_DEG_PROXIMALMEDIOPALMARODISTAL_OBLIQUE = CodedConcept(
    value="R-40AB4",
    meaning="Lateral 45 deg dorsal 50 deg proximal-mediopalmarodistal oblique",
    scheme_designator="SRT"
)

PALMAROMEDIALDORSOLATERAL = CodedConcept(
    value="R-40AF8",
    meaning="Palmaromedial-dorsolateral",
    scheme_designator="SRT"
)

VENTROROSTRALDORSOCAUDAL_OBLIQUE = CodedConcept(
    value="R-40AF7",
    meaning="Ventrorostral-dorsocaudal oblique",
    scheme_designator="SRT"
)

DORSAL_40_DEGREE_LATERALPLANTAROMEDIAL_OBLIQUE = CodedConcept(
    value="R-40AB6",
    meaning="Dorsal 40 degree lateral-plantaromedial oblique",
    scheme_designator="SRT"
)

DORSAL_35_DEGREE_MEDIALPALMAROLATERAL_OBLIQUE = CodedConcept(
    value="R-40AB5",
    meaning="Dorsal 35 degree medial-palmarolateral oblique",
    scheme_designator="SRT"
)

RIGHT_20_DEGREE_ROSTRALLEFT_CAUDAL_OBLIQUE = CodedConcept(
    value="R-40AF9",
    meaning="Right 20 degree rostral-left caudal oblique",
    scheme_designator="SRT"
)

VENTRAL_RIGHTDORSAL_LEFT_OBLIQUE = CodedConcept(
    value="R-40AF4",
    meaning="Ventral right-dorsal left oblique",
    scheme_designator="SRT"
)

VENTRODORSAL = CodedConcept(
    value="R-40AB0",
    meaning="Ventro-dorsal",
    scheme_designator="SRT"
)

ROSTRAL_20_DEGREE_DORSALCAUDOVENTRAL_OBLIQUE = CodedConcept(
    value="R-40AF3",
    meaning="Rostral 20 degree dorsal-caudoventral oblique",
    scheme_designator="SRT"
)

PALMAR_45_DEGREE_MEDIALDORSOLATERAL = CodedConcept(
    value="R-40AF6",
    meaning="Palmar 45 degree medial-dorsolateral",
    scheme_designator="SRT"
)

LEFT_VENTRALRIGHT_DORSAL_OBLIQUE = CodedConcept(
    value="R-40AF5",
    meaning="Left ventral-right dorsal oblique",
    scheme_designator="SRT"
)

ROSTROCAUDAL = CodedConcept(
    value="R-40AF0",
    meaning="Rostrocaudal",
    scheme_designator="SRT"
)

DORSOMEDIALPALMAROLATERAL = CodedConcept(
    value="R-40AF2",
    meaning="Dorsomedial-palmarolateral",
    scheme_designator="SRT"
)

VENTRAL_20_DEGREE_ROSTRALDORSOCAUDAL_OBLIQUE = CodedConcept(
    value="R-40AF1",
    meaning="Ventral 20 degree rostral-dorsocaudal oblique",
    scheme_designator="SRT"
)

DORSOVENTRAL = CodedConcept(
    value="R-40AAC",
    meaning="Dorso-ventral",
    scheme_designator="SRT"
)

PLANTAR_60_DEGREE_LATERALDORSOMEDIAL_OBLIQUE = CodedConcept(
    value="R-40AEF",
    meaning="Plantar 60 degree lateral-dorsomedial oblique",
    scheme_designator="SRT"
)

LATERAL_45_DEG_DORSAL_50_DEG_PROXIMALMEDIOPLANTARODISTAL_OBLIQ = CodedConcept(
    value="R-40AEC",
    meaning="Lateral 45 deg dorsal 50 deg proximal-medioplantarodistal obliq",
    scheme_designator="SRT"
)

LATEROMEDIAL = CodedConcept(
    value="R-10228",
    meaning="Lateromedial",
    scheme_designator="SRT"
)

RIGHT_45_DEGREE_DORSALLEFT_VENTRAL_OBLIQUE = CodedConcept(
    value="R-40AEB",
    meaning="Right 45 degree dorsal-left ventral oblique",
    scheme_designator="SRT"
)

PALMAROPROXIMALDORSODISTAL_OBLIQUE = CodedConcept(
    value="R-40AEE",
    meaning="Palmaroproximal-dorsodistal oblique",
    scheme_designator="SRT"
)

DORSOROSTRALVENTROCAUDAL_OBLIQUE = CodedConcept(
    value="R-40AEA",
    meaning="Dorsorostral-ventrocaudal oblique",
    scheme_designator="SRT"
)

DORSOPALMAR = CodedConcept(
    value="R-40AA9",
    meaning="Dorsopalmar",
    scheme_designator="SRT"
)

DORSOPLANTAR = CodedConcept(
    value="R-102C4",
    meaning="Dorsoplantar",
    scheme_designator="SRT"
)

LEFT_ROSTRALRIGHT_CAUDAL_OBLIQUE = CodedConcept(
    value="R-40AE6",
    meaning="Left rostral-right caudal oblique",
    scheme_designator="SRT"
)

PLANTAROLATERALDORSOMEDIAL_OBLIQUE = CodedConcept(
    value="R-40AE9",
    meaning="Plantarolateral-dorsomedial oblique",
    scheme_designator="SRT"
)

DORSOLATERALPALMAROMEDIAL_OBLIQUE = CodedConcept(
    value="R-40AE8",
    meaning="Dorsolateral-palmaromedial oblique",
    scheme_designator="SRT"
)

DORSAL_60_DEGREE_MEDIALPLANTAROLATERAL_OBLIQUE = CodedConcept(
    value="R-40AE3",
    meaning="Dorsal 60 degree medial-plantarolateral oblique",
    scheme_designator="SRT"
)

LEFT_DORSALRIGHT_VENTRAL_OBLIQUE = CodedConcept(
    value="R-40AE5",
    meaning="Left dorsal-right ventral oblique",
    scheme_designator="SRT"
)

DORSAL_45_DEGREE_LATERALPLANTAROMEDIAL_OBLIQUE = CodedConcept(
    value="R-40AE4",
    meaning="Dorsal 45 degree lateral-plantaromedial oblique",
    scheme_designator="SRT"
)

DORSAL_60_DEGREE_LATERALPALMAROMEDIAL_OBLIQUE = CodedConcept(
    value="R-40AE1",
    meaning="Dorsal 60 degree lateral-palmaromedial oblique",
    scheme_designator="SRT"
)

LEFT_CAUDALRIGHT_ROSTRAL_OBLIQUE = CodedConcept(
    value="R-40AE0",
    meaning="Left caudal-right rostral oblique",
    scheme_designator="SRT"
)

MEDIOLATERAL = CodedConcept(
    value="R-10224",
    meaning="Mediolateral",
    scheme_designator="SRT"
)

ROSTRODORSALCAUDOVENTRAL_OBLIQUE = CodedConcept(
    value="R-40ADF",
    meaning="Rostrodorsal-caudoventral oblique",
    scheme_designator="SRT"
)

LEFT_20_DEGREE_VENTRALRIGHT_DORSAL_OBLIQUE = CodedConcept(
    value="R-40ADE",
    meaning="Left 20 degree ventral-right dorsal oblique",
    scheme_designator="SRT"
)

LATERODORSOPROXIMALMEDIOPALMARODISTAL_OBLIQUE = CodedConcept(
    value="R-40ADB",
    meaning="Laterodorsoproximal-mediopalmarodistal oblique",
    scheme_designator="SRT"
)

RIGHT_CAUDALLEFT_ROSTRAL_OBLIQUE = CodedConcept(
    value="R-40ADA",
    meaning="Right caudal-left rostral oblique",
    scheme_designator="SRT"
)

LEFT_20_DEGREE_ROSTRALRIGHT_CAUDAL_OBLIQUE = CodedConcept(
    value="R-40ADD",
    meaning="Left 20 degree rostral-right caudal oblique",
    scheme_designator="SRT"
)

LATERODORSOPROXIMALMEDIOPLANTARODISTAL_OBLIQUE = CodedConcept(
    value="R-40ADC",
    meaning="Laterodorsoproximal-medioplantarodistal oblique",
    scheme_designator="SRT"
)

RIGHTLEFT_LATERAL = CodedConcept(
    value="R-10236",
    meaning="Right-left lateral",
    scheme_designator="SRT"
)

RIGHT_45_DEGREE_VENTRALLEFT_DORSAL_OBLIQUE = CodedConcept(
    value="R-40AD9",
    meaning="Right 45 degree ventral-left dorsal oblique",
    scheme_designator="SRT"
)

PLANTAROPROXIMALDORSODISTAL_OBLIQUE = CodedConcept(
    value="R-40AD6",
    meaning="Plantaroproximal-dorsodistal oblique",
    scheme_designator="SRT"
)

DORSAL_65_DEGREE_PROXIMALPLANTARODISTAL_OBLIQUE = CodedConcept(
    value="R-40AD5",
    meaning="Dorsal 65 degree proximal-plantarodistal oblique",
    scheme_designator="SRT"
)

RIGHT_20_DEGREE_DORSALLEFT_VENTRAL_OBLIQUE = CodedConcept(
    value="R-40AD8",
    meaning="Right 20 degree dorsal-left ventral oblique",
    scheme_designator="SRT"
)

PROXIMODISTAL = CodedConcept(
    value="R-40AD7",
    meaning="Proximo-distal",
    scheme_designator="SRT"
)

DORSAL_40_DEGREE_MEDIALPALMAROLATERAL_OBLIQUE = CodedConcept(
    value="R-40AD2",
    meaning="Dorsal 40 degree medial-palmarolateral oblique",
    scheme_designator="SRT"
)

RIGHT_20_DEGREE_VENTRALLEFT_DORSAL_OBLIQUE = CodedConcept(
    value="R-40AD1",
    meaning="Right 20 degree ventral-left dorsal oblique",
    scheme_designator="SRT"
)

DORSAL_45_DEGREE_MEDIALPALMAROLATERAL = CodedConcept(
    value="R-40AD4",
    meaning="Dorsal 45 degree medial-palmarolateral",
    scheme_designator="SRT"
)

DORSAL_40_DEGREE_MEDIALPLANTAROLATERAL_OBLIQUE = CodedConcept(
    value="R-40AD3",
    meaning="Dorsal 40 degree medial-plantarolateral oblique",
    scheme_designator="SRT"
)

DORSOMEDIALPLANTAROLATERAL_OBLIQUE = CodedConcept(
    value="R-40AD0",
    meaning="Dorsomedial-plantarolateral oblique",
    scheme_designator="SRT"
)

DORSAL_65_DEGREE_PROXIMALPALMARODISTAL_OBLIQUE = CodedConcept(
    value="R-40ACE",
    meaning="Dorsal 65 degree proximal-palmarodistal oblique",
    scheme_designator="SRT"
)

DORSAL_35_DEGREE_MEDIALPLANTAROLATERAL_OBLIQUE = CodedConcept(
    value="R-40ACD",
    meaning="Dorsal 35 degree medial-plantarolateral oblique",
    scheme_designator="SRT"
)

DORSOLATERALPLANTAROMEDIAL_OBLIQUE = CodedConcept(
    value="R-40ACF",
    meaning="Dorsolateral-plantaromedial oblique",
    scheme_designator="SRT"
)

LEFTRIGHT_LATERAL = CodedConcept(
    value="R-10232",
    meaning="Left-right lateral",
    scheme_designator="SRT"
)

