"""CID 7193 PhysicalObjectSegmentationPropertyTypes
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


OTHER_MARKER = CodedConcept(
    value="111175",
    meaning="Other Marker",
    scheme_designator="DCM"
)

MOLD = CodedConcept(
    value="130113",
    meaning="Mold",
    scheme_designator="DCM"
)

BRACHYTHERAPY_CHANNEL_SHIELD = CodedConcept(
    value="130079",
    meaning="Brachytherapy channel shield",
    scheme_designator="DCM"
)

HEAD_AND_NECK_MASK = CodedConcept(
    value="130112",
    meaning="Head and Neck Mask",
    scheme_designator="DCM"
)

BRACHYTHERAPY_SOURCE_APPLICATOR = CodedConcept(
    value="130078",
    meaning="Brachytherapy source applicator",
    scheme_designator="DCM"
)

HEAD_MASK = CodedConcept(
    value="130111",
    meaning="Head Mask",
    scheme_designator="DCM"
)

HEADFRAME = CodedConcept(
    value="130110",
    meaning="Headframe",
    scheme_designator="DCM"
)

BODY_FRAME = CodedConcept(
    value="130117",
    meaning="Body Frame",
    scheme_designator="DCM"
)

BREAST_BOARD = CodedConcept(
    value="130116",
    meaning="Breast Board",
    scheme_designator="DCM"
)

CAST = CodedConcept(
    value="130114",
    meaning="Cast",
    scheme_designator="DCM"
)

WHOLE_BODY_POD = CodedConcept(
    value="130119",
    meaning="Whole Body Pod",
    scheme_designator="DCM"
)

VACUUM_MOLD = CodedConcept(
    value="130118",
    meaning="Vacuum Mold",
    scheme_designator="DCM"
)

PORTACATH = CodedConcept(
    value="112172",
    meaning="Portacath",
    scheme_designator="DCM"
)

CHEST_TUBE = CodedConcept(
    value="112173",
    meaning="Chest tube",
    scheme_designator="DCM"
)

CENTRAL_LINE = CodedConcept(
    value="112174",
    meaning="Central line",
    scheme_designator="DCM"
)

KIDNEY_STENT = CodedConcept(
    value="112175",
    meaning="Kidney stent",
    scheme_designator="DCM"
)

PANCREATIC_STENT = CodedConcept(
    value="112176",
    meaning="Pancreatic stent",
    scheme_designator="DCM"
)

NIPPLE_RING = CodedConcept(
    value="112177",
    meaning="Nipple ring",
    scheme_designator="DCM"
)

COIN = CodedConcept(
    value="112178",
    meaning="Coin",
    scheme_designator="DCM"
)

BRACHYTHERAPY_CHANNEL = CodedConcept(
    value="130080",
    meaning="Brachytherapy channel",
    scheme_designator="DCM"
)

RECTAL_BALLOON = CodedConcept(
    value="130120",
    meaning="Rectal Balloon",
    scheme_designator="DCM"
)

FIDUCIAL_MARK = CodedConcept(
    value="112171",
    meaning="Fiducial mark",
    scheme_designator="DCM"
)

VAGINAL_CYLINDER = CodedConcept(
    value="130121",
    meaning="Vaginal Cylinder",
    scheme_designator="DCM"
)

ION_CHAMBER_ARRAY = CodedConcept(
    value="128703",
    meaning="Ion Chamber Array",
    scheme_designator="DCM"
)

DIODE_ARRAY = CodedConcept(
    value="128702",
    meaning="Diode Array",
    scheme_designator="DCM"
)

LIQUID_ION_CHAMBER = CodedConcept(
    value="128705",
    meaning="Liquid Ion Chamber",
    scheme_designator="DCM"
)

DIODE = CodedConcept(
    value="128704",
    meaning="Diode",
    scheme_designator="DCM"
)

ION_CHAMBER = CodedConcept(
    value="128707",
    meaning="Ion Chamber",
    scheme_designator="DCM"
)

OSLD = CodedConcept(
    value="128706",
    meaning="OSLD",
    scheme_designator="DCM"
)

DIAMOND_DETECTOR = CodedConcept(
    value="128708",
    meaning="Diamond Detector",
    scheme_designator="DCM"
)

SPHERE = CodedConcept(
    value="122485",
    meaning="Sphere",
    scheme_designator="DCM"
)

JEJUNOSTOMY_TUBE = CodedConcept(
    value="A-26434",
    meaning="Jejunostomy tube",
    scheme_designator="SRT"
)

THERMOLUMINESCENT_RADIATION_DOSIMETER = CodedConcept(
    value="R-FCE69",
    meaning="Thermoluminescent radiation dosimeter",
    scheme_designator="SRT"
)

STENT = CodedConcept(
    value="A-25500",
    meaning="Stent",
    scheme_designator="SRT"
)

TRACHEOTOMY = CodedConcept(
    value="P1-26100",
    meaning="Tracheotomy",
    scheme_designator="SRT"
)

OPAQUE_MARKER = CodedConcept(
    value="A-00D7B",
    meaning="Opaque Marker",
    scheme_designator="SRT"
)

PERCUTANEOUS_TRANSLUMINAL_ANGIOPLASTY_BALLOON = CodedConcept(
    value="A-26912",
    meaning="Percutaneous transluminal angioplasty balloon",
    scheme_designator="SRT"
)

PROSTHESIS = CodedConcept(
    value="A-04000",
    meaning="Prosthesis",
    scheme_designator="SRT"
)

DENTAL_PROSTHESIS = CodedConcept(
    value="A-04200",
    meaning="Dental Prosthesis",
    scheme_designator="SRT"
)

FEEDING_TUBE = CodedConcept(
    value="A-26430",
    meaning="Feeding tube",
    scheme_designator="SRT"
)

DETACHABLE_BALLOON = CodedConcept(
    value="A-27322",
    meaning="Detachable balloon",
    scheme_designator="SRT"
)

J_WIRE = CodedConcept(
    value="A-1016B",
    meaning="J Wire",
    scheme_designator="SRT"
)

JEWELRY = CodedConcept(
    value="A-61000",
    meaning="Jewelry",
    scheme_designator="SRT"
)

CARDIAC_PACEMAKER = CodedConcept(
    value="A-11101",
    meaning="Cardiac Pacemaker",
    scheme_designator="SRT"
)

STAPLE = CodedConcept(
    value="A-13600",
    meaning="Staple",
    scheme_designator="SRT"
)

VENA_CAVA_FILTER = CodedConcept(
    value="A-14611",
    meaning="Vena cava filter",
    scheme_designator="SRT"
)

EMBOLIZATION_PARTICULATE = CodedConcept(
    value="A-25616",
    meaning="Embolization particulate",
    scheme_designator="SRT"
)

CLOTHING = CodedConcept(
    value="A-00916",
    meaning="Clothing",
    scheme_designator="SRT"
)

BONE_SCREW = CodedConcept(
    value="A-12030",
    meaning="Bone Screw",
    scheme_designator="SRT"
)

INLAY_DENTAL_RESTORATION = CodedConcept(
    value="A-04036",
    meaning="Inlay Dental Restoration",
    scheme_designator="SRT"
)

GUIDING_CATHETER = CodedConcept(
    value="A-26802",
    meaning="Guiding catheter",
    scheme_designator="SRT"
)

CATHETER = CodedConcept(
    value="A-26800",
    meaning="Catheter",
    scheme_designator="SRT"
)

HEART_VALVE_PROSTHESIS = CodedConcept(
    value="A-04110",
    meaning="Heart valve prosthesis",
    scheme_designator="SRT"
)

CARDIAC_PACEMAKER_LEAD = CodedConcept(
    value="A-040CB",
    meaning="Cardiac pacemaker lead",
    scheme_designator="SRT"
)

DIGITAL_IMAGER = CodedConcept(
    value="R-FD5EB",
    meaning="Digital imager",
    scheme_designator="SRT"
)

RADIOACTIVE_IMPLANT = CodedConcept(
    value="A-04034",
    meaning="Radioactive implant",
    scheme_designator="SRT"
)

ENDOTRACHEAL_TUBE = CodedConcept(
    value="A-25350",
    meaning="Endotracheal tube",
    scheme_designator="SRT"
)

MEASURING_RULER = CodedConcept(
    value="A-10141",
    meaning="Measuring ruler",
    scheme_designator="SRT"
)

LASER = CodedConcept(
    value="A-81080",
    meaning="Laser",
    scheme_designator="SRT"
)

BB_SHOT_LEAD_PELLET_ = CodedConcept(
    value="A-32475",
    meaning="BB shot (Lead Pellet)",
    scheme_designator="SRT"
)

BULLET = CodedConcept(
    value="A-32110",
    meaning="Bullet",
    scheme_designator="SRT"
)

URETERIC_STENT = CodedConcept(
    value="A-11C08",
    meaning="Ureteric stent",
    scheme_designator="SRT"
)

ATHERECTOMY_DEVICE = CodedConcept(
    value="A-25600",
    meaning="Atherectomy device",
    scheme_designator="SRT"
)

CHAIR = CodedConcept(
    value="R-FE814",
    meaning="Chair",
    scheme_designator="SRT"
)

CERVICAL_COLLAR = CodedConcept(
    value="A-12210",
    meaning="Cervical collar",
    scheme_designator="SRT"
)

COLLIMATOR = CodedConcept(
    value="A-0110F",
    meaning="Collimator",
    scheme_designator="SRT"
)

HEADREST = CodedConcept(
    value="R-FEEC3",
    meaning="Headrest",
    scheme_designator="SRT"
)

ID_PLATE = CodedConcept(
    value="A-16016",
    meaning="ID Plate",
    scheme_designator="SRT"
)

SUTURE = CodedConcept(
    value="A-13500",
    meaning="Suture",
    scheme_designator="SRT"
)

LEFT_VENTRICULAR_ASSIST_DEVICE = CodedConcept(
    value="A-11FCD",
    meaning="Left ventricular assist device",
    scheme_designator="SRT"
)

NEEDLE = CodedConcept(
    value="A-30360",
    meaning="Needle",
    scheme_designator="SRT"
)

MOSFET_RADIATION_THERAPY_DOSIMETRY_SYSTEM_DOSIMETER = CodedConcept(
    value="R-FCC16",
    meaning="MOSFET radiation therapy dosimetry system dosimeter",
    scheme_designator="SRT"
)

GLUE = CodedConcept(
    value="C-20005",
    meaning="Glue",
    scheme_designator="SRT"
)

ROTATIONAL_ATHERECTOMY_DEVICE = CodedConcept(
    value="A-25610",
    meaning="Rotational atherectomy device",
    scheme_designator="SRT"
)

EMBOLIZATION_COIL = CodedConcept(
    value="A-25612",
    meaning="Embolization coil",
    scheme_designator="SRT"
)

BITE_BLOCK = CodedConcept(
    value="A-01105",
    meaning="Bite block",
    scheme_designator="SRT"
)

EMBOLIZATION_BALL = CodedConcept(
    value="A-25614",
    meaning="Embolization ball",
    scheme_designator="SRT"
)

DEFIBRILLATOR = CodedConcept(
    value="A-11206",
    meaning="Defibrillator",
    scheme_designator="SRT"
)

IMPLANT = CodedConcept(
    value="A-04010",
    meaning="Implant",
    scheme_designator="SRT"
)

BONE_PIN = CodedConcept(
    value="A-12024",
    meaning="Bone Pin",
    scheme_designator="SRT"
)

COMPRESSION_PADDLE = CodedConcept(
    value="A-10042",
    meaning="Compression paddle",
    scheme_designator="SRT"
)

FOREIGN_BODY = CodedConcept(
    value="M-30400",
    meaning="Foreign body",
    scheme_designator="SRT"
)

TABLE = CodedConcept(
    value="A-17350",
    meaning="Table",
    scheme_designator="SRT"
)

CLIP = CodedConcept(
    value="A-12062",
    meaning="Clip",
    scheme_designator="SRT"
)

