"""CID 6105 AbnormalLucencyFindingorFeature
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


HALO_SIGN = CodedConcept(
    value="112073",
    meaning="Halo sign",
    scheme_designator="DCM"
)

AIR_BRONCHIOLOGRAM = CodedConcept(
    value="112070",
    meaning="Air bronchiologram",
    scheme_designator="DCM"
)

AIR_BRONCHOGRAM = CodedConcept(
    value="112071",
    meaning="Air bronchogram",
    scheme_designator="DCM"
)

AIR_CRESCENT = CodedConcept(
    value="112072",
    meaning="Air crescent",
    scheme_designator="DCM"
)

AIRTRAPPING = CodedConcept(
    value="F-20240",
    meaning="Air-trapping",
    scheme_designator="SRT"
)

PNEUMOMEDIASTINUM = CodedConcept(
    value="D2-81180",
    meaning="Pneumomediastinum",
    scheme_designator="SRT"
)

PNEUMOTHORAX = CodedConcept(
    value="D2-80300",
    meaning="Pneumothorax",
    scheme_designator="SRT"
)

