"""CID 3746 PercutaneousEntrySite
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


VIA_FEMORAL_VEIN = CodedConcept(
    value="G-D071",
    meaning="Via femoral vein",
    scheme_designator="SRT"
)

VIA_RADIAL_ARTERY = CodedConcept(
    value="G-D1E4",
    meaning="Via radial artery",
    scheme_designator="SRT"
)

VIA_ARTERY = CodedConcept(
    value="G-D054",
    meaning="Via artery",
    scheme_designator="SRT"
)

VIA_VEIN = CodedConcept(
    value="G-D052",
    meaning="Via vein",
    scheme_designator="SRT"
)

VIA_ARM_VEIN = CodedConcept(
    value="G-D0C6",
    meaning="Via arm vein",
    scheme_designator="SRT"
)

VIA_FEMORAL_ARTERY = CodedConcept(
    value="G-D067",
    meaning="Via femoral artery",
    scheme_designator="SRT"
)

VIA_BRACHIAL_ARTERY = CodedConcept(
    value="G-D05F",
    meaning="Via brachial artery",
    scheme_designator="SRT"
)

