"""CID 3200 StressTestProcedure
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


EXERCISE_STRESS_TEST = CodedConcept(
    value="P0-006E4",
    meaning="Exercise stress test",
    scheme_designator="SRT"
)

PHARMACOLOGIC_STRESS_TEST = CodedConcept(
    value="P2-31107",
    meaning="Pharmacologic stress test",
    scheme_designator="SRT"
)

PACED_STRESS_TEST = CodedConcept(
    value="P2-3110B",
    meaning="Paced stress test",
    scheme_designator="SRT"
)

PHARMACOLOGIC_AND_EXERCISE_STRESS_TEST = CodedConcept(
    value="P2-31011",
    meaning="Pharmacologic and exercise stress test",
    scheme_designator="SRT"
)

