"""CID 3405 ProcedureActionValues
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


ARTERIAL_CONDUIT_ANGIOGRAPHY = CodedConcept(
    value="122058",
    meaning="Arterial conduit angiography",
    scheme_designator="DCM"
)

VASCULAR_INTERVENTION = CodedConcept(
    value="122056",
    meaning="Vascular Intervention",
    scheme_designator="DCM"
)

MYOCARDIAL_BIOPSY = CodedConcept(
    value="122057",
    meaning="Myocardial biopsy",
    scheme_designator="DCM"
)

AORTIC_INTERVENTION = CodedConcept(
    value="122054",
    meaning="Aortic Intervention",
    scheme_designator="DCM"
)

SEPTAL_DEFECT_INTERVENTION = CodedConcept(
    value="122055",
    meaning="Septal Defect Intervention",
    scheme_designator="DCM"
)

VALVULAR_INTERVENTION = CodedConcept(
    value="122053",
    meaning="Valvular Intervention",
    scheme_designator="DCM"
)

TRANSSEPTAL_CATHETERIZATION = CodedConcept(
    value="P1-31612",
    meaning="Transseptal catheterization",
    scheme_designator="SRT"
)

TRANSESOPHAGEAL_ECHOCARDIOGRAPHY = CodedConcept(
    value="P5-B3002",
    meaning="Transesophageal echocardiography",
    scheme_designator="SRT"
)

AORTOGRAPHY = CodedConcept(
    value="P5-32130",
    meaning="Aortography",
    scheme_designator="SRT"
)

BYPASS_GRAFT_ANGIOGRAPHY = CodedConcept(
    value="P5-30107",
    meaning="Bypass graft angiography",
    scheme_designator="SRT"
)

DRUG_INFUSION_CHALLENGE = CodedConcept(
    value="P2-71317",
    meaning="Drug Infusion Challenge",
    scheme_designator="SRT"
)

CORONARY_ARTERIOGRAPHY = CodedConcept(
    value="P5-30100",
    meaning="Coronary Arteriography",
    scheme_designator="SRT"
)

RESTING_STATE = CodedConcept(
    value="F-01604",
    meaning="Resting State",
    scheme_designator="SRT"
)

EXERCISE_CHALLENGE = CodedConcept(
    value="P2-71310",
    meaning="Exercise challenge",
    scheme_designator="SRT"
)

SELECTIVE_EMBOLIZATION_OF_ARTERY = CodedConcept(
    value="P1-30530",
    meaning="Selective embolization of artery",
    scheme_designator="SRT"
)

CARDIAC_CATHETERIZATION_TEST_CHALLENGE_PHASE = CodedConcept(
    value="R-002E4",
    meaning="Cardiac catheterization test/challenge phase",
    scheme_designator="SRT"
)

INTRACARDIAC_ECHOCARDIOGRAPHY = CodedConcept(
    value="P5-B3006",
    meaning="Intracardiac echocardiography",
    scheme_designator="SRT"
)

TRANSTHORACIC_ECHOCARDIOGRAPHY = CodedConcept(
    value="P5-B3012",
    meaning="Transthoracic echocardiography",
    scheme_designator="SRT"
)

CARDIAC_CATHETERIZATION_POST_CONTRAST_PHASE = CodedConcept(
    value="G-729B",
    meaning="Cardiac catheterization post contrast phase",
    scheme_designator="SRT"
)

ATHERECTOMY_BY_LASER = CodedConcept(
    value="P1-30352",
    meaning="Atherectomy by laser",
    scheme_designator="SRT"
)

CATHETERIZATION_OF_RIGHT_HEART = CodedConcept(
    value="P1-31602",
    meaning="Catheterization of right heart",
    scheme_designator="SRT"
)

ATHERECTOMY_BY_ROTARY_CUTTER = CodedConcept(
    value="P1-30351",
    meaning="Atherectomy by rotary cutter",
    scheme_designator="SRT"
)

ATHERECTOMY = CodedConcept(
    value="P1-30350",
    meaning="Atherectomy",
    scheme_designator="SRT"
)

LEFT_VENTRICULOGRAPHY = CodedConcept(
    value="P5-30041",
    meaning="Left Ventriculography",
    scheme_designator="SRT"
)

CATHETERIZATION_OF_LEFT_HEART = CodedConcept(
    value="P1-31604",
    meaning="Catheterization of left heart",
    scheme_designator="SRT"
)

TRANSCATHETER_DEPLOYMENT_OF_DETACHABLE_BALLOON = CodedConcept(
    value="P5-39015",
    meaning="Transcatheter deployment of detachable balloon",
    scheme_designator="SRT"
)

CARDIAC_CATHETERIZATION_POSTINTERVENTION_PHASE = CodedConcept(
    value="G-7298",
    meaning="Cardiac catheterization post-intervention phase",
    scheme_designator="SRT"
)

CARDIAC_CATHETERIZATION_THERAPY_PHASE = CodedConcept(
    value="G-7297",
    meaning="Cardiac catheterization therapy phase",
    scheme_designator="SRT"
)

TRANSCATHETER_THERAPY_FOR_EMBOLIZATION = CodedConcept(
    value="P5-39010",
    meaning="Transcatheter therapy for embolization",
    scheme_designator="SRT"
)

RIGHT_VENTRICULOGRAPHY = CodedConcept(
    value="P5-3003F",
    meaning="Right Ventriculography",
    scheme_designator="SRT"
)

CARDIAC_CATHETERIZATION_BAILOUT_PHASE = CodedConcept(
    value="G-7299",
    meaning="Cardiac catheterization bailout phase",
    scheme_designator="SRT"
)

STENT_PLACEMENT = CodedConcept(
    value="P1-05550",
    meaning="Stent placement",
    scheme_designator="SRT"
)

PERCUTANEOUS_INSERTION_OF_INTRAVASCULAR_FILTER = CodedConcept(
    value="P5-39191",
    meaning="Percutaneous insertion of intravascular filter",
    scheme_designator="SRT"
)

CARDIAC_CATHETERIZATION_IMAGE_ACQUISITION_PHASE = CodedConcept(
    value="G-7294",
    meaning="Cardiac catheterization image acquisition phase",
    scheme_designator="SRT"
)

CARDIAC_CATHETERIZATION_BASELINE_PHASE = CodedConcept(
    value="G-7293",
    meaning="Cardiac catheterization baseline phase",
    scheme_designator="SRT"
)

PERCUTANEOUS_RETRIEVAL_OF_INTRAVASCULAR_FOREIGN_BODY = CodedConcept(
    value="P5-39050",
    meaning="Percutaneous retrieval of intravascular foreign body",
    scheme_designator="SRT"
)

INTRAVASCULAR_ULTRASOUND = CodedConcept(
    value="P5-B001D",
    meaning="Intravascular ultrasound",
    scheme_designator="SRT"
)

CARDIAC_CATHETERIZATION_PREINTERVENTION_PHASE = CodedConcept(
    value="G-7296",
    meaning="Cardiac catheterization pre-intervention phase",
    scheme_designator="SRT"
)

CARDIAC_CATHETERIZATION_INTERVENTION_PHASE = CodedConcept(
    value="G-7295",
    meaning="Cardiac catheterization intervention phase",
    scheme_designator="SRT"
)

CATHETERIZATION_OF_BOTH_LEFT_AND_RIGHT_HEART_WITH_GRAFT = CodedConcept(
    value="P1-3160A",
    meaning="Catheterization of both left and right heart with graft",
    scheme_designator="SRT"
)

CATHETERIZATION_OF_BOTH_LEFT_AND_RIGHT_HEART_WITHOUT_GRAFT = CodedConcept(
    value="P1-3160B",
    meaning="Catheterization of both left and right heart without graft",
    scheme_designator="SRT"
)

CARDIAC_VENTRICULOGRAPHY = CodedConcept(
    value="P5-3003A",
    meaning="Cardiac ventriculography",
    scheme_designator="SRT"
)

EPICARDIAL_ECHOCARDIOGRAPHY = CodedConcept(
    value="P0-05F95",
    meaning="Epicardial echocardiography",
    scheme_designator="SRT"
)

ANGIOGRAPHY = CodedConcept(
    value="P5-009A0",
    meaning="Angiography",
    scheme_designator="SRT"
)

PERCUTANEOUS_TRANSLUMINAL_BALLOON_ANGIOPLASTY = CodedConcept(
    value="P5-31500",
    meaning="Percutaneous transluminal balloon angioplasty",
    scheme_designator="SRT"
)

