"""CID 3110 NuclearCardiologyProtocols
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


STRESS_TECHNETIUM_REST_TECHNETIUM_1_DAY_PROCEDURE = CodedConcept(
    value="122784",
    meaning="Stress technetium/rest technetium 1 day procedure",
    scheme_designator="DCM"
)

NM_MYOCARDIAL_VIABILITY_PROCEDURE = CodedConcept(
    value="122785",
    meaning="NM Myocardial Viability procedure",
    scheme_designator="DCM"
)

REST_TECHNETIUM_STRESS_TECHNETIUM_1_DAY_PROCEDURE = CodedConcept(
    value="122782",
    meaning="Rest technetium/stress technetium 1 day procedure",
    scheme_designator="DCM"
)

REST_TECHNETIUM_STRESS_TECHNETIUM_2_DAY_PROCEDURE = CodedConcept(
    value="122783",
    meaning="Rest technetium/stress technetium 2 day procedure",
    scheme_designator="DCM"
)

REST_THALLIUM_STRESS_TECHNETIUM_PROCEDURE = CodedConcept(
    value="122781",
    meaning="Rest thallium/stress technetium procedure",
    scheme_designator="DCM"
)

STRESS_THALLIUM_PROCEDURE = CodedConcept(
    value="P5-D300B",
    meaning="Stress thallium procedure",
    scheme_designator="SRT"
)

