"""CID 9512 TomotherapeuticRadiotherapyProcedureTechniques
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


TOPOGRAPHIC_BEAM = CodedConcept(
    value="130109",
    meaning="Topographic Beam",
    scheme_designator="DCM"
)

HELICAL_BEAM = CodedConcept(
    value="130108",
    meaning="Helical Beam",
    scheme_designator="DCM"
)

