"""CID 69 ImagingAgentAdministrationConsumables
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


TUBE_DEVICE_PHYSICAL_OBJECT_ = CodedConcept(
    value="A-26400",
    meaning="Tube, device (physical object)",
    scheme_designator="SRT"
)

BOTTLE = CodedConcept(
    value="A-27500",
    meaning="Bottle",
    scheme_designator="SRT"
)

CONTRAST_MEDIUM_INJECTION_SYSTEM_MANIFOLD_KIT = CodedConcept(
    value="R-FDF5C",
    meaning="Contrast medium injection system manifold kit",
    scheme_designator="SRT"
)

CATHETER = CodedConcept(
    value="A-26800",
    meaning="Catheter",
    scheme_designator="SRT"
)

NEEDLE = CodedConcept(
    value="A-30360",
    meaning="Needle",
    scheme_designator="SRT"
)

SYRINGE = CodedConcept(
    value="A-10150",
    meaning="Syringe",
    scheme_designator="SRT"
)

