"""CID 7165 AbstractSegmentationTypes
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


REGISTRATION_INPUT = CodedConcept(
    value="125041",
    meaning="Registration Input",
    scheme_designator="DCM"
)

BACKGROUND = CodedConcept(
    value="125040",
    meaning="Background",
    scheme_designator="DCM"
)

SINGLE_SUBJECT_EXTRACTED_FROM_GROUP = CodedConcept(
    value="113132",
    meaning="Single subject extracted from group",
    scheme_designator="DCM"
)

REFERENCE_REGION = CodedConcept(
    value="C94970",
    meaning="Reference Region",
    scheme_designator="NCIt"
)

TISSUE = CodedConcept(
    value="T-D0050",
    meaning="Tissue",
    scheme_designator="SRT"
)

WASTE_MATERIAL = CodedConcept(
    value="F-61779",
    meaning="Waste Material",
    scheme_designator="SRT"
)

