"""CID 9522 MultiSourceRadiotherapyProcedureTechniques
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


MULTIPLE_FIXED_SOURCES = CodedConcept(
    value="130138",
    meaning="Multiple Fixed Sources",
    scheme_designator="DCM"
)

