"""CID 7451 FamilyMember
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


AUNT = CodedConcept(
    value="S-101A1",
    meaning="Aunt",
    scheme_designator="SRT"
)

UNCLE = CodedConcept(
    value="S-101A2",
    meaning="Uncle",
    scheme_designator="SRT"
)

NATURAL_GRANDMOTHER = CodedConcept(
    value="S-10115",
    meaning="Natural grand-mother",
    scheme_designator="SRT"
)

NATURAL_GRANDFATHER = CodedConcept(
    value="S-10116",
    meaning="Natural grand-father",
    scheme_designator="SRT"
)

NATURAL_SISTER = CodedConcept(
    value="S-10151",
    meaning="Natural sister",
    scheme_designator="SRT"
)

NATURAL_BROTHER = CodedConcept(
    value="S-10161",
    meaning="Natural brother",
    scheme_designator="SRT"
)

NATURAL_FATHER = CodedConcept(
    value="S-10131",
    meaning="Natural father",
    scheme_designator="SRT"
)

HALFBROTHER = CodedConcept(
    value="S-10164",
    meaning="Half-brother",
    scheme_designator="SRT"
)

MALE_FIRST_COUSIN = CodedConcept(
    value="S-101AA",
    meaning="Male first cousin",
    scheme_designator="SRT"
)

NATURAL_MOTHER = CodedConcept(
    value="S-10121",
    meaning="Natural mother",
    scheme_designator="SRT"
)

HALFSISTER = CodedConcept(
    value="S-10154",
    meaning="Half-sister",
    scheme_designator="SRT"
)

NATURAL_SON = CodedConcept(
    value="S-10191",
    meaning="Natural son",
    scheme_designator="SRT"
)

FEMALE_FIRST_COUSIN = CodedConcept(
    value="S-101A9",
    meaning="Female first cousin",
    scheme_designator="SRT"
)

NATURAL_DAUGHTER = CodedConcept(
    value="S-10181",
    meaning="Natural daughter",
    scheme_designator="SRT"
)

