"""CID 7222 ParametricMapDerivationImagePurposeofReference
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


SOURCE_IMAGE_FOR_IMAGE_PROCESSING_OPERATION = CodedConcept(
    value="121322",
    meaning="Source Image for Image Processing Operation",
    scheme_designator="DCM"
)

