"""CID 3760 HypertensionTherapy
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


CALCIUM_CHANNEL_BLOCKER = CodedConcept(
    value="C-80160",
    meaning="Calcium channel blocker",
    scheme_designator="SRT"
)

ACE_INHIBITOR = CodedConcept(
    value="C-80150",
    meaning="ACE inhibitor",
    scheme_designator="SRT"
)

DIURETIC = CodedConcept(
    value="C-72000",
    meaning="Diuretic",
    scheme_designator="SRT"
)

NITRATE_VASODILATOR = CodedConcept(
    value="C-81520",
    meaning="Nitrate vasodilator",
    scheme_designator="SRT"
)

ANGIOTENSIN_II_RECEPTOR_ANTAGONIST = CodedConcept(
    value="C-81300",
    meaning="Angiotensin II receptor antagonist",
    scheme_designator="SRT"
)

BETA_BLOCKER = CodedConcept(
    value="C-80135",
    meaning="Beta blocker",
    scheme_designator="SRT"
)

