"""CID 6035 CompositeFeatureRelations
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


TARGET_CONTENT_ITEMS_ARE_RELATED_TEMPORALLY = CodedConcept(
    value="111153",
    meaning="Target content items are related temporally",
    scheme_designator="DCM"
)

TARGET_CONTENT_ITEMS_ARE_RELATED_SPATIALLY = CodedConcept(
    value="111154",
    meaning="Target content items are related spatially",
    scheme_designator="DCM"
)

TARGET_CONTENT_ITEMS_ARE_RELATED_CONTRALATERALLY = CodedConcept(
    value="111155",
    meaning="Target content items are related contra-laterally",
    scheme_designator="DCM"
)

