"""CID 9303 InterpretationRequestDiscontinuationReasons
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


RESOURCE_PREEMPTED = CodedConcept(
    value="110526",
    meaning="Resource pre-empted",
    scheme_designator="DCM"
)

PATIENT_DIED = CodedConcept(
    value="110504",
    meaning="Patient died",
    scheme_designator="DCM"
)

INCORRECT_PROCEDURE_ORDERED = CodedConcept(
    value="110502",
    meaning="Incorrect procedure ordered",
    scheme_designator="DCM"
)

DISCONTINUED_FOR_UNSPECIFIED_REASON = CodedConcept(
    value="110513",
    meaning="Discontinued for unspecified reason",
    scheme_designator="DCM"
)

OBJECT_SET_INCOMPLETE = CodedConcept(
    value="110523",
    meaning="Object Set incomplete",
    scheme_designator="DCM"
)

DOCTOR_CANCELED_PROCEDURE = CodedConcept(
    value="110500",
    meaning="Doctor canceled procedure",
    scheme_designator="DCM"
)

DUPLICATE_ORDER = CodedConcept(
    value="110510",
    meaning="Duplicate order",
    scheme_designator="DCM"
)

INTERPRETATION_REQUIRES_SPECIALIST_EXPERTISE = CodedConcept(
    value="110532",
    meaning="Interpretation requires specialist expertise",
    scheme_designator="DCM"
)

INSUFFICIENT_QUALITY_FOR_INTERPRETATION = CodedConcept(
    value="110531",
    meaning="Insufficient quality for interpretation",
    scheme_designator="DCM"
)

WORKITEM_ASSIGNMENT_REJECTED_BY_ASSIGNED_RESOURCE = CodedConcept(
    value="110530",
    meaning="Workitem assignment rejected by assigned resource",
    scheme_designator="DCM"
)

CHANGE_OF_PROCEDURE_FOR_CORRECT_CHARGING = CodedConcept(
    value="110509",
    meaning="Change of procedure for correct charging",
    scheme_designator="DCM"
)

