"""CID 10015 CTDoseReferenceAuthorities
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


ICRP_PUB_60 = CodedConcept(
    value="113808",
    meaning="ICRP Pub 60",
    scheme_designator="DCM"
)

ICRP_PUB_103 = CodedConcept(
    value="113841",
    meaning="ICRP Pub 103",
    scheme_designator="DCM"
)

