"""CID 6072 BreastImplantFindings
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


DISTORTED_IMPLANT = CodedConcept(
    value="111506",
    meaning="Distorted implant",
    scheme_designator="DCM"
)

SILICONELADEN_LYMPH_NODES = CodedConcept(
    value="111507",
    meaning="Silicone-laden lymph nodes",
    scheme_designator="DCM"
)

FREE_SILICONE = CodedConcept(
    value="111508",
    meaning="Free silicone",
    scheme_designator="DCM"
)

HERNIATED_IMPLANT = CodedConcept(
    value="111509",
    meaning="Herniated implant",
    scheme_designator="DCM"
)

EXPLANTATION = CodedConcept(
    value="111510",
    meaning="Explantation",
    scheme_designator="DCM"
)

NORMAL_IMPLANTS = CodedConcept(
    value="111503",
    meaning="Normal implants",
    scheme_designator="DCM"
)

ASYMMETRIC_IMPLANTS = CodedConcept(
    value="111504",
    meaning="Asymmetric implants",
    scheme_designator="DCM"
)

CALCIFIED_IMPLANT = CodedConcept(
    value="111505",
    meaning="Calcified implant",
    scheme_designator="DCM"
)

RUPTURE_OF_BREAST_IMPLANT = CodedConcept(
    value="DD-66544",
    meaning="Rupture of breast implant",
    scheme_designator="SRT"
)

