"""CID 7262 DiffusionTractographyAlgorithmFamilies
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


DETERMINISTIC = CodedConcept(
    value="113211",
    meaning="Deterministic",
    scheme_designator="DCM"
)

PROBABILISTIC = CodedConcept(
    value="113212",
    meaning="Probabilistic",
    scheme_designator="DCM"
)

GLOBAL = CodedConcept(
    value="113213",
    meaning="Global",
    scheme_designator="DCM"
)

FACT = CodedConcept(
    value="113214",
    meaning="FACT",
    scheme_designator="DCM"
)

STREAMLINE = CodedConcept(
    value="113215",
    meaning="Streamline",
    scheme_designator="DCM"
)

TEND = CodedConcept(
    value="113216",
    meaning="TEND",
    scheme_designator="DCM"
)

BOOTSTRAP = CodedConcept(
    value="113217",
    meaning="Bootstrap",
    scheme_designator="DCM"
)

EULER = CodedConcept(
    value="113218",
    meaning="Euler",
    scheme_designator="DCM"
)

RUNGEKUTTA = CodedConcept(
    value="113219",
    meaning="Runge-Kutta",
    scheme_designator="DCM"
)

