"""CID 12286 CardiacUltrasoundInterventricularSeptumFindingSites
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


VENTRICULAR_SEPTAL_DEFECT = CodedConcept(
    value="D4-31150",
    meaning="Ventricular Septal Defect",
    scheme_designator="SRT"
)

BULBOVENTRICULAR_FORAMEN = CodedConcept(
    value="M-20102",
    meaning="Bulboventricular Foramen",
    scheme_designator="SRT"
)

INTERVENTRICULAR_SEPTUM = CodedConcept(
    value="T-32410",
    meaning="Interventricular Septum",
    scheme_designator="SRT"
)

