"""CID 6146 TimePointTypes
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


POSTTREATMENT = CodedConcept(
    value="126074",
    meaning="Posttreatment",
    scheme_designator="DCM"
)

ELIGIBILITY = CodedConcept(
    value="126075",
    meaning="Eligibility",
    scheme_designator="DCM"
)

UNSCHEDULED = CodedConcept(
    value="C1699701",
    meaning="Unscheduled",
    scheme_designator="UMLS"
)

BASELINE = CodedConcept(
    value="C1442488",
    meaning="Baseline",
    scheme_designator="UMLS"
)

PRETREATMENT = CodedConcept(
    value="C3539075",
    meaning="Pretreatment",
    scheme_designator="UMLS"
)

NADIR = CodedConcept(
    value="C1708760",
    meaning="Nadir",
    scheme_designator="UMLS"
)

