"""CID 7024 RTProcessInput
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


FOR_RT_PLAN_SUMMATION = CodedConcept(
    value="128200",
    meaning="For RT Plan Summation",
    scheme_designator="DCM"
)

FOR_PHYSICIST_REVIEW = CodedConcept(
    value="128202",
    meaning="For Physicist Review",
    scheme_designator="DCM"
)

FOR_PHYSICIAN_REVIEW = CodedConcept(
    value="128201",
    meaning="For Physician Review",
    scheme_designator="DCM"
)

FOR_PLAN_QUALITY_ASSURANCE = CodedConcept(
    value="128204",
    meaning="For Plan Quality Assurance",
    scheme_designator="DCM"
)

FOR_PATIENT_SETUP_VERIFICATION = CodedConcept(
    value="128206",
    meaning="For Patient Setup Verification",
    scheme_designator="DCM"
)

FOR_MACHINE_QUALITY_ASSURANCE = CodedConcept(
    value="128205",
    meaning="For Machine Quality Assurance",
    scheme_designator="DCM"
)

FOR_RT_WORKFLOW = CodedConcept(
    value="128180",
    meaning="For RT Workflow",
    scheme_designator="DCM"
)

FOR_RT_TREATMENT_PLANNING = CodedConcept(
    value="128198",
    meaning="For RT Treatment Planning",
    scheme_designator="DCM"
)

FOR_RT_PRESCRIPTION = CodedConcept(
    value="128197",
    meaning="For RT Prescription",
    scheme_designator="DCM"
)

