"""CID 7181 AbstractMultidimensionalImageModelComponentUnits
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


CENTIMETER_2_MILLILITER = CodedConcept(
    value="cm2/ml",
    meaning="Centimeter**2/milliliter",
    scheme_designator="UCUM"
)

MM2_S = CodedConcept(
    value="mm2/s",
    meaning="mm2/s",
    scheme_designator="UCUM"
)

CUBIC_CENTIMETER = CodedConcept(
    value="cm3",
    meaning="cubic centimeter",
    scheme_designator="UCUM"
)

SQUARE_CENTIMETER = CodedConcept(
    value="cm2",
    meaning="square centimeter",
    scheme_designator="UCUM"
)

UM2_MS = CodedConcept(
    value="um2/ms",
    meaning="um2/ms",
    scheme_designator="UCUM"
)

STANDARDIZED_UPTAKE_VALUE_BODY_SURFACE_AREA = CodedConcept(
    value="cm2/ml{SUVbsa}",
    meaning="Standardized Uptake Value body surface area",
    scheme_designator="UCUM"
)

STANDARDIZED_UPTAKE_VALUE_LEAN_BODY_MASS_JANMA_ = CodedConcept(
    value="g/ml{SUVlbm(Janma)}",
    meaning="Standardized Uptake Value lean body mass (Janma)",
    scheme_designator="UCUM"
)

MILLITESLA = CodedConcept(
    value="mT",
    meaning="milliTesla",
    scheme_designator="UCUM"
)

SV = CodedConcept(
    value="Sv",
    meaning="Sv",
    scheme_designator="UCUM"
)

SECOND_PER_SQUARE_MILLIMETER = CodedConcept(
    value="s/mm2",
    meaning="second per square millimeter",
    scheme_designator="UCUM"
)

CUBIC_MILLIMETER = CodedConcept(
    value="mm3",
    meaning="cubic millimeter",
    scheme_designator="UCUM"
)

SQUARE_MILLIMETER = CodedConcept(
    value="mm2",
    meaning="square millimeter",
    scheme_designator="UCUM"
)

MILLIGRAMS_MINUTE_MILLILITER = CodedConcept(
    value="mg/min/ml",
    meaning="Milligrams/minute/milliliter",
    scheme_designator="UCUM"
)

STANDARDIZED_UPTAKE_VALUE_IDEAL_BODY_WEIGHT = CodedConcept(
    value="g/ml{SUVibw}",
    meaning="Standardized Uptake Value ideal body weight",
    scheme_designator="UCUM"
)

MM2_S_106 = CodedConcept(
    value="10-6.mm2/s",
    meaning="10-6.mm2/s",
    scheme_designator="UCUM"
)

BECQUERELS_MILLILITER = CodedConcept(
    value="Bq/ml",
    meaning="Becquerels/milliliter",
    scheme_designator="UCUM"
)

MICROMETER = CodedConcept(
    value="um",
    meaning="micrometer",
    scheme_designator="UCUM"
)

MILLIMOLES_PER_KG_WET_WEIGHT = CodedConcept(
    value="mmol/kg{WetWeight}",
    meaning="millimoles per kg wet weight",
    scheme_designator="UCUM"
)

GY = CodedConcept(
    value="Gy",
    meaning="Gy",
    scheme_designator="UCUM"
)

MICROMOLE_MINUTE_MILLILITER = CodedConcept(
    value="umol/min/ml",
    meaning="Micromole/minute/milliliter",
    scheme_designator="UCUM"
)

DECIBEL = CodedConcept(
    value="dB",
    meaning="decibel",
    scheme_designator="UCUM"
)

ARBITRARY_UNIT = CodedConcept(
    value="[arb'U]",
    meaning="arbitrary unit",
    scheme_designator="UCUM"
)

WOOD_U_M2 = CodedConcept(
    value="[wood'U]/m2",
    meaning="Wood U/m2",
    scheme_designator="UCUM"
)

DYN_S_CM5 = CodedConcept(
    value="dyn.s.cm-5",
    meaning="dyn.s.cm-5",
    scheme_designator="UCUM"
)

MILLILITER_MINUTE_GRAM = CodedConcept(
    value="ml/min/g",
    meaning="Milliliter/minute/gram",
    scheme_designator="UCUM"
)

UM2_S = CodedConcept(
    value="um2/s",
    meaning="um2/s",
    scheme_designator="UCUM"
)

STANDARDIZED_UPTAKE_VALUE_BODY_WEIGHT = CodedConcept(
    value="g/ml{SUVbw}",
    meaning="Standardized Uptake Value body weight",
    scheme_designator="UCUM"
)

MILLILITER_PER_100_MILLILITER = CodedConcept(
    value="ml/[100]ml",
    meaning="milliliter per 100 milliliter",
    scheme_designator="UCUM"
)

MILLIMETER_SECOND = CodedConcept(
    value="mm/s",
    meaning="millimeter/second",
    scheme_designator="UCUM"
)

MICROMOLE_MILLILITER = CodedConcept(
    value="umol/ml",
    meaning="Micromole/milliliter",
    scheme_designator="UCUM"
)

PROPORTIONAL_TO_COUNTS_PER_SECOND = CodedConcept(
    value="{propcounts}/s",
    meaning="Proportional to counts per second",
    scheme_designator="UCUM"
)

CENTIMETER = CodedConcept(
    value="cm",
    meaning="centimeter",
    scheme_designator="UCUM"
)

MILLILITER_PER_MINUTE = CodedConcept(
    value="ml/min",
    meaning="milliliter per minute",
    scheme_designator="UCUM"
)

COUNTS_PER_SECOND = CodedConcept(
    value="{counts}/s",
    meaning="Counts per second",
    scheme_designator="UCUM"
)

PPM = CodedConcept(
    value="ppm",
    meaning="ppm",
    scheme_designator="UCUM"
)

SECOND = CodedConcept(
    value="s",
    meaning="second",
    scheme_designator="UCUM"
)

P_R_U_M2 = CodedConcept(
    value="[PRU]/m2",
    meaning="P.R.U./m2",
    scheme_designator="UCUM"
)

STANDARDIZED_UPTAKE_VALUE_LEAN_BODY_MASS_JAMES_128_MULTIPLIER_ = CodedConcept(
    value="g/ml{SUVlbm(James128)}",
    meaning="Standardized Uptake Value lean body mass (James 128 multiplier)",
    scheme_designator="UCUM"
)

WOOD_U = CodedConcept(
    value="[wood'U]",
    meaning="Wood U",
    scheme_designator="UCUM"
)

MILLILITER_GRAM = CodedConcept(
    value="ml/g",
    meaning="Milliliter/gram",
    scheme_designator="UCUM"
)

PROPORTIONAL_TO_COUNTS = CodedConcept(
    value="{propcounts}",
    meaning="Proportional to counts",
    scheme_designator="UCUM"
)

KPA = CodedConcept(
    value="kPa",
    meaning="kPa",
    scheme_designator="UCUM"
)

NUMBER_PARTICLES_PER_100_GRAM_OF_TISSUE = CodedConcept(
    value="{Particles}/[100]g{Tissue}",
    meaning="number particles per 100 gram of tissue",
    scheme_designator="UCUM"
)

MILLILITER_PER_100_GRAM_PER_MINUTE = CodedConcept(
    value="ml/[100]g/min",
    meaning="milliliter per 100 gram per minute",
    scheme_designator="UCUM"
)

_MIN = CodedConcept(
    value="/min",
    meaning="/min",
    scheme_designator="UCUM"
)

_CENTIMETER = CodedConcept(
    value="/cm",
    meaning="/Centimeter",
    scheme_designator="UCUM"
)

CUBIC_DECIMETER = CodedConcept(
    value="dm3",
    meaning="cubic decimeter",
    scheme_designator="UCUM"
)

MILLIMETER = CodedConcept(
    value="mm",
    meaning="millimeter",
    scheme_designator="UCUM"
)

CENTIMETER_SECOND = CodedConcept(
    value="cm/s",
    meaning="centimeter/second",
    scheme_designator="UCUM"
)

P_R_U_ = CodedConcept(
    value="[PRU]",
    meaning="P.R.U.",
    scheme_designator="UCUM"
)

RATIO = CodedConcept(
    value="{ratio}",
    meaning="ratio",
    scheme_designator="UCUM"
)

CUBIC_MICROMETER = CodedConcept(
    value="um3",
    meaning="cubic micrometer",
    scheme_designator="UCUM"
)

SQUARE_MICROMETER = CodedConcept(
    value="um2",
    meaning="square micrometer",
    scheme_designator="UCUM"
)

COUNTS = CodedConcept(
    value="{counts}",
    meaning="Counts",
    scheme_designator="UCUM"
)

MILLISECOND = CodedConcept(
    value="ms",
    meaning="millisecond",
    scheme_designator="UCUM"
)

DYN_S_CM5_M2 = CodedConcept(
    value="dyn.s.cm-5/m2",
    meaning="dyn.s.cm-5/m2",
    scheme_designator="UCUM"
)

PERCENT = CodedConcept(
    value="%",
    meaning="Percent",
    scheme_designator="UCUM"
)

_S = CodedConcept(
    value="/s",
    meaning="/s",
    scheme_designator="UCUM"
)

NO_UNITS = CodedConcept(
    value="1",
    meaning="no units",
    scheme_designator="UCUM"
)

HOUNSFIELD_UNIT = CodedConcept(
    value="[hnsf'U]",
    meaning="Hounsfield Unit",
    scheme_designator="UCUM"
)

MILLILITER_PER_SECOND = CodedConcept(
    value="ml/s",
    meaning="milliliter per second",
    scheme_designator="UCUM"
)

DEGREES_CELSIUS = CodedConcept(
    value="Cel",
    meaning="degrees Celsius",
    scheme_designator="UCUM"
)

MMHG = CodedConcept(
    value="mm[Hg]",
    meaning="mmHg",
    scheme_designator="UCUM"
)

STANDARDIZED_UPTAKE_VALUE_LEAN_BODY_MASS_JAMES_ = CodedConcept(
    value="g/ml{SUVlbm}",
    meaning="Standardized Uptake Value lean body mass (James)",
    scheme_designator="UCUM"
)

HERTZ = CodedConcept(
    value="Hz",
    meaning="Hertz",
    scheme_designator="UCUM"
)

