"""CID 7453 PerformingRoles
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


STANDBY = CodedConcept(
    value="121101",
    meaning="Standby",
    scheme_designator="DCM"
)

IRRADIATION_ADMINISTERING = CodedConcept(
    value="113851",
    meaning="Irradiation Administering",
    scheme_designator="DCM"
)

IRRADIATION_AUTHORIZING = CodedConcept(
    value="113850",
    meaning="Irradiation Authorizing",
    scheme_designator="DCM"
)

IMAGE_QUALITY_CONTROLLER = CodedConcept(
    value="129003",
    meaning="Image Quality Controller",
    scheme_designator="DCM"
)

DESIGNATOR = CodedConcept(
    value="129002",
    meaning="Designator",
    scheme_designator="DCM"
)

RESULTS_QUALITY_CONTROLLER = CodedConcept(
    value="129004",
    meaning="Results Quality Controller",
    scheme_designator="DCM"
)

ASSISTING = CodedConcept(
    value="121099",
    meaning="Assisting",
    scheme_designator="DCM"
)

RECORDING = CodedConcept(
    value="121097",
    meaning="Recording",
    scheme_designator="DCM"
)

VERIFYING = CodedConcept(
    value="121098",
    meaning="Verifying",
    scheme_designator="DCM"
)

REQUESTING = CodedConcept(
    value="121096",
    meaning="Requesting",
    scheme_designator="DCM"
)

ELIGIBILITY_READER = CodedConcept(
    value="129001",
    meaning="Eligibility Reader",
    scheme_designator="DCM"
)

PERFORMING = CodedConcept(
    value="121094",
    meaning="Performing",
    scheme_designator="DCM"
)

READER = CodedConcept(
    value="C28747",
    meaning="Reader",
    scheme_designator="NCIt"
)

ADJUDICATOR = CodedConcept(
    value="C96561",
    meaning="Adjudicator",
    scheme_designator="NCIt"
)

REVIEWER = CodedConcept(
    value="C54634",
    meaning="Reviewer",
    scheme_designator="NCIt"
)

CIRCULATING_NURSE = CodedConcept(
    value="J-0714B",
    meaning="Circulating Nurse",
    scheme_designator="SRT"
)

REFERRING = CodedConcept(
    value="C1709880",
    meaning="Referring",
    scheme_designator="UMLS"
)

