"""CID 6093 QualitativeConceptsforUsage,ExposureAmount
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


RELATIVE_DOSE_AMOUNT = CodedConcept(
    value="111581",
    meaning="Relative dose amount",
    scheme_designator="DCM"
)

RELATIVE_AMOUNT_OF_EXPOSURE = CodedConcept(
    value="111582",
    meaning="Relative amount of exposure",
    scheme_designator="DCM"
)

RELATIVE_AMOUNT_OF_USE = CodedConcept(
    value="111583",
    meaning="Relative amount of use",
    scheme_designator="DCM"
)

