"""CID 6302 ProstateSectorAnatomyfromEuropeanConcensus16Sector(Minimal)Model
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


RIGHT_SEMINAL_VESICLE = CodedConcept(
    value="T-93010",
    meaning="Right seminal vesicle",
    scheme_designator="SRT"
)

LEFT_SEMINAL_VESICLE = CodedConcept(
    value="T-93020",
    meaning="Left seminal vesicle",
    scheme_designator="SRT"
)

LEFT_BASAL_PART_TRANSITION_ZONE_OF_PROSTATE = CodedConcept(
    value="R0-00020",
    meaning="Left basal part transition zone of prostate",
    scheme_designator="SRT"
)

RIGHT_BASAL_TRANSITION_ZONE_OF_PROSTATE = CodedConcept(
    value="R-FFFBE",
    meaning="Right basal transition zone of prostate",
    scheme_designator="SRT"
)

CENTRAL_ZONE_OF_RIGHT_HALF_PROSTATE = CodedConcept(
    value="R-FFFD0",
    meaning="Central zone of right half prostate",
    scheme_designator="SRT"
)

LEFT_APICAL_PERIPHERAL_ZONE_OF_PROSTATE = CodedConcept(
    value="R-FFFD3",
    meaning="Left apical peripheral zone of prostate",
    scheme_designator="SRT"
)

RIGHT_APICAL_TRANSITION_ZONE_OF_PROSTATE = CodedConcept(
    value="R-FFFC1",
    meaning="Right apical transition zone of prostate",
    scheme_designator="SRT"
)

RIGHT_BASAL_PERIPHERAL_ZONE_OF_PROSTATE = CodedConcept(
    value="R0-00018",
    meaning="Right basal peripheral zone of prostate",
    scheme_designator="SRT"
)

MALE_EXTERNAL_URETHRAL_SPHINCTER = CodedConcept(
    value="R-FFFD9",
    meaning="Male external urethral sphincter",
    scheme_designator="SRT"
)

RIGHT_MIDDLE_TRANSITION_ZONE_OF_PROSTATE = CodedConcept(
    value="R-FFFB6",
    meaning="Right middle transition zone of prostate",
    scheme_designator="SRT"
)

LEFT_BASAL_PERIPHERAL_ZONE_OF_PROSTATE = CodedConcept(
    value="R-FFFC4",
    meaning="Left basal peripheral zone of prostate",
    scheme_designator="SRT"
)

LEFT_LATERAL_MIDDLE_PERIPHERAL_ZONE_OF_PROSTATE = CodedConcept(
    value="R-FFFE6",
    meaning="Left lateral middle peripheral zone of prostate",
    scheme_designator="SRT"
)

LEFT_MIDDLE_TRANSITION_ZONE_OF_PROSTATE = CodedConcept(
    value="R-FFFD5",
    meaning="Left middle transition zone of prostate",
    scheme_designator="SRT"
)

RIGHT_APICAL_PERIPHERAL_ZONE_OF_PROSTATE = CodedConcept(
    value="R-FFFB3",
    meaning="Right apical peripheral zone of prostate",
    scheme_designator="SRT"
)

RIGHT_POSTEROMEDIAL_MIDDLE_PERIPHERAL_ZONE_OF_PROSTATE = CodedConcept(
    value="R-FFFD4",
    meaning="Right posteromedial middle peripheral zone of prostate",
    scheme_designator="SRT"
)

LEFT_POSTEROMEDIAL_MIDDLE_PERIPHERAL_ZONE_OF_PROSTATE = CodedConcept(
    value="R-FFFB5",
    meaning="Left posteromedial middle peripheral zone of prostate",
    scheme_designator="SRT"
)

CENTRAL_ZONE_OF_LEFT_HALF_PROSTATE = CodedConcept(
    value="R-FFFFC",
    meaning="Central zone of left half prostate",
    scheme_designator="SRT"
)

LEFT_APICAL_TRANSITION_ZONE_OF_PROSTATE = CodedConcept(
    value="R-FFFA9",
    meaning="Left apical transition zone of prostate",
    scheme_designator="SRT"
)

RIGHT_LATERAL_MIDDLE_PERIPHERAL_ZONE_OF_PROSTATE = CodedConcept(
    value="R0-0000F",
    meaning="Right lateral middle peripheral zone of prostate",
    scheme_designator="SRT"
)

