"""CID 7270 MRDiffusionComponentSemantics
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


VOLUMETRIC_DIFFUSION_DXZ_COMPONENT = CodedConcept(
    value="110812",
    meaning="Volumetric Diffusion Dxz Component",
    scheme_designator="DCM"
)

VOLUMETRIC_DIFFUSION_DXY_COMPONENT = CodedConcept(
    value="110811",
    meaning="Volumetric Diffusion Dxy Component",
    scheme_designator="DCM"
)

DIFFUSION_WEIGHTED = CodedConcept(
    value="113043",
    meaning="Diffusion weighted",
    scheme_designator="DCM"
)

VOLUMETRIC_DIFFUSION_DXX_COMPONENT = CodedConcept(
    value="110810",
    meaning="Volumetric Diffusion Dxx Component",
    scheme_designator="DCM"
)

VOLUMETRIC_DIFFUSION_DZZ_COMPONENT = CodedConcept(
    value="110815",
    meaning="Volumetric Diffusion Dzz Component",
    scheme_designator="DCM"
)

VOLUMETRIC_DIFFUSION_DYZ_COMPONENT = CodedConcept(
    value="110814",
    meaning="Volumetric Diffusion Dyz Component",
    scheme_designator="DCM"
)

VOLUMETRIC_DIFFUSION_DYY_COMPONENT = CodedConcept(
    value="110813",
    meaning="Volumetric Diffusion Dyy Component",
    scheme_designator="DCM"
)

