"""CID 9509 PurposeofReferenceforRTPhysicianIntentInput
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


HISTORICAL_RT_PRESCRIPTION = CodedConcept(
    value="130135",
    meaning="Historical RT Prescription",
    scheme_designator="DCM"
)

RT_PRESCRIPTION_INPUT_IMAGES = CodedConcept(
    value="130136",
    meaning="RT Prescription Input Images",
    scheme_designator="DCM"
)

DIAGNOSTIC_SOURCE_IMAGES = CodedConcept(
    value="128181",
    meaning="Diagnostic Source Images",
    scheme_designator="DCM"
)

REGISTRATION_RESULT = CodedConcept(
    value="128183",
    meaning="Registration Result",
    scheme_designator="DCM"
)

SEGMENTATION_RESULT = CodedConcept(
    value="128182",
    meaning="Segmentation Result",
    scheme_designator="DCM"
)

RELEVANT_DIAGNOSTIC_TESTS_AND_OR_LABORATORY_DATA = CodedConcept(
    value="30954-2",
    meaning="Relevant Diagnostic Tests and/or Laboratory Data",
    scheme_designator="LN"
)

