"""CID 9517 RadiotherapyBlockDeviceTypes
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


APERTURE_BLOCK = CodedConcept(
    value="130123",
    meaning="Aperture Block",
    scheme_designator="DCM"
)

SHIELDING_BLOCK = CodedConcept(
    value="A-010FE",
    meaning="Shielding Block",
    scheme_designator="SRT"
)

