"""CID 702 RTContentAssessmentTypes
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


RT_PRETREATMENT_CONSISTENCY_CHECK = CodedConcept(
    value="121374",
    meaning="RT Pre-Treatment Consistency Check",
    scheme_designator="DCM"
)

RT_PRETREATMENT_DOSE_CHECK = CodedConcept(
    value="121373",
    meaning="RT Pre-Treatment Dose Check",
    scheme_designator="DCM"
)

