"""CID 6119 ChestBorderShape
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


ELLIPTIC = CodedConcept(
    value="112134",
    meaning="Elliptic",
    scheme_designator="DCM"
)

LOBULATED = CodedConcept(
    value="112135",
    meaning="Lobulated",
    scheme_designator="DCM"
)

SPICULATED = CodedConcept(
    value="112136",
    meaning="Spiculated",
    scheme_designator="DCM"
)

IRREGULAR = CodedConcept(
    value="G-A402",
    meaning="Irregular",
    scheme_designator="SRT"
)

ROUND_SHAPE = CodedConcept(
    value="M-02100",
    meaning="Round shape",
    scheme_designator="SRT"
)

