"""CID 6005 CharacteristicsofShapefromBIRADS®
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


IRREGULAR = CodedConcept(
    value="G-A402",
    meaning="Irregular",
    scheme_designator="SRT"
)

ROUND_SHAPE = CodedConcept(
    value="M-02100",
    meaning="Round shape",
    scheme_designator="SRT"
)

OVOID_SHAPE_OVAL_ = CodedConcept(
    value="M-02120",
    meaning="Ovoid shape (Oval)",
    scheme_designator="SRT"
)

LOBULAR = CodedConcept(
    value="G-A640",
    meaning="Lobular",
    scheme_designator="SRT"
)

