"""CID 6039 NippleCharacteristic
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


NIPPLE_RETRACTION = CodedConcept(
    value="D7-90554",
    meaning="Nipple retraction",
    scheme_designator="SRT"
)

NORMAL_SHAPE = CodedConcept(
    value="M-02000",
    meaning="Normal shape",
    scheme_designator="SRT"
)

