"""CID 3019 CardiovascularAnatomicLocationModifiers
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


GRAFT_TO_CITED_SEGMENT_DISTAL_SECTION = CodedConcept(
    value="122104",
    meaning="Graft to cited segment, distal section",
    scheme_designator="DCM"
)

GRAFT_TO_CITED_SEGMENT_PROXIMAL_SECTION = CodedConcept(
    value="122102",
    meaning="Graft to cited segment, proximal section",
    scheme_designator="DCM"
)

GRAFT_TO_CITED_SEGMENT_MID_SECTION = CodedConcept(
    value="122103",
    meaning="Graft to cited segment, mid section",
    scheme_designator="DCM"
)

ANEURYSM_ON_CITED_VESSEL = CodedConcept(
    value="122101",
    meaning="Aneurysm on cited vessel",
    scheme_designator="DCM"
)

OSTIUM = CodedConcept(
    value="R-4215C",
    meaning="Ostium",
    scheme_designator="SRT"
)

ARTERIAL_GRAFT_TO_CITED_SEGMENT = CodedConcept(
    value="G-D873",
    meaning="Arterial graft to cited segment",
    scheme_designator="SRT"
)

GRAFT_TO_CITED_SEGMENT_DISTAL_ANASTOMOSIS = CodedConcept(
    value="G-D872",
    meaning="Graft to cited segment, distal anastomosis",
    scheme_designator="SRT"
)

POSTERIOR = CodedConcept(
    value="R-404CE",
    meaning="Posterior",
    scheme_designator="SRT"
)

GRAFT_TO_CITED_SEGMENT_PROXIMAL_ANASTOMOSIS = CodedConcept(
    value="G-D871",
    meaning="Graft to cited segment, proximal anastomosis",
    scheme_designator="SRT"
)

RIGHT = CodedConcept(
    value="G-A100",
    meaning="Right",
    scheme_designator="SRT"
)

CENTRAL = CodedConcept(
    value="G-A110",
    meaning="Central",
    scheme_designator="SRT"
)

GRAFT_TO_CITED_SEGMENT_BODY = CodedConcept(
    value="G-D870",
    meaning="Graft to cited segment, body",
    scheme_designator="SRT"
)

LEFT = CodedConcept(
    value="G-A101",
    meaning="Left",
    scheme_designator="SRT"
)

LATERAL = CodedConcept(
    value="G-A104",
    meaning="Lateral",
    scheme_designator="SRT"
)

ANTERIOR = CodedConcept(
    value="R-404CC",
    meaning="Anterior",
    scheme_designator="SRT"
)

VENOUS_GRAFT_TO_CITED_SEGMENT = CodedConcept(
    value="G-D874",
    meaning="Venous graft to cited segment",
    scheme_designator="SRT"
)

DISTAL = CodedConcept(
    value="G-A119",
    meaning="Distal",
    scheme_designator="SRT"
)

PROXIMAL = CodedConcept(
    value="G-A118",
    meaning="Proximal",
    scheme_designator="SRT"
)

INFERIOR = CodedConcept(
    value="R-4094A",
    meaning="Inferior",
    scheme_designator="SRT"
)

ENTIRE_VESSEL = CodedConcept(
    value="T-40003",
    meaning="Entire Vessel",
    scheme_designator="SRT"
)

SUPERIOR = CodedConcept(
    value="R-42191",
    meaning="Superior",
    scheme_designator="SRT"
)

