"""CID 633 PhaseofImagingProcedureRequiringAnesthesia
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


BEFORE_PROCEDURE = CodedConcept(
    value="R-40FB9",
    meaning="Before procedure",
    scheme_designator="SRT"
)

DURING_PROCEDURE = CodedConcept(
    value="R-40FBA",
    meaning="During procedure",
    scheme_designator="SRT"
)

AFTER_PROCEDURE = CodedConcept(
    value="R-422A4",
    meaning="After procedure",
    scheme_designator="SRT"
)

