"""CID 4273 RetinalSegmentationSurfaces
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


POSTERIOR_SURFACE_OF_THE_RPE = CodedConcept(
    value="128299",
    meaning="Posterior surface of the RPE",
    scheme_designator="DCM"
)

SURFACE_OF_THE_CENTER_OF_THE_RPE = CodedConcept(
    value="128298",
    meaning="Surface of the center of the RPE",
    scheme_designator="DCM"
)

SURFACE_OF_THE_CHOROIDSCLERA_INTERFACE = CodedConcept(
    value="128301",
    meaning="Surface of the choroid-sclera interface",
    scheme_designator="DCM"
)

OUTER_SURFACE_OF_RNFL = CodedConcept(
    value="128289",
    meaning="Outer surface of RNFL",
    scheme_designator="DCM"
)

OUTER_SURFACE_OF_THE_BM = CodedConcept(
    value="128300",
    meaning="Outer surface of the BM",
    scheme_designator="DCM"
)

OUTER_SURFACE_OF_THE_CC = CodedConcept(
    value="128302",
    meaning="Outer surface of the CC",
    scheme_designator="DCM"
)

OUTER_SURFACE_OF_IPL = CodedConcept(
    value="128291",
    meaning="Outer surface of IPL",
    scheme_designator="DCM"
)

OUTER_SURFACE_OF_GCL = CodedConcept(
    value="128290",
    meaning="Outer surface of GCL",
    scheme_designator="DCM"
)

OUTER_SURFACE_OF_OPL = CodedConcept(
    value="128293",
    meaning="Outer surface of OPL",
    scheme_designator="DCM"
)

OUTER_SURFACE_OF_INL = CodedConcept(
    value="128292",
    meaning="Outer surface of INL",
    scheme_designator="DCM"
)

SURFACE_BETWEEN_INNER_AND_OUTER_SEGMENTS_OF_THE_PHOTORECEPTORS = CodedConcept(
    value="128295",
    meaning="Surface between Inner and Outer Segments of the photoreceptors",
    scheme_designator="DCM"
)

OUTER_SURFACE_OF_HFL = CodedConcept(
    value="128294",
    meaning="Outer surface of HFL",
    scheme_designator="DCM"
)

ANTERIOR_SURFACE_OF_THE_RPE = CodedConcept(
    value="128297",
    meaning="Anterior surface of the RPE",
    scheme_designator="DCM"
)

SURFACE_OF_THE_INTERDIGITATING_ZONE_BETWEEN_RETINA_AND_RPE = CodedConcept(
    value="128296",
    meaning="Surface of the interdigitating zone between retina and RPE",
    scheme_designator="DCM"
)

ELM_EXTERNAL_LIMITING_MEMBRANE = CodedConcept(
    value="T-AA650",
    meaning="ELM - External limiting membrane",
    scheme_designator="SRT"
)

ILM_INTERNAL_LIMITING_MEMBRANE = CodedConcept(
    value="T-AA62D",
    meaning="ILM - Internal limiting membrane",
    scheme_designator="SRT"
)

