"""CID 6126 LocationinLung
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


SUBPLEURAL = CodedConcept(
    value="112153",
    meaning="Subpleural",
    scheme_designator="DCM"
)

MIDDLE_LOBE_OF_LUNG = CodedConcept(
    value="T-28825",
    meaning="Middle lobe of lung",
    scheme_designator="SRT"
)

MIDDLE_ZONE_OF_LUNG = CodedConcept(
    value="T-D3209",
    meaning="Middle zone of lung",
    scheme_designator="SRT"
)

LOWER_LOBE_OF_LUNG = CodedConcept(
    value="T-28830",
    meaning="Lower lobe of lung",
    scheme_designator="SRT"
)

UPPER_ZONE_OF_LUNG = CodedConcept(
    value="T-D3208",
    meaning="Upper zone of lung",
    scheme_designator="SRT"
)

LOWER_ZONE_OF_LUNG = CodedConcept(
    value="T-D320A",
    meaning="Lower zone of lung",
    scheme_designator="SRT"
)

UPPER_LOBE_OF_LUNG = CodedConcept(
    value="T-28820",
    meaning="Upper lobe of lung",
    scheme_designator="SRT"
)

