"""CID 12300 CoreEchoMeasurements
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


TRICUSPID_VALVE_DIASTOLIC_VTI = CodedConcept(
    value="18175-0",
    meaning="Tricuspid valve diastolic VTI",
    scheme_designator="LN"
)

MITRAL_VALVE_PEAK_INSTANTANEOUS_GRADIENT = CodedConcept(
    value="80074-8",
    meaning="Mitral valve peak instantaneous gradient",
    scheme_designator="LN"
)

LEFT_ATRIAL_END_SYSTOLIC_VOLUME_BIPLANE_AREALENGTH_ = CodedConcept(
    value="79981-7",
    meaning="Left atrial end systolic volume biplane (area-length)",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_INTERNAL_SYSTOLIC_DIMENSION_BSA = CodedConcept(
    value="80013-6",
    meaning="Left ventricular internal systolic dimension / BSA",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_PREEJECTION_PERIOD = CodedConcept(
    value="79989-0",
    meaning="Left ventricular pre-ejection period",
    scheme_designator="LN"
)

LV_BASAL_ANTERIOR_TIME_TO_S_VMAX_TSBASAL_ANTERIOR_ = CodedConcept(
    value="80036-7",
    meaning="LV basal anterior time to S Vmax (Ts-basal anterior)",
    scheme_designator="LN"
)

MITRAL_REGURGITATION_PISA_RADIUS = CodedConcept(
    value="80059-9",
    meaning="Mitral regurgitation PISA radius",
    scheme_designator="LN"
)

PULMONIC_VALVE_VMAX = CodedConcept(
    value="79920-5",
    meaning="Pulmonic valve Vmax",
    scheme_designator="LN"
)

PULMONARY_VEIN_SWAVE_VMAX = CodedConcept(
    value="79917-1",
    meaning="Pulmonary vein S-wave Vmax",
    scheme_designator="LN"
)

LEFT_ATRIAL_END_SYSTOLIC_DIAMETER_AP_MM_BSA = CodedConcept(
    value="79978-3",
    meaning="Left atrial end systolic diameter (AP) MM / BSA",
    scheme_designator="LN"
)

RIGHT_VENTRICULAR_MIDCAVITY_DIMENSION_4C = CodedConcept(
    value="80085-4",
    meaning="Right ventricular mid-cavity dimension 4C",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_END_SYSTOLIC_VOLUME_BIPLANE_MOD_ = CodedConcept(
    value="80001-1",
    meaning="Left ventricular end systolic volume biplane (MOD)",
    scheme_designator="LN"
)

MITRAL_REGURGITATION_VMAX = CodedConcept(
    value="80062-3",
    meaning="Mitral regurgitation Vmax",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_EJECTION_FRACTION_SINGLE_PLANE_4C_MOD_ = CodedConcept(
    value="79993-2",
    meaning="Left ventricular ejection fraction single plane 4C (MOD)",
    scheme_designator="LN"
)

INTERVENTRICULAR_SEPTUM_SYSTOLIC_DIMENSION_MM = CodedConcept(
    value="79970-0",
    meaning="Interventricular septum systolic dimension MM",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_MASS_DIMENSION_METHOD_MM_HEIGHT_2_7 = CodedConcept(
    value="80024-3",
    meaning="Left ventricular mass (dimension method) MM / height^^2.7",
    scheme_designator="LN"
)

LV_MID_SEPTAL_TIME_TO_S_VMAX_TSMID_SEPTAL_ = CodedConcept(
    value="80047-4",
    meaning="LV mid septal time to S Vmax (Ts-mid septal)",
    scheme_designator="LN"
)

AORTIC_SINOTUBULAR_JUNCTION_DIMENSION = CodedConcept(
    value="79955-1",
    meaning="Aortic sinotubular junction dimension",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_INTERNAL_DIASTOLIC_DIMENSION_BSA = CodedConcept(
    value="80009-4",
    meaning="Left ventricular internal diastolic dimension / BSA",
    scheme_designator="LN"
)

TRICUSPID_REGURGITATION_PISA_RADIUS = CodedConcept(
    value="79932-0",
    meaning="Tricuspid regurgitation PISA radius",
    scheme_designator="LN"
)

INFERIOR_VENA_CAVA_DIAMETER = CodedConcept(
    value="79967-6",
    meaning="Inferior vena cava diameter",
    scheme_designator="LN"
)

AORTIC_REGURGITANT_JET_WIDTH_LVOT_WIDTH_ = CodedConcept(
    value="79944-5",
    meaning="Aortic regurgitant jet width/LVOT width %",
    scheme_designator="LN"
)

MITRAL_VALVE_MEAN_GRADIENT = CodedConcept(
    value="80073-0",
    meaning="Mitral valve mean gradient",
    scheme_designator="LN"
)

RIGHT_VENTRICULAR_EJECTION_TIME = CodedConcept(
    value="79929-6",
    meaning="Right ventricular ejection time",
    scheme_designator="LN"
)

MITRAL_ANNULUS_DIASTOLIC_DIAMETER_A2C = CodedConcept(
    value="80050-8",
    meaning="Mitral annulus diastolic diameter - A2C",
    scheme_designator="LN"
)

LEFT_ATRIAL_END_SYSTOLIC_VOLUME_BIPLANE_AREALENGTH_BSA = CodedConcept(
    value="79982-5",
    meaning="Left atrial end systolic volume biplane (area-length) / BSA",
    scheme_designator="LN"
)

MITRAL_REGURGITATION_PEAK_GRADIENT = CodedConcept(
    value="80058-1",
    meaning="Mitral regurgitation peak gradient",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_INTERNAL_SYSTOLIC_DIMENSION_MM = CodedConcept(
    value="80012-8",
    meaning="Left ventricular internal systolic dimension - MM",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_STROKE_VOLUME_3D = CodedConcept(
    value="80035-9",
    meaning="Left ventricular stroke volume 3D",
    scheme_designator="LN"
)

TRICUSPID_REGURGITATION_VMAX = CodedConcept(
    value="79921-3",
    meaning="Tricuspid regurgitation Vmax",
    scheme_designator="LN"
)

AORTIC_VALVE_AREA_CONTINUITY_VMAX_ = CodedConcept(
    value="79956-9",
    meaning="Aortic valve area (Continuity Vmax)",
    scheme_designator="LN"
)

TRICUSPID_REGURGITATION_VENA_CONTRACTA_WIDTH = CodedConcept(
    value="79933-8",
    meaning="Tricuspid regurgitation vena contracta width",
    scheme_designator="LN"
)

PULMONIC_VALVE_VTI = CodedConcept(
    value="79910-6",
    meaning="Pulmonic valve VTI",
    scheme_designator="LN"
)

PULMONIC_REGURGITATION_END_DIASTOLIC_VELOCITY = CodedConcept(
    value="79918-9",
    meaning="Pulmonic regurgitation end diastolic velocity",
    scheme_designator="LN"
)

MITRAL_REGURGITATION_VENA_CONTRACTA_WIDTH = CodedConcept(
    value="80061-5",
    meaning="Mitral regurgitation vena contracta width",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_END_SYSTOLIC_VOLUME_3D_ = CodedConcept(
    value="80000-3",
    meaning="Left ventricular end systolic volume (3D)",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_MASS_DIMENSION_METHOD_MM_BSA = CodedConcept(
    value="80023-5",
    meaning="Left ventricular mass (dimension method) MM / BSA",
    scheme_designator="LN"
)

MITRAL_VALVE_DECELERATION_TIME = CodedConcept(
    value="78191-4",
    meaning="Mitral valve deceleration time",
    scheme_designator="LN"
)

RIGHT_VENTRICULAR_FREE_WALL_THICKNESS_MM = CodedConcept(
    value="80084-7",
    meaning="Right ventricular free wall thickness MM",
    scheme_designator="LN"
)

LEFT_ATRIAL_END_SYSTOLIC_LENGTH_2C = CodedConcept(
    value="79979-1",
    meaning="Left atrial end systolic length 2C",
    scheme_designator="LN"
)

LV_MID_POSTERIOR_TIME_TO_S_VMAX_TSMID_POSTERIOR_ = CodedConcept(
    value="80046-6",
    meaning="LV mid posterior time to S Vmax (Ts-mid posterior)",
    scheme_designator="LN"
)

INTERVENTRICULAR_SEPTUM_SYSTOLIC_DIMENSION_2D = CodedConcept(
    value="79971-8",
    meaning="Interventricular septum systolic dimension 2D",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_FRACTIONAL_SHORTENING_OF_MINOR_AXIS_MM_ = CodedConcept(
    value="29435-5",
    meaning="Left ventricular fractional shortening (of minor axis) (MM)",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_INTERNAL_DIASTOLIC_DIMENSION_MM = CodedConcept(
    value="80008-6",
    meaning="Left ventricular internal diastolic dimension - MM",
    scheme_designator="LN"
)

MITRAL_VALVE_AREA_PRESSURE_HALFTIME_ = CodedConcept(
    value="80069-8",
    meaning="Mitral valve area (Pressure Half-Time)",
    scheme_designator="LN"
)

TRICUSPID_VALVE_PRESSURE_HALFTIME = CodedConcept(
    value="18032-3",
    meaning="Tricuspid valve pressure half-time",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_END_DIASTOLIC_LENGTH_4C = CodedConcept(
    value="79994-0",
    meaning="Left ventricular end diastolic length 4C",
    scheme_designator="LN"
)

INTERVENTRICULAR_SEPTUM_DIASTOLIC_DIMENSION_MM = CodedConcept(
    value="79968-4",
    meaning="Interventricular septum diastolic dimension MM",
    scheme_designator="LN"
)

MITRAL_VALVE_FLOW_PROPAGATION_VELOCITY_VP_ = CodedConcept(
    value="80072-2",
    meaning="Mitral valve flow propagation velocity (Vp)",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_INTERNAL_SYSTOLIC_DIMENSION_2D = CodedConcept(
    value="80011-0",
    meaning="Left ventricular internal systolic dimension - 2D",
    scheme_designator="LN"
)

AORTIC_VALVE_EFFECTIVE_REGURGITANT_ORIFICE_AREA = CodedConcept(
    value="79960-1",
    meaning="Aortic valve effective regurgitant orifice area",
    scheme_designator="LN"
)

MITRAL_REGURGITANT_FLOW_PISA_ = CodedConcept(
    value="80057-3",
    meaning="Mitral regurgitant flow (PISA)",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_POSTERIOR_WALL_SYSTOLIC_THICKNESS = CodedConcept(
    value="80034-2",
    meaning="Left ventricular posterior wall systolic thickness",
    scheme_designator="LN"
)

LEFT_ATRIAL_END_SYSTOLIC_VOLUME_BIPLANE_MOD_ = CodedConcept(
    value="79983-3",
    meaning="Left atrial end systolic volume biplane (MOD)",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_EJECTION_FRACTION_TEICHHOLZ_MM = CodedConcept(
    value="18049-7",
    meaning="Left ventricular ejection fraction (Teichholz) MM",
    scheme_designator="LN"
)

TRICUSPID_VALVE_APRIME_VMAX = CodedConcept(
    value="79922-1",
    meaning="Tricuspid valve a-prime Vmax",
    scheme_designator="LN"
)

AORTIC_REGURGITATION_PISA_RADIUS = CodedConcept(
    value="79945-2",
    meaning="Aortic regurgitation PISA radius",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_MASS_DIMENSION_METHOD_2D = CodedConcept(
    value="80019-3",
    meaning="Left ventricular mass (dimension method) 2D",
    scheme_designator="LN"
)

AORTIC_VALVE_AREA_CONTINUITY_VMAX_BSA = CodedConcept(
    value="79957-7",
    meaning="Aortic valve area (Continuity Vmax) / BSA",
    scheme_designator="LN"
)

MITRAL_SEPTAL_EPRIME_VMAX = CodedConcept(
    value="79911-4",
    meaning="Mitral septal e-prime Vmax",
    scheme_designator="LN"
)

PULMONIC_REGURGITATION_END_DIASTOLIC_PEAK_GRADIENT = CodedConcept(
    value="79934-6",
    meaning="Pulmonic regurgitation end diastolic peak gradient",
    scheme_designator="LN"
)

MITRAL_VALVE_AREA_PLANIMETRY_ = CodedConcept(
    value="80068-0",
    meaning="Mitral valve area (Planimetry)",
    scheme_designator="LN"
)

MITRAL_REGURGITATION_PISA_VELOCITY = CodedConcept(
    value="80060-7",
    meaning="Mitral regurgitation PISA velocity",
    scheme_designator="LN"
)

PULMONIC_REGURGITATION_VMAX = CodedConcept(
    value="79919-7",
    meaning="Pulmonic regurgitation Vmax",
    scheme_designator="LN"
)

LV_MID_LATERAL_TIME_TO_S_VMAX_TSMID_LATERAL_ = CodedConcept(
    value="80045-8",
    meaning="LV mid lateral time to S Vmax (Ts-mid lateral)",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_MASS_DIMENSION_METHOD_MM = CodedConcept(
    value="80022-7",
    meaning="Left ventricular mass (dimension method) MM",
    scheme_designator="LN"
)

RIGHT_VENTRICULAR_FREE_WALL_THICKNESS_2D = CodedConcept(
    value="80083-9",
    meaning="Right ventricular free wall thickness 2D",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_END_DIASTOLIC_VOLUME_3D_ = CodedConcept(
    value="79995-7",
    meaning="Left ventricular end diastolic volume (3D)",
    scheme_designator="LN"
)

INTERVENTRICULAR_SEPTUM_TIME_TO_PEAK_DISPLACEMENT = CodedConcept(
    value="79972-6",
    meaning="Interventricular septum time to peak displacement",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_FRACTIONAL_SHORTENING_OF_MINOR_AXIS_2D_ = CodedConcept(
    value="29434-8",
    meaning="Left ventricular fractional shortening (of minor axis) (2D)",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_INTERNAL_DIASTOLIC_DIMENSION_2D = CodedConcept(
    value="80007-8",
    meaning="Left ventricular internal diastolic dimension - 2D",
    scheme_designator="LN"
)

TRICUSPID_VALVE_AWAVE_VMAX = CodedConcept(
    value="79923-9",
    meaning="Tricuspid valve A-wave Vmax",
    scheme_designator="LN"
)

INTERVENTRICULAR_SEPTUM_DIASTOLIC_DIMENSION_2D = CodedConcept(
    value="79969-2",
    meaning="Interventricular septum diastolic dimension 2D",
    scheme_designator="LN"
)

AORTIC_VALVE_MEAN_BLOOD_VELOCITY = CodedConcept(
    value="79961-9",
    meaning="Aortic valve mean blood velocity",
    scheme_designator="LN"
)

MITRAL_VALVE_EFFECTIVE_REGURGITANT_ORIFICE_AREA_PISA_ = CodedConcept(
    value="80071-4",
    meaning="Mitral valve effective regurgitant orifice area (PISA)",
    scheme_designator="LN"
)

LEFT_ATRIAL_END_SYSTOLIC_VOLUME_BIPLANE_MOD_BSA = CodedConcept(
    value="79984-1",
    meaning="Left atrial end systolic volume biplane (MOD) / BSA",
    scheme_designator="LN"
)

MITRAL_REGURGITANT_FRACTION_PISA_ = CodedConcept(
    value="80056-5",
    meaning="Mitral regurgitant fraction (PISA)",
    scheme_designator="LN"
)

RIGHT_PULMONARY_ARTERY_DIAMETER = CodedConcept(
    value="80079-7",
    meaning="Right pulmonary artery diameter",
    scheme_designator="LN"
)

AORTIC_REGURGITATION_PISA_VELOCITY = CodedConcept(
    value="79946-0",
    meaning="Aortic regurgitation PISA velocity",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_MASS_AREALENGTH_HEIGHT_2_7 = CodedConcept(
    value="80018-5",
    meaning="Left ventricular mass (area-length) / height^^2.7",
    scheme_designator="LN"
)

AORTIC_VALVE_AREA_CONTINUITY_VTI_ = CodedConcept(
    value="79958-5",
    meaning="Aortic valve area (Continuity VTI)",
    scheme_designator="LN"
)

PULMONIC_VALVE_EJECTION_TIME = CodedConcept(
    value="18042-2",
    meaning="Pulmonic valve ejection time",
    scheme_designator="LN"
)

PULMONIC_VALVE_PEAK_GRADIENT = CodedConcept(
    value="79935-3",
    meaning="Pulmonic valve peak gradient",
    scheme_designator="LN"
)

LV_MID_INFERIOR_TIME_TO_S_VMAX_TSMID_INFERIOR_ = CodedConcept(
    value="80044-1",
    meaning="LV mid inferior time to S Vmax (Ts-mid inferior)",
    scheme_designator="LN"
)

RIGHT_VENTRICULAR_END_SYSTOLIC_AREA_4C = CodedConcept(
    value="80082-1",
    meaning="Right ventricular end systolic area 4C",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_EPICARDIAL_AREA_SAX_PM_LEVEL = CodedConcept(
    value="80006-0",
    meaning="Left ventricular epicardial area SAX PM level",
    scheme_designator="LN"
)

MITRAL_VALVE_AREA_PISA_ = CodedConcept(
    value="80067-2",
    meaning="Mitral valve area (PISA)",
    scheme_designator="LN"
)

LEFT_ATRIAL_END_SYSTOLIC_AREA_2C = CodedConcept(
    value="79973-4",
    meaning="Left atrial end systolic area 2C",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_MASS_DIMENSION_METHOD_2D_HEIGHT_2_7 = CodedConcept(
    value="80021-9",
    meaning="Left ventricular mass (dimension method) 2D / height^^2.7",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_END_DIASTOLIC_VOLUME_BIPLANE_MOD_ = CodedConcept(
    value="79996-5",
    meaning="Left ventricular end diastolic volume biplane (MOD)",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_OUTFLOW_TRACT_VMAX = CodedConcept(
    value="80029-2",
    meaning="Left ventricular outflow tract Vmax",
    scheme_designator="LN"
)

MITRAL_VALVE_PRESSURE_HALFTIME = CodedConcept(
    value="79912-2",
    meaning="Mitral valve pressure half-time",
    scheme_designator="LN"
)

AORTIC_REGURGITATION_VOLUME_CONTINUITY_VTI_ = CodedConcept(
    value="79950-2",
    meaning="Aortic regurgitation volume (Continuity VTI)",
    scheme_designator="LN"
)

MITRAL_VALVE_ETOA_RATIO = CodedConcept(
    value="18038-0",
    meaning="Mitral valve E-to-A ratio",
    scheme_designator="LN"
)

TRICUSPID_VALVE_EPRIME_VMAX = CodedConcept(
    value="79924-7",
    meaning="Tricuspid valve e-prime Vmax",
    scheme_designator="LN"
)

AORTIC_REGURGITATION_PRESSURE_HALFTIME = CodedConcept(
    value="79947-8",
    meaning="Aortic regurgitation pressure half-time",
    scheme_designator="LN"
)

LEFT_ATRIAL_END_SYSTOLIC_VOLUME_SINGLE_PLANE_2C_MOD_ = CodedConcept(
    value="79985-8",
    meaning="Left atrial end systolic volume single plane 2C (MOD)",
    scheme_designator="LN"
)

PULMONIC_ANNULUS_DIAMETER = CodedConcept(
    value="79909-8",
    meaning="Pulmonic annulus diameter",
    scheme_designator="LN"
)

MITRAL_VALVE_EWAVE_VMAX = CodedConcept(
    value="80070-6",
    meaning="Mitral valve E-wave Vmax",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_POSTERIOR_WALL_DIASTOLIC_THICKNESS = CodedConcept(
    value="80032-6",
    meaning="Left ventricular posterior wall diastolic thickness",
    scheme_designator="LN"
)

RIGHT_ATRIAL_MINOR_AXIS_DIMENSION_4C_BSA = CodedConcept(
    value="80078-9",
    meaning="Right atrial minor axis dimension 4C / BSA",
    scheme_designator="LN"
)

MITRAL_REGURGITANT_FRACTION_CONTINUITY_VTI_ = CodedConcept(
    value="80055-7",
    meaning="Mitral regurgitant fraction (Continuity VTI)",
    scheme_designator="LN"
)

AORTIC_VALVE_MEAN_GRADIENT = CodedConcept(
    value="79962-7",
    meaning="Aortic valve mean gradient",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_MASS_AREALENGTH_BSA = CodedConcept(
    value="80017-7",
    meaning="Left ventricular mass (area-length) / BSA",
    scheme_designator="LN"
)

AORTIC_VALVE_AREA_CONTINUITY_VTI_BSA = CodedConcept(
    value="79959-3",
    meaning="Aortic valve area (Continuity VTI) / BSA",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_EJECTION_FRACTION_TEICHHOLZ_2D = CodedConcept(
    value="77891-0",
    meaning="Left ventricular ejection fraction (Teichholz) 2D",
    scheme_designator="LN"
)

RIGHT_VENTRICULAR_FRACTIONAL_AREA_CHANGE = CodedConcept(
    value="79936-1",
    meaning="Right ventricular fractional area change",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_MASS_DIMENSION_METHOD_2D_BSA = CodedConcept(
    value="80020-1",
    meaning="Left ventricular mass (dimension method) 2D / BSA",
    scheme_designator="LN"
)

LV_MID_ANTEROSEPTAL_TIME_TO_S_VMAX_TSMID_ANTEROSEPTAL_ = CodedConcept(
    value="80043-3",
    meaning="LV mid anteroseptal time to S Vmax (Ts-mid anteroseptal)",
    scheme_designator="LN"
)

RIGHT_VENTRICULAR_END_DIASTOLIC_AREA_4C = CodedConcept(
    value="80081-3",
    meaning="Right ventricular end diastolic area 4C",
    scheme_designator="LN"
)

RIGHT_VENTRICULAR_OUTFLOW_TRACT_VTI = CodedConcept(
    value="80089-6",
    meaning="Right ventricular outflow tract VTI",
    scheme_designator="LN"
)

MITRAL_VALVE_AWAVE_VMAX = CodedConcept(
    value="80066-4",
    meaning="Mitral valve A-wave Vmax",
    scheme_designator="LN"
)

LEFT_ATRIAL_END_SYSTOLIC_AREA_4C = CodedConcept(
    value="79974-2",
    meaning="Left atrial end systolic area 4C",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_ENDOCARDIAL_AREA_SAX_PM_LEVEL = CodedConcept(
    value="80005-2",
    meaning="Left ventricular endocardial area SAX PM level",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_END_DIASTOLIC_VOLUME_BIPLANE_MOD_BSA = CodedConcept(
    value="79997-3",
    meaning="Left ventricular end diastolic volume biplane (MOD) / BSA",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_OUTFLOW_TRACT_DIMENSION_2D_ = CodedConcept(
    value="80028-4",
    meaning="Left ventricular outflow tract dimension (2D)",
    scheme_designator="LN"
)

MITRAL_VALVE_VMAX = CodedConcept(
    value="79913-0",
    meaning="Mitral valve Vmax",
    scheme_designator="LN"
)

AORTIC_REGURGITATION_VOLUME_PISA_ = CodedConcept(
    value="79951-0",
    meaning="Aortic regurgitation volume (PISA)",
    scheme_designator="LN"
)

AORTIC_REGURGITATION_VENA_CONTRACTA_WIDTH = CodedConcept(
    value="79948-6",
    meaning="Aortic regurgitation vena contracta width",
    scheme_designator="LN"
)

TRICUSPID_VALVE_EWAVE_VMAX = CodedConcept(
    value="79925-4",
    meaning="Tricuspid valve E-wave Vmax",
    scheme_designator="LN"
)

LEFT_ATRIAL_END_SYSTOLIC_VOLUME_SINGLE_PLANE_4C_MOD_ = CodedConcept(
    value="79986-6",
    meaning="Left atrial end systolic volume single plane 4C (MOD)",
    scheme_designator="LN"
)

RIGHT_ATRIAL_MINOR_AXIS_DIMENSION_4C = CodedConcept(
    value="80077-1",
    meaning="Right atrial minor axis dimension 4C",
    scheme_designator="LN"
)

MITRAL_LATERAL_EPRIME_VMAX = CodedConcept(
    value="80054-0",
    meaning="Mitral lateral e-prime Vmax",
    scheme_designator="LN"
)

LV_BASAL_LATERAL_TIME_TO_S_VMAX_TSBASAL_LATERAL_ = CodedConcept(
    value="80039-1",
    meaning="LV basal lateral time to S Vmax (Ts-basal lateral)",
    scheme_designator="LN"
)

PULMONARY_VEIN_AWAVE_DURATION = CodedConcept(
    value="78184-9",
    meaning="Pulmonary vein A-wave duration",
    scheme_designator="LN"
)

AORTIC_VALVE_PEAK_INSTANTANEOUS_GRADIENT = CodedConcept(
    value="79963-5",
    meaning="Aortic valve peak instantaneous gradient",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_MASS_AREALENGTH_ = CodedConcept(
    value="80016-9",
    meaning="Left ventricular mass (area-length)",
    scheme_designator="LN"
)

AORTIC_ANNULUS_DIAMETER = CodedConcept(
    value="79940-3",
    meaning="Aortic annulus diameter",
    scheme_designator="LN"
)

MITRAL_VALVE_VTI = CodedConcept(
    value="79914-8",
    meaning="Mitral valve VTI",
    scheme_designator="LN"
)

AORTIC_REGURGITATION_VTI = CodedConcept(
    value="79952-8",
    meaning="Aortic regurgitation VTI",
    scheme_designator="LN"
)

LEFT_ATRIAL_END_SYSTOLIC_DIAMETER_AP_2D = CodedConcept(
    value="79975-9",
    meaning="Left atrial end systolic diameter (AP) 2D",
    scheme_designator="LN"
)

RIGHT_VENTRICULAR_BASAL_DIMENSION_4C = CodedConcept(
    value="80080-5",
    meaning="Right ventricular basal dimension 4C",
    scheme_designator="LN"
)

TRICUSPID_REGURGITATION_PEAK_GRADIENT = CodedConcept(
    value="79937-9",
    meaning="Tricuspid regurgitation peak gradient",
    scheme_designator="LN"
)

MITRAL_VALVE_AWAVE_DURATION = CodedConcept(
    value="80065-6",
    meaning="Mitral valve A-wave duration",
    scheme_designator="LN"
)

RIGHT_VENTRICULAR_OUTFLOW_TRACT_DIAMETER_AT_SUBVALVULAR_LEVEL_RVOTPROXIMAL_ = CodedConcept(
    value="80088-8",
    meaning="Right ventricular outflow tract diameter at subvalvular level (RVOT-Proximal)",
    scheme_designator="LN"
)

LV_MID_ANTERIOR_TIME_TO_S_VMAX_TSMID_ANTERIOR_ = CodedConcept(
    value="80042-5",
    meaning="LV mid anterior time to S Vmax (Ts-mid anterior)",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_EJECTION_FRACTION_3D = CodedConcept(
    value="79990-8",
    meaning="Left ventricular ejection fraction 3D",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_END_DIASTOLIC_VOLUME_SINGLE_PLANE_2C_MOD_ = CodedConcept(
    value="79998-1",
    meaning="Left ventricular end diastolic volume single plane 2C (MOD)",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_END_SYSTOLIC_VOLUME_SINGLE_PLANE_4C_MOD_ = CodedConcept(
    value="80004-5",
    meaning="Left ventricular end systolic volume single plane 4C (MOD)",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_MASS_TRUNCATED_ELLIPSE_HEIGHT_2_7 = CodedConcept(
    value="80027-6",
    meaning="Left ventricular mass (truncated ellipse) / height^^2.7",
    scheme_designator="LN"
)

AORTIC_REGURGITATION_VMAX = CodedConcept(
    value="79949-4",
    meaning="Aortic regurgitation Vmax",
    scheme_designator="LN"
)

TRICUSPID_ANNULUS_DIAMETER = CodedConcept(
    value="80091-2",
    meaning="Tricuspid annulus diameter",
    scheme_designator="LN"
)

TRICUSPID_VALVE_SPRIME_VMAX = CodedConcept(
    value="79926-2",
    meaning="Tricuspid valve s-prime Vmax",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_OUTFLOW_TRACT_VTI = CodedConcept(
    value="80030-0",
    meaning="Left ventricular outflow tract VTI",
    scheme_designator="LN"
)

RIGHT_ATRIAL_MAJOR_AXIS_DIMENSION_4C = CodedConcept(
    value="80076-3",
    meaning="Right atrial major axis dimension 4C",
    scheme_designator="LN"
)

MITRAL_ANNULUS_VTI = CodedConcept(
    value="80053-2",
    meaning="Mitral annulus VTI",
    scheme_designator="LN"
)

MAIN_PULMONARY_ARTERY_VMAX = CodedConcept(
    value="",
    meaning="Main pulmonary artery Vmax",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_ISOVOLUMIC_RELAXATION_TIME_BY_TDI = CodedConcept(
    value="80015-1",
    meaning="Left ventricular isovolumic relaxation time by TDI",
    scheme_designator="LN"
)

LEFT_PULMONARY_ARTERY_DIAMETER = CodedConcept(
    value="79987-4",
    meaning="Left pulmonary artery diameter",
    scheme_designator="LN"
)

LV_BASAL_INFERIOR_TIME_TO_S_VMAX_TSBASAL_INFERIOR_ = CodedConcept(
    value="80038-3",
    meaning="LV basal inferior time to S Vmax (Ts-basal inferior)",
    scheme_designator="LN"
)

AORTIC_VALVE_VMAX = CodedConcept(
    value="79964-3",
    meaning="Aortic valve Vmax",
    scheme_designator="LN"
)

AORTIC_REGURGITANT_FLOW = CodedConcept(
    value="79941-1",
    meaning="Aortic regurgitant flow",
    scheme_designator="LN"
)

PULMONARY_VEIN_AWAVE_VMAX = CodedConcept(
    value="79915-5",
    meaning="Pulmonary vein A-wave Vmax",
    scheme_designator="LN"
)

AORTIC_ROOT_DIAMETER = CodedConcept(
    value="79953-6",
    meaning="Aortic root diameter",
    scheme_designator="LN"
)

RIGHT_VENTRICULAR_OUTFLOW_TRACT_DIAMETER_AT_PULMONIC_VALVE_RVOTDISTAL_ = CodedConcept(
    value="80087-0",
    meaning="Right ventricular outflow tract diameter at pulmonic valve (RVOT-Distal)",
    scheme_designator="LN"
)

LEFT_ATRIAL_END_SYSTOLIC_DIAMETER_AP_2D_BSA = CodedConcept(
    value="79976-7",
    meaning="Left atrial end systolic diameter (AP) 2D / BSA",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_END_DIASTOLIC_VOLUME_SINGLE_PLANE_4C_MOD_ = CodedConcept(
    value="79999-9",
    meaning="Left ventricular end diastolic volume single plane 4C (MOD)",
    scheme_designator="LN"
)

TRICUSPID_VALVE_MEAN_GRADIENT = CodedConcept(
    value="79938-7",
    meaning="Tricuspid valve mean gradient",
    scheme_designator="LN"
)

MAIN_PULMONARY_ARTERY_DIAMETER = CodedConcept(
    value="80049-0",
    meaning="Main pulmonary artery diameter",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_EJECTION_FRACTION_BIPLANE_MOD_ = CodedConcept(
    value="79991-6",
    meaning="Left ventricular ejection fraction biplane (MOD)",
    scheme_designator="LN"
)

LV_BASAL_SEPTAL_TIME_TO_S_VMAX_TSBASAL_SEPTAL_ = CodedConcept(
    value="80041-7",
    meaning="LV basal septal time to S Vmax (Ts-basal septal)",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_END_SYSTOLIC_VOLUME_SINGLE_PLANE_2C_MOD_ = CodedConcept(
    value="80003-7",
    meaning="Left ventricular end systolic volume single plane 2C (MOD)",
    scheme_designator="LN"
)

MITRAL_REGURGITATION_VOLUME_PISA_ = CodedConcept(
    value="80064-9",
    meaning="Mitral regurgitation volume (PISA)",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_MASS_TRUNCATED_ELLIPSE_BSA = CodedConcept(
    value="80026-8",
    meaning="Left ventricular mass (truncated ellipse) / BSA",
    scheme_designator="LN"
)

TRICUSPID_VALVE_CLOSURE_TO_OPENING_TIME = CodedConcept(
    value="79930-4",
    meaning="Tricuspid valve closure to opening time",
    scheme_designator="LN"
)

TRICUSPID_VALVE_VMAX = CodedConcept(
    value="79927-0",
    meaning="Tricuspid valve Vmax",
    scheme_designator="LN"
)

AORTIC_REGURGITANT_FRACTION = CodedConcept(
    value="79942-9",
    meaning="Aortic regurgitant fraction",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_ISOVOLUMIC_RELAXATION_TIME_BY_DOPPLER = CodedConcept(
    value="18071-1",
    meaning="Left ventricular isovolumic relaxation time by Doppler",
    scheme_designator="LN"
)

MITRAL_ANNULUS_DIASTOLIC_DIAMETER_PLAX = CodedConcept(
    value="80052-4",
    meaning="Mitral annulus diastolic diameter - PLAX",
    scheme_designator="LN"
)

RIGHT_VENTRICULAR_PREEJECTION_PERIOD = CodedConcept(
    value="80090-4",
    meaning="Right ventricular pre-ejection period",
    scheme_designator="LN"
)

RIGHT_ATRIAL_END_SYSTOLIC_AREA_4C = CodedConcept(
    value="80075-5",
    meaning="Right atrial end systolic area 4C",
    scheme_designator="LN"
)

LV_BASAL_ANTEROSEPTAL_TIME_TO_S_VMAX_TSBASAL_ANTEROSEPTAL_ = CodedConcept(
    value="80037-5",
    meaning="LV basal anteroseptal time to S Vmax (TS-basal anteroseptal)",
    scheme_designator="LN"
)

LEFT_ATRIAL_END_SYSTOLIC_LENGTH_4C = CodedConcept(
    value="79980-9",
    meaning="Left atrial end systolic length 4C",
    scheme_designator="LN"
)

LEFT_VENTICULAR_POSTERIOR_WALL_TIME_TO_PEAK_DISPLACEMENT = CodedConcept(
    value="79988-2",
    meaning="Left venticular posterior wall time to peak displacement",
    scheme_designator="LN"
)

AORTIC_VALVE_VTI = CodedConcept(
    value="79965-0",
    meaning="Aortic valve VTI",
    scheme_designator="LN"
)

TRICUSPID_ANNULAR_PLANE_SYSTOLIC_EXCURSION_TAPSE_ = CodedConcept(
    value="77903-3",
    meaning="Tricuspid Annular Plane Systolic Excursion (TAPSE)",
    scheme_designator="LN"
)

PULMONARY_VEIN_DWAVE_VMAX = CodedConcept(
    value="79916-3",
    meaning="Pulmonary vein D-wave Vmax",
    scheme_designator="LN"
)

TRICUSPID_VALVE_PEAK_GRADIENT = CodedConcept(
    value="79939-5",
    meaning="Tricuspid valve peak gradient",
    scheme_designator="LN"
)

MITRAL_REGURGITATION_VOLUME_CONTINUITY_VTI_ = CodedConcept(
    value="80063-1",
    meaning="Mitral regurgitation volume (Continuity VTI)",
    scheme_designator="LN"
)

LEFT_ATRIAL_END_SYSTOLIC_DIAMETER_AP_MM = CodedConcept(
    value="79977-5",
    meaning="Left atrial end systolic diameter (AP) MM",
    scheme_designator="LN"
)

RIGHT_VENTRICULAR_MYOCARDIAL_PERFORMANCE_INDEX = CodedConcept(
    value="80086-2",
    meaning="Right ventricular myocardial performance index",
    scheme_designator="LN"
)

LV_BASAL_POSTERIOR_TIME_TO_S_VMAX_TSBASAL_POSTERIOR_ = CodedConcept(
    value="80040-9",
    meaning="LV basal posterior time to S Vmax (Ts-basal posterior)",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_EJECTION_FRACTION_SINGLE_PLANE_2C_MOD_ = CodedConcept(
    value="79992-4",
    meaning="Left ventricular ejection fraction single plane 2C (MOD)",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_MASS_TRUNCATED_ELLIPSE_ = CodedConcept(
    value="80025-0",
    meaning="Left ventricular mass (truncated ellipse)",
    scheme_designator="LN"
)

LV_TSSD_DYSSYNCHRONY_INDEX_ = CodedConcept(
    value="80048-2",
    meaning="LV Ts-SD (Dyssynchrony Index)",
    scheme_designator="LN"
)

AORTIC_ROOT_DIAMETER_BSA = CodedConcept(
    value="79954-4",
    meaning="Aortic root diameter / BSA",
    scheme_designator="LN"
)

LEFT_VENTRICULAR_END_SYSTOLIC_VOLUME_BIPLANE_MOD_BSA = CodedConcept(
    value="80002-9",
    meaning="Left ventricular end systolic volume biplane (MOD) / BSA",
    scheme_designator="LN"
)

TRICUSPID_VALVE_DECELERATION_TIME = CodedConcept(
    value="79931-2",
    meaning="Tricuspid valve deceleration time",
    scheme_designator="LN"
)

ASCENDING_AORTA_DIMENSION = CodedConcept(
    value="79966-8",
    meaning="Ascending Aorta Dimension",
    scheme_designator="LN"
)

AORTIC_REGURGITANT_JET_AREA_LVOT_AREA_ = CodedConcept(
    value="79943-7",
    meaning="Aortic regurgitant jet area/LVOT area %",
    scheme_designator="LN"
)

MITRAL_ANNULUS_DIASTOLIC_DIAMETER_A4C = CodedConcept(
    value="80051-6",
    meaning="Mitral annulus diastolic diameter - A4C",
    scheme_designator="LN"
)

PULMONIC_VALVE_ACCELERATION_TIME = CodedConcept(
    value="79928-8",
    meaning="Pulmonic valve acceleration time",
    scheme_designator="LN"
)

