"""CID 3011 ElectrophysiologyAnatomicLocations
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


INFERIOR_LEFT_PULMONARY_VEIN = CodedConcept(
    value="T-48540",
    meaning="Inferior left pulmonary vein",
    scheme_designator="SRT"
)

EPICARDIUM = CodedConcept(
    value="T-39010",
    meaning="Epicardium",
    scheme_designator="SRT"
)

INFERIOR_RIGHT_PULMONARY_VEIN = CodedConcept(
    value="T-48520",
    meaning="Inferior right pulmonary vein",
    scheme_designator="SRT"
)

GREAT_CARDIAC_VEIN = CodedConcept(
    value="T-48420",
    meaning="Great cardiac vein",
    scheme_designator="SRT"
)

LEFT_ANTERIOR_DIVISION_OF_LEFT_BRANCH_ATRIOVENTRICULAR_BUNDLE = CodedConcept(
    value="T-32833",
    meaning="Left anterior division of left branch atrioventricular bundle",
    scheme_designator="SRT"
)

LEFT_BRANCH_OF_ATRIOVENTRICULAR_BUNDLE = CodedConcept(
    value="T-32832",
    meaning="Left branch of atrioventricular bundle",
    scheme_designator="SRT"
)

SINOATRIAL_NODE = CodedConcept(
    value="T-32810",
    meaning="Sino-atrial node",
    scheme_designator="SRT"
)

LEFT_POSTERIOR_DIVISION_OF_LEFT_BRANCH_ATRIOVENTRICULAR_BUNDLE = CodedConcept(
    value="T-32834",
    meaning="Left posterior division of left branch atrioventricular bundle",
    scheme_designator="SRT"
)

PULMONARY_VEIN = CodedConcept(
    value="T-48581",
    meaning="Pulmonary vein",
    scheme_designator="SRT"
)

ACCESSORY_ATRIOVENTRICULAR_BUNDLE = CodedConcept(
    value="T-32850",
    meaning="Accessory atrioventricular bundle",
    scheme_designator="SRT"
)

COMMON_VENTRICLE = CodedConcept(
    value="D4-31120",
    meaning="Common ventricle",
    scheme_designator="SRT"
)

RIGHT_BRANCH_OF_ATRIOVENTRICULAR_BUNDLE = CodedConcept(
    value="T-32831",
    meaning="Right branch of Atrioventricular bundle",
    scheme_designator="SRT"
)

ATRIOVENTRICULAR_BUNDLE = CodedConcept(
    value="T-32830",
    meaning="Atrioventricular bundle",
    scheme_designator="SRT"
)

RIGHT_VENTRICLE_OUTFLOW_TRACT = CodedConcept(
    value="T-32550",
    meaning="Right ventricle outflow tract",
    scheme_designator="SRT"
)

RIGHT_AURICULAR_APPENDAGE = CodedConcept(
    value="T-32210",
    meaning="Right auricular appendage",
    scheme_designator="SRT"
)

LEFT_AURICULAR_APPENDAGE = CodedConcept(
    value="T-32310",
    meaning="Left auricular appendage",
    scheme_designator="SRT"
)

LEFT_VENTRICLE_OUTFLOW_TRACT = CodedConcept(
    value="T-32650",
    meaning="Left ventricle outflow tract",
    scheme_designator="SRT"
)

RIGHT_ATRIOVENTRICULAR_OSTIUM = CodedConcept(
    value="T-35120",
    meaning="Right atrioventricular ostium",
    scheme_designator="SRT"
)

HIGH_RIGHT_ATRIUM = CodedConcept(
    value="G-DE02",
    meaning="High right atrium",
    scheme_designator="SRT"
)

MID_RIGHT_ATRIUM = CodedConcept(
    value="G-DE06",
    meaning="Mid right atrium",
    scheme_designator="SRT"
)

OSTIUM_OF_CORONARY_SINUS = CodedConcept(
    value="T-48411",
    meaning="Ostium of coronary sinus",
    scheme_designator="SRT"
)

SUPERIOR_RIGHT_PULMONARY_VEIN = CodedConcept(
    value="T-48510",
    meaning="Superior right pulmonary vein",
    scheme_designator="SRT"
)

LATERAL_HIGH_RIGHT_ATRIUM = CodedConcept(
    value="G-DE04",
    meaning="Lateral high right atrium",
    scheme_designator="SRT"
)

MIDDLE_CARDIAC_VEIN = CodedConcept(
    value="T-48430",
    meaning="Middle cardiac vein",
    scheme_designator="SRT"
)

CORONARY_SINUS = CodedConcept(
    value="T-48410",
    meaning="Coronary sinus",
    scheme_designator="SRT"
)

LOW_RIGHT_ATRIUM = CodedConcept(
    value="G-DE08",
    meaning="Low right atrium",
    scheme_designator="SRT"
)

SUPERIOR_LEFT_PULMONARY_VEIN = CodedConcept(
    value="T-48530",
    meaning="Superior left pulmonary vein",
    scheme_designator="SRT"
)

APEX_OF_LEFT_VENTRICLE = CodedConcept(
    value="T-32602",
    meaning="Apex of left ventricle",
    scheme_designator="SRT"
)

APEX_OF_RIGHT_VENTRICLE = CodedConcept(
    value="T-32502",
    meaning="Apex of right ventricle",
    scheme_designator="SRT"
)

LEFT_ATRIUM = CodedConcept(
    value="T-32300",
    meaning="Left Atrium",
    scheme_designator="SRT"
)

PURKINJE_FIBERS = CodedConcept(
    value="T-32840",
    meaning="Purkinje fibers",
    scheme_designator="SRT"
)

TENDON_OF_TODARO = CodedConcept(
    value="T-32202",
    meaning="Tendon of Todaro",
    scheme_designator="SRT"
)

ATRIOVENTRICULAR_NODE = CodedConcept(
    value="T-32820",
    meaning="Atrioventricular node",
    scheme_designator="SRT"
)

LEFT_VENTRICLE = CodedConcept(
    value="T-32600",
    meaning="Left ventricle",
    scheme_designator="SRT"
)

RIGHT_VENTRICLE = CodedConcept(
    value="T-32500",
    meaning="Right ventricle",
    scheme_designator="SRT"
)

LEFT_VENTRICLE_INFLOW = CodedConcept(
    value="T-32640",
    meaning="Left ventricle inflow",
    scheme_designator="SRT"
)

MITRAL_RING = CodedConcept(
    value="T-35310",
    meaning="Mitral ring",
    scheme_designator="SRT"
)

RIGHT_VENTRICLE_INFLOW = CodedConcept(
    value="T-32540",
    meaning="Right ventricle inflow",
    scheme_designator="SRT"
)

RIGHT_ATRIUM = CodedConcept(
    value="T-32200",
    meaning="Right Atrium",
    scheme_designator="SRT"
)

TRICUSPID_RING = CodedConcept(
    value="T-35110",
    meaning="Tricuspid ring",
    scheme_designator="SRT"
)

PULMONIC_RING = CodedConcept(
    value="T-35210",
    meaning="Pulmonic ring",
    scheme_designator="SRT"
)

