"""CID 12021 FetalLongBoneAnatomicSites
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


FEMUR = CodedConcept(
    value="T-12710",
    meaning="Femur",
    scheme_designator="SRT"
)

ULNA = CodedConcept(
    value="T-12430",
    meaning="Ulna",
    scheme_designator="SRT"
)

CLAVICLE = CodedConcept(
    value="T-12310",
    meaning="Clavicle",
    scheme_designator="SRT"
)

FIBULA = CodedConcept(
    value="T-12750",
    meaning="Fibula",
    scheme_designator="SRT"
)

RADIUS = CodedConcept(
    value="T-12420",
    meaning="Radius",
    scheme_designator="SRT"
)

TIBIA = CodedConcept(
    value="T-12740",
    meaning="Tibia",
    scheme_designator="SRT"
)

