"""CID 12106 IntracranialCerebralVessels(Unilateral)
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


BASILAR_ARTERY = CodedConcept(
    value="T-45800",
    meaning="Basilar Artery",
    scheme_designator="SRT"
)

