"""CID 9536 RadiotherapyPrescribingandSegmentingPersonRoles
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


LEAD_RADIOLOGIC_TECHNOLOGIST = CodedConcept(
    value="128674",
    meaning="Lead Radiologic Technologist",
    scheme_designator="DCM"
)

MEDICAL_PRACTITIONER = CodedConcept(
    value="J-0016E",
    meaning="Medical Practitioner",
    scheme_designator="SRT"
)

RADIOLOGIC_TECHNOLOGIST = CodedConcept(
    value="J-00187",
    meaning="Radiologic Technologist",
    scheme_designator="SRT"
)

PHYSICIAN = CodedConcept(
    value="J-004E8",
    meaning="Physician",
    scheme_designator="SRT"
)

RESIDENT = CodedConcept(
    value="J-005E6",
    meaning="Resident",
    scheme_designator="SRT"
)

RADIATION_THERAPIST = CodedConcept(
    value="J-06173",
    meaning="Radiation Therapist",
    scheme_designator="SRT"
)

CONSULTING_PHYSICIAN = CodedConcept(
    value="C1441532",
    meaning="Consulting Physician",
    scheme_designator="UMLS"
)

RADIATION_PHYSICIST = CodedConcept(
    value="C2985483",
    meaning="Radiation Physicist",
    scheme_designator="UMLS"
)

MEDICAL_PHYSICIST = CodedConcept(
    value="C1708969",
    meaning="Medical Physicist",
    scheme_designator="UMLS"
)

