"""CID 3621 FractionalFlowReserve
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


FRACTIONAL_FLOW_RESERVE_USING_INTRACORONARY_BOLUS = CodedConcept(
    value="R-00308",
    meaning="Fractional Flow Reserve using intracoronary bolus",
    scheme_designator="SRT"
)

FRACTIONAL_FLOW_RESERVE = CodedConcept(
    value="R-00307",
    meaning="Fractional flow reserve",
    scheme_designator="SRT"
)

FRACTIONAL_FLOW_RESERVE_USING_INTRAVENOUS_INFUSION = CodedConcept(
    value="R-00309",
    meaning="Fractional Flow Reserve using intravenous infusion",
    scheme_designator="SRT"
)

