"""CID 3421 ProcedureAction
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


SUSPEND_PROCEDURE_ACTION = CodedConcept(
    value="121132",
    meaning="Suspend Procedure Action",
    scheme_designator="DCM"
)

RESUME_PROCEDURE_ACTION = CodedConcept(
    value="121133",
    meaning="Resume Procedure Action",
    scheme_designator="DCM"
)

START_PROCEDURE_ACTION = CodedConcept(
    value="121130",
    meaning="Start Procedure Action",
    scheme_designator="DCM"
)

END_PROCEDURE_ACTION = CodedConcept(
    value="121131",
    meaning="End Procedure Action",
    scheme_designator="DCM"
)

