"""CID 224 SelectionMethod
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


MOST_RECENT_VALUE_CHOSEN = CodedConcept(
    value="121411",
    meaning="Most recent value chosen",
    scheme_designator="DCM"
)

MEAN_VALUE_CHOSEN = CodedConcept(
    value="121412",
    meaning="Mean value chosen",
    scheme_designator="DCM"
)

USER_CHOSEN_VALUE = CodedConcept(
    value="121410",
    meaning="User chosen value",
    scheme_designator="DCM"
)

