"""CID 12002 UltrasoundProtocolStageTypes
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


CARDIAC_PACING = CodedConcept(
    value="P2-35000",
    meaning="Cardiac pacing",
    scheme_designator="SRT"
)

VALSALVA_MANEUVER = CodedConcept(
    value="R-40928",
    meaning="Valsalva maneuver",
    scheme_designator="SRT"
)

PEAK_CARDIAC_STRESS_STATE = CodedConcept(
    value="F-05028",
    meaning="Peak cardiac stress state",
    scheme_designator="SRT"
)

HAND_GRIP = CodedConcept(
    value="P2-71306",
    meaning="Hand grip",
    scheme_designator="SRT"
)

BEFORE_PROCEDURE = CodedConcept(
    value="R-40FB9",
    meaning="Before Procedure",
    scheme_designator="SRT"
)

RESTING_STATE = CodedConcept(
    value="F-01604",
    meaning="Resting State",
    scheme_designator="SRT"
)

CARDIAC_STRESS_RECOVERY_STATE = CodedConcept(
    value="F-05018",
    meaning="Cardiac stress recovery state",
    scheme_designator="SRT"
)

CARDIAC_STRESS_STATE = CodedConcept(
    value="F-05019",
    meaning="Cardiac stress state",
    scheme_designator="SRT"
)

DURING_PROCEDURE = CodedConcept(
    value="R-40FBA",
    meaning="During Procedure",
    scheme_designator="SRT"
)

HYPERVENTILATION = CodedConcept(
    value="F-25040",
    meaning="Hyperventilation",
    scheme_designator="SRT"
)

AFTER_PROCEDURE = CodedConcept(
    value="R-422A4",
    meaning="After Procedure",
    scheme_designator="SRT"
)

