"""CID 7002 DiagnosticImagingReportElements
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


PREVIOUS_FINDING = CodedConcept(
    value="121069",
    meaning="Previous Finding",
    scheme_designator="DCM"
)

CONCLUSION = CodedConcept(
    value="121077",
    meaning="Conclusion",
    scheme_designator="DCM"
)

PATIENT_PRESENTATION = CodedConcept(
    value="121110",
    meaning="Patient Presentation",
    scheme_designator="DCM"
)

SUMMARY = CodedConcept(
    value="121111",
    meaning="Summary",
    scheme_designator="DCM"
)

RECOMMENDATION = CodedConcept(
    value="121075",
    meaning="Recommendation",
    scheme_designator="DCM"
)

PROCEDURE_DESCRIPTION = CodedConcept(
    value="121065",
    meaning="Procedure Description",
    scheme_designator="DCM"
)

IMPRESSION = CodedConcept(
    value="121073",
    meaning="Impression",
    scheme_designator="DCM"
)

FINDING = CodedConcept(
    value="121071",
    meaning="Finding",
    scheme_designator="DCM"
)

HISTORY = CodedConcept(
    value="11329-0",
    meaning="History",
    scheme_designator="LN"
)

REQUEST = CodedConcept(
    value="55115-0",
    meaning="Request",
    scheme_designator="LN"
)

COMPLICATION_OF_PROCEDURE = CodedConcept(
    value="DD-60002",
    meaning="Complication of Procedure",
    scheme_designator="SRT"
)

