"""CID 222 NormalityCodes
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


NORMALITY_UNDETERMINED = CodedConcept(
    value="R-0039B",
    meaning="Normality Undetermined",
    scheme_designator="SRT"
)

ABNORMALLY_HIGH = CodedConcept(
    value="R-002C4",
    meaning="Abnormally High",
    scheme_designator="SRT"
)

NORMAL = CodedConcept(
    value="G-A460",
    meaning="Normal",
    scheme_designator="SRT"
)

ABNORMALLY_LOW = CodedConcept(
    value="R-002C5",
    meaning="Abnormally Low",
    scheme_designator="SRT"
)

ABNORMAL = CodedConcept(
    value="R-42037",
    meaning="Abnormal",
    scheme_designator="SRT"
)

