"""CID 3402 PatientStatusandEvents
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


PATIENT_PRONOUNCED_DEAD = CodedConcept(
    value="122038",
    meaning="Patient pronounced dead",
    scheme_designator="DCM"
)

PATIENT_TRANSFERRED_TO_MORGUE = CodedConcept(
    value="122039",
    meaning="Patient transferred to morgue",
    scheme_designator="DCM"
)

PATIENT_GIVEN_POSTPROCEDURE_INSTRUCTION = CodedConcept(
    value="122036",
    meaning="Patient given post-procedure instruction",
    scheme_designator="DCM"
)

PATIENT_DISCHARGED_FROM_DEPARTMENT = CodedConcept(
    value="122037",
    meaning="Patient discharged from department",
    scheme_designator="DCM"
)

PATIENT_TRANSFERRED_TO_CCU = CodedConcept(
    value="122012",
    meaning="Patient transferred to CCU",
    scheme_designator="DCM"
)

HEMOSTASIS_NOT_ACHIEVED_OOZING = CodedConcept(
    value="122034",
    meaning="Hemostasis not achieved - oozing",
    scheme_designator="DCM"
)

HEMOSTASIS_NOT_ACHIEVED_ACTIVELY_BLEEDING = CodedConcept(
    value="122035",
    meaning="Hemostasis not achieved - actively bleeding",
    scheme_designator="DCM"
)

PATIENT_TRANSFERRED_TO_HOLDING_AREA = CodedConcept(
    value="122010",
    meaning="Patient transferred to holding area",
    scheme_designator="DCM"
)

PATIENT_DISCONNECTED_FROM_CONTINUOUS_MONITORING = CodedConcept(
    value="122032",
    meaning="Patient disconnected from continuous monitoring",
    scheme_designator="DCM"
)

PATIENT_TRANSFERRED_TO_SURGERY = CodedConcept(
    value="122011",
    meaning="Patient transferred to surgery",
    scheme_designator="DCM"
)

HEMOSTASIS_ACHIEVED = CodedConcept(
    value="122033",
    meaning="Hemostasis achieved",
    scheme_designator="DCM"
)

PATIENT_HAS_RESPIRATORY_DIFFICULTY = CodedConcept(
    value="122030",
    meaning="Patient has respiratory difficulty",
    scheme_designator="DCM"
)

PATIENT_COUGHED = CodedConcept(
    value="122031",
    meaning="Patient coughed",
    scheme_designator="DCM"
)

PATIENT_CONNECTED_TO_CONTINUOUS_MONITORING = CodedConcept(
    value="122009",
    meaning="Patient connected to continuous monitoring",
    scheme_designator="DCM"
)

PATIENT_ASSISTED_TO_TABLE = CodedConcept(
    value="122007",
    meaning="Patient assisted to table",
    scheme_designator="DCM"
)

PATIENT_UNRESPONSIVE = CodedConcept(
    value="122029",
    meaning="Patient unresponsive",
    scheme_designator="DCM"
)

PATIENT_PREPPED_AND_DRAPED = CodedConcept(
    value="122008",
    meaning="Patient prepped and draped",
    scheme_designator="DCM"
)

PATIENT_ADVANCE_DIRECTIVE_GIVEN = CodedConcept(
    value="122005",
    meaning="Patient advance directive given",
    scheme_designator="DCM"
)

PATIENT_SEDATED = CodedConcept(
    value="122027",
    meaning="Patient sedated",
    scheme_designator="DCM"
)

NIL_PER_OS_NPO_STATUS_CONFIRMED = CodedConcept(
    value="122006",
    meaning="Nil Per Os (NPO) status confirmed",
    scheme_designator="DCM"
)

PATIENT_ASLEEP = CodedConcept(
    value="122028",
    meaning="Patient asleep",
    scheme_designator="DCM"
)

PATIENT_GIVEN_PREPROCEDURE_INSTRUCTION = CodedConcept(
    value="122003",
    meaning="Patient given pre-procedure instruction",
    scheme_designator="DCM"
)

PATIENT_ALERT = CodedConcept(
    value="122025",
    meaning="Patient alert",
    scheme_designator="DCM"
)

PATIENT_INFORMED_CONSENT_GIVEN = CodedConcept(
    value="122004",
    meaning="Patient informed consent given",
    scheme_designator="DCM"
)

PATIENT_RESTLESS = CodedConcept(
    value="122026",
    meaning="Patient restless",
    scheme_designator="DCM"
)

PATIENT_CALLED_TO_PROCEDURE_ROOM = CodedConcept(
    value="122001",
    meaning="Patient called to procedure room",
    scheme_designator="DCM"
)

PATIENT_REPORTS_CHEST_PAIN = CodedConcept(
    value="122023",
    meaning="Patient reports chest pain",
    scheme_designator="DCM"
)

PATIENT_ADMITTED_TO_PROCEDURE_ROOM = CodedConcept(
    value="122002",
    meaning="Patient admitted to procedure room",
    scheme_designator="DCM"
)

PATIENT_REPORTS_NO_PAIN = CodedConcept(
    value="122024",
    meaning="Patient reports no pain",
    scheme_designator="DCM"
)

PATIENT_REPORTS_NAUSEA = CodedConcept(
    value="122021",
    meaning="Patient reports nausea",
    scheme_designator="DCM"
)

PATIENT_REPORTS_DISCOMFORT = CodedConcept(
    value="122022",
    meaning="Patient reports discomfort",
    scheme_designator="DCM"
)

PATIENT_DISORIENTED = CodedConcept(
    value="122020",
    meaning="Patient disoriented",
    scheme_designator="DCM"
)

