"""CID 3427 EquipmentEvents
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


EQUIPMENT_FAILURE = CodedConcept(
    value="110501",
    meaning="Equipment failure",
    scheme_designator="DCM"
)

EQUIPMENT_REMOVED = CodedConcept(
    value="122049",
    meaning="Equipment removed",
    scheme_designator="DCM"
)

EQUIPMENT_BROUGHT_TO_PROCEDURE_ROOM = CodedConcept(
    value="122047",
    meaning="Equipment brought to procedure room",
    scheme_designator="DCM"
)

EQUIPMENT_READY = CodedConcept(
    value="122048",
    meaning="Equipment ready",
    scheme_designator="DCM"
)

