"""CID 3837 FiducialFeature
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


AORTIC_BIFURCATION = CodedConcept(
    value="T-42580",
    meaning="Aortic Bifurcation",
    scheme_designator="SRT"
)

COMMON_ILIAC_BIFURCATION = CodedConcept(
    value="R-10258",
    meaning="Common Iliac Bifurcation",
    scheme_designator="SRT"
)

OSTIUM = CodedConcept(
    value="R-4215C",
    meaning="Ostium",
    scheme_designator="SRT"
)

RENAL_ARTERY = CodedConcept(
    value="T-46600",
    meaning="Renal Artery",
    scheme_designator="SRT"
)

