"""CID 6034 IntendedUseofCADOutput
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


PRESENTATION_REQUIRED_RENDERING_DEVICE_IS_EXPECTED_TO_PRESENT = CodedConcept(
    value="111150",
    meaning="Presentation Required: Rendering device is expected to present",
    scheme_designator="DCM"
)

PRESENTATION_OPTIONAL_RENDERING_DEVICE_MAY_PRESENT = CodedConcept(
    value="111151",
    meaning="Presentation Optional: Rendering device may present",
    scheme_designator="DCM"
)

NOT_FOR_PRESENTATION_RENDERING_DEVICE_EXPECTED_NOT_TO_PRESENT = CodedConcept(
    value="111152",
    meaning="Not for Presentation: Rendering device expected not to present",
    scheme_designator="DCM"
)

