"""CID 4207 OphthalmicImagePosition
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


LESION_CENTERED = CodedConcept(
    value="111902",
    meaning="Lesion centered",
    scheme_designator="DCM"
)

DISCMACULA_CENTERED = CodedConcept(
    value="111903",
    meaning="Disc-macula centered",
    scheme_designator="DCM"
)

MIDPERIPHERALSUPERIOR = CodedConcept(
    value="111904",
    meaning="Mid-peripheral-superior",
    scheme_designator="DCM"
)

MIDPERIPHERALSUPERIOR_TEMPORAL = CodedConcept(
    value="111905",
    meaning="Mid-peripheral-superior temporal",
    scheme_designator="DCM"
)

MIDPERIPHERALTEMPORAL = CodedConcept(
    value="111906",
    meaning="Mid-peripheral-temporal",
    scheme_designator="DCM"
)

MIDPERIPHERALINFERIOR_TEMPORAL = CodedConcept(
    value="111907",
    meaning="Mid-peripheral-inferior temporal",
    scheme_designator="DCM"
)

MIDPERIPHERALINFERIOR = CodedConcept(
    value="111908",
    meaning="Mid-peripheral-inferior",
    scheme_designator="DCM"
)

MIDPERIPHERALINFERIOR_NASAL = CodedConcept(
    value="111909",
    meaning="Mid-peripheral-inferior nasal",
    scheme_designator="DCM"
)

FIELD_1_FOR_JOSLIN3_FIELD = CodedConcept(
    value="111621",
    meaning="Field 1 for Joslin3 field",
    scheme_designator="DCM"
)

FIELD_2_FOR_JOSLIN_3_FIELD = CodedConcept(
    value="111622",
    meaning="Field 2 for Joslin 3 field",
    scheme_designator="DCM"
)

FIELD_3_FOR_JOSLIN_3_FIELD = CodedConcept(
    value="111623",
    meaning="Field 3 for Joslin 3 field",
    scheme_designator="DCM"
)

MACULA_CENTERED = CodedConcept(
    value="111900",
    meaning="Macula centered",
    scheme_designator="DCM"
)

DISC_CENTERED = CodedConcept(
    value="111901",
    meaning="Disc centered",
    scheme_designator="DCM"
)

PERIPHERALSUPERIOR_TEMPORAL = CodedConcept(
    value="111913",
    meaning="Peripheral-superior temporal",
    scheme_designator="DCM"
)

PERIPHERALTEMPORAL = CodedConcept(
    value="111914",
    meaning="Peripheral-temporal",
    scheme_designator="DCM"
)

PERIPHERALINFERIOR_TEMPORAL = CodedConcept(
    value="111915",
    meaning="Peripheral-inferior temporal",
    scheme_designator="DCM"
)

PERIPHERALINFERIOR = CodedConcept(
    value="111916",
    meaning="Peripheral-inferior",
    scheme_designator="DCM"
)

PERIPHERALINFERIOR_NASAL = CodedConcept(
    value="111917",
    meaning="Peripheral-inferior nasal",
    scheme_designator="DCM"
)

PERIPHERALNASAL = CodedConcept(
    value="111918",
    meaning="Peripheral-nasal",
    scheme_designator="DCM"
)

PERIPHERALSUPERIOR_NASAL = CodedConcept(
    value="111919",
    meaning="Peripheral-superior nasal",
    scheme_designator="DCM"
)

MIDPERIPHERALNASAL = CodedConcept(
    value="111910",
    meaning="Mid-peripheral-nasal",
    scheme_designator="DCM"
)

MIDPERIPHERALSUPERIOR_NASAL = CodedConcept(
    value="111911",
    meaning="Mid-peripheral-superior nasal",
    scheme_designator="DCM"
)

PERIPHERALSUPERIOR = CodedConcept(
    value="111912",
    meaning="Peripheral-superior",
    scheme_designator="DCM"
)

DIABETIC_RETINOPATHY_STUDY_FIELD_1 = CodedConcept(
    value="R-10229",
    meaning="Diabetic Retinopathy Study field 1",
    scheme_designator="SRT"
)

DIABETIC_RETINOPATHY_STUDY_FIELD_4 = CodedConcept(
    value="R-1022C",
    meaning="Diabetic Retinopathy Study field 4",
    scheme_designator="SRT"
)

DIABETIC_RETINOPATHY_STUDY_FIELD_3 = CodedConcept(
    value="R-1022B",
    meaning="Diabetic Retinopathy Study field 3",
    scheme_designator="SRT"
)

DIABETIC_RETINOPATHY_STUDY_FIELD_2 = CodedConcept(
    value="R-1022A",
    meaning="Diabetic Retinopathy Study field 2",
    scheme_designator="SRT"
)

DIABETIC_RETINOPATHY_STUDY_FIELD_6 = CodedConcept(
    value="R-1022F",
    meaning="Diabetic Retinopathy Study field 6",
    scheme_designator="SRT"
)

DIABETIC_RETINOPATHY_STUDY_FIELD_5 = CodedConcept(
    value="R-1022E",
    meaning="Diabetic Retinopathy Study field 5",
    scheme_designator="SRT"
)

DIABETIC_RETINOPATHY_STUDY_FIELD_7 = CodedConcept(
    value="R-10231",
    meaning="Diabetic Retinopathy Study field 7",
    scheme_designator="SRT"
)

