"""CID 6138 ChestNonlesionObjectType
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


PORTACATH = CodedConcept(
    value="112172",
    meaning="Portacath",
    scheme_designator="DCM"
)

CHEST_TUBE = CodedConcept(
    value="112173",
    meaning="Chest tube",
    scheme_designator="DCM"
)

CENTRAL_LINE = CodedConcept(
    value="112174",
    meaning="Central line",
    scheme_designator="DCM"
)

KIDNEY_STENT = CodedConcept(
    value="112175",
    meaning="Kidney stent",
    scheme_designator="DCM"
)

PANCREATIC_STENT = CodedConcept(
    value="112176",
    meaning="Pancreatic stent",
    scheme_designator="DCM"
)

NIPPLE_RING = CodedConcept(
    value="112177",
    meaning="Nipple ring",
    scheme_designator="DCM"
)

COIN = CodedConcept(
    value="112178",
    meaning="Coin",
    scheme_designator="DCM"
)

FIDUCIAL_MARK = CodedConcept(
    value="112171",
    meaning="Fiducial mark",
    scheme_designator="DCM"
)

JEJUNOSTOMY_TUBE = CodedConcept(
    value="A-26434",
    meaning="Jejunostomy tube",
    scheme_designator="SRT"
)

TRACHEOTOMY = CodedConcept(
    value="P1-26100",
    meaning="Tracheotomy",
    scheme_designator="SRT"
)

PROSTHESIS = CodedConcept(
    value="A-04000",
    meaning="Prosthesis",
    scheme_designator="SRT"
)

FEEDING_TUBE = CodedConcept(
    value="A-26430",
    meaning="Feeding tube",
    scheme_designator="SRT"
)

JEWELRY = CodedConcept(
    value="A-61000",
    meaning="Jewelry",
    scheme_designator="SRT"
)

SCAR_TISSUE = CodedConcept(
    value="M-78060",
    meaning="Scar tissue",
    scheme_designator="SRT"
)

CARDIAC_PACEMAKER = CodedConcept(
    value="A-11100",
    meaning="Cardiac Pacemaker",
    scheme_designator="SRT"
)

CERVICAL_COLLAR = CodedConcept(
    value="A-12210",
    meaning="Cervical collar",
    scheme_designator="SRT"
)

SUTURE = CodedConcept(
    value="A-13500",
    meaning="Suture",
    scheme_designator="SRT"
)

STAPLE = CodedConcept(
    value="A-13600",
    meaning="Staple",
    scheme_designator="SRT"
)

VENA_CAVA_FILTER = CodedConcept(
    value="A-14611",
    meaning="Vena cava filter",
    scheme_designator="SRT"
)

NEEDLE = CodedConcept(
    value="A-30360",
    meaning="Needle",
    scheme_designator="SRT"
)

CATHETER = CodedConcept(
    value="A-26800",
    meaning="Catheter",
    scheme_designator="SRT"
)

HEART_VALVE_PROSTHESIS = CodedConcept(
    value="A-04110",
    meaning="Heart valve prosthesis",
    scheme_designator="SRT"
)

CARDIAC_PACEMAKER_LEAD = CodedConcept(
    value="A-040CB",
    meaning="Cardiac pacemaker lead",
    scheme_designator="SRT"
)

ENDOTRACHEAL_TUBE = CodedConcept(
    value="A-25350",
    meaning="Endotracheal tube",
    scheme_designator="SRT"
)

PIN = CodedConcept(
    value="A-12024",
    meaning="Pin",
    scheme_designator="SRT"
)

BULLET = CodedConcept(
    value="A-32110",
    meaning="Bullet",
    scheme_designator="SRT"
)

URETERIC_STENT = CodedConcept(
    value="A-11C08",
    meaning="Ureteric stent",
    scheme_designator="SRT"
)

