"""CID 9231 WorkitemDefinition
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


NO_SUBSEQUENT_WORKITEMS = CodedConcept(
    value="110009",
    meaning="No subsequent Workitems",
    scheme_designator="DCM"
)

ADD_ADDENDUM_TO_REPORT = CodedConcept(
    value="128001",
    meaning="Add Addendum to Report",
    scheme_designator="DCM"
)

PRINT = CodedConcept(
    value="110008",
    meaning="Print",
    scheme_designator="DCM"
)

REPORT_VERIFICATION = CodedConcept(
    value="110007",
    meaning="Report Verification",
    scheme_designator="DCM"
)

TRANSCRIPTION = CodedConcept(
    value="110006",
    meaning="Transcription",
    scheme_designator="DCM"
)

INTERPRETATION = CodedConcept(
    value="110005",
    meaning="Interpretation",
    scheme_designator="DCM"
)

COMPUTER_AIDED_DETECTION = CodedConcept(
    value="110004",
    meaning="Computer Aided Detection",
    scheme_designator="DCM"
)

COMPUTER_AIDED_DIAGNOSIS = CodedConcept(
    value="110003",
    meaning="Computer Aided Diagnosis",
    scheme_designator="DCM"
)

QUALITY_CONTROL = CodedConcept(
    value="110002",
    meaning="Quality Control",
    scheme_designator="DCM"
)

MEDIA_IMPORT = CodedConcept(
    value="110013",
    meaning="Media Import",
    scheme_designator="DCM"
)

IMAGE_PROCESSING = CodedConcept(
    value="110001",
    meaning="Image Processing",
    scheme_designator="DCM"
)

