"""CID 8124 MicroscopyFilter
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


NO_FILTER = CodedConcept(
    value="111609",
    meaning="No filter",
    scheme_designator="DCM"
)

DE_S_NARMONT_COMPENSATOR = CodedConcept(
    value="A-00123",
    meaning="de Sénarmont compensator",
    scheme_designator="SRT"
)

RED_OPTICAL_FILTER = CodedConcept(
    value="A-010DF",
    meaning="Red optical filter",
    scheme_designator="SRT"
)

VIOLET_OPTICAL_FILTER = CodedConcept(
    value="A-010DE",
    meaning="Violet optical filter",
    scheme_designator="SRT"
)

HOFFMAN_MODULATOR = CodedConcept(
    value="A-00121",
    meaning="Hoffman modulator",
    scheme_designator="SRT"
)

ULTRAVIOLET_OPTICAL_FILTER = CodedConcept(
    value="A-010DD",
    meaning="Ultraviolet optical filter",
    scheme_designator="SRT"
)

CONDENSER_ANNULUS = CodedConcept(
    value="A-00120",
    meaning="Condenser annulus",
    scheme_designator="SRT"
)

DICHROIC_BEAMSPLITTER = CodedConcept(
    value="A-0010F",
    meaning="Dichroic beamsplitter",
    scheme_designator="SRT"
)

INFRARED_OPTICAL_FILTER = CodedConcept(
    value="A-010DC",
    meaning="Infrared optical filter",
    scheme_designator="SRT"
)

BLUE_OPTICAL_FILTER = CodedConcept(
    value="A-010DA",
    meaning="Blue optical filter",
    scheme_designator="SRT"
)

NOMARSKI_PRISM = CodedConcept(
    value="A-0011F",
    meaning="Nomarski prism",
    scheme_designator="SRT"
)

PHASE_CONTRAST_PLATE = CodedConcept(
    value="A-0011E",
    meaning="Phase contrast plate",
    scheme_designator="SRT"
)

DARKFIELD_STOP = CodedConcept(
    value="A-0011D",
    meaning="Darkfield stop",
    scheme_designator="SRT"
)

RHEINBERG_FILTER = CodedConcept(
    value="A-0011C",
    meaning="Rheinberg filter",
    scheme_designator="SRT"
)

GREEN_OPTICAL_FILTER = CodedConcept(
    value="A-010E2",
    meaning="Green optical filter",
    scheme_designator="SRT"
)

POLARIZING_OPTICAL_FILTER = CodedConcept(
    value="A-010E1",
    meaning="Polarizing optical filter",
    scheme_designator="SRT"
)

