"""CID 9514 AnatomicalStructuresforRadiotherapy
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


MARGINAL_CORONARY_ARTERY_LATERALS_1ST = CodedConcept(
    value="20A",
    meaning="1st Marginal Coronary Artery Laterals",
    scheme_designator="BARI"
)

MARGINAL_CORONARY_ARTERY_LATERALS_2ND = CodedConcept(
    value="21A",
    meaning="2nd Marginal Coronary Artery Laterals",
    scheme_designator="BARI"
)

MARGINAL_CORONARY_ARTERY_LATERALS_3RD = CodedConcept(
    value="22A",
    meaning="3rd Marginal Coronary Artery Laterals",
    scheme_designator="BARI"
)

DIAGONAL_CORONARY_ARTERY_LATERALS_1ST = CodedConcept(
    value="15A",
    meaning="1st Diagonal Coronary Artery Laterals",
    scheme_designator="BARI"
)

DIAGONAL_CORONARY_ARTERY_LATERALS_2ND = CodedConcept(
    value="16A",
    meaning="2nd Diagonal Coronary Artery Laterals",
    scheme_designator="BARI"
)

RAMUS_LATERALS = CodedConcept(
    value="28A",
    meaning="Ramus Laterals",
    scheme_designator="BARI"
)

DIAGONAL_CORONARY_ARTERY_LATERALS_3RD = CodedConcept(
    value="29A",
    meaning="3rd Diagonal Coronary Artery Laterals",
    scheme_designator="BARI"
)

POSTERIOR_DESCENDING_SEPTAL_PERFORATORS = CodedConcept(
    value="9",
    meaning="Posterior descending septal perforators",
    scheme_designator="BARI"
)

PHANTOM = CodedConcept(
    value="113681",
    meaning="Phantom",
    scheme_designator="DCM"
)

AORTIC_KNOB = CodedConcept(
    value="112102",
    meaning="Aortic knob",
    scheme_designator="DCM"
)

ARCH_OF_THE_AZYGOS_VEIN = CodedConcept(
    value="112103",
    meaning="Arch of the Azygos vein",
    scheme_designator="DCM"
)

SECONDARY_PULMONARY_LOBULE = CodedConcept(
    value="112054",
    meaning="Secondary pulmonary lobule",
    scheme_designator="DCM"
)

HIATUS = CodedConcept(
    value="112095",
    meaning="Hiatus",
    scheme_designator="DCM"
)

AZYGOESOPHAGEAL_RECESS_INTERFACE = CodedConcept(
    value="112090",
    meaning="Azygoesophageal recess interface",
    scheme_designator="DCM"
)

PARASPINAL_LINE = CodedConcept(
    value="112091",
    meaning="Paraspinal line",
    scheme_designator="DCM"
)

POSTERIOR_TRACHEAL_STRIPE = CodedConcept(
    value="112092",
    meaning="Posterior tracheal stripe",
    scheme_designator="DCM"
)

RIGHT_TRACHEAL_STRIPE = CodedConcept(
    value="112093",
    meaning="Right tracheal stripe",
    scheme_designator="DCM"
)

STRIPE = CodedConcept(
    value="112094",
    meaning="Stripe",
    scheme_designator="DCM"
)

MIDLUNG_WINDOW = CodedConcept(
    value="112085",
    meaning="Midlung window",
    scheme_designator="DCM"
)

CARINA_ANGLE = CodedConcept(
    value="112086",
    meaning="Carina angle",
    scheme_designator="DCM"
)

CENTRILOBULAR_STRUCTURES = CodedConcept(
    value="112087",
    meaning="Centrilobular structures",
    scheme_designator="DCM"
)

ANTERIOR_JUNCTION_LINE = CodedConcept(
    value="112088",
    meaning="Anterior junction line",
    scheme_designator="DCM"
)

POSTERIOR_JUNCTION_LINE = CodedConcept(
    value="112089",
    meaning="Posterior junction line",
    scheme_designator="DCM"
)

SURFACE_OF_THE_CHOROIDSCLERA_INTERFACE = CodedConcept(
    value="128301",
    meaning="Surface of the choroid-sclera interface",
    scheme_designator="DCM"
)

OUTER_SURFACE_OF_THE_BM = CodedConcept(
    value="128300",
    meaning="Outer surface of the BM",
    scheme_designator="DCM"
)

OUTER_SURFACE_OF_THE_CC = CodedConcept(
    value="128302",
    meaning="Outer surface of the CC",
    scheme_designator="DCM"
)

POSTERIOR_SURFACE_OF_THE_RPE = CodedConcept(
    value="128299",
    meaning="Posterior surface of the RPE",
    scheme_designator="DCM"
)

SURFACE_OF_THE_CENTER_OF_THE_RPE = CodedConcept(
    value="128298",
    meaning="Surface of the center of the RPE",
    scheme_designator="DCM"
)

OUTER_SURFACE_OF_IPL = CodedConcept(
    value="128291",
    meaning="Outer surface of IPL",
    scheme_designator="DCM"
)

OUTER_SURFACE_OF_GCL = CodedConcept(
    value="128290",
    meaning="Outer surface of GCL",
    scheme_designator="DCM"
)

OUTER_SURFACE_OF_OPL = CodedConcept(
    value="128293",
    meaning="Outer surface of OPL",
    scheme_designator="DCM"
)

OUTER_SURFACE_OF_INL = CodedConcept(
    value="128292",
    meaning="Outer surface of INL",
    scheme_designator="DCM"
)

SURFACE_BETWEEN_INNER_AND_OUTER_SEGMENTS_OF_THE_PHOTORECEPTORS = CodedConcept(
    value="128295",
    meaning="Surface between Inner and Outer Segments of the photoreceptors",
    scheme_designator="DCM"
)

OUTER_SURFACE_OF_HFL = CodedConcept(
    value="128294",
    meaning="Outer surface of HFL",
    scheme_designator="DCM"
)

ANTERIOR_SURFACE_OF_THE_RPE = CodedConcept(
    value="128297",
    meaning="Anterior surface of the RPE",
    scheme_designator="DCM"
)

SURFACE_OF_THE_INTERDIGITATING_ZONE_BETWEEN_RETINA_AND_RPE = CodedConcept(
    value="128296",
    meaning="Surface of the interdigitating zone between retina and RPE",
    scheme_designator="DCM"
)

OUTER_SURFACE_OF_RNFL = CodedConcept(
    value="128289",
    meaning="Outer surface of RNFL",
    scheme_designator="DCM"
)

ARCUATE_FASCICULUS = CodedConcept(
    value="276650",
    meaning="Arcuate Fasciculus",
    scheme_designator="FMA"
)

PROSTATE = CodedConcept(
    value="T-92000",
    meaning="Prostate",
    scheme_designator="SRT"
)

ANTERIOR_CARDIAC_VEIN = CodedConcept(
    value="T-48403",
    meaning="Anterior cardiac vein",
    scheme_designator="SRT"
)

PULMONARY_ARTERY_CONDUIT = CodedConcept(
    value="D4-33142",
    meaning="Pulmonary artery conduit",
    scheme_designator="SRT"
)

OCCIPITAL_ARTERY = CodedConcept(
    value="T-45250",
    meaning="Occipital artery",
    scheme_designator="SRT"
)

SPLENIC_ARTERY = CodedConcept(
    value="T-46460",
    meaning="Splenic artery",
    scheme_designator="SRT"
)

CAROTID_ARTERY = CodedConcept(
    value="T-45010",
    meaning="Carotid Artery",
    scheme_designator="SRT"
)

INFERIOR_RIGHT_PULMONARY_VEIN = CodedConcept(
    value="T-48520",
    meaning="Inferior right pulmonary vein",
    scheme_designator="SRT"
)

SUBCLAVIAN_ARTERY = CodedConcept(
    value="T-46100",
    meaning="Subclavian artery",
    scheme_designator="SRT"
)

COSTAL_CARTILAGE = CodedConcept(
    value="T-11240",
    meaning="Costal Cartilage",
    scheme_designator="SRT"
)

DELTOID_MUSCLE = CodedConcept(
    value="T-13660",
    meaning="Deltoid muscle",
    scheme_designator="SRT"
)

PARIETAL_BONE = CodedConcept(
    value="T-11120",
    meaning="Parietal bone",
    scheme_designator="SRT"
)

MUSCLE_OF_NECK = CodedConcept(
    value="T-13300",
    meaning="Muscle of neck",
    scheme_designator="SRT"
)

ILM_INTERNAL_LIMITING_MEMBRANE = CodedConcept(
    value="T-AA62D",
    meaning="ILM - Internal limiting membrane",
    scheme_designator="SRT"
)

ILEAL_VEIN = CodedConcept(
    value="G-0370",
    meaning="Ileal vein",
    scheme_designator="SRT"
)

DUODENUM = CodedConcept(
    value="T-58200",
    meaning="Duodenum",
    scheme_designator="SRT"
)

FEMALE_INTERNAL_GENITALIA = CodedConcept(
    value="T-80020",
    meaning="Female internal genitalia",
    scheme_designator="SRT"
)

SOLEAL_VEIN = CodedConcept(
    value="G-036B",
    meaning="Soleal vein",
    scheme_designator="SRT"
)

TRANSJUGULAR_INTRAHEPATIC_PORTOSYSTEMIC_SHUNT = CodedConcept(
    value="G-036C",
    meaning="Transjugular Intrahepatic Portosystemic Shunt",
    scheme_designator="SRT"
)

PULMONARY_VALVE = CodedConcept(
    value="T-35200",
    meaning="Pulmonary valve",
    scheme_designator="SRT"
)

GIACOMINI_VEIN = CodedConcept(
    value="G-036F",
    meaning="Giacomini vein",
    scheme_designator="SRT"
)

KNEE = CodedConcept(
    value="T-D9200",
    meaning="Knee",
    scheme_designator="SRT"
)

THROMBUS = CodedConcept(
    value="M-35001",
    meaning="Thrombus",
    scheme_designator="SRT"
)

INFERIOR_RIGHT_HEPATIC_VEIN = CodedConcept(
    value="G-036D",
    meaning="Inferior Right Hepatic Vein",
    scheme_designator="SRT"
)

POSTERIOR_ARCH_VEIN = CodedConcept(
    value="G-036E",
    meaning="Posterior arch vein",
    scheme_designator="SRT"
)

LEFT_INGUINAL_REGION = CodedConcept(
    value="T-D7020",
    meaning="Left inguinal region",
    scheme_designator="SRT"
)

ANTERIORMIDDLE_CEREBRAL_ARTERY_BIFURCATION = CodedConcept(
    value="G-0368",
    meaning="Anterior-Middle Cerebral Artery Bifurcation",
    scheme_designator="SRT"
)

ANTERIORPOSTERIOR_CEREBRAL_ARTERY_BIFURCATION = CodedConcept(
    value="G-0369",
    meaning="Anterior-Posterior Cerebral Artery Bifurcation",
    scheme_designator="SRT"
)

SMALLEST_CARDIAC_VEIN = CodedConcept(
    value="T-48405",
    meaning="Smallest Cardiac Vein",
    scheme_designator="SRT"
)

INFERIOR_CEREBELLAR_PEDUNCLE = CodedConcept(
    value="T-A6640",
    meaning="Inferior cerebellar peduncle",
    scheme_designator="SRT"
)

VENTRICULAR_VEIN = CodedConcept(
    value="T-48404",
    meaning="Ventricular Vein",
    scheme_designator="SRT"
)

ATRIOVENTRICULAR_VEIN = CodedConcept(
    value="T-48407",
    meaning="Atrioventricular Vein",
    scheme_designator="SRT"
)

ATRIAL_VEIN = CodedConcept(
    value="T-48406",
    meaning="Atrial Vein",
    scheme_designator="SRT"
)

FIFTH_LUMBAR_ARTERY = CodedConcept(
    value="G-0362",
    meaning="Fifth Lumbar Artery",
    scheme_designator="SRT"
)

SIXTH_LUMBAR_ARTERY = CodedConcept(
    value="G-0363",
    meaning="Sixth Lumbar Artery",
    scheme_designator="SRT"
)

PARANASAL_SINUS = CodedConcept(
    value="T-22000",
    meaning="Paranasal sinus",
    scheme_designator="SRT"
)

THIRD_LUMBAR_ARTERY = CodedConcept(
    value="G-0360",
    meaning="Third Lumbar Artery",
    scheme_designator="SRT"
)

FOURTH_LUMBAR_ARTERY = CodedConcept(
    value="G-0361",
    meaning="Fourth Lumbar Artery",
    scheme_designator="SRT"
)

PROFUNDA_FEMORIS_ARTERY = CodedConcept(
    value="T-47440",
    meaning="Profunda Femoris Artery",
    scheme_designator="SRT"
)

SAPHENOFEMORAL_JUNCTION = CodedConcept(
    value="T-D930A",
    meaning="Saphenofemoral junction",
    scheme_designator="SRT"
)

SUPERIOR_PHRENIC_ARTERY = CodedConcept(
    value="T-46350",
    meaning="Superior phrenic artery",
    scheme_designator="SRT"
)

POSTERIOR_TIBIAL_VEIN = CodedConcept(
    value="T-49620",
    meaning="Posterior Tibial Vein",
    scheme_designator="SRT"
)

TESTICULAR_VEIN = CodedConcept(
    value="T-48770",
    meaning="Testicular Vein",
    scheme_designator="SRT"
)

CORONARY_SINUS = CodedConcept(
    value="T-48410",
    meaning="Coronary sinus",
    scheme_designator="SRT"
)

ULNAR_ARTERY = CodedConcept(
    value="T-47200",
    meaning="Ulnar artery",
    scheme_designator="SRT"
)

SUPERIOR_LEFT_PULMONARY_VEIN = CodedConcept(
    value="T-48530",
    meaning="Superior left pulmonary vein",
    scheme_designator="SRT"
)

SPLENIC_VEIN = CodedConcept(
    value="T-48890",
    meaning="Splenic vein",
    scheme_designator="SRT"
)

SUBSCAPULARIS_MUSCLE = CodedConcept(
    value="T-13650",
    meaning="Subscapularis muscle",
    scheme_designator="SRT"
)

HIP_JOINT = CodedConcept(
    value="T-15710",
    meaning="Hip joint",
    scheme_designator="SRT"
)

FRONTAL_BONE = CodedConcept(
    value="T-11110",
    meaning="Frontal bone",
    scheme_designator="SRT"
)

SUPERFICIAL_FEMORAL_VEIN = CodedConcept(
    value="G-035A",
    meaning="Superficial Femoral Vein",
    scheme_designator="SRT"
)

STOMACH = CodedConcept(
    value="T-57000",
    meaning="Stomach",
    scheme_designator="SRT"
)

COMMON_FEMORAL_VEIN = CodedConcept(
    value="G-035B",
    meaning="Common Femoral Vein",
    scheme_designator="SRT"
)

VULVA = CodedConcept(
    value="T-81000",
    meaning="Vulva",
    scheme_designator="SRT"
)

AORTIC_FISTULA = CodedConcept(
    value="D3-81922",
    meaning="Aortic fistula",
    scheme_designator="SRT"
)

AXILLA = CodedConcept(
    value="T-D8104",
    meaning="Axilla",
    scheme_designator="SRT"
)

FIRST_LUMBAR_ARTERY = CodedConcept(
    value="G-035E",
    meaning="First Lumbar Artery",
    scheme_designator="SRT"
)

SECOND_LUMBAR_ARTERY = CodedConcept(
    value="G-035F",
    meaning="Second Lumbar Artery",
    scheme_designator="SRT"
)

HILAR_ARTERY = CodedConcept(
    value="G-035C",
    meaning="Hilar Artery",
    scheme_designator="SRT"
)

POPLITEAL_FOSSA = CodedConcept(
    value="T-D9310",
    meaning="Popliteal fossa",
    scheme_designator="SRT"
)

RIGHT_INGUINAL_REGION = CodedConcept(
    value="T-D7010",
    meaning="Right inguinal region",
    scheme_designator="SRT"
)

COLON = CodedConcept(
    value="T-59300",
    meaning="Colon",
    scheme_designator="SRT"
)

LUMBOSACRAL_SPINE = CodedConcept(
    value="T-D00F9",
    meaning="Lumbo-sacral spine",
    scheme_designator="SRT"
)

THORACOLUMBAR_SPINE = CodedConcept(
    value="T-D00F8",
    meaning="Thoraco-lumbar spine",
    scheme_designator="SRT"
)

CERVICOTHORACIC_SPINE = CodedConcept(
    value="T-D00F7",
    meaning="Cervico-thoracic spine",
    scheme_designator="SRT"
)

INTERNAL_MAMMARY_ARTERY = CodedConcept(
    value="T-46200",
    meaning="Internal mammary artery",
    scheme_designator="SRT"
)

INNOMINATE_VEIN = CodedConcept(
    value="T-48620",
    meaning="Innominate vein",
    scheme_designator="SRT"
)

RIGHT_FEMORAL_ARTERY = CodedConcept(
    value="T-47410",
    meaning="Right femoral artery",
    scheme_designator="SRT"
)

SKIN_OF_CHEST = CodedConcept(
    value="T-02424",
    meaning="Skin of chest",
    scheme_designator="SRT"
)

LEFT_PULMONARY_VEIN = CodedConcept(
    value="T-48502",
    meaning="Left Pulmonary Vein",
    scheme_designator="SRT"
)

RIGHT_PULMONARY_VEIN = CodedConcept(
    value="T-48501",
    meaning="Right Pulmonary Vein",
    scheme_designator="SRT"
)

ELM_EXTERNAL_LIMITING_MEMBRANE = CodedConcept(
    value="T-AA650",
    meaning="ELM - External limiting membrane",
    scheme_designator="SRT"
)

EYEBALL = CodedConcept(
    value="T-AA770",
    meaning="Eyeball",
    scheme_designator="SRT"
)

LINGUAL_ARTERY = CodedConcept(
    value="T-45230",
    meaning="Lingual artery",
    scheme_designator="SRT"
)

RENAL_VEIN = CodedConcept(
    value="T-48740",
    meaning="Renal vein",
    scheme_designator="SRT"
)

GASTRODUODENAL_ARTERY = CodedConcept(
    value="T-46440",
    meaning="Gastroduodenal Artery",
    scheme_designator="SRT"
)

PERINEUM = CodedConcept(
    value="T-D2700",
    meaning="Perineum",
    scheme_designator="SRT"
)

OCCIPITAL_BONE = CodedConcept(
    value="T-11140",
    meaning="Occipital bone",
    scheme_designator="SRT"
)

DESCENDING_AORTA = CodedConcept(
    value="T-D0765",
    meaning="Descending aorta",
    scheme_designator="SRT"
)

ESOPHAGUS = CodedConcept(
    value="T-56000",
    meaning="Esophagus",
    scheme_designator="SRT"
)

NASOPHARYNX = CodedConcept(
    value="T-2300C",
    meaning="Nasopharynx",
    scheme_designator="SRT"
)

NASAL_BONE = CodedConcept(
    value="T-11149",
    meaning="Nasal bone",
    scheme_designator="SRT"
)

TRICUSPID_VALVE = CodedConcept(
    value="T-35100",
    meaning="Tricuspid Valve",
    scheme_designator="SRT"
)

ARCUATE_ARTERY_OF_THE_KIDNEY = CodedConcept(
    value="T-4668A",
    meaning="Arcuate Artery of the Kidney",
    scheme_designator="SRT"
)

SUBMENTAL = CodedConcept(
    value="T-D161E",
    meaning="Submental",
    scheme_designator="SRT"
)

THIGH = CodedConcept(
    value="T-D9100",
    meaning="Thigh",
    scheme_designator="SRT"
)

PULMONARY_CHAMBER_OF_COR_TRIATRIATUM = CodedConcept(
    value="T-32190",
    meaning="Pulmonary chamber of cor triatriatum",
    scheme_designator="SRT"
)

THALAMUS = CodedConcept(
    value="T-A4000",
    meaning="Thalamus",
    scheme_designator="SRT"
)

ANOMALOUS_PULMONARY_VEIN = CodedConcept(
    value="T-48503",
    meaning="Anomalous pulmonary vein",
    scheme_designator="SRT"
)

RADIAL_ARTERY = CodedConcept(
    value="T-47300",
    meaning="Radial artery",
    scheme_designator="SRT"
)

SUPERIOR_RIGHT_PULMONARY_VEIN = CodedConcept(
    value="T-48510",
    meaning="Superior right pulmonary vein",
    scheme_designator="SRT"
)

SEMINAL_VESICLE = CodedConcept(
    value="T-93000",
    meaning="Seminal Vesicle",
    scheme_designator="SRT"
)

APEX_OF_LUNG = CodedConcept(
    value="T-280A0",
    meaning="Apex of Lung",
    scheme_designator="SRT"
)

SUBMANDIBULAR_AREA = CodedConcept(
    value="T-D1603",
    meaning="Submandibular area",
    scheme_designator="SRT"
)

FACIAL_ARTERY = CodedConcept(
    value="T-45240",
    meaning="Facial artery",
    scheme_designator="SRT"
)

LEFT_FEMORAL_ARTERY = CodedConcept(
    value="T-47420",
    meaning="Left femoral artery",
    scheme_designator="SRT"
)

PERICARDIOPHRENIC_ARTERY = CodedConcept(
    value="T-46210",
    meaning="Pericardiophrenic Artery",
    scheme_designator="SRT"
)

NECK = CodedConcept(
    value="T-D1600",
    meaning="Neck",
    scheme_designator="SRT"
)

ILIUM = CodedConcept(
    value="T-12340",
    meaning="Ilium",
    scheme_designator="SRT"
)

TEMPORAL_BONE = CodedConcept(
    value="T-11130",
    meaning="Temporal bone",
    scheme_designator="SRT"
)

VERTEBRAL_COLUMN_AND_CRANIUM = CodedConcept(
    value="T-11011",
    meaning="Vertebral column and cranium",
    scheme_designator="SRT"
)

FASCIAL_LAYER = CodedConcept(
    value="T-D0634",
    meaning="Fascial layer",
    scheme_designator="SRT"
)

MASTOID_BONE = CodedConcept(
    value="T-11133",
    meaning="Mastoid bone",
    scheme_designator="SRT"
)

STERNOCLEIDOMASTOID_MUSCLE = CodedConcept(
    value="T-13310",
    meaning="Sternocleidomastoid muscle",
    scheme_designator="SRT"
)

STERNOCLAVICULAR_JOINT = CodedConcept(
    value="T-15610",
    meaning="Sternoclavicular joint",
    scheme_designator="SRT"
)

CERVIX = CodedConcept(
    value="T-83200",
    meaning="Cervix",
    scheme_designator="SRT"
)

FISSURE_OF_LUNG = CodedConcept(
    value="T-D051D",
    meaning="Fissure of lung",
    scheme_designator="SRT"
)

UPPER_LIMB = CodedConcept(
    value="T-D8000",
    meaning="Upper limb",
    scheme_designator="SRT"
)

VASCULAR_SCLEROSIS = CodedConcept(
    value="M-520F8",
    meaning="Vascular sclerosis",
    scheme_designator="SRT"
)

MIDBRAIN = CodedConcept(
    value="T-A5100",
    meaning="Midbrain",
    scheme_designator="SRT"
)

LEFT_MAIN_BRONCHUS = CodedConcept(
    value="T-26500",
    meaning="Left main bronchus",
    scheme_designator="SRT"
)

POSTERIOR_MEDIAL_TRIBUTARY = CodedConcept(
    value="T-49535",
    meaning="Posterior medial tributary",
    scheme_designator="SRT"
)

SEGMENT_OF_LUNG = CodedConcept(
    value="T-280D0",
    meaning="Segment of lung",
    scheme_designator="SRT"
)

MALE_INTERNAL_GENITALIA = CodedConcept(
    value="T-90020",
    meaning="Male internal genitalia",
    scheme_designator="SRT"
)

FEMORAL_VEIN = CodedConcept(
    value="T-49410",
    meaning="Femoral vein",
    scheme_designator="SRT"
)

POPLITEAL_VEIN = CodedConcept(
    value="T-49650",
    meaning="Popliteal Vein",
    scheme_designator="SRT"
)

GREAT_SAPHENOUS_VEIN = CodedConcept(
    value="T-49530",
    meaning="Great saphenous vein",
    scheme_designator="SRT"
)

PALATINE_BONE = CodedConcept(
    value="T-11160",
    meaning="Palatine bone",
    scheme_designator="SRT"
)

EXTREMITY = CodedConcept(
    value="T-D0300",
    meaning="Extremity",
    scheme_designator="SRT"
)

RETROPERITONEAL_SPACE = CodedConcept(
    value="T-D4900",
    meaning="Retroperitoneal space",
    scheme_designator="SRT"
)

BUTTOCK = CodedConcept(
    value="T-D2600",
    meaning="Buttock",
    scheme_designator="SRT"
)

CAROTID_BULB = CodedConcept(
    value="T-45170",
    meaning="Carotid Bulb",
    scheme_designator="SRT"
)

MOUTH = CodedConcept(
    value="T-D0662",
    meaning="Mouth",
    scheme_designator="SRT"
)

THYROID = CodedConcept(
    value="T-B6000",
    meaning="Thyroid",
    scheme_designator="SRT"
)

MUSCLE_OF_HEAD = CodedConcept(
    value="T-13100",
    meaning="Muscle of head",
    scheme_designator="SRT"
)

ZYGOMA = CodedConcept(
    value="T-11166",
    meaning="Zygoma",
    scheme_designator="SRT"
)

UPPER_URINARY_TRACT = CodedConcept(
    value="T-7000B",
    meaning="Upper urinary tract",
    scheme_designator="SRT"
)

SMALL_INTESTINE = CodedConcept(
    value="T-58000",
    meaning="Small intestine",
    scheme_designator="SRT"
)

SUBMANDIBULAR_GLAND = CodedConcept(
    value="T-61300",
    meaning="Submandibular gland",
    scheme_designator="SRT"
)

SAPHENOPOPLITEAL_JUNCTION = CodedConcept(
    value="T-4941A",
    meaning="Saphenopopliteal junction",
    scheme_designator="SRT"
)

LOWER_LIMB = CodedConcept(
    value="T-D9000",
    meaning="Lower limb",
    scheme_designator="SRT"
)

LOWER_LOBE_OF_LUNG = CodedConcept(
    value="T-28830",
    meaning="Lower lobe of lung",
    scheme_designator="SRT"
)

CARINA = CodedConcept(
    value="T-25201",
    meaning="Carina",
    scheme_designator="SRT"
)

URINARY_SYSTEM = CodedConcept(
    value="T-70001",
    meaning="Urinary system",
    scheme_designator="SRT"
)

OCCIPITAL_VEIN = CodedConcept(
    value="T-48214",
    meaning="Occipital vein",
    scheme_designator="SRT"
)

COCKETT_S_PERFORATING_VEIN = CodedConcept(
    value="T-49426",
    meaning="Cockett's perforating vein",
    scheme_designator="SRT"
)

BOYD_S_PERFORATING_VEIN = CodedConcept(
    value="T-49424",
    meaning="Boyd's perforating vein",
    scheme_designator="SRT"
)

LARYNX = CodedConcept(
    value="T-24100",
    meaning="Larynx",
    scheme_designator="SRT"
)

SUBCLAVIAN_VEIN = CodedConcept(
    value="T-48330",
    meaning="Subclavian vein",
    scheme_designator="SRT"
)

PENIS = CodedConcept(
    value="T-91000",
    meaning="Penis",
    scheme_designator="SRT"
)

CORNEA = CodedConcept(
    value="T-AA200",
    meaning="Cornea",
    scheme_designator="SRT"
)

ANKLE_JOINT = CodedConcept(
    value="T-15750",
    meaning="Ankle joint",
    scheme_designator="SRT"
)

SCALENOUS_ANTERIOR_MUSCLE = CodedConcept(
    value="T-13450",
    meaning="Scalenous anterior muscle",
    scheme_designator="SRT"
)

SPHENOID_BONE = CodedConcept(
    value="T-11150",
    meaning="Sphenoid bone",
    scheme_designator="SRT"
)

PROFUNDA_FEMORIS_VEIN = CodedConcept(
    value="T-49660",
    meaning="Profunda Femoris Vein",
    scheme_designator="SRT"
)

SUPERFICIAL_PALMAR_ARCH = CodedConcept(
    value="T-47240",
    meaning="Superficial Palmar Arch",
    scheme_designator="SRT"
)

ETHMOID_BONE = CodedConcept(
    value="T-11156",
    meaning="Ethmoid bone",
    scheme_designator="SRT"
)

SUPRACLAVICULAR_REGION_OF_NECK = CodedConcept(
    value="T-D1620",
    meaning="Supraclavicular region of neck",
    scheme_designator="SRT"
)

MUSCLE_OF_LOWER_LIMB = CodedConcept(
    value="T-14668",
    meaning="Muscle of lower limb",
    scheme_designator="SRT"
)

GASTROCNEMIUS_VEIN = CodedConcept(
    value="T-4942D",
    meaning="Gastrocnemius vein",
    scheme_designator="SRT"
)

HUNTERIAN_PERFORATING_VEIN = CodedConcept(
    value="T-4942A",
    meaning="Hunterian perforating vein",
    scheme_designator="SRT"
)

LACRIMAL_BONE = CodedConcept(
    value="T-1115A",
    meaning="Lacrimal bone",
    scheme_designator="SRT"
)

AUTONOMIC_NERVE = CodedConcept(
    value="T-A9605",
    meaning="Autonomic nerve",
    scheme_designator="SRT"
)

DODD_S_PERFORATING_VEIN = CodedConcept(
    value="T-49429",
    meaning="Dodd's perforating vein",
    scheme_designator="SRT"
)

UPPER_LOBE_OF_LUNG = CodedConcept(
    value="T-28820",
    meaning="Upper lobe of lung",
    scheme_designator="SRT"
)

INFERIOR_LEFT_PULMONARY_VEIN = CodedConcept(
    value="T-48540",
    meaning="Inferior left pulmonary vein",
    scheme_designator="SRT"
)

ANTERIOR_TIBIAL_VEIN = CodedConcept(
    value="T-49630",
    meaning="Anterior Tibial Vein",
    scheme_designator="SRT"
)

MANDIBLE = CodedConcept(
    value="T-11180",
    meaning="Mandible",
    scheme_designator="SRT"
)

GREAT_CARDIAC_VEIN = CodedConcept(
    value="T-48420",
    meaning="Great cardiac vein",
    scheme_designator="SRT"
)

MIDDLE_EAR = CodedConcept(
    value="T-AB300",
    meaning="Middle ear",
    scheme_designator="SRT"
)

ACROMIOCLAVICULAR_JOINT = CodedConcept(
    value="T-15420",
    meaning="Acromioclavicular joint",
    scheme_designator="SRT"
)

SUPERFICIAL_TEMPORAL_ARTERY = CodedConcept(
    value="T-45270",
    meaning="Superficial temporal artery",
    scheme_designator="SRT"
)

OVARIAN_VEIN = CodedConcept(
    value="T-48780",
    meaning="Ovarian vein",
    scheme_designator="SRT"
)

PLANTAR_ARTERIAL_ARCH = CodedConcept(
    value="T-47690",
    meaning="Plantar Arterial Arch",
    scheme_designator="SRT"
)

VAGUS_NERVE = CodedConcept(
    value="T-A8640",
    meaning="Vagus nerve",
    scheme_designator="SRT"
)

CHORDAE_TENDINEAE_CORDIS = CodedConcept(
    value="T-35020",
    meaning="Chordae tendineae cordis",
    scheme_designator="SRT"
)

BRAIN_STEM = CodedConcept(
    value="T-D0558",
    meaning="Brain stem",
    scheme_designator="SRT"
)

SMALL_CARDIAC_VEIN = CodedConcept(
    value="T-48435",
    meaning="Small Cardiac Vein",
    scheme_designator="SRT"
)

MIDDLE_CARDIAC_VEIN = CodedConcept(
    value="T-48430",
    meaning="Middle Cardiac Vein",
    scheme_designator="SRT"
)

THYROCERVICAL_TRUNK = CodedConcept(
    value="T-46130",
    meaning="Thyrocervical trunk",
    scheme_designator="SRT"
)

PARATHYROID = CodedConcept(
    value="T-B7000",
    meaning="Parathyroid",
    scheme_designator="SRT"
)

INNOMINATE_ARTERY = CodedConcept(
    value="T-46010",
    meaning="Innominate artery",
    scheme_designator="SRT"
)

DEEP_PALMAR_ARCH_OF_RADIAL_ARTERY = CodedConcept(
    value="T-47340",
    meaning="Deep Palmar Arch of Radial Artery",
    scheme_designator="SRT"
)

MAXILLA = CodedConcept(
    value="T-11170",
    meaning="Maxilla",
    scheme_designator="SRT"
)

TRACHEA_AND_BRONCHUS = CodedConcept(
    value="T-DD006",
    meaning="Trachea and bronchus",
    scheme_designator="SRT"
)

AXILLARY_ARTERY = CodedConcept(
    value="T-47100",
    meaning="Axillary Artery",
    scheme_designator="SRT"
)

PERONEAL_VEIN = CodedConcept(
    value="T-49640",
    meaning="Peroneal Vein",
    scheme_designator="SRT"
)

TARSAL_JOINT = CodedConcept(
    value="T-15770",
    meaning="Tarsal joint",
    scheme_designator="SRT"
)

CAROTID_BIFURCATION = CodedConcept(
    value="T-45160",
    meaning="Carotid Bifurcation",
    scheme_designator="SRT"
)

INTRACRANIAL = CodedConcept(
    value="T-D1400",
    meaning="Intracranial",
    scheme_designator="SRT"
)

FEMALE_EXTERNAL_GENITALIA = CodedConcept(
    value="T-80010",
    meaning="Female external genitalia",
    scheme_designator="SRT"
)

SAPHENOUS_VEIN = CodedConcept(
    value="T-4940B",
    meaning="Saphenous vein",
    scheme_designator="SRT"
)

THYMUS = CodedConcept(
    value="T-C8000",
    meaning="Thymus",
    scheme_designator="SRT"
)

PULMONARY_VALVE_SINUSES = CodedConcept(
    value="T-35250",
    meaning="pulmonary valve sinuses",
    scheme_designator="SRT"
)

BLADDER_AND_URETHRA = CodedConcept(
    value="T-DD123",
    meaning="Bladder and urethra",
    scheme_designator="SRT"
)

ANTERIOR_COMMUNICATING_ARTERY = CodedConcept(
    value="T-45530",
    meaning="Anterior communicating artery",
    scheme_designator="SRT"
)

INTERNAL_ILIAC_ARTERY = CodedConcept(
    value="T-46740",
    meaning="Internal iliac artery",
    scheme_designator="SRT"
)

COMMON_ILIAC_VEIN = CodedConcept(
    value="T-48920",
    meaning="Common iliac vein",
    scheme_designator="SRT"
)

LACRIMAL_ARTERY = CodedConcept(
    value="T-45410",
    meaning="Lacrimal artery",
    scheme_designator="SRT"
)

MESENTERIC_ARTERY = CodedConcept(
    value="T-46500",
    meaning="Mesenteric artery",
    scheme_designator="SRT"
)

EXTERNAL_AUDITORY_CANAL = CodedConcept(
    value="T-AB200",
    meaning="External auditory canal",
    scheme_designator="SRT"
)

DISTAL_LEFT_ANTERIOR_DESCENDING_CORONARY_ARTERY = CodedConcept(
    value="T-43112",
    meaning="Distal Left Anterior Descending Coronary Artery",
    scheme_designator="SRT"
)

BAFFLE = CodedConcept(
    value="A-00203",
    meaning="Baffle",
    scheme_designator="SRT"
)

RIGHT_PULMONARY_ARTERY = CodedConcept(
    value="T-44200",
    meaning="Right pulmonary artery",
    scheme_designator="SRT"
)

PROXIMAL_LEFT_ANTERIOR_DESCENDING_CORONARY_ARTERY = CodedConcept(
    value="T-43111",
    meaning="Proximal Left Anterior Descending Coronary Artery",
    scheme_designator="SRT"
)

SCLERA = CodedConcept(
    value="T-AA110",
    meaning="Sclera",
    scheme_designator="SRT"
)

LEFT_ANTERIOR_DESCENDING_CORONARY_ARTERY = CodedConcept(
    value="T-43110",
    meaning="Left Anterior Descending Coronary Artery",
    scheme_designator="SRT"
)

MARGINAL_CORONARY_ARTERY = CodedConcept(
    value="T-43230",
    meaning="Marginal Coronary Artery",
    scheme_designator="SRT"
)

OVARIAN_ARTERY = CodedConcept(
    value="T-46980",
    meaning="Ovarian Artery",
    scheme_designator="SRT"
)

MIDDLE_CEREBRAL_ARTERY_M1_SEGMENT = CodedConcept(
    value="R-1024F",
    meaning="Middle Cerebral Artery M1 Segment",
    scheme_designator="SRT"
)

PATELLA = CodedConcept(
    value="T-12730",
    meaning="Patella",
    scheme_designator="SRT"
)

HILUM_OF_LUNG = CodedConcept(
    value="T-28080",
    meaning="Hilum of lung",
    scheme_designator="SRT"
)

SYMPATHETIC_TRUNK = CodedConcept(
    value="T-A9630",
    meaning="Sympathetic trunk",
    scheme_designator="SRT"
)

RIGHT_AURICULAR_APPENDAGE = CodedConcept(
    value="T-32210",
    meaning="Right auricular appendage",
    scheme_designator="SRT"
)

CEREBELLUM = CodedConcept(
    value="T-A6000",
    meaning="Cerebellum",
    scheme_designator="SRT"
)

ILEUM = CodedConcept(
    value="T-58600",
    meaning="Ileum",
    scheme_designator="SRT"
)

SYSTEMIC_ARTERY = CodedConcept(
    value="T-4105E",
    meaning="Systemic artery",
    scheme_designator="SRT"
)

MEDIAL_LEMNISCUS = CodedConcept(
    value="T-A5271",
    meaning="Medial Lemniscus",
    scheme_designator="SRT"
)

LACRIMAL_ARTERY_OF_RIGHT_EYE = CodedConcept(
    value="T-45416",
    meaning="Lacrimal artery of right eye",
    scheme_designator="SRT"
)

MID_LEFT_ANTERIOR_DESCENDING_CORONARY_ARTERY = CodedConcept(
    value="T-43115",
    meaning="Mid Left Anterior Descending Coronary Artery",
    scheme_designator="SRT"
)

DIAGONAL_CORONARY_ARTERY_3RD = CodedConcept(
    value="T-43119",
    meaning="3rd diagonal Coronary Artery",
    scheme_designator="SRT"
)

DIAGONAL_CORONARY_ARTERY_2ND = CodedConcept(
    value="T-43118",
    meaning="2nd Diagonal Coronary Artery",
    scheme_designator="SRT"
)

DIAGONAL_CORONARY_ARTERY_1ST = CodedConcept(
    value="T-43117",
    meaning="1st Diagonal Coronary Artery",
    scheme_designator="SRT"
)

ANTERIOR_CEREBRAL_ARTERY = CodedConcept(
    value="T-45540",
    meaning="Anterior Cerebral Artery",
    scheme_designator="SRT"
)

INTERNAL_CAROTID_ARTERY = CodedConcept(
    value="T-45300",
    meaning="Internal carotid artery",
    scheme_designator="SRT"
)

PORTAL_VEIN = CodedConcept(
    value="T-48810",
    meaning="Portal vein",
    scheme_designator="SRT"
)

POSTERIOR_TIBIAL_ARTERY = CodedConcept(
    value="T-47600",
    meaning="Posterior tibial artery",
    scheme_designator="SRT"
)

SUPERIOR_MESENTERIC_ARTERY = CodedConcept(
    value="T-46510",
    meaning="Superior mesenteric artery",
    scheme_designator="SRT"
)

GREAT_SAPHENOUS_VEIN_OF_THIGH = CodedConcept(
    value="R-10259",
    meaning="Great Saphenous Vein of Thigh",
    scheme_designator="SRT"
)

EXTERNAL_ILIAC_VEIN = CodedConcept(
    value="T-48930",
    meaning="External iliac vein",
    scheme_designator="SRT"
)

COMMON_ILIAC_ARTERY_BIFURCATION = CodedConcept(
    value="R-10258",
    meaning="Common Iliac Artery Bifurcation",
    scheme_designator="SRT"
)

CORONARY_ARTERY_GRAFT = CodedConcept(
    value="T-41065",
    meaning="Coronary Artery Graft",
    scheme_designator="SRT"
)

SEPTAL_CORONARY_ARTERY_1ST = CodedConcept(
    value="T-43002",
    meaning="1st Septal Coronary Artery",
    scheme_designator="SRT"
)

PANCREATIC_DUCT = CodedConcept(
    value="T-65010",
    meaning="Pancreatic duct",
    scheme_designator="SRT"
)

EYE = CodedConcept(
    value="T-AA000",
    meaning="Eye",
    scheme_designator="SRT"
)

DISTAL_CIRCUMFLEX_CORONARY_ARTERY = CodedConcept(
    value="T-43122",
    meaning="Distal Circumflex Coronary Artery",
    scheme_designator="SRT"
)

CORONARY_ARTERY = CodedConcept(
    value="T-43000",
    meaning="Coronary artery",
    scheme_designator="SRT"
)

PROXIMAL_CIRCUMFLEX_CORONARY_ARTERY = CodedConcept(
    value="T-43121",
    meaning="Proximal Circumflex Coronary Artery",
    scheme_designator="SRT"
)

CIRCUMFLEX_CORONARY_ARTERY = CodedConcept(
    value="T-43120",
    meaning="Circumflex Coronary Artery",
    scheme_designator="SRT"
)

GREAT_SAPHENOUS_VEIN_OF_CALF = CodedConcept(
    value="R-1025A",
    meaning="Great Saphenous Vein of Calf",
    scheme_designator="SRT"
)

SUBSTANTIA_NIGRA = CodedConcept(
    value="T-A5160",
    meaning="Substantia nigra",
    scheme_designator="SRT"
)

VERTEBRA = CodedConcept(
    value="T-11510",
    meaning="Vertebra",
    scheme_designator="SRT"
)

RIGHT_ATRIUM = CodedConcept(
    value="T-32200",
    meaning="Right atrium",
    scheme_designator="SRT"
)

LEFT_POSTEROLATERAL_CORONARY_ARTERY_2ND = CodedConcept(
    value="T-4312C",
    meaning="2nd Left Posterolateral Coronary Artery",
    scheme_designator="SRT"
)

LEFT_POSTEROLATERAL_CORONARY_ARTERY_1ST = CodedConcept(
    value="T-4312B",
    meaning="1st Left Posterolateral Coronary Artery",
    scheme_designator="SRT"
)

MARGINAL_CORONARY_ARTERY_3RD = CodedConcept(
    value="T-4312A",
    meaning="3rd Marginal Coronary Artery",
    scheme_designator="SRT"
)

TOOTH = CodedConcept(
    value="T-54010",
    meaning="Tooth",
    scheme_designator="SRT"
)

MID_CIRCUMFLEX_CORONARY_ARTERY = CodedConcept(
    value="T-43127",
    meaning="Mid Circumflex Coronary Artery",
    scheme_designator="SRT"
)

POSTERIOR_CEREBRAL_ARTERY_P1_SEGMENT = CodedConcept(
    value="R-10253",
    meaning="Posterior Cerebral Artery P1 Segment",
    scheme_designator="SRT"
)

LEFT_POSTEROLATERAL_CIRCUMFLEX_CORONARY_ARTERY = CodedConcept(
    value="T-43125",
    meaning="Left Posterolateral Circumflex Coronary Artery",
    scheme_designator="SRT"
)

CAROTID_SIPHON = CodedConcept(
    value="T-45308",
    meaning="Carotid Siphon",
    scheme_designator="SRT"
)

MIDDLE_CEREBRAL_ARTERY_M2_SEGMENT = CodedConcept(
    value="R-10251",
    meaning="Middle Cerebral Artery M2 Segment",
    scheme_designator="SRT"
)

ILIAC_AND_OR_FEMORAL_ARTERY = CodedConcept(
    value="T-41068",
    meaning="Iliac and/or femoral artery",
    scheme_designator="SRT"
)

AV_GROOVE_CONTINUATION_OF_CIRCUMFLEX_ARTERY = CodedConcept(
    value="T-43124",
    meaning="AV groove continuation of Circumflex Artery",
    scheme_designator="SRT"
)

INTERMEDIATE_ARTERY_RAMUS_ = CodedConcept(
    value="T-43003",
    meaning="Intermediate Artery (Ramus)",
    scheme_designator="SRT"
)

PHARYNX_AND_LARYNX = CodedConcept(
    value="T-20101",
    meaning="Pharynx and larynx",
    scheme_designator="SRT"
)

MARGINAL_CORONARY_ARTERY_2ND = CodedConcept(
    value="T-43129",
    meaning="2nd Marginal Coronary Artery",
    scheme_designator="SRT"
)

LEFT_MAIN_BRANCH_OF_PORTAL_VEIN = CodedConcept(
    value="T-48814",
    meaning="Left Main Branch of Portal Vein",
    scheme_designator="SRT"
)

POSTERIOR_CEREBRAL_ARTERY_P2_SEGMENT = CodedConcept(
    value="R-10255",
    meaning="Posterior Cerebral Artery P2 Segment",
    scheme_designator="SRT"
)

MARGINAL_CORONARY_ARTERY_1ST = CodedConcept(
    value="T-43128",
    meaning="1st Marginal Coronary Artery",
    scheme_designator="SRT"
)

RIGHT_MAIN_BRANCH_OF_PORTAL_VEIN = CodedConcept(
    value="T-48813",
    meaning="Right Main Branch of Portal Vein",
    scheme_designator="SRT"
)

VOMER_BONE = CodedConcept(
    value="T-21342",
    meaning="Vomer bone",
    scheme_designator="SRT"
)

LUMBAR_ARTERY = CodedConcept(
    value="T-46960",
    meaning="Lumbar artery",
    scheme_designator="SRT"
)

CEREBRAL_ARTERY = CodedConcept(
    value="T-45510",
    meaning="Cerebral artery",
    scheme_designator="SRT"
)

PANCREAS = CodedConcept(
    value="T-65000",
    meaning="Pancreas",
    scheme_designator="SRT"
)

CEREBRAL_AQUEDUCT = CodedConcept(
    value="T-A1800",
    meaning="Cerebral aqueduct",
    scheme_designator="SRT"
)

AORTA = CodedConcept(
    value="T-42000",
    meaning="Aorta",
    scheme_designator="SRT"
)

POSTERIOR_DESCENDING_RIGHT_CORONARY_ARTERY = CodedConcept(
    value="T-43210",
    meaning="Posterior Descending Right Coronary Artery",
    scheme_designator="SRT"
)

EXTERNAL_EAR = CodedConcept(
    value="T-AB100",
    meaning="External ear",
    scheme_designator="SRT"
)

FIBULA = CodedConcept(
    value="T-12750",
    meaning="Fibula",
    scheme_designator="SRT"
)

LUMBAR_REGION = CodedConcept(
    value="T-D2300",
    meaning="Lumbar region",
    scheme_designator="SRT"
)

JAW_REGION = CodedConcept(
    value="T-D1213",
    meaning="Jaw region",
    scheme_designator="SRT"
)

RIB = CodedConcept(
    value="T-11300",
    meaning="Rib",
    scheme_designator="SRT"
)

OMENTUM = CodedConcept(
    value="T-D4600",
    meaning="Omentum",
    scheme_designator="SRT"
)

THIGH_PERFORATOR = CodedConcept(
    value="T-F6713",
    meaning="Thigh perforator",
    scheme_designator="SRT"
)

MUSCLE_OF_UPPER_LIMB = CodedConcept(
    value="T-13600",
    meaning="Muscle of upper limb",
    scheme_designator="SRT"
)

SELLA_TURCICA = CodedConcept(
    value="T-D1460",
    meaning="Sella turcica",
    scheme_designator="SRT"
)

ENTIRE_BODY = CodedConcept(
    value="T-D0010",
    meaning="Entire body",
    scheme_designator="SRT"
)

RIGHT_POSTEROLATERAL_CORONARY_ARTERY_3RD = CodedConcept(
    value="T-43215",
    meaning="3rd Right posterolateral Coronary Artery",
    scheme_designator="SRT"
)

RIGHT_POSTEROLATERAL_CORONARY_ARTERY_2ND = CodedConcept(
    value="T-43214",
    meaning="2nd Right posterolateral Coronary Artery",
    scheme_designator="SRT"
)

RIGHT_POSTEROLATERAL_CORONARY_ARTERY_1ST = CodedConcept(
    value="T-43213",
    meaning="1st Right posterolateral Coronary Artery",
    scheme_designator="SRT"
)

RIGHT_POSTERIOR_AV_CORONARY_ARTERY = CodedConcept(
    value="T-43212",
    meaning="Right posterior AV Coronary Artery",
    scheme_designator="SRT"
)

RENAL_ARTERY = CodedConcept(
    value="T-46600",
    meaning="Renal artery",
    scheme_designator="SRT"
)

TESTICULAR_ARTERY = CodedConcept(
    value="T-46970",
    meaning="Testicular Artery",
    scheme_designator="SRT"
)

LIGAMENTUM_ARTERIOSUM = CodedConcept(
    value="T-42370",
    meaning="Ligamentum arteriosum",
    scheme_designator="SRT"
)

CIRCLE_OF_WILLIS = CodedConcept(
    value="T-45520",
    meaning="Circle of Willis",
    scheme_designator="SRT"
)

AIRWAY_STRUCTURE = CodedConcept(
    value="T-20001",
    meaning="Airway structure",
    scheme_designator="SRT"
)

OPHTHALMIC_ARTERY = CodedConcept(
    value="T-45400",
    meaning="Ophthalmic artery",
    scheme_designator="SRT"
)

MALE_EXTERNAL_GENITALIA = CodedConcept(
    value="T-90010",
    meaning="Male external genitalia",
    scheme_designator="SRT"
)

BUCCAL_REGION_OF_FACE = CodedConcept(
    value="T-D1206",
    meaning="Buccal region of face",
    scheme_designator="SRT"
)

SESAMOID_BONES_OF_FOOT = CodedConcept(
    value="T-12980",
    meaning="Sesamoid bones of foot",
    scheme_designator="SRT"
)

FACE = CodedConcept(
    value="T-D1200",
    meaning="Face",
    scheme_designator="SRT"
)

LATERAL_CALF_PERFORATOR = CodedConcept(
    value="T-F6724",
    meaning="Lateral calf perforator",
    scheme_designator="SRT"
)

ATRIUM = CodedConcept(
    value="T-32100",
    meaning="Atrium",
    scheme_designator="SRT"
)

LEFT_MAIN_CORONARY_ARTERY_OSTIUM = CodedConcept(
    value="T-43105",
    meaning="Left Main Coronary Artery Ostium",
    scheme_designator="SRT"
)

ANTERIOR_TIBIAL_ARTERY = CodedConcept(
    value="T-47700",
    meaning="Anterior tibial artery",
    scheme_designator="SRT"
)

INFERIOR_MESENTERIC_VEIN = CodedConcept(
    value="T-48910",
    meaning="Inferior Mesenteric Vein",
    scheme_designator="SRT"
)

ESOPHAGUS_STOMACH_AND_DUODENUM = CodedConcept(
    value="T-DD163",
    meaning="Esophagus, stomach and duodenum",
    scheme_designator="SRT"
)

LEFT_MAIN_CORONARY_ARTERY = CodedConcept(
    value="T-43107",
    meaning="Left Main Coronary Artery",
    scheme_designator="SRT"
)

HEPATIC_ARTERY = CodedConcept(
    value="T-46420",
    meaning="Hepatic artery",
    scheme_designator="SRT"
)

HEPATIC_VEIN = CodedConcept(
    value="T-48720",
    meaning="Hepatic vein",
    scheme_designator="SRT"
)

SUPERIOR_THYROID_ARTERY = CodedConcept(
    value="T-45210",
    meaning="Superior thyroid artery",
    scheme_designator="SRT"
)

PERONEAL_ARTERY = CodedConcept(
    value="T-47630",
    meaning="Peroneal artery",
    scheme_designator="SRT"
)

COMMON_HEPATIC_ARTERY = CodedConcept(
    value="T-46421",
    meaning="Common Hepatic Artery",
    scheme_designator="SRT"
)

SUPERIOR_MESENTERIC_VEIN = CodedConcept(
    value="T-48840",
    meaning="Superior Mesenteric Vein",
    scheme_designator="SRT"
)

PROPER_HEPATIC_ARTERY = CodedConcept(
    value="T-46422",
    meaning="Proper Hepatic Artery",
    scheme_designator="SRT"
)

FOURTH_VENTRICLE = CodedConcept(
    value="T-A1820",
    meaning="Fourth ventricle",
    scheme_designator="SRT"
)

RIGHT_BRANCH_OF_HEPATIC_ARTERY = CodedConcept(
    value="T-46423",
    meaning="Right Branch of Hepatic Artery",
    scheme_designator="SRT"
)

NOSE = CodedConcept(
    value="T-21000",
    meaning="Nose",
    scheme_designator="SRT"
)

EAR = CodedConcept(
    value="T-AB001",
    meaning="Ear",
    scheme_designator="SRT"
)

PULMONARY_ARTERY = CodedConcept(
    value="T-44000",
    meaning="Pulmonary artery",
    scheme_designator="SRT"
)

CALCANEUS = CodedConcept(
    value="T-12770",
    meaning="Calcaneus",
    scheme_designator="SRT"
)

HUMERUS = CodedConcept(
    value="T-12410",
    meaning="Humerus",
    scheme_designator="SRT"
)

ESOPHAGEAL_HIATUS = CodedConcept(
    value="T-D3412",
    meaning="Esophageal Hiatus",
    scheme_designator="SRT"
)

INFRASPINATUS_MUSCLE = CodedConcept(
    value="T-13620",
    meaning="Infraspinatus muscle",
    scheme_designator="SRT"
)

AORTIC_VALVE = CodedConcept(
    value="T-35400",
    meaning="Aortic Valve",
    scheme_designator="SRT"
)

MESENTERIC_VEIN = CodedConcept(
    value="T-4884A",
    meaning="Mesenteric vein",
    scheme_designator="SRT"
)

BILE_DUCT = CodedConcept(
    value="T-60610",
    meaning="Bile duct",
    scheme_designator="SRT"
)

SPINAL_CORD = CodedConcept(
    value="T-A7010",
    meaning="Spinal cord",
    scheme_designator="SRT"
)

HEAD_AND_NECK = CodedConcept(
    value="T-D1000",
    meaning="Head and Neck",
    scheme_designator="SRT"
)

JEJUNUM = CodedConcept(
    value="T-58400",
    meaning="Jejunum",
    scheme_designator="SRT"
)

INTRAARTICULAR = CodedConcept(
    value="G-A15A",
    meaning="Intra-articular",
    scheme_designator="SRT"
)

SYSTEMIC_COLLATERAL_ARTERY_TO_LUNG = CodedConcept(
    value="T-44007",
    meaning="Systemic collateral artery to lung",
    scheme_designator="SRT"
)

LEFT_HEPATIC_VEIN = CodedConcept(
    value="T-48727",
    meaning="Left Hepatic Vein",
    scheme_designator="SRT"
)

MIDDLE_HEPATIC_VEIN = CodedConcept(
    value="T-48726",
    meaning="Middle Hepatic Vein",
    scheme_designator="SRT"
)

PERFORATING_ARTERY_OF_KIDNEY = CodedConcept(
    value="T-46668",
    meaning="Perforating Artery of Kidney",
    scheme_designator="SRT"
)

LEFT_BRANCH_OF_HEPATIC_ARTERY = CodedConcept(
    value="T-46427",
    meaning="Left Branch of Hepatic Artery",
    scheme_designator="SRT"
)

RIGHT_HEPATIC_VEIN = CodedConcept(
    value="T-48725",
    meaning="Right Hepatic Vein",
    scheme_designator="SRT"
)

COMMON_CAROTID_ARTERY = CodedConcept(
    value="T-45100",
    meaning="Common carotid artery",
    scheme_designator="SRT"
)

FEMORAL_ARTERY = CodedConcept(
    value="T-47400",
    meaning="Femoral artery",
    scheme_designator="SRT"
)

SUPERIOR_VENA_CAVA = CodedConcept(
    value="T-48610",
    meaning="Superior vena cava",
    scheme_designator="SRT"
)

SUPRAPULMONIC_VALVE_AREA = CodedConcept(
    value="T-44010",
    meaning="Suprapulmonic valve area",
    scheme_designator="SRT"
)

BRONCHIAL_ARTERY = CodedConcept(
    value="T-46310",
    meaning="Bronchial artery",
    scheme_designator="SRT"
)

COMMON_FEMORAL_ARTERY = CodedConcept(
    value="T-47402",
    meaning="Common Femoral Artery",
    scheme_designator="SRT"
)

PERIPHERAL_NERVE = CodedConcept(
    value="T-A0500",
    meaning="Peripheral nerve",
    scheme_designator="SRT"
)

HEAD = CodedConcept(
    value="T-D1100",
    meaning="Head",
    scheme_designator="SRT"
)

THORACIC_AORTA = CodedConcept(
    value="T-42070",
    meaning="Thoracic aorta",
    scheme_designator="SRT"
)

FLANK = CodedConcept(
    value="T-D2310",
    meaning="Flank",
    scheme_designator="SRT"
)

DIAPHRAGM = CodedConcept(
    value="T-D3400",
    meaning="Diaphragm",
    scheme_designator="SRT"
)

ESOPHAGEAL_ARTERY = CodedConcept(
    value="T-4630D",
    meaning="Esophageal artery",
    scheme_designator="SRT"
)

SUPRASPINATUS_MUSCLE = CodedConcept(
    value="T-13610",
    meaning="Supraspinatus muscle",
    scheme_designator="SRT"
)

SPINAL_CORD_GRAY_MATTER = CodedConcept(
    value="T-A7020",
    meaning="Spinal cord gray matter",
    scheme_designator="SRT"
)

LOBAR_ARTERY = CodedConcept(
    value="T-4667C",
    meaning="Lobar Artery",
    scheme_designator="SRT"
)

HEART = CodedConcept(
    value="T-32000",
    meaning="Heart",
    scheme_designator="SRT"
)

INTERLOBAR_ARTERY_OF_KIDNEY = CodedConcept(
    value="T-4667D",
    meaning="Interlobar Artery of Kidney",
    scheme_designator="SRT"
)

SUPERFICIAL_FEMORAL_ARTERY = CodedConcept(
    value="T-47403",
    meaning="Superficial Femoral Artery",
    scheme_designator="SRT"
)

INTERNAL_ILIAC_VEIN = CodedConcept(
    value="T-48940",
    meaning="Internal iliac vein",
    scheme_designator="SRT"
)

ACCESSORY_RENAL_ARTERY = CodedConcept(
    value="T-46640",
    meaning="Accessory Renal Artery",
    scheme_designator="SRT"
)

CENTRAL_RETINAL_ARTERY = CodedConcept(
    value="T-45430",
    meaning="Central Retinal Artery",
    scheme_designator="SRT"
)

INFERIOR_MESENTERIC_ARTERY = CodedConcept(
    value="T-46520",
    meaning="Inferior mesenteric artery",
    scheme_designator="SRT"
)

TRUNCUS_COELIACUS = CodedConcept(
    value="T-46400",
    meaning="Truncus coeliacus",
    scheme_designator="SRT"
)

BRAIN_VENTRICLE = CodedConcept(
    value="T-A1600",
    meaning="Brain ventricle",
    scheme_designator="SRT"
)

GASTRIC_VEIN = CodedConcept(
    value="T-48820",
    meaning="Gastric vein",
    scheme_designator="SRT"
)

TRUNK_OF_PULMONARY_ARTERY = CodedConcept(
    value="T-44100",
    meaning="Trunk of pulmonary artery",
    scheme_designator="SRT"
)

FALLOPIAN_TUBE = CodedConcept(
    value="T-88000",
    meaning="Fallopian tube",
    scheme_designator="SRT"
)

LEFT_POSTERIOR_DESCENDING_CIRCUMFLEX_CORONARY_ARTERY = CodedConcept(
    value="T-4312E",
    meaning="Left Posterior Descending Circumflex Coronary Artery",
    scheme_designator="SRT"
)

LEFT_POSTEROLATERAL_CORONARY_ARTERY_3RD = CodedConcept(
    value="T-4312D",
    meaning="3rd Left Posterolateral Coronary Artery",
    scheme_designator="SRT"
)

CLAVICLE = CodedConcept(
    value="T-12310",
    meaning="Clavicle",
    scheme_designator="SRT"
)

SKULL = CodedConcept(
    value="T-11100",
    meaning="Skull",
    scheme_designator="SRT"
)

PERITIONEUM = CodedConcept(
    value="T-D4400",
    meaning="Peritioneum",
    scheme_designator="SRT"
)

TERES_MAJOR_MUSCLE = CodedConcept(
    value="T-13640",
    meaning="Teres major muscle",
    scheme_designator="SRT"
)

OPTIC_CANAL = CodedConcept(
    value="T-11102",
    meaning="Optic canal",
    scheme_designator="SRT"
)

CRANIAL_NERVE = CodedConcept(
    value="T-A8000",
    meaning="Cranial nerve",
    scheme_designator="SRT"
)

BONE_OF_THORAX = CodedConcept(
    value="T-D0170",
    meaning="Bone of thorax",
    scheme_designator="SRT"
)

MITRAL_VALVE = CodedConcept(
    value="T-35300",
    meaning="Mitral Valve",
    scheme_designator="SRT"
)

INTERATRIAL_SEPTUM = CodedConcept(
    value="T-32150",
    meaning="Interatrial septum",
    scheme_designator="SRT"
)

CONGENITAL_PULMONARY_ARTERIOVENOUS_FISTULA = CodedConcept(
    value="D3-40208",
    meaning="Congenital pulmonary arteriovenous fistula",
    scheme_designator="SRT"
)

CORPUS_CALLOSUM = CodedConcept(
    value="T-A2700",
    meaning="Corpus callosum",
    scheme_designator="SRT"
)

POSTERIOR_COMMUNICATION_ARTERY = CodedConcept(
    value="T-45320",
    meaning="Posterior communication artery",
    scheme_designator="SRT"
)

EXTERNAL_CAROTID_ARTERY = CodedConcept(
    value="T-45200",
    meaning="External carotid artery",
    scheme_designator="SRT"
)

DORSALIS_PEDIS_ARTERY = CodedConcept(
    value="T-47740",
    meaning="Dorsalis Pedis Artery",
    scheme_designator="SRT"
)

GASTRIC_ARTERY = CodedConcept(
    value="T-46410",
    meaning="Gastric Artery",
    scheme_designator="SRT"
)

UMBILICAL_VEIN = CodedConcept(
    value="T-48832",
    meaning="Umbilical vein",
    scheme_designator="SRT"
)

INFERIOR_VENA_CAVA = CodedConcept(
    value="T-48710",
    meaning="Inferior vena cava",
    scheme_designator="SRT"
)

OPTIC_CHIASM = CodedConcept(
    value="T-A800B",
    meaning="Optic chiasm",
    scheme_designator="SRT"
)

SUPERIOR_LONGITUDINAL_FASCICULUS = CodedConcept(
    value="T-A2820",
    meaning="Superior longitudinal fasciculus",
    scheme_designator="SRT"
)

POPLITEAL_ARTERY = CodedConcept(
    value="T-47500",
    meaning="Popliteal artery",
    scheme_designator="SRT"
)

MEDIASTINUM = CodedConcept(
    value="T-D3300",
    meaning="Mediastinum",
    scheme_designator="SRT"
)

TERES_MINOR_MUSCLE = CodedConcept(
    value="T-13630",
    meaning="Teres minor muscle",
    scheme_designator="SRT"
)

STERNUM = CodedConcept(
    value="T-11210",
    meaning="Sternum",
    scheme_designator="SRT"
)

LEFT_LUMBAR_REGION = CodedConcept(
    value="T-D2340",
    meaning="Left lumbar region",
    scheme_designator="SRT"
)

RECTUM = CodedConcept(
    value="T-59600",
    meaning="Rectum",
    scheme_designator="SRT"
)

SHOULDER = CodedConcept(
    value="T-D2220",
    meaning="Shoulder",
    scheme_designator="SRT"
)

BACK = CodedConcept(
    value="T-D2100",
    meaning="Back",
    scheme_designator="SRT"
)

RIGHT_LUMBAR_REGION = CodedConcept(
    value="T-D2342",
    meaning="Right lumbar region",
    scheme_designator="SRT"
)

SUPRASTERNAL_NOTCH = CodedConcept(
    value="T-11218",
    meaning="Suprasternal notch",
    scheme_designator="SRT"
)

PHARYNX = CodedConcept(
    value="T-55000",
    meaning="Pharynx",
    scheme_designator="SRT"
)

SEGMENTAL_ARTERY = CodedConcept(
    value="T-46659",
    meaning="Segmental Artery",
    scheme_designator="SRT"
)

THIRD_VENTRICLE = CodedConcept(
    value="T-A1740",
    meaning="Third ventricle",
    scheme_designator="SRT"
)

SUBARACHNOID_SPACE = CodedConcept(
    value="T-A1500",
    meaning="Subarachnoid space",
    scheme_designator="SRT"
)

UNCINATE_FASCICULUS = CodedConcept(
    value="T-A2830",
    meaning="Uncinate fasciculus",
    scheme_designator="SRT"
)

BONE_STRUCTURE_OF_HEAD_AND_OR_NECK = CodedConcept(
    value="T-D006D",
    meaning="Bone structure of head and/or neck",
    scheme_designator="SRT"
)

GALLBLADDER = CodedConcept(
    value="T-63000",
    meaning="Gallbladder",
    scheme_designator="SRT"
)

CEREBELLAR_WHITE_MATTER = CodedConcept(
    value="T-A6080",
    meaning="Cerebellar white matter",
    scheme_designator="SRT"
)

TRUNCUS_ARTERIOSUS_COMMUNIS = CodedConcept(
    value="D4-31400",
    meaning="Truncus arteriosus communis",
    scheme_designator="SRT"
)

SYSTEMIC_VEIN = CodedConcept(
    value="T-48081",
    meaning="Systemic vein",
    scheme_designator="SRT"
)

SUBXIPHOID = CodedConcept(
    value="T-D3213",
    meaning="Subxiphoid",
    scheme_designator="SRT"
)

PERITONEAL_CAVITY = CodedConcept(
    value="T-D4425",
    meaning="Peritoneal cavity",
    scheme_designator="SRT"
)

INFERIOR_CARDIAC_VEIN = CodedConcept(
    value="T-484A4",
    meaning="Inferior cardiac vein",
    scheme_designator="SRT"
)

SCALP = CodedConcept(
    value="T-D1160",
    meaning="Scalp",
    scheme_designator="SRT"
)

DORSAL_SCAPULAR_ARTERY = CodedConcept(
    value="T-461A0",
    meaning="Dorsal scapular artery",
    scheme_designator="SRT"
)

AORTIC_ARCH = CodedConcept(
    value="T-42300",
    meaning="Aortic arch",
    scheme_designator="SRT"
)

BLOOD_VESSEL = CodedConcept(
    value="T-40000",
    meaning="Blood Vessel",
    scheme_designator="SRT"
)

ENDOVESICAL = CodedConcept(
    value="T-74250",
    meaning="Endo-vesical",
    scheme_designator="SRT"
)

CINGULUM = CodedConcept(
    value="T-A2840",
    meaning="Cingulum",
    scheme_designator="SRT"
)

POSTERIOR_CEREBRAL_COMMISSURE = CodedConcept(
    value="T-A4904",
    meaning="Posterior cerebral commissure",
    scheme_designator="SRT"
)

APEX_OF_LEFT_VENTRICLE = CodedConcept(
    value="T-32602",
    meaning="Apex of left ventricle",
    scheme_designator="SRT"
)

LEFT_VENTRICLE = CodedConcept(
    value="T-32600",
    meaning="Left ventricle",
    scheme_designator="SRT"
)

NEUROHYPOPHYSIS = CodedConcept(
    value="T-B1200",
    meaning="Neurohypophysis",
    scheme_designator="SRT"
)

CONGENITAL_CORONARY_ARTERY_FISTULA_TO_LEFT_VENTRICLE = CodedConcept(
    value="D4-32506",
    meaning="Congenital coronary artery fistula to left ventricle",
    scheme_designator="SRT"
)

CONGENITAL_CORONARY_ARTERY_FISTULA_TO_RIGHT_ATRIUM = CodedConcept(
    value="D4-32509",
    meaning="Congenital coronary artery fistula to right atrium",
    scheme_designator="SRT"
)

CONGENITAL_CORONARY_ARTERY_FISTULA_TO_LEFT_ATRIUM = CodedConcept(
    value="D4-32504",
    meaning="Congenital coronary artery fistula to left atrium",
    scheme_designator="SRT"
)

BLADDER = CodedConcept(
    value="T-74000",
    meaning="Bladder",
    scheme_designator="SRT"
)

AORTIC_ISTHMUS = CodedConcept(
    value="T-42310",
    meaning="Aortic isthmus",
    scheme_designator="SRT"
)

INFERIOR_LONGITUDINAL_FASCICULUS = CodedConcept(
    value="T-A2850",
    meaning="Inferior longitudinal fasciculus",
    scheme_designator="SRT"
)

EXTERNAL_ILIAC_ARTERY = CodedConcept(
    value="T-46910",
    meaning="External iliac artery",
    scheme_designator="SRT"
)

VERTEBRAL_ARTERY = CodedConcept(
    value="T-45700",
    meaning="Vertebral artery",
    scheme_designator="SRT"
)

CEREBRAL_FORNIX = CodedConcept(
    value="T-A2970",
    meaning="Cerebral fornix",
    scheme_designator="SRT"
)

INSULA = CodedConcept(
    value="T-A2610",
    meaning="Insula",
    scheme_designator="SRT"
)

COCCYX = CodedConcept(
    value="T-11BF0",
    meaning="Coccyx",
    scheme_designator="SRT"
)

SACRUM = CodedConcept(
    value="T-11AD0",
    meaning="Sacrum",
    scheme_designator="SRT"
)

SPINAL_CORD_WHITE_MATTER = CodedConcept(
    value="T-A7070",
    meaning="Spinal cord white matter",
    scheme_designator="SRT"
)

FINGER = CodedConcept(
    value="T-D8800",
    meaning="Finger",
    scheme_designator="SRT"
)

THUMB = CodedConcept(
    value="T-D8810",
    meaning="Thumb",
    scheme_designator="SRT"
)

SUBCOSTAL = CodedConcept(
    value="T-D4210",
    meaning="Subcostal",
    scheme_designator="SRT"
)

CHEST = CodedConcept(
    value="T-D3000",
    meaning="Chest",
    scheme_designator="SRT"
)

RIGHT_HYPOCHONDRIAC_REGION = CodedConcept(
    value="T-D4212",
    meaning="Right hypochondriac region",
    scheme_designator="SRT"
)

LEFT_HYPOCHONDRIAC_REGION = CodedConcept(
    value="T-D4211",
    meaning="Left hypochondriac region",
    scheme_designator="SRT"
)

OMENTAL_BURSA = CodedConcept(
    value="T-D4450",
    meaning="Omental bursa",
    scheme_designator="SRT"
)

SCROTUM = CodedConcept(
    value="T-98000",
    meaning="Scrotum",
    scheme_designator="SRT"
)

INFRARENAL_AORTA = CodedConcept(
    value="T-42520",
    meaning="Infra-renal Aorta",
    scheme_designator="SRT"
)

LATERAL_VENTRICLE = CodedConcept(
    value="T-A1650",
    meaning="Lateral ventricle",
    scheme_designator="SRT"
)

TEMPORAL_LOBE = CodedConcept(
    value="T-A2500",
    meaning="Temporal lobe",
    scheme_designator="SRT"
)

TEMPOROMANDIBULAR_JOINT = CodedConcept(
    value="T-15290",
    meaning="Temporomandibular joint",
    scheme_designator="SRT"
)

LUMEN_OF_BLOOD_VESSEL = CodedConcept(
    value="T-40230",
    meaning="Lumen of blood vessel",
    scheme_designator="SRT"
)

PERICARDIUM = CodedConcept(
    value="T-39000",
    meaning="Pericardium",
    scheme_designator="SRT"
)

APEX_OF_RIGHT_VENTRICLE = CodedConcept(
    value="T-32502",
    meaning="Apex of right ventricle",
    scheme_designator="SRT"
)

OVARY = CodedConcept(
    value="T-87000",
    meaning="Ovary",
    scheme_designator="SRT"
)

RIGHT_VENTRICLE = CodedConcept(
    value="T-32500",
    meaning="Right ventricle",
    scheme_designator="SRT"
)

ADENOHYPOPHYSIS = CodedConcept(
    value="T-B1100",
    meaning="Adenohypophysis",
    scheme_designator="SRT"
)

BROAD_LIGAMENT = CodedConcept(
    value="T-D6500",
    meaning="Broad ligament",
    scheme_designator="SRT"
)

EPIGASTRIC_REGION = CodedConcept(
    value="T-D4200",
    meaning="Epigastric region",
    scheme_designator="SRT"
)

LIVER = CodedConcept(
    value="T-62000",
    meaning="Liver",
    scheme_designator="SRT"
)

LUNG = CodedConcept(
    value="T-28000",
    meaning="Lung",
    scheme_designator="SRT"
)

SOFT_PALATE = CodedConcept(
    value="T-51120",
    meaning="Soft palate",
    scheme_designator="SRT"
)

BASILAR_ARTERY = CodedConcept(
    value="T-45800",
    meaning="Basilar artery",
    scheme_designator="SRT"
)

PERICARDIAL_CAVITY = CodedConcept(
    value="T-39050",
    meaning="Pericardial cavity",
    scheme_designator="SRT"
)

ANTERIOR_SPINAL_ARTERY = CodedConcept(
    value="T-45730",
    meaning="Anterior spinal artery",
    scheme_designator="SRT"
)

INFERIOR_PHRENIC_ARTERY = CodedConcept(
    value="T-46940",
    meaning="Inferior phrenic artery",
    scheme_designator="SRT"
)

ASCENDING_AORTA = CodedConcept(
    value="T-42100",
    meaning="Ascending aorta",
    scheme_designator="SRT"
)

OPTIC_TRACT = CodedConcept(
    value="T-A8060",
    meaning="Optic tract",
    scheme_designator="SRT"
)

INTERVENTRICULAR_SEPTUM = CodedConcept(
    value="T-32410",
    meaning="Interventricular septum",
    scheme_designator="SRT"
)

PARASTERNAL = CodedConcept(
    value="T-D3136",
    meaning="Parasternal",
    scheme_designator="SRT"
)

TOE = CodedConcept(
    value="T-D9800",
    meaning="Toe",
    scheme_designator="SRT"
)

INTIMA = CodedConcept(
    value="T-1A170",
    meaning="Intima",
    scheme_designator="SRT"
)

RIGHT_UPPER_QUADRANT_OF_ABDOMEN = CodedConcept(
    value="T-D4110",
    meaning="Right upper quadrant of abdomen",
    scheme_designator="SRT"
)

LEFT_VENTRICLE_OUTFLOW_TRACT = CodedConcept(
    value="T-32650",
    meaning="Left ventricle outflow tract",
    scheme_designator="SRT"
)

LATERAL_CORTICOSPINAL_TRACT = CodedConcept(
    value="T-A7093",
    meaning="Lateral corticospinal tract",
    scheme_designator="SRT"
)

UMBILICAL_REGION = CodedConcept(
    value="T-D4230",
    meaning="Umbilical region",
    scheme_designator="SRT"
)

PLEURA = CodedConcept(
    value="T-29000",
    meaning="Pleura",
    scheme_designator="SRT"
)

OPTIC_RADIATION = CodedConcept(
    value="T-A2880",
    meaning="Optic radiation",
    scheme_designator="SRT"
)

LEFT_PULMONARY_ARTERY = CodedConcept(
    value="T-44400",
    meaning="Left pulmonary artery",
    scheme_designator="SRT"
)

VAS_DEFERENS = CodedConcept(
    value="T-96000",
    meaning="Vas deferens",
    scheme_designator="SRT"
)

UTERINE_ARTERY = CodedConcept(
    value="T-46820",
    meaning="Uterine Artery",
    scheme_designator="SRT"
)

OCCIPITAL_LOBE = CodedConcept(
    value="T-A2400",
    meaning="Occipital lobe",
    scheme_designator="SRT"
)

ILIAC_ARTERY = CodedConcept(
    value="T-46700",
    meaning="Iliac artery",
    scheme_designator="SRT"
)

BRAIN = CodedConcept(
    value="T-A0100",
    meaning="Brain",
    scheme_designator="SRT"
)

TELENCEPHALON = CodedConcept(
    value="T-A0103",
    meaning="Telencephalon",
    scheme_designator="SRT"
)

UMBILICAL_ARTERY = CodedConcept(
    value="T-F1810",
    meaning="Umbilical artery",
    scheme_designator="SRT"
)

DIENCEPHALON = CodedConcept(
    value="T-A0102",
    meaning="Diencephalon",
    scheme_designator="SRT"
)

RIGHT_CORONARY_ARTERY = CodedConcept(
    value="T-43200",
    meaning="Right Coronary Artery",
    scheme_designator="SRT"
)

BRAIN_CEREBROSPINAL_FLUID_PATHWAY = CodedConcept(
    value="T-A0109",
    meaning="Brain cerebrospinal fluid pathway",
    scheme_designator="SRT"
)

PULMONARY_VEIN_CONFLUENCE = CodedConcept(
    value="D4-33512",
    meaning="Pulmonary vein confluence",
    scheme_designator="SRT"
)

ANUS = CodedConcept(
    value="T-59900",
    meaning="Anus",
    scheme_designator="SRT"
)

VENTRICLE = CodedConcept(
    value="T-32400",
    meaning="Ventricle",
    scheme_designator="SRT"
)

MID_RIGHT_CORONARY_ARTERY = CodedConcept(
    value="T-D6515",
    meaning="Mid Right Coronary Artery",
    scheme_designator="SRT"
)

HAND = CodedConcept(
    value="T-D8700",
    meaning="Hand",
    scheme_designator="SRT"
)

PITUITARY = CodedConcept(
    value="T-B1000",
    meaning="Pituitary",
    scheme_designator="SRT"
)

LEFT_VENTRICLE_INFLOW = CodedConcept(
    value="T-32640",
    meaning="Left ventricle inflow",
    scheme_designator="SRT"
)

PULMONARY_VENOUS_ATRIUM = CodedConcept(
    value="D4-33514",
    meaning="Pulmonary venous atrium",
    scheme_designator="SRT"
)

HYPOPHARYNX = CodedConcept(
    value="T-55300",
    meaning="Hypopharynx",
    scheme_designator="SRT"
)

PRIMITIVE_AORTA = CodedConcept(
    value="T-F7001",
    meaning="Primitive aorta",
    scheme_designator="SRT"
)

SYSTEMIC_VENOUS_ATRIUM = CodedConcept(
    value="D4-33516",
    meaning="Systemic venous atrium",
    scheme_designator="SRT"
)

TONGUE = CodedConcept(
    value="T-53000",
    meaning="Tongue",
    scheme_designator="SRT"
)

DISTAL_RIGHT_CORONARY_ARTERY = CodedConcept(
    value="T-43202",
    meaning="Distal Right Coronary Artery",
    scheme_designator="SRT"
)

PROXIMAL_RIGHT_CORONARY_ARTERY = CodedConcept(
    value="T-43201",
    meaning="Proximal Right Coronary Artery",
    scheme_designator="SRT"
)

COMMON_ILIAC_ARTERY = CodedConcept(
    value="T-46710",
    meaning="Common iliac artery",
    scheme_designator="SRT"
)

GLOBUS_PALLIDUS = CodedConcept(
    value="T-A3500",
    meaning="Globus pallidus",
    scheme_designator="SRT"
)

RIGHT_CORONARY_ARTERY_OSTIUM = CodedConcept(
    value="T-43205",
    meaning="Right Coronary Artery Ostium",
    scheme_designator="SRT"
)

CONGENITAL_CORONARY_ARTERY_FISTULA_TO_RIGHT_VENTRICLE = CodedConcept(
    value="D4-32510",
    meaning="Congenital coronary artery fistula to right ventricle",
    scheme_designator="SRT"
)

ORBITAL_STRUCTURE = CodedConcept(
    value="T-D14AE",
    meaning="Orbital structure",
    scheme_designator="SRT"
)

VASCULAR_GRAFT = CodedConcept(
    value="A-04140",
    meaning="Vascular graft",
    scheme_designator="SRT"
)

FEMUR = CodedConcept(
    value="T-12710",
    meaning="Femur",
    scheme_designator="SRT"
)

FOOT = CodedConcept(
    value="T-D9700",
    meaning="Foot",
    scheme_designator="SRT"
)

RIGHT_VENTRICLE_OUTFLOW_TRACT = CodedConcept(
    value="T-32550",
    meaning="Right ventricle outflow tract",
    scheme_designator="SRT"
)

CERVICAL_SPINE = CodedConcept(
    value="T-11501",
    meaning="Cervical spine",
    scheme_designator="SRT"
)

THORACIC_SPINE = CodedConcept(
    value="T-11502",
    meaning="Thoracic spine",
    scheme_designator="SRT"
)

ADVENTITIA = CodedConcept(
    value="T-1A190",
    meaning="Adventitia",
    scheme_designator="SRT"
)

LEFT_AURICULAR_APPENDAGE = CodedConcept(
    value="T-32310",
    meaning="Left auricular appendage",
    scheme_designator="SRT"
)

LUMBAR_SPINE = CodedConcept(
    value="T-11503",
    meaning="Lumbar spine",
    scheme_designator="SRT"
)

ABDOMINAL_CAVITY = CodedConcept(
    value="T-D4010",
    meaning="Abdominal cavity",
    scheme_designator="SRT"
)

LIP = CodedConcept(
    value="T-52000",
    meaning="Lip",
    scheme_designator="SRT"
)

LEFT_UPPER_QUADRANT_OF_ABDOMEN = CodedConcept(
    value="T-D4130",
    meaning="Left upper quadrant of abdomen",
    scheme_designator="SRT"
)

URETHRA = CodedConcept(
    value="T-75000",
    meaning="Urethra",
    scheme_designator="SRT"
)

NECK_CHEST_AND_ABDOMEN = CodedConcept(
    value="R-FAB53",
    meaning="Neck, Chest and Abdomen",
    scheme_designator="SRT"
)

PARIETAL_LOBE = CodedConcept(
    value="T-A2300",
    meaning="Parietal lobe",
    scheme_designator="SRT"
)

NECK_AND_CHEST = CodedConcept(
    value="R-FAB52",
    meaning="Neck and Chest",
    scheme_designator="SRT"
)

THORACIC_DUCT = CodedConcept(
    value="T-C6510",
    meaning="Thoracic Duct",
    scheme_designator="SRT"
)

ENDONASAL = CodedConcept(
    value="T-21300",
    meaning="Endo-nasal",
    scheme_designator="SRT"
)

ABDOMEN_AND_PELVIS = CodedConcept(
    value="R-FAB57",
    meaning="Abdomen and Pelvis",
    scheme_designator="SRT"
)

CHEST_ABDOMEN_AND_PELVIS = CodedConcept(
    value="R-FAB56",
    meaning="Chest, Abdomen and Pelvis",
    scheme_designator="SRT"
)

CHEST_AND_ABDOMEN = CodedConcept(
    value="R-FAB55",
    meaning="Chest and Abdomen",
    scheme_designator="SRT"
)

SPLEEN = CodedConcept(
    value="T-C3000",
    meaning="Spleen",
    scheme_designator="SRT"
)

NECK_CHEST_ABDOMEN_AND_PELVIS = CodedConcept(
    value="R-FAB54",
    meaning="Neck, Chest, Abdomen and Pelvis",
    scheme_designator="SRT"
)

ARTERY = CodedConcept(
    value="T-41000",
    meaning="Artery",
    scheme_designator="SRT"
)

PELVIS_AND_LOWER_EXTREMITIES = CodedConcept(
    value="R-FAB58",
    meaning="Pelvis and lower extremities",
    scheme_designator="SRT"
)

LEFT_ATRIUM = CodedConcept(
    value="T-32300",
    meaning="Left atrium",
    scheme_designator="SRT"
)

TRABECULAE_CARNAE = CodedConcept(
    value="T-32423",
    meaning="Trabeculae carnae",
    scheme_designator="SRT"
)

ABDOMEN = CodedConcept(
    value="T-D4000",
    meaning="Abdomen",
    scheme_designator="SRT"
)

BONE_OF_LOWER_LIMB = CodedConcept(
    value="T-12700",
    meaning="Bone of lower limb",
    scheme_designator="SRT"
)

MEDIA = CodedConcept(
    value="T-1A180",
    meaning="Media",
    scheme_designator="SRT"
)

RIGHT_VENTRICLE_INFLOW = CodedConcept(
    value="T-32540",
    meaning="Right ventricle inflow",
    scheme_designator="SRT"
)

CARDIOVASCULAR_SYSTEM = CodedConcept(
    value="T-30000",
    meaning="Cardiovascular system",
    scheme_designator="SRT"
)

RIGHT_LOWER_QUADRANT_OF_ABDOMEN = CodedConcept(
    value="T-D4120",
    meaning="Right lower quadrant of abdomen",
    scheme_designator="SRT"
)

HYPOGASTRIC_REGION = CodedConcept(
    value="T-D4240",
    meaning="Hypogastric region",
    scheme_designator="SRT"
)

PUTAMEN = CodedConcept(
    value="T-A3400",
    meaning="Putamen",
    scheme_designator="SRT"
)

ARACHNOID = CodedConcept(
    value="T-A1220",
    meaning="Arachnoid",
    scheme_designator="SRT"
)

MIDDLE_CEREBRAL_ARTERY = CodedConcept(
    value="T-45600",
    meaning="Middle Cerebral Artery",
    scheme_designator="SRT"
)

SUPERFICIAL_PALMAR_VENOUS_ARCH = CodedConcept(
    value="T-49217",
    meaning="Superficial Palmar Venous Arch",
    scheme_designator="SRT"
)

ANTECUBITAL_VEIN = CodedConcept(
    value="T-49215",
    meaning="Antecubital vein",
    scheme_designator="SRT"
)

SACROILIAC_JOINT = CodedConcept(
    value="T-15680",
    meaning="Sacroiliac joint",
    scheme_designator="SRT"
)

VEIN = CodedConcept(
    value="T-48000",
    meaning="Vein",
    scheme_designator="SRT"
)

INTERCOSTAL_ARTERY = CodedConcept(
    value="T-D305A",
    meaning="Intercostal artery",
    scheme_designator="SRT"
)

VENOUS_NETWORK = CodedConcept(
    value="T-48003",
    meaning="Venous network",
    scheme_designator="SRT"
)

FONTANEL_OF_SKULL = CodedConcept(
    value="T-15200",
    meaning="Fontanel of skull",
    scheme_designator="SRT"
)

PECTORALIS_MAJOR_MUSCLE = CodedConcept(
    value="T-14110",
    meaning="Pectoralis major muscle",
    scheme_designator="SRT"
)

ULNAR_VEIN = CodedConcept(
    value="T-49330",
    meaning="Ulnar vein",
    scheme_designator="SRT"
)

COMMON_ATRIUM = CodedConcept(
    value="D4-31005",
    meaning="Common atrium",
    scheme_designator="SRT"
)

PINEAL_GLAND = CodedConcept(
    value="T-B2000",
    meaning="Pineal Gland",
    scheme_designator="SRT"
)

COMMON_VENTRICLE = CodedConcept(
    value="D4-31120",
    meaning="Common ventricle",
    scheme_designator="SRT"
)

SPINE = CodedConcept(
    value="T-D04FF",
    meaning="Spine",
    scheme_designator="SRT"
)

COSTOCERVICAL_TRUNK = CodedConcept(
    value="T-46180",
    meaning="Costocervical trunk",
    scheme_designator="SRT"
)

PAROTID_GLAND = CodedConcept(
    value="T-61100",
    meaning="Parotid gland",
    scheme_designator="SRT"
)

SKIN_OF_ABDOMEN = CodedConcept(
    value="T-02480",
    meaning="Skin of abdomen",
    scheme_designator="SRT"
)

TRACHEA = CodedConcept(
    value="T-25000",
    meaning="Trachea",
    scheme_designator="SRT"
)

PERIPHERAL_NERVOUS_SYSTEM = CodedConcept(
    value="T-A0140",
    meaning="Peripheral nervous system",
    scheme_designator="SRT"
)

MENINGES = CodedConcept(
    value="T-A1110",
    meaning="Meninges",
    scheme_designator="SRT"
)

DEEP_PALMAR_VENOUS_ARCH = CodedConcept(
    value="T-49218",
    meaning="Deep Palmar Venous Arch",
    scheme_designator="SRT"
)

ANUS_RECTUM_AND_SIGMOID_COLON = CodedConcept(
    value="T-59490",
    meaning="Anus, rectum and sigmoid colon",
    scheme_designator="SRT"
)

FRONTAL_LOBE = CodedConcept(
    value="T-A2200",
    meaning="Frontal lobe",
    scheme_designator="SRT"
)

NUCLEUS_ACCUMBENS = CodedConcept(
    value="T-A0149",
    meaning="Nucleus accumbens",
    scheme_designator="SRT"
)

HYOID_BONE = CodedConcept(
    value="T-11190",
    meaning="Hyoid bone",
    scheme_designator="SRT"
)

SCAPULA = CodedConcept(
    value="T-12280",
    meaning="Scapula",
    scheme_designator="SRT"
)

CALYX = CodedConcept(
    value="T-72100",
    meaning="Calyx",
    scheme_designator="SRT"
)

RADIAL_VEIN = CodedConcept(
    value="T-49340",
    meaning="Radial vein",
    scheme_designator="SRT"
)

BRACHIAL_ARTERY = CodedConcept(
    value="T-47160",
    meaning="Brachial artery",
    scheme_designator="SRT"
)

ENDONASOPHARYNGEAL = CodedConcept(
    value="T-23050",
    meaning="Endo-nasopharyngeal",
    scheme_designator="SRT"
)

FACIAL_BONES = CodedConcept(
    value="T-11196",
    meaning="Facial bones",
    scheme_designator="SRT"
)

ELBOW_JOINT = CodedConcept(
    value="T-15430",
    meaning="Elbow joint",
    scheme_designator="SRT"
)

FOREARM = CodedConcept(
    value="T-D8500",
    meaning="Forearm",
    scheme_designator="SRT"
)

LEFT_LOWER_QUADRANT_OF_ABDOMEN = CodedConcept(
    value="T-D4140",
    meaning="Left lower quadrant of abdomen",
    scheme_designator="SRT"
)

DURA_MATER = CodedConcept(
    value="T-A1120",
    meaning="Dura mater",
    scheme_designator="SRT"
)

HIPPOCAMPUS = CodedConcept(
    value="T-A2570",
    meaning="Hippocampus",
    scheme_designator="SRT"
)

CEREBROSPINAL_FLUID = CodedConcept(
    value="T-A1000",
    meaning="Cerebrospinal Fluid",
    scheme_designator="SRT"
)

PRIMITIVE_PULMONARY_ARTERY = CodedConcept(
    value="T-F7040",
    meaning="Primitive pulmonary artery",
    scheme_designator="SRT"
)

LIMBIC_LOBE = CodedConcept(
    value="T-A0036",
    meaning="Limbic lobe",
    scheme_designator="SRT"
)

EYE_REGION = CodedConcept(
    value="T-D0801",
    meaning="Eye region",
    scheme_designator="SRT"
)

WRIST_JOINT = CodedConcept(
    value="T-15460",
    meaning="Wrist joint",
    scheme_designator="SRT"
)

LYMPH_NODE = CodedConcept(
    value="T-C4000",
    meaning="Lymph node",
    scheme_designator="SRT"
)

KIDNEY = CodedConcept(
    value="T-71000",
    meaning="Kidney",
    scheme_designator="SRT"
)

GENICULAR_ARTERY = CodedConcept(
    value="T-47490",
    meaning="Genicular artery",
    scheme_designator="SRT"
)

LESSER_SAPHENOUS_VEIN = CodedConcept(
    value="T-49550",
    meaning="Lesser Saphenous Vein",
    scheme_designator="SRT"
)

AZYGOS_VEIN = CodedConcept(
    value="T-48340",
    meaning="Azygos vein",
    scheme_designator="SRT"
)

PULMONARY_VEIN = CodedConcept(
    value="T-48581",
    meaning="Pulmonary vein",
    scheme_designator="SRT"
)

BRACHIAL_PLEXUS = CodedConcept(
    value="T-A9090",
    meaning="Brachial plexus",
    scheme_designator="SRT"
)

ATRIAL_SEPTAL_DEFECT = CodedConcept(
    value="D4-31220",
    meaning="Atrial Septal Defect",
    scheme_designator="SRT"
)

LOBE_OF_LUNG = CodedConcept(
    value="T-28770",
    meaning="Lobe of lung",
    scheme_designator="SRT"
)

SIGMOID_COLON = CodedConcept(
    value="T-59470",
    meaning="Sigmoid colon",
    scheme_designator="SRT"
)

EYELID = CodedConcept(
    value="T-AA810",
    meaning="Eyelid",
    scheme_designator="SRT"
)

TERMINAL_INTERNAL_CAROTID_ARTERY = CodedConcept(
    value="R-102BD",
    meaning="Terminal internal carotid artery",
    scheme_designator="SRT"
)

INTERNAL_CAROTID_ARTERY_C5_SEGMENT = CodedConcept(
    value="R-102BB",
    meaning="Internal Carotid Artery C5 segment",
    scheme_designator="SRT"
)

DIGITAL_ARTERY_OF_HAND = CodedConcept(
    value="T-47260",
    meaning="Digital artery of hand",
    scheme_designator="SRT"
)

PECTORALIS_MINOR_MUSCLE = CodedConcept(
    value="T-14120",
    meaning="Pectoralis minor muscle",
    scheme_designator="SRT"
)

ABDOMINAL_WALL_MUSCLE = CodedConcept(
    value="T-14001",
    meaning="Abdominal wall muscle",
    scheme_designator="SRT"
)

ADRENAL_GLAND = CodedConcept(
    value="T-B3000",
    meaning="Adrenal gland",
    scheme_designator="SRT"
)

CHEST_WALL_MUSCLE = CodedConcept(
    value="T-14122",
    meaning="Chest wall muscle",
    scheme_designator="SRT"
)

LARGE_INTESTINE = CodedConcept(
    value="T-59000",
    meaning="Large intestine",
    scheme_designator="SRT"
)

INTRAPELVIC = CodedConcept(
    value="T-D6221",
    meaning="Intra-pelvic",
    scheme_designator="SRT"
)

ENTORHINAL_CORTEX = CodedConcept(
    value="T-A2594",
    meaning="Entorhinal Cortex",
    scheme_designator="SRT"
)

RIGHT_MAIN_BRONCHUS = CodedConcept(
    value="T-26100",
    meaning="Right main bronchus",
    scheme_designator="SRT"
)

CAUDATE_NUCLEUS = CodedConcept(
    value="T-A3200",
    meaning="Caudate nucleus",
    scheme_designator="SRT"
)

LEVATORES_COSTARUM_MUSCLES = CodedConcept(
    value="T-14150",
    meaning="Levatores costarum muscles",
    scheme_designator="SRT"
)

URETER = CodedConcept(
    value="T-73000",
    meaning="Ureter",
    scheme_designator="SRT"
)

CENTRAL_RETINAL_VEIN = CodedConcept(
    value="T-48286",
    meaning="Central Retinal Vein",
    scheme_designator="SRT"
)

ILIOCOSTALIS_MUSCLE = CodedConcept(
    value="T-14030",
    meaning="Iliocostalis muscle",
    scheme_designator="SRT"
)

MEDIAN_CUBITAL_VEIN = CodedConcept(
    value="T-49250",
    meaning="Median Cubital vein",
    scheme_designator="SRT"
)

JOINT = CodedConcept(
    value="T-15001",
    meaning="Joint",
    scheme_designator="SRT"
)

BONE_OF_UPPER_LIMB = CodedConcept(
    value="T-D0821",
    meaning="Bone of upper limb",
    scheme_designator="SRT"
)

PATENT_DUCTUS_ARTERIOSUS = CodedConcept(
    value="D4-32012",
    meaning="Patent ductus arteriosus",
    scheme_designator="SRT"
)

VAGINA = CodedConcept(
    value="T-82000",
    meaning="Vagina",
    scheme_designator="SRT"
)

LOWER_LEG = CodedConcept(
    value="T-D9400",
    meaning="Lower leg",
    scheme_designator="SRT"
)

ABDOMINAL_AORTA = CodedConcept(
    value="T-42500",
    meaning="Abdominal aorta",
    scheme_designator="SRT"
)

JUXTAPOSED_ATRIAL_APPENDAGE = CodedConcept(
    value="D4-31052",
    meaning="Juxtaposed atrial appendage",
    scheme_designator="SRT"
)

ERECTOR_SPINAE_MUSCLE = CodedConcept(
    value="T-14020",
    meaning="Erector spinae muscle",
    scheme_designator="SRT"
)

SERRATUS_ANTERIOR_MUSCLE = CodedConcept(
    value="T-14140",
    meaning="Serratus anterior muscle",
    scheme_designator="SRT"
)

BODY_CONDUIT = CodedConcept(
    value="T-D00AB",
    meaning="Body conduit",
    scheme_designator="SRT"
)

INTERNAL_JUGULAR_VEIN = CodedConcept(
    value="T-48170",
    meaning="Internal jugular vein",
    scheme_designator="SRT"
)

PELVIS = CodedConcept(
    value="T-D6000",
    meaning="Pelvis",
    scheme_designator="SRT"
)

CRANIAL_VENOUS_SYSTEM = CodedConcept(
    value="T-A0191",
    meaning="Cranial venous system",
    scheme_designator="SRT"
)

PIA_MATER = CodedConcept(
    value="T-A1280",
    meaning="Pia mater",
    scheme_designator="SRT"
)

BRONCHUS = CodedConcept(
    value="T-26000",
    meaning="Bronchus",
    scheme_designator="SRT"
)

MIDDLE_LOBE_OF_RIGHT_LUNG = CodedConcept(
    value="T-28300",
    meaning="Middle lobe of right lung",
    scheme_designator="SRT"
)

POSTERIOR_CEREBRAL_ARTERY = CodedConcept(
    value="T-45900",
    meaning="Posterior Cerebral Artery",
    scheme_designator="SRT"
)

CORPUS_STRIATUM = CodedConcept(
    value="T-A3100",
    meaning="Corpus striatum",
    scheme_designator="SRT"
)

SUPRARENAL_AORTA = CodedConcept(
    value="T-42510",
    meaning="Supra-renal Aorta",
    scheme_designator="SRT"
)

TESTIS = CodedConcept(
    value="T-94000",
    meaning="Testis",
    scheme_designator="SRT"
)

LATISSIMUS_DORSI_MUSCLE = CodedConcept(
    value="T-14172",
    meaning="Latissimus dorsi muscle",
    scheme_designator="SRT"
)

TRAPEZIUS_MUSCLE = CodedConcept(
    value="T-14171",
    meaning="Trapezius muscle",
    scheme_designator="SRT"
)

SPINALIS_MUSCLE = CodedConcept(
    value="T-14050",
    meaning="Spinalis muscle",
    scheme_designator="SRT"
)

BASILIC_VEIN = CodedConcept(
    value="T-49230",
    meaning="Basilic vein",
    scheme_designator="SRT"
)

AXILLARY_VEIN = CodedConcept(
    value="T-49110",
    meaning="Axillary vein",
    scheme_designator="SRT"
)

AXILLARY_FASCIA = CodedConcept(
    value="T-18774",
    meaning="Axillary Fascia",
    scheme_designator="SRT"
)

CAROTID_BODY = CodedConcept(
    value="T-B4000",
    meaning="Carotid Body",
    scheme_designator="SRT"
)

BRACHIAL_VEIN = CodedConcept(
    value="T-49350",
    meaning="Brachial vein",
    scheme_designator="SRT"
)

SPINAL_CEREBROSPINAL_FLUID_PATHWAY = CodedConcept(
    value="T-D0721",
    meaning="Spinal cerebrospinal fluid pathway",
    scheme_designator="SRT"
)

UTERUS_AND_FALLOPIAN_TUBES = CodedConcept(
    value="T-88920",
    meaning="Uterus and fallopian tubes",
    scheme_designator="SRT"
)

INGUINAL_REGION = CodedConcept(
    value="T-D7000",
    meaning="Inguinal region",
    scheme_designator="SRT"
)

LOWER_INNER_QUADRANT_OF_BREAST = CodedConcept(
    value="T-04003",
    meaning="Lower inner quadrant of breast",
    scheme_designator="SRT"
)

UPPER_INNER_QUADRANT_OF_BREAST = CodedConcept(
    value="T-04002",
    meaning="Upper inner quadrant of breast",
    scheme_designator="SRT"
)

BREAST = CodedConcept(
    value="T-04000",
    meaning="Breast",
    scheme_designator="SRT"
)

PANCREATIC_DUCT_AND_BILE_DUCT_SYSTEMS = CodedConcept(
    value="T-65600",
    meaning="Pancreatic duct and bile duct systems",
    scheme_designator="SRT"
)

AMYGDALA = CodedConcept(
    value="T-A3230",
    meaning="Amygdala",
    scheme_designator="SRT"
)

CEREBRAL_CORTEX = CodedConcept(
    value="T-A2020",
    meaning="Cerebral cortex",
    scheme_designator="SRT"
)

INNER_EAR = CodedConcept(
    value="T-AB700",
    meaning="Inner ear",
    scheme_designator="SRT"
)

LOWER_OUTER_QUADRANT_OF_BREAST = CodedConcept(
    value="T-04005",
    meaning="Lower outer quadrant of breast",
    scheme_designator="SRT"
)

SALIVARY_GLAND = CodedConcept(
    value="T-61007",
    meaning="Salivary gland",
    scheme_designator="SRT"
)

SUPERIOR_CEREBELLAR_PEDUNCLE = CodedConcept(
    value="T-A6620",
    meaning="Superior cerebellar peduncle",
    scheme_designator="SRT"
)

UPPER_OUTER_QUADRANT_OF_BREAST = CodedConcept(
    value="T-04004",
    meaning="Upper outer quadrant of breast",
    scheme_designator="SRT"
)

RENAL_PELVIS = CodedConcept(
    value="T-72000",
    meaning="Renal pelvis",
    scheme_designator="SRT"
)

EXTERNAL_INTERCOSTAL_MUSCLE = CodedConcept(
    value="T-14161",
    meaning="External intercostal muscle",
    scheme_designator="SRT"
)

LONGISSIMUS_MUSCLE = CodedConcept(
    value="T-14040",
    meaning="Longissimus muscle",
    scheme_designator="SRT"
)

INTERNAL_INTERCOSTAL_MUSCLE = CodedConcept(
    value="T-14163",
    meaning="Internal intercostal muscle",
    scheme_designator="SRT"
)

INNERMOST_INTERCOSTAL_MUSCLES = CodedConcept(
    value="T-14165",
    meaning="Innermost intercostal muscles",
    scheme_designator="SRT"
)

TRANSVERSUS_THORACIS = CodedConcept(
    value="T-14167",
    meaning="Transversus thoracis",
    scheme_designator="SRT"
)

CEPHALIC_VEIN = CodedConcept(
    value="T-49240",
    meaning="Cephalic vein",
    scheme_designator="SRT"
)

SUBCOSTAL_MUSCLE = CodedConcept(
    value="T-14166",
    meaning="Subcostal muscle",
    scheme_designator="SRT"
)

INTERNAL_AUDITORY_CANAL = CodedConcept(
    value="T-AB959",
    meaning="Internal Auditory Canal",
    scheme_designator="SRT"
)

UTERUS = CodedConcept(
    value="T-83000",
    meaning="Uterus",
    scheme_designator="SRT"
)

INTERNAL_CAROTID_ARTERY_C6_SEGMENT = CodedConcept(
    value="R-FAED1",
    meaning="Internal Carotid Artery C6 segment",
    scheme_designator="SRT"
)

UPPER_ARM = CodedConcept(
    value="T-D8200",
    meaning="Upper arm",
    scheme_designator="SRT"
)

CENTRAL_NERVOUS_SYSTEM = CodedConcept(
    value="T-A0090",
    meaning="Central nervous system",
    scheme_designator="SRT"
)

WHITE_MATTER = CodedConcept(
    value="T-A0095",
    meaning="White Matter",
    scheme_designator="SRT"
)

CEREBRAL_WHITE_MATTER = CodedConcept(
    value="T-A2030",
    meaning="Cerebral White Matter",
    scheme_designator="SRT"
)

GRAY_MATTER = CodedConcept(
    value="T-A0096",
    meaning="Gray Matter",
    scheme_designator="SRT"
)

MIDDLE_CEREBELLAR_PEDUNCLE = CodedConcept(
    value="T-A6630",
    meaning="Middle cerebellar peduncle",
    scheme_designator="SRT"
)

