"""CID 4268 CornealTopographyMapValueType
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


CORNEAL_AXIAL_POWER_MAP = CodedConcept(
    value="111940",
    meaning="Corneal axial power map",
    scheme_designator="DCM"
)

CORNEAL_INSTANTANEOUS_POWER_MAP = CodedConcept(
    value="111941",
    meaning="Corneal instantaneous power map",
    scheme_designator="DCM"
)

CORNEAL_REFRACTIVE_POWER_MAP = CodedConcept(
    value="111942",
    meaning="Corneal refractive power map",
    scheme_designator="DCM"
)

CORNEAL_ELEVATION_MAP = CodedConcept(
    value="111943",
    meaning="Corneal elevation map",
    scheme_designator="DCM"
)

CORNEAL_WAVEFRONT_MAP = CodedConcept(
    value="111944",
    meaning="Corneal wavefront map",
    scheme_designator="DCM"
)

