"""CID 9523 RoboticRadiotherapyProcedureTechniques
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


SYNCHRONIZED_ROBOTIC_TREATMENT = CodedConcept(
    value="130139",
    meaning="Synchronized Robotic Treatment",
    scheme_designator="DCM"
)

NONSYNCHRONIZED_ROBOTIC_TREATMENT = CodedConcept(
    value="130140",
    meaning="Non-Synchronized Robotic Treatment",
    scheme_designator="DCM"
)

