"""CID 6147 ResponseCriteria
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


RECIST_1_0 = CodedConcept(
    value="126080",
    meaning="RECIST 1.0",
    scheme_designator="DCM"
)

RECIST_1_1 = CodedConcept(
    value="126081",
    meaning="RECIST 1.1",
    scheme_designator="DCM"
)

WHO = CodedConcept(
    value="112029",
    meaning="WHO",
    scheme_designator="DCM"
)

RANO = CodedConcept(
    value="C114879",
    meaning="RANO",
    scheme_designator="NCIt"
)

