"""CID 6202 ColonFindingorFeatureModifier
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


CHEST_TUBE = CodedConcept(
    value="112173",
    meaning="Chest tube",
    scheme_designator="DCM"
)

KIDNEY_STENT = CodedConcept(
    value="112175",
    meaning="Kidney stent",
    scheme_designator="DCM"
)

PANCREATIC_STENT = CodedConcept(
    value="112176",
    meaning="Pancreatic stent",
    scheme_designator="DCM"
)

COIN = CodedConcept(
    value="112178",
    meaning="Coin",
    scheme_designator="DCM"
)

FIDUCIAL_MARK = CodedConcept(
    value="112171",
    meaning="Fiducial mark",
    scheme_designator="DCM"
)

JEJUNOSTOMY_TUBE = CodedConcept(
    value="A-26434",
    meaning="Jejunostomy tube",
    scheme_designator="SRT"
)

PROSTATE = CodedConcept(
    value="T-92000",
    meaning="Prostate",
    scheme_designator="SRT"
)

TESTIS = CodedConcept(
    value="T-94000",
    meaning="Testis",
    scheme_designator="SRT"
)

UROSTOMY_BAG = CodedConcept(
    value="A-105E3",
    meaning="Urostomy bag",
    scheme_designator="SRT"
)

AORTA = CodedConcept(
    value="T-42000",
    meaning="Aorta",
    scheme_designator="SRT"
)

COLOSTOMY_BAG = CodedConcept(
    value="A-10DBC",
    meaning="Colostomy bag",
    scheme_designator="SRT"
)

KIDNEY = CodedConcept(
    value="T-71000",
    meaning="Kidney",
    scheme_designator="SRT"
)

PROSTHESIS = CodedConcept(
    value="A-04000",
    meaning="Prosthesis",
    scheme_designator="SRT"
)

ILEOSTOMY_BAG = CodedConcept(
    value="A-10029",
    meaning="Ileostomy bag",
    scheme_designator="SRT"
)

MUSCLE = CodedConcept(
    value="T-13001",
    meaning="Muscle",
    scheme_designator="SRT"
)

UROSTOMY_SET = CodedConcept(
    value="A-10703",
    meaning="Urostomy set",
    scheme_designator="SRT"
)

JEWELRY = CodedConcept(
    value="A-61000",
    meaning="Jewelry",
    scheme_designator="SRT"
)

SCAR_TISSUE = CodedConcept(
    value="M-78060",
    meaning="Scar tissue",
    scheme_designator="SRT"
)

SUTURE = CodedConcept(
    value="A-13500",
    meaning="Suture",
    scheme_designator="SRT"
)

STAPLE = CodedConcept(
    value="A-13600",
    meaning="Staple",
    scheme_designator="SRT"
)

VENA_CAVA_FILTER = CodedConcept(
    value="A-14611",
    meaning="Vena cava filter",
    scheme_designator="SRT"
)

BLOOD_VESSEL = CodedConcept(
    value="T-40000",
    meaning="Blood Vessel",
    scheme_designator="SRT"
)

BONE = CodedConcept(
    value="T-D016E",
    meaning="Bone",
    scheme_designator="SRT"
)

NEEDLE = CodedConcept(
    value="A-30360",
    meaning="Needle",
    scheme_designator="SRT"
)

URETHRAL_CATHETER = CodedConcept(
    value="A-26864",
    meaning="Urethral catheter",
    scheme_designator="SRT"
)

SPLEEN = CodedConcept(
    value="T-C3000",
    meaning="Spleen",
    scheme_designator="SRT"
)

INFERIOR_VENA_CAVA = CodedConcept(
    value="T-48710",
    meaning="Inferior vena cava",
    scheme_designator="SRT"
)

SEMINAL_VESICLE = CodedConcept(
    value="T-93000",
    meaning="Seminal Vesicle",
    scheme_designator="SRT"
)

CATHETER = CodedConcept(
    value="A-26800",
    meaning="Catheter",
    scheme_designator="SRT"
)

OVARY = CodedConcept(
    value="T-87000",
    meaning="Ovary",
    scheme_designator="SRT"
)

ADRENAL_GLAND = CodedConcept(
    value="T-B3000",
    meaning="Adrenal gland",
    scheme_designator="SRT"
)

APPENDICEAL_STUMP = CodedConcept(
    value="T-D0874",
    meaning="Appendiceal stump",
    scheme_designator="SRT"
)

ILEOSTOMY_SET = CodedConcept(
    value="A-1009E",
    meaning="Ileostomy set",
    scheme_designator="SRT"
)

RECTAL_TUBE = CodedConcept(
    value="A-26440",
    meaning="Rectal tube",
    scheme_designator="SRT"
)

PIN = CodedConcept(
    value="A-12024",
    meaning="Pin",
    scheme_designator="SRT"
)

CERVIX = CodedConcept(
    value="T-83200",
    meaning="Cervix",
    scheme_designator="SRT"
)

COLOSTOMY_SET = CodedConcept(
    value="A-120DD",
    meaning="Colostomy set",
    scheme_designator="SRT"
)

UTERUS = CodedConcept(
    value="T-83000",
    meaning="Uterus",
    scheme_designator="SRT"
)

RECTUM = CodedConcept(
    value="T-59600",
    meaning="Rectum",
    scheme_designator="SRT"
)

APPENDIX = CodedConcept(
    value="T-59200",
    meaning="Appendix",
    scheme_designator="SRT"
)

LIVER = CodedConcept(
    value="T-62000",
    meaning="Liver",
    scheme_designator="SRT"
)

LUNG = CodedConcept(
    value="T-28000",
    meaning="Lung",
    scheme_designator="SRT"
)

BLADDER = CodedConcept(
    value="T-74000",
    meaning="Bladder",
    scheme_designator="SRT"
)

BULLET = CodedConcept(
    value="A-32110",
    meaning="Bullet",
    scheme_designator="SRT"
)

URETERAL_STENT = CodedConcept(
    value="A-11C08",
    meaning="Ureteral stent",
    scheme_designator="SRT"
)

