"""CID 3710 CoronaryDominance
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


BALANCED_CORONARY_DOMINANCE = CodedConcept(
    value="D4-3252D",
    meaning="Balanced Coronary Dominance",
    scheme_designator="SRT"
)

LEFT_CORONARY_DOMINANCE = CodedConcept(
    value="D4-3252C",
    meaning="Left Coronary Dominance",
    scheme_designator="SRT"
)

RIGHT_CORONARY_DOMINANCE = CodedConcept(
    value="D4-3252B",
    meaning="Right Coronary Dominance",
    scheme_designator="SRT"
)

