"""CID 3691 ECGControlVariablesText
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


INTERPOLATOR = CodedConcept(
    value="10:11414",
    meaning="Interpolator",
    scheme_designator="MDC"
)

HIGH_PASS_FILTER = CodedConcept(
    value="10:11404",
    meaning="High pass filter",
    scheme_designator="MDC"
)

INTERPOLATOR_DESCRIPTION = CodedConcept(
    value="10:11416",
    meaning="Interpolator description",
    scheme_designator="MDC"
)

HIGH_PASS_FILTER_DESCRIPTION = CodedConcept(
    value="10:11406",
    meaning="High pass filter description",
    scheme_designator="MDC"
)

NOTCH_FILTER = CodedConcept(
    value="10:11407",
    meaning="Notch filter",
    scheme_designator="MDC"
)

NOTCH_FILTER_DESCRIPTION = CodedConcept(
    value="10:11410",
    meaning="Notch filter description",
    scheme_designator="MDC"
)

BASELINE_DESCRIPTION = CodedConcept(
    value="10:11412",
    meaning="Baseline description",
    scheme_designator="MDC"
)

LOW_PASS_FILTER = CodedConcept(
    value="10:11402",
    meaning="Low pass filter",
    scheme_designator="MDC"
)

