"""CID 6129 ChestSiteInvolvement
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


LOBAR = CodedConcept(
    value="112158",
    meaning="Lobar",
    scheme_designator="DCM"
)

BRONCHIAL = CodedConcept(
    value="R-40939",
    meaning="Bronchial",
    scheme_designator="SRT"
)

UPPER_ABDOMEN = CodedConcept(
    value="T-D4001",
    meaning="Upper abdomen",
    scheme_designator="SRT"
)

INTERSTITIAL_TISSUE = CodedConcept(
    value="T-1A007",
    meaning="Interstitial tissue",
    scheme_designator="SRT"
)

CHEST_WALL = CodedConcept(
    value="T-D3050",
    meaning="Chest wall",
    scheme_designator="SRT"
)

AORTA = CodedConcept(
    value="T-42000",
    meaning="Aorta",
    scheme_designator="SRT"
)

LUNG = CodedConcept(
    value="T-28000",
    meaning="Lung",
    scheme_designator="SRT"
)

PLEURAL_STRUCTURE = CodedConcept(
    value="T-29000",
    meaning="Pleural structure",
    scheme_designator="SRT"
)

MEDIASTINUM = CodedConcept(
    value="T-D3300",
    meaning="Mediastinum",
    scheme_designator="SRT"
)

HILUM_OF_LUNG = CodedConcept(
    value="T-28080",
    meaning="Hilum of lung",
    scheme_designator="SRT"
)

