"""CID 3117 AttenuationCorrectionMethods
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


OSEM_ALGORITHM = CodedConcept(
    value="122720",
    meaning="OSEM algorithm",
    scheme_designator="DCM"
)

CHANG_METHOD = CodedConcept(
    value="122721",
    meaning="Chang method",
    scheme_designator="DCM"
)

