"""CID 8111 SpecimenPreparationProcedure
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


SPECIMEN_STORAGE = CodedConcept(
    value="111729",
    meaning="Specimen storage",
    scheme_designator="DCM"
)

SPECIMEN_PROCESSING = CodedConcept(
    value="P3-05000",
    meaning="Specimen processing",
    scheme_designator="SRT"
)

SPECIMEN_COLLECTION = CodedConcept(
    value="P3-02000",
    meaning="Specimen collection",
    scheme_designator="SRT"
)

SAMPLING_OF_TISSUE_SPECIMEN = CodedConcept(
    value="P3-4000A",
    meaning="Sampling of tissue specimen",
    scheme_designator="SRT"
)

SPECIMEN_RECEIVING = CodedConcept(
    value="P3-05013",
    meaning="Specimen receiving",
    scheme_designator="SRT"
)

STAINING = CodedConcept(
    value="P3-00003",
    meaning="Staining",
    scheme_designator="SRT"
)

