"""CID 12231 VolumeFlowMethods
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


DOPPLER_VOLUME_FLOW = CodedConcept(
    value="125219",
    meaning="Doppler Volume Flow",
    scheme_designator="DCM"
)

PROXIMAL_ISOVELOCITY_SURFACE_AREA = CodedConcept(
    value="125216",
    meaning="Proximal Isovelocity Surface Area",
    scheme_designator="DCM"
)

