"""CID 3748 AngiographicEFTestingMethod
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


BIPLANE_ANGIOGRAPHY = CodedConcept(
    value="122060",
    meaning="Bi-plane Angiography",
    scheme_designator="DCM"
)

SINGLE_PLANE_ANGIOGRAPHY = CodedConcept(
    value="122059",
    meaning="Single plane Angiography",
    scheme_designator="DCM"
)

