"""CID 3491 IVUSLesionMorphologies
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


INSTENT_NEOINTIMA = CodedConcept(
    value="122357",
    meaning="In-Stent Neointima",
    scheme_designator="DCM"
)

SOFT_PLAQUE = CodedConcept(
    value="122356",
    meaning="Soft plaque",
    scheme_designator="DCM"
)

VULNERABLE_PLAQUE = CodedConcept(
    value="122389",
    meaning="Vulnerable Plaque",
    scheme_designator="DCM"
)

ERODED_PLAQUE = CodedConcept(
    value="122390",
    meaning="Eroded Plaque",
    scheme_designator="DCM"
)

NECROTICLIPIDIC_PLAQUE = CodedConcept(
    value="122395",
    meaning="Necrotic-Lipidic Plaque",
    scheme_designator="DCM"
)

PLAQUE_RUPTURE = CodedConcept(
    value="122363",
    meaning="Plaque Rupture",
    scheme_designator="DCM"
)

FALSE_LUMEN = CodedConcept(
    value="122361",
    meaning="False Lumen",
    scheme_designator="DCM"
)

FIBROLIPIDIC_PLAQUE = CodedConcept(
    value="122394",
    meaning="Fibro-Lipidic Plaque",
    scheme_designator="DCM"
)

CONCENTRIC = CodedConcept(
    value="R-4047B",
    meaning="Concentric",
    scheme_designator="SRT"
)

PLAQUE_ULCERATION = CodedConcept(
    value="M-52103",
    meaning="Plaque Ulceration",
    scheme_designator="SRT"
)

VASCULAR_CALCIFICATION = CodedConcept(
    value="D6-34737",
    meaning="Vascular Calcification",
    scheme_designator="SRT"
)

ECCENTRIC = CodedConcept(
    value="R-40416",
    meaning="Eccentric",
    scheme_designator="SRT"
)

FIBROUS_PLAQUE = CodedConcept(
    value="M-78260",
    meaning="Fibrous Plaque",
    scheme_designator="SRT"
)

ARTERIAL_TRUE_ANEURYSM = CodedConcept(
    value="D3-80027",
    meaning="Arterial (True) Aneurysm",
    scheme_designator="SRT"
)

PSEUDO_ANEURYSM = CodedConcept(
    value="M-32390",
    meaning="Pseudo Aneurysm",
    scheme_designator="SRT"
)

THROMBUS = CodedConcept(
    value="M-35001",
    meaning="Thrombus",
    scheme_designator="SRT"
)

