"""CID 7111 Fiducials
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


MR_MARKER = CodedConcept(
    value="129308",
    meaning="MR Marker",
    scheme_designator="DCM"
)

INFRARED_REFLECTOR_MARKER = CodedConcept(
    value="129309",
    meaning="Infrared Reflector Marker",
    scheme_designator="DCM"
)

COIL_MARKER = CodedConcept(
    value="129301",
    meaning="Coil Marker",
    scheme_designator="DCM"
)

CYLINDER_MARKER = CodedConcept(
    value="129303",
    meaning="Cylinder Marker",
    scheme_designator="DCM"
)

TRANSPONDER_MARKER = CodedConcept(
    value="129306",
    meaning="Transponder Marker",
    scheme_designator="DCM"
)

WIRE_MARKER = CodedConcept(
    value="129305",
    meaning="Wire Marker",
    scheme_designator="DCM"
)

INTERHEMISPHERIC_PLANE = CodedConcept(
    value="125030",
    meaning="Inter-Hemispheric Plane",
    scheme_designator="DCM"
)

VISIBLE_REFLECTOR_MARKER = CodedConcept(
    value="129310",
    meaning="Visible Reflector Marker",
    scheme_designator="DCM"
)

LEFT_HEMISPHERE_MOST_INFERIOR = CodedConcept(
    value="125038",
    meaning="Left Hemisphere Most Inferior",
    scheme_designator="DCM"
)

SPHERE = CodedConcept(
    value="122485",
    meaning="Sphere",
    scheme_designator="DCM"
)

LEFT_HEMISPHERE_MOST_SUPERIOR = CodedConcept(
    value="125037",
    meaning="Left Hemisphere Most Superior",
    scheme_designator="DCM"
)

LEFT_HEMISPHERE_MOST_POSTERIOR = CodedConcept(
    value="125036",
    meaning="Left Hemisphere Most Posterior",
    scheme_designator="DCM"
)

LEFT_HEMISPHERE_MOST_ANTERIOR = CodedConcept(
    value="125035",
    meaning="Left Hemisphere Most Anterior",
    scheme_designator="DCM"
)

RIGHT_HEMISPHERE_MOST_INFERIOR = CodedConcept(
    value="125034",
    meaning="Right Hemisphere Most Inferior",
    scheme_designator="DCM"
)

RIGHT_HEMISPHERE_MOST_SUPERIOR = CodedConcept(
    value="125033",
    meaning="Right Hemisphere Most Superior",
    scheme_designator="DCM"
)

RIGHT_HEMISPHERE_MOST_POSTERIOR = CodedConcept(
    value="125032",
    meaning="Right Hemisphere Most Posterior",
    scheme_designator="DCM"
)

RIGHT_HEMISPHERE_MOST_ANTERIOR = CodedConcept(
    value="125031",
    meaning="Right Hemisphere Most Anterior",
    scheme_designator="DCM"
)

AORTIC_BIFURCATION = CodedConcept(
    value="T-42580",
    meaning="Aortic Bifurcation",
    scheme_designator="SRT"
)

STENT = CodedConcept(
    value="A-25500",
    meaning="Stent",
    scheme_designator="SRT"
)

OSTIUM = CodedConcept(
    value="R-4215C",
    meaning="Ostium",
    scheme_designator="SRT"
)

VEIN = CodedConcept(
    value="T-48000",
    meaning="Vein",
    scheme_designator="SRT"
)

VASCULAR_CALCIFICATION = CodedConcept(
    value="D6-34737",
    meaning="Vascular Calcification",
    scheme_designator="SRT"
)

VESSEL_ORIGIN = CodedConcept(
    value="G-036A",
    meaning="Vessel Origin",
    scheme_designator="SRT"
)

CONTRAST_MEDIA = CodedConcept(
    value="F-61D54",
    meaning="Contrast media",
    scheme_designator="SRT"
)

RENAL_ARTERY = CodedConcept(
    value="T-46600",
    meaning="Renal Artery",
    scheme_designator="SRT"
)

ANTERIOR_COMMISSURE = CodedConcept(
    value="T-A2980",
    meaning="Anterior Commissure",
    scheme_designator="SRT"
)

COMMON_ILIAC_BIFURCATION = CodedConcept(
    value="R-10258",
    meaning="Common Iliac Bifurcation",
    scheme_designator="SRT"
)

POSTERIOR_COMMISSURE = CodedConcept(
    value="T-A4904",
    meaning="Posterior Commissure",
    scheme_designator="SRT"
)

CATHETER = CodedConcept(
    value="A-26800",
    meaning="Catheter",
    scheme_designator="SRT"
)

RADIOACTIVE_IMPLANT = CodedConcept(
    value="A-04034",
    meaning="Radioactive implant",
    scheme_designator="SRT"
)

FIBROUS_PLAQUE = CodedConcept(
    value="M-78260",
    meaning="Fibrous Plaque",
    scheme_designator="SRT"
)

COLLATERAL_BRANCH_OF_VESSEL = CodedConcept(
    value="G-035D",
    meaning="Collateral Branch of vessel",
    scheme_designator="SRT"
)

BB_SHOT_LEAD_PELLET_ = CodedConcept(
    value="A-32475",
    meaning="BB Shot (Lead Pellet)",
    scheme_designator="SRT"
)

CLIP = CodedConcept(
    value="A-12062",
    meaning="Clip",
    scheme_designator="SRT"
)

