"""CID 9241 RadiotherapyGeneralWorkitemDefinition
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


RT_PATIENT_SETUP = CodedConcept(
    value="121701",
    meaning="RT Patient Setup",
    scheme_designator="DCM"
)

RT_PATIENT_POSITION_INTREATMENTSESSION_REVIEW = CodedConcept(
    value="121723",
    meaning="RT Patient Position In-treatment-session Review",
    scheme_designator="DCM"
)

RT_TREATMENT_QA_BY_RT_ION_PLAN_DIFFERENCE_CHECK = CodedConcept(
    value="121734",
    meaning="RT Treatment QA by RT Ion Plan Difference Check",
    scheme_designator="DCM"
)

RT_TREATMENT_SIMULATION_WITH_INTERNAL_VERIFICATION = CodedConcept(
    value="121724",
    meaning="RT Treatment Simulation with Internal Verification",
    scheme_designator="DCM"
)

RT_BRACHY_TREATMENT = CodedConcept(
    value="121735",
    meaning="RT Brachy Treatment",
    scheme_designator="DCM"
)

RT_TREATMENT_QA_BY_RT_PLAN_DIFFERENCE_CHECK = CodedConcept(
    value="121732",
    meaning="RT Treatment QA by RT Plan Difference Check",
    scheme_designator="DCM"
)

RT_PATIENT_POSITION_ADJUSTMENT = CodedConcept(
    value="121722",
    meaning="RT Patient Position Adjustment",
    scheme_designator="DCM"
)

RT_TREATMENT_QA_BY_RT_ION_PLAN_DOSE_CHECK = CodedConcept(
    value="121733",
    meaning="RT Treatment QA by RT Ion Plan Dose Check",
    scheme_designator="DCM"
)

RT_MACHINE_QA = CodedConcept(
    value="121730",
    meaning="RT Machine QA",
    scheme_designator="DCM"
)

RT_TREATMENT_QA_BY_RT_PLAN_DOSE_CHECK = CodedConcept(
    value="121731",
    meaning="RT Treatment QA by RT Plan Dose Check",
    scheme_designator="DCM"
)

RT_TREATMENT_QA_WITH_EXTERNAL_VERIFICATION = CodedConcept(
    value="121729",
    meaning="RT Treatment QA with External Verification",
    scheme_designator="DCM"
)

RT_TREATMENT_WITH_EXTERNAL_VERIFICATION = CodedConcept(
    value="121727",
    meaning="RT Treatment with External Verification",
    scheme_designator="DCM"
)

RT_TREATMENT_QA_WITH_INTERNAL_VERIFICATION = CodedConcept(
    value="121728",
    meaning="RT Treatment QA with Internal Verification",
    scheme_designator="DCM"
)

RT_TREATMENT_SIMULATION_WITH_EXTERNAL_VERIFICATION = CodedConcept(
    value="121725",
    meaning="RT Treatment Simulation with External Verification",
    scheme_designator="DCM"
)

RT_TREATMENT_WITH_INTERNAL_VERIFICATION = CodedConcept(
    value="121726",
    meaning="RT Treatment with Internal Verification",
    scheme_designator="DCM"
)

