"""CID 12115 RenalVessels
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


LOBAR_ARTERY = CodedConcept(
    value="T-4667C",
    meaning="Lobar Artery",
    scheme_designator="SRT"
)

ACCESSORY_RENAL_ARTERY = CodedConcept(
    value="T-46640",
    meaning="Accessory Renal Artery",
    scheme_designator="SRT"
)

INTERLOBAR_ARTERY_OF_KIDNEY = CodedConcept(
    value="T-4667D",
    meaning="Interlobar Artery of Kidney",
    scheme_designator="SRT"
)

ARCUATE_ARTERY_OF_THE_KIDNEY = CodedConcept(
    value="T-4668A",
    meaning="Arcuate Artery of the Kidney",
    scheme_designator="SRT"
)

HILAR_ARTERY = CodedConcept(
    value="G-035C",
    meaning="Hilar Artery",
    scheme_designator="SRT"
)

RENAL_VEIN = CodedConcept(
    value="T-48740",
    meaning="Renal Vein",
    scheme_designator="SRT"
)

SEGMENTAL_ARTERY = CodedConcept(
    value="T-46659",
    meaning="Segmental Artery",
    scheme_designator="SRT"
)

RENAL_ARTERY = CodedConcept(
    value="T-46600",
    meaning="Renal Artery",
    scheme_designator="SRT"
)

PERFORATING_ARTERY_OF_KIDNEY = CodedConcept(
    value="T-46668",
    meaning="Perforating Artery of Kidney",
    scheme_designator="SRT"
)

