"""CID 7456 UnitsofMeasureforAge
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


YEAR = CodedConcept(
    value="a",
    meaning="year",
    scheme_designator="UCUM"
)

MINUTE = CodedConcept(
    value="min",
    meaning="minute",
    scheme_designator="UCUM"
)

HOUR = CodedConcept(
    value="h",
    meaning="hour",
    scheme_designator="UCUM"
)

WEEK = CodedConcept(
    value="wk",
    meaning="week",
    scheme_designator="UCUM"
)

DAY = CodedConcept(
    value="d",
    meaning="day",
    scheme_designator="UCUM"
)

MONTH = CodedConcept(
    value="mo",
    meaning="month",
    scheme_designator="UCUM"
)

