"""CID 9233 RequestedReportTypes
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


FINAL_REPORT = CodedConcept(
    value="128005",
    meaning="Final Report",
    scheme_designator="DCM"
)

PRELIMINARY_REPORT = CodedConcept(
    value="121362",
    meaning="Preliminary Report",
    scheme_designator="DCM"
)

