"""CID 3815 SourceofVascularFinding
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


HYPERPLASIA = CodedConcept(
    value="M-72000",
    meaning="hyperplasia",
    scheme_designator="SRT"
)

EMBOLISM = CodedConcept(
    value="M-35300",
    meaning="embolism",
    scheme_designator="SRT"
)

VASCULITIS = CodedConcept(
    value="D3-80650",
    meaning="vasculitis",
    scheme_designator="SRT"
)

TRAUMA = CodedConcept(
    value="DF-00777",
    meaning="trauma",
    scheme_designator="SRT"
)

THROMBOSIS = CodedConcept(
    value="D3-80515",
    meaning="thrombosis",
    scheme_designator="SRT"
)

TUMOR = CodedConcept(
    value="M-8FFFF",
    meaning="tumor",
    scheme_designator="SRT"
)

SURGICAL = CodedConcept(
    value="G-B102",
    meaning="surgical",
    scheme_designator="SRT"
)

AFTER_PROCEDURE = CodedConcept(
    value="R-422A4",
    meaning="after procedure",
    scheme_designator="SRT"
)

