"""CID 12224 UltrasoundImageModes
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


M_MODE = CodedConcept(
    value="G-0394",
    meaning="M mode",
    scheme_designator="SRT"
)

MODE_2D = CodedConcept(
    value="G-03A2",
    meaning="2D mode",
    scheme_designator="SRT"
)

POWER_DOPPLER = CodedConcept(
    value="P0-02241",
    meaning="Power Doppler",
    scheme_designator="SRT"
)

MODE_3D = CodedConcept(
    value="P0-02242",
    meaning="3D mode",
    scheme_designator="SRT"
)

DOPPLER_CONTINUOUS_WAVE = CodedConcept(
    value="R-409E3",
    meaning="Doppler Continuous Wave",
    scheme_designator="SRT"
)

DOPPLER_COLOR_FLOW = CodedConcept(
    value="R-409E2",
    meaning="Doppler Color Flow",
    scheme_designator="SRT"
)

TISSUE_DOPPLER_IMAGING = CodedConcept(
    value="P5-B0128",
    meaning="Tissue Doppler Imaging",
    scheme_designator="SRT"
)

DOPPLER_PULSED = CodedConcept(
    value="R-409E4",
    meaning="Doppler Pulsed",
    scheme_designator="SRT"
)

