"""CID 7022 RadiotherapyPurposesofReference
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


REGISTRATION_CREATED_DURING_TREATMENT = CodedConcept(
    value="129211",
    meaning="Registration created during Treatment",
    scheme_designator="DCM"
)

RT_TREATMENT_PLAN_FOR_THE_POSITION_BEING_VERIFIED = CodedConcept(
    value="121310",
    meaning="RT treatment plan for the position being verified",
    scheme_designator="DCM"
)

REGISTRATION_USED_IN_PLANNING = CodedConcept(
    value="129210",
    meaning="Registration used in Planning",
    scheme_designator="DCM"
)

