"""CID 3111 NuclearCardiologyRadiopharmaceuticals
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


TC99M_SESTAMIBI = CodedConcept(
    value="C-B10A2",
    meaning="Tc-99m sestamibi",
    scheme_designator="SRT"
)

TC99M_TETROFOSMIN = CodedConcept(
    value="C-B10A4",
    meaning="Tc-99m tetrofosmin",
    scheme_designator="SRT"
)

THALLIUM201 = CodedConcept(
    value="C-B1130",
    meaning="Thallium-201",
    scheme_designator="SRT"
)

