"""CID 9505 FixationorPositioningDevices
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


RECTAL_BALLOON = CodedConcept(
    value="130120",
    meaning="Rectal Balloon",
    scheme_designator="DCM"
)

MOLD = CodedConcept(
    value="130113",
    meaning="Mold",
    scheme_designator="DCM"
)

HEAD_AND_NECK_MASK = CodedConcept(
    value="130112",
    meaning="Head and Neck Mask",
    scheme_designator="DCM"
)

HEAD_MASK = CodedConcept(
    value="130111",
    meaning="Head Mask",
    scheme_designator="DCM"
)

HEADFRAME = CodedConcept(
    value="130110",
    meaning="Headframe",
    scheme_designator="DCM"
)

VAGINAL_CYLINDER = CodedConcept(
    value="130121",
    meaning="Vaginal Cylinder",
    scheme_designator="DCM"
)

BODY_FRAME = CodedConcept(
    value="130117",
    meaning="Body Frame",
    scheme_designator="DCM"
)

BREAST_BOARD = CodedConcept(
    value="130116",
    meaning="Breast Board",
    scheme_designator="DCM"
)

CAST = CodedConcept(
    value="130114",
    meaning="Cast",
    scheme_designator="DCM"
)

WHOLE_BODY_POD = CodedConcept(
    value="130119",
    meaning="Whole Body Pod",
    scheme_designator="DCM"
)

VACUUM_MOLD = CodedConcept(
    value="130118",
    meaning="Vacuum Mold",
    scheme_designator="DCM"
)

BITE_BLOCK = CodedConcept(
    value="A-01105",
    meaning="Bite block",
    scheme_designator="SRT"
)

CHAIR = CodedConcept(
    value="R-FE814",
    meaning="Chair",
    scheme_designator="SRT"
)

HEADREST = CodedConcept(
    value="R-FEEC3",
    meaning="Headrest",
    scheme_designator="SRT"
)

TABLE = CodedConcept(
    value="A-17350",
    meaning="Table",
    scheme_designator="SRT"
)

