"""CID 6140 CalculationMethods
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


UNSPECIFIED_METHOD_OF_CALCULATION = CodedConcept(
    value="112187",
    meaning="Unspecified method of calculation",
    scheme_designator="DCM"
)

AGATSTON_SCORING_METHOD = CodedConcept(
    value="112055",
    meaning="Agatston scoring method",
    scheme_designator="DCM"
)

VOLUME_SCORING_METHOD = CodedConcept(
    value="112056",
    meaning="Volume scoring method",
    scheme_designator="DCM"
)

TWODIMENSIONAL_METHOD = CodedConcept(
    value="112188",
    meaning="Two-dimensional method",
    scheme_designator="DCM"
)

MASS_SCORING_METHOD = CodedConcept(
    value="112057",
    meaning="Mass scoring method",
    scheme_designator="DCM"
)

THREEDIMENSIONAL_METHOD = CodedConcept(
    value="112189",
    meaning="Three-dimensional method",
    scheme_designator="DCM"
)

ESTIMATED = CodedConcept(
    value="R-10260",
    meaning="Estimated",
    scheme_designator="SRT"
)

