"""CID 3118 LevelofRisk
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


MODERATE_TO_HIGH_RISK = CodedConcept(
    value="G-4046",
    meaning="Moderate to high risk",
    scheme_designator="SRT"
)

LOW_TO_MODERATE_RISK = CodedConcept(
    value="G-4045",
    meaning="Low to moderate risk",
    scheme_designator="SRT"
)

UNCERTAIN_RISK = CodedConcept(
    value="G-A648",
    meaning="Uncertain risk",
    scheme_designator="SRT"
)

NORMAL_RISK = CodedConcept(
    value="G-4044",
    meaning="Normal risk",
    scheme_designator="SRT"
)

HIGH_RISK = CodedConcept(
    value="G-4043",
    meaning="High risk",
    scheme_designator="SRT"
)

MODERATE_RISK = CodedConcept(
    value="G-4042",
    meaning="Moderate risk",
    scheme_designator="SRT"
)

LOW_RISK = CodedConcept(
    value="G-4041",
    meaning="Low risk",
    scheme_designator="SRT"
)

