"""CID 3451 CalibrationObjects
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


SPHERE = CodedConcept(
    value="122485",
    meaning="Sphere",
    scheme_designator="DCM"
)

MEASURING_RULER = CodedConcept(
    value="A-10141",
    meaning="Measuring Ruler",
    scheme_designator="SRT"
)

CATHETER = CodedConcept(
    value="A-26800",
    meaning="Catheter",
    scheme_designator="SRT"
)

