"""CID 6041 MammographyImageQualityFinding
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


VIEW_AND_LATERALITY_MARKER_IS_PARTIALLY_OBSCURED = CodedConcept(
    value="111182",
    meaning="View and Laterality Marker is partially obscured",
    scheme_designator="DCM"
)

VIEW_AND_LATERALITY_MARKER_IS_INCORRECT = CodedConcept(
    value="111183",
    meaning="View and Laterality Marker is incorrect",
    scheme_designator="DCM"
)

VIEW_AND_LATERALITY_MARKER_IS_OFF_IMAGE = CodedConcept(
    value="111184",
    meaning="View and Laterality Marker is off image",
    scheme_designator="DCM"
)

FLASH_IS_NOT_NEAR_EDGE_OF_FILM = CodedConcept(
    value="111185",
    meaning="Flash is not near edge of film",
    scheme_designator="DCM"
)

FLASH_IS_ILLEGIBLE_DOES_NOT_FIT_OR_IS_LOPSIDED = CodedConcept(
    value="111186",
    meaning="Flash is illegible, does not fit, or is lopsided",
    scheme_designator="DCM"
)

FLASH_DOESN_T_INCLUDE_PATIENT_NAME_AND_ADDITIONAL_PATIENT_ID = CodedConcept(
    value="111187",
    meaning="Flash doesn't include patient name and additional patient id",
    scheme_designator="DCM"
)

OTHER_FAILURE = CodedConcept(
    value="111220",
    meaning="Other failure",
    scheme_designator="DCM"
)

FLASH_DOESN_T_INCLUDE_DATE_OF_EXAMINATION = CodedConcept(
    value="111188",
    meaning="Flash doesn't include date of examination",
    scheme_designator="DCM"
)

UNKNOWN_FAILURE = CodedConcept(
    value="111221",
    meaning="Unknown failure",
    scheme_designator="DCM"
)

FLASH_DOESN_T_INCLUDE_FACILITY_NAME_AND_LOCATION = CodedConcept(
    value="111189",
    meaning="Flash doesn't include facility name and location",
    scheme_designator="DCM"
)

MLO_EVIDENCE_OF_MOTION_BLUR = CodedConcept(
    value="111200",
    meaning="MLO Evidence of motion blur",
    scheme_designator="DCM"
)

VIEW_AND_LATERALITY_MARKER_IS_NOT_NEAR_THE_AXILLA = CodedConcept(
    value="111180",
    meaning="View and Laterality Marker is not near the axilla",
    scheme_designator="DCM"
)

VIEW_AND_LATERALITY_MARKER_OVERLAPS_BREAST_TISSUE = CodedConcept(
    value="111181",
    meaning="View and Laterality Marker overlaps breast tissue",
    scheme_designator="DCM"
)

POSITIONING = CodedConcept(
    value="111209",
    meaning="Positioning",
    scheme_designator="DCM"
)

MLO_INFRAMAMMARY_FOLD_IS_NOT_OPEN = CodedConcept(
    value="111201",
    meaning="MLO Inframammary fold is not open",
    scheme_designator="DCM"
)

CC_NOT_ALL_MEDIAL_TISSUE_VISUALIZED = CodedConcept(
    value="111202",
    meaning="CC Not all medial tissue visualized",
    scheme_designator="DCM"
)

CC_NIPPLE_NOT_CENTERED_ON_IMAGE = CodedConcept(
    value="111203",
    meaning="CC Nipple not centered on image",
    scheme_designator="DCM"
)

CC_POSTERIOR_NIPPLE_LINE_DOES_NOT_MEASURE_WITHIN_1_CM_OF_MLO = CodedConcept(
    value="111204",
    meaning="CC Posterior nipple line does not measure within 1 cm of MLO",
    scheme_designator="DCM"
)

NIPPLE_NOT_IN_PROFILE = CodedConcept(
    value="111205",
    meaning="Nipple not in profile",
    scheme_designator="DCM"
)

INSUFFICIENT_IMPLANT_DISPLACEMENT_INCORRECT = CodedConcept(
    value="111206",
    meaning="Insufficient implant displacement incorrect",
    scheme_designator="DCM"
)

GRID_ARTIFACT_S_ = CodedConcept(
    value="111208",
    meaning="Grid artifact(s)",
    scheme_designator="DCM"
)

DATE_STICKER_IS_MISSING = CodedConcept(
    value="111193",
    meaning="Date sticker is missing",
    scheme_designator="DCM"
)

TECHNICAL_FACTORS_MISSING = CodedConcept(
    value="111194",
    meaning="Technical factors missing",
    scheme_designator="DCM"
)

COLLIMATION_TOO_CLOSE_TO_BREAST = CodedConcept(
    value="111195",
    meaning="Collimation too close to breast",
    scheme_designator="DCM"
)

INADEQUATE_COMPRESSION = CodedConcept(
    value="111196",
    meaning="Inadequate compression",
    scheme_designator="DCM"
)

MLO_INSUFFICIENT_PECTORAL_MUSCLE = CodedConcept(
    value="111197",
    meaning="MLO Insufficient pectoral muscle",
    scheme_designator="DCM"
)

MLO_NO_FAT_IS_VISUALIZED_POSTERIOR_TO_FIBROGLANDULAR_TISSUES = CodedConcept(
    value="111198",
    meaning="MLO No fat is visualized posterior to fibroglandular tissues",
    scheme_designator="DCM"
)

VIEW_AND_LATERALITY_MARKER_IS_MISSING = CodedConcept(
    value="111177",
    meaning="View and Laterality Marker is missing",
    scheme_designator="DCM"
)

MLO_POOR_SEPARATION_OF_DEEP_AND_SUPERFICIAL_BREAST_TISSUES = CodedConcept(
    value="111199",
    meaning="MLO Poor separation of deep and superficial breast tissues",
    scheme_designator="DCM"
)

MOTION_BLUR = CodedConcept(
    value="111210",
    meaning="Motion blur",
    scheme_designator="DCM"
)

VIEW_AND_LATERALITY_MARKER_DOES_NOT_HAVE_BOTH_VIEW_AND_LATERALITY = CodedConcept(
    value="111178",
    meaning="View and Laterality Marker does not have both view and laterality",
    scheme_designator="DCM"
)

UNDER_EXPOSED = CodedConcept(
    value="111211",
    meaning="Under exposed",
    scheme_designator="DCM"
)

FLASH_DOESN_T_INCLUDE_TECHNOLOGIST_IDENTIFICATION = CodedConcept(
    value="111190",
    meaning="Flash doesn't include technologist identification",
    scheme_designator="DCM"
)

FLASH_DOESN_T_INCLUDE_CASSETTE_SCREEN_DETECTOR_IDENTIFICATION = CodedConcept(
    value="111191",
    meaning="Flash doesn't include cassette/screen/detector identification",
    scheme_designator="DCM"
)

FLASH_DOESN_T_INCLUDE_MAMMOGRAPHY_UNIT_IDENTIFICATION = CodedConcept(
    value="111192",
    meaning="Flash doesn't include mammography unit identification",
    scheme_designator="DCM"
)

VIEW_AND_LATERALITY_MARKER_DOES_NOT_HAVE_APPROVED_CODES = CodedConcept(
    value="111179",
    meaning="View and Laterality Marker does not have approved codes",
    scheme_designator="DCM"
)

OVER_EXPOSED = CodedConcept(
    value="111212",
    meaning="Over exposed",
    scheme_designator="DCM"
)

NO_IMAGE = CodedConcept(
    value="111213",
    meaning="No image",
    scheme_designator="DCM"
)

DETECTOR_ARTIFACT_S_ = CodedConcept(
    value="111214",
    meaning="Detector artifact(s)",
    scheme_designator="DCM"
)

ARTIFACT_S_OTHER_THAN_GRID_OR_DETECTOR_ARTIFACT = CodedConcept(
    value="111215",
    meaning="Artifact(s) other than grid or detector artifact",
    scheme_designator="DCM"
)

MECHANICAL_FAILURE = CodedConcept(
    value="111216",
    meaning="Mechanical failure",
    scheme_designator="DCM"
)

ELECTRICAL_FAILURE = CodedConcept(
    value="111217",
    meaning="Electrical failure",
    scheme_designator="DCM"
)

SOFTWARE_FAILURE = CodedConcept(
    value="111218",
    meaning="Software failure",
    scheme_designator="DCM"
)

INAPPROPRIATE_IMAGE_PROCESSING = CodedConcept(
    value="111219",
    meaning="Inappropriate image processing",
    scheme_designator="DCM"
)

