"""CID 6124 LocationinChest
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


SUBPLEURAL = CodedConcept(
    value="112153",
    meaning="Subpleural",
    scheme_designator="DCM"
)

MIDDLE_LOBE_OF_LUNG = CodedConcept(
    value="T-28825",
    meaning="Middle lobe of lung",
    scheme_designator="SRT"
)

MIDDLE_ZONE_OF_LUNG = CodedConcept(
    value="T-D3209",
    meaning="Middle zone of lung",
    scheme_designator="SRT"
)

PERIPHERAL = CodedConcept(
    value="G-A111",
    meaning="Peripheral",
    scheme_designator="SRT"
)

APICAL = CodedConcept(
    value="G-A122",
    meaning="Apical",
    scheme_designator="SRT"
)

UPPER_ZONE_OF_LUNG = CodedConcept(
    value="T-D3208",
    meaning="Upper zone of lung",
    scheme_designator="SRT"
)

CENTRAL = CodedConcept(
    value="G-A110",
    meaning="Central",
    scheme_designator="SRT"
)

BASAL = CodedConcept(
    value="G-A123",
    meaning="Basal",
    scheme_designator="SRT"
)

ANTERIOR_SEGMENT_OF_RIGHT_UPPER_LOBE = CodedConcept(
    value="T-28230",
    meaning="Anterior segment of right upper lobe",
    scheme_designator="SRT"
)

POSTERIOR_SEGMENT_OF_RIGHT_UPPER_LOBE = CodedConcept(
    value="T-28220",
    meaning="Posterior segment of right upper lobe",
    scheme_designator="SRT"
)

ANTERIOR_SEGMENT_OF_LEFT_UPPER_LOBE = CodedConcept(
    value="T-28630",
    meaning="Anterior segment of left upper lobe",
    scheme_designator="SRT"
)

LOWER_LOBE_OF_LUNG = CodedConcept(
    value="T-28830",
    meaning="Lower lobe of lung",
    scheme_designator="SRT"
)

LOWER_ZONE_OF_LUNG = CodedConcept(
    value="T-D320A",
    meaning="Lower zone of lung",
    scheme_designator="SRT"
)

UPPER_LOBE_OF_LUNG = CodedConcept(
    value="T-28820",
    meaning="Upper lobe of lung",
    scheme_designator="SRT"
)

