"""CID 6057 DuctographyFindingsforBreast
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


DUCT_NARROWING = CodedConcept(
    value="111429",
    meaning="Duct narrowing",
    scheme_designator="DCM"
)

NORMAL_BREAST_TISSUE = CodedConcept(
    value="111287",
    meaning="Normal breast tissue",
    scheme_designator="DCM"
)

CYST_FILL = CodedConcept(
    value="111430",
    meaning="Cyst fill",
    scheme_designator="DCM"
)

INTRALUMINAL_FILLING_DEFECT = CodedConcept(
    value="111425",
    meaning="Intraluminal filling defect",
    scheme_designator="DCM"
)

MULTIPLE_FILLING_DEFECT = CodedConcept(
    value="111426",
    meaning="Multiple filling defect",
    scheme_designator="DCM"
)

ABRUPT_DUCT_TERMINATION = CodedConcept(
    value="111427",
    meaning="Abrupt duct termination",
    scheme_designator="DCM"
)

EXTRAVASATION = CodedConcept(
    value="111428",
    meaning="Extravasation",
    scheme_designator="DCM"
)

MAMMARY_DUCT_ECTASIA = CodedConcept(
    value="D7-90370",
    meaning="Mammary duct ectasia",
    scheme_designator="SRT"
)

