"""CID 8113 SpecimenPreparationSteps
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


SPECIMEN_STEAM_HEATING = CodedConcept(
    value="P3-40009",
    meaning="Specimen steam heating",
    scheme_designator="SRT"
)

SPECIMEN_FREEZING = CodedConcept(
    value="P3-05050",
    meaning="Specimen freezing",
    scheme_designator="SRT"
)

SPECIMEN_CLEARING = CodedConcept(
    value="P3-40003",
    meaning="Specimen clearing",
    scheme_designator="SRT"
)

SPECIMEN_DEHYDRATION = CodedConcept(
    value="P3-4000B",
    meaning="Specimen dehydration",
    scheme_designator="SRT"
)

SPECIMEN_MICROWAVE_HEATING = CodedConcept(
    value="P3-40005",
    meaning="Specimen microwave heating",
    scheme_designator="SRT"
)

PROTEASE_DIGESTION_OF_TISSUE_SPECIMEN = CodedConcept(
    value="P3-40006",
    meaning="Protease digestion of tissue specimen",
    scheme_designator="SRT"
)

