"""CID 3743 Clopidogrel/TiclopidineAdministration
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


ADMINISTERED_LESS_THAN_72_HOURS_BEFORE_PCI = CodedConcept(
    value="R-0031E",
    meaning="Administered Less than 72 Hours before PCI",
    scheme_designator="SRT"
)

ADMINISTERED_AFTER_PERCUTANEOUS_CORONARY_INTERVENTION = CodedConcept(
    value="R-00399",
    meaning="Administered After Percutaneous Coronary Intervention",
    scheme_designator="SRT"
)

CONTRAINDICATED = CodedConcept(
    value="R-00321",
    meaning="Contraindicated",
    scheme_designator="SRT"
)

NOT_ADMINISTERED = CodedConcept(
    value="R-00320",
    meaning="Not Administered",
    scheme_designator="SRT"
)

