"""CID 4019 PrimaryAnatomicStructureforIntraoralRadiography(DeciduousDentitionDesignationofTeeth)
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


DECIDUOUS_MAXILLARY_RIGHT_CENTRAL_INCISOR_TOOTH = CodedConcept(
    value="T-54610",
    meaning="Deciduous maxillary right central incisor tooth",
    scheme_designator="SRT"
)

DECIDUOUS_MANDIBULAR_RIGHT_LATERAL_INCISOR_TOOTH = CodedConcept(
    value="T-54720",
    meaning="Deciduous mandibular right lateral incisor tooth",
    scheme_designator="SRT"
)

DECIDUOUS_MANDIBULAR_RIGHT_CENTRAL_INCISOR_TOOTH = CodedConcept(
    value="T-54710",
    meaning="Deciduous mandibular right central incisor tooth",
    scheme_designator="SRT"
)

DECIDUOUS_MAXILLARY_RIGHT_CANINE_TOOTH = CodedConcept(
    value="T-54630",
    meaning="Deciduous maxillary right canine tooth",
    scheme_designator="SRT"
)

DECIDUOUS_MANDIBULAR_RIGHT_FIRST_MOLAR_TOOTH = CodedConcept(
    value="T-54740",
    meaning="Deciduous mandibular right first molar tooth",
    scheme_designator="SRT"
)

DECIDUOUS_MAXILLARY_RIGHT_LATERAL_INCISOR_TOOTH = CodedConcept(
    value="T-54620",
    meaning="Deciduous maxillary right lateral incisor tooth",
    scheme_designator="SRT"
)

DECIDUOUS_MANDIBULAR_RIGHT_CANINE_TOOTH = CodedConcept(
    value="T-54730",
    meaning="Deciduous mandibular right canine tooth",
    scheme_designator="SRT"
)

DECIDUOUS_MAXILLARY_LEFT_SECOND_MOLAR_TOOTH = CodedConcept(
    value="T-54700",
    meaning="Deciduous maxillary left second molar tooth",
    scheme_designator="SRT"
)

DECIDUOUS_MANDIBULAR_LEFT_SECOND_MOLAR_TOOTH = CodedConcept(
    value="T-54800",
    meaning="Deciduous mandibular left second molar tooth",
    scheme_designator="SRT"
)

DECIDUOUS_MAXILLARY_LEFT_FIRST_MOLAR_TOOTH = CodedConcept(
    value="T-54690",
    meaning="Deciduous maxillary left first molar tooth",
    scheme_designator="SRT"
)

DECIDUOUS_MAXILLARY_LEFT_CANINE_TOOTH = CodedConcept(
    value="T-54680",
    meaning="Deciduous maxillary left canine tooth",
    scheme_designator="SRT"
)

DECIDUOUS_MANDIBULAR_LEFT_FIRST_MOLAR_TOOTH = CodedConcept(
    value="T-54790",
    meaning="Deciduous mandibular left first molar tooth",
    scheme_designator="SRT"
)

DECIDUOUS_MAXILLARY_RIGHT_SECOND_MOLAR_TOOTH = CodedConcept(
    value="T-54650",
    meaning="Deciduous maxillary right second molar tooth",
    scheme_designator="SRT"
)

DECIDUOUS_MANDIBULAR_LEFT_CENTRAL_INCISOR_TOOTH = CodedConcept(
    value="T-54760",
    meaning="Deciduous mandibular left central incisor tooth",
    scheme_designator="SRT"
)

DECIDUOUS_MAXILLARY_RIGHT_FIRST_MOLAR_TOOTH = CodedConcept(
    value="T-54640",
    meaning="Deciduous maxillary right first molar tooth",
    scheme_designator="SRT"
)

DECIDUOUS_MANDIBULAR_RIGHT_SECOND_MOLAR_TOOTH = CodedConcept(
    value="T-54750",
    meaning="Deciduous mandibular right second molar tooth",
    scheme_designator="SRT"
)

DECIDUOUS_MAXILLARY_LEFT_LATERAL_INCISOR_TOOTH = CodedConcept(
    value="T-54670",
    meaning="Deciduous maxillary left lateral incisor tooth",
    scheme_designator="SRT"
)

DECIDUOUS_MANDIBULAR_LEFT_CANINE_TOOTH = CodedConcept(
    value="T-54780",
    meaning="Deciduous mandibular left canine tooth",
    scheme_designator="SRT"
)

DECIDUOUS_MAXILLARY_LEFT_CENTRAL_INCISOR_TOOTH = CodedConcept(
    value="T-54660",
    meaning="Deciduous maxillary left central incisor tooth",
    scheme_designator="SRT"
)

DECIDUOUS_MANDIBULAR_LEFT_LATERAL_INCISOR_TOOTH = CodedConcept(
    value="T-54770",
    meaning="Deciduous mandibular left lateral incisor tooth",
    scheme_designator="SRT"
)

