"""CID 65 PreMedicationforImagingAgentAdministration
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


REMIFENTANIL = CodedConcept(
    value="386839004",
    meaning="Remifentanil",
    scheme_designator="SCT"
)

SUFENTANIL = CodedConcept(
    value="49998007",
    meaning="Sufentanil",
    scheme_designator="SCT"
)

PREDNISONE = CodedConcept(
    value="C-37138",
    meaning="Prednisone",
    scheme_designator="SRT"
)

METHYLPREDNISOLONE = CodedConcept(
    value="C-37128",
    meaning="Methylprednisolone",
    scheme_designator="SRT"
)

EPHEDRINE = CodedConcept(
    value="C-68050",
    meaning="Ephedrine",
    scheme_designator="SRT"
)

METHYLPREDNISOLONE_SODIUM_SUCCINATE = CodedConcept(
    value="C-A01D1",
    meaning="Methylprednisolone sodium succinate",
    scheme_designator="SRT"
)

DIPHENHYDRAMINE = CodedConcept(
    value="C-51450",
    meaning="Diphenhydramine",
    scheme_designator="SRT"
)

PAPAVERINE = CodedConcept(
    value="R-F2989",
    meaning="Papaverine",
    scheme_designator="SRT"
)

MIDAZOLAM = CodedConcept(
    value="F-6183C",
    meaning="Midazolam",
    scheme_designator="SRT"
)

PROPOFOL = CodedConcept(
    value="F-61B48",
    meaning="Propofol",
    scheme_designator="SRT"
)

H1_ANTIHISTAMINE = CodedConcept(
    value="C-51071",
    meaning="H-1 Antihistamine",
    scheme_designator="SRT"
)

ALFENTANIL = CodedConcept(
    value="F-61C65",
    meaning="Alfentanil",
    scheme_designator="SRT"
)

HYDROCORTISONE_SODIUM_SUCCINATE = CodedConcept(
    value="C-A0173",
    meaning="Hydrocortisone sodium succinate",
    scheme_designator="SRT"
)

DEXAMETHASONE_SODIUM_SULFATE = CodedConcept(
    value="C-913A4",
    meaning="Dexamethasone sodium sulfate",
    scheme_designator="SRT"
)

