"""CID 1004 AnatomicalReferenceBasisChest
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


CORONARY_ARTERY_GRAFT = CodedConcept(
    value="T-41065",
    meaning="Coronary artery graft",
    scheme_designator="SRT"
)

SCAPULA = CodedConcept(
    value="T-12280",
    meaning="Scapula",
    scheme_designator="SRT"
)

ACROMIOCLAVICULAR_JOINT = CodedConcept(
    value="T-15420",
    meaning="Acromioclavicular Joint",
    scheme_designator="SRT"
)

APEX_OF_HEART = CodedConcept(
    value="T-32004",
    meaning="Apex of heart",
    scheme_designator="SRT"
)

DIAPHRAGM = CodedConcept(
    value="T-D3400",
    meaning="Diaphragm",
    scheme_designator="SRT"
)

STERNUM = CodedConcept(
    value="T-11210",
    meaning="Sternum",
    scheme_designator="SRT"
)

STERNOCLAVICULAR_JOINT = CodedConcept(
    value="T-15610",
    meaning="Sternoclavicular Joint",
    scheme_designator="SRT"
)

HEART = CodedConcept(
    value="T-32000",
    meaning="Heart",
    scheme_designator="SRT"
)

SHOULDER_REGION_STRUCTURE = CodedConcept(
    value="T-D2220",
    meaning="Shoulder region structure",
    scheme_designator="SRT"
)

XIPHOID_PROCESS = CodedConcept(
    value="T-11227",
    meaning="Xiphoid Process",
    scheme_designator="SRT"
)

THORACIC_INLET = CodedConcept(
    value="T-D3160",
    meaning="Thoracic Inlet",
    scheme_designator="SRT"
)

SUPRASTERNAL_NOTCH = CodedConcept(
    value="T-11218",
    meaning="Suprasternal Notch",
    scheme_designator="SRT"
)

LUNG = CodedConcept(
    value="T-28000",
    meaning="Lung",
    scheme_designator="SRT"
)

AORTIC_ARCH = CodedConcept(
    value="T-42300",
    meaning="Aortic Arch",
    scheme_designator="SRT"
)

CARINA = CodedConcept(
    value="T-25201",
    meaning="Carina",
    scheme_designator="SRT"
)

