"""CID 3663 BodySurfaceAreaEquations
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


BSA_0_038189_WT_0_423_HT_0_362 = CodedConcept(
    value="122269",
    meaning="BSA = 0.038189*WT^ 0.423*HT^0.362",
    scheme_designator="DCM"
)

BSA_1321_0_3433_WT = CodedConcept(
    value="122245",
    meaning="BSA = 1321+0.3433*WT",
    scheme_designator="DCM"
)

BSA_0_010265_WT_0_423_HT_0_651 = CodedConcept(
    value="122267",
    meaning="BSA = 0.010265*WT^ 0.423*HT^0.651",
    scheme_designator="DCM"
)

BSA_0_0004688_WT_0_81680_0154_LOG_WT_ = CodedConcept(
    value="122246",
    meaning="BSA = 0.0004688*WT^(0.8168-0.0154*log(WT))",
    scheme_designator="DCM"
)

BSA_0_008883_WT_0_444_HT_0_663 = CodedConcept(
    value="122268",
    meaning="BSA = 0.008883*WT^ 0.444*HT^0.663",
    scheme_designator="DCM"
)

BSA_0_024265_WT_0_5378_HTCM_0_3964 = CodedConcept(
    value="122243",
    meaning="BSA = 0.024265*WT^0.5378*HTcm^0.3964",
    scheme_designator="DCM"
)

BSA_HT_WT_36_0_5 = CodedConcept(
    value="122244",
    meaning="BSA = (HT * WT/36) ^0.5",
    scheme_designator="DCM"
)

BSA_0_007358_WT_0_425_HT_0_725 = CodedConcept(
    value="122266",
    meaning="BSA = 0.007358*WT^ 0.425*HT^0.725",
    scheme_designator="DCM"
)

BSA_0_007184_WT_0_425_HT_0_725 = CodedConcept(
    value="122241",
    meaning="BSA = 0.007184*WT^ 0.425*HT^0.725",
    scheme_designator="DCM"
)

BSA_0_0235_WT_0_51456_HTCM_0_42246 = CodedConcept(
    value="122242",
    meaning="BSA = 0.0235*WT^0.51456*HTcm^ 0.42246",
    scheme_designator="DCM"
)

BSA_0_003207_WT_0_72850_0188_LOG_WT_HT_0_3 = CodedConcept(
    value="122240",
    meaning="BSA = 0.003207*WT^(0.7285-0.0188 log (WT)) *HT^0.3",
    scheme_designator="DCM"
)

BSA_0_009568_WT_0_473_HT_0_655 = CodedConcept(
    value="122270",
    meaning="BSA = 0.009568*WT^ 0.473*HT^0.655",
    scheme_designator="DCM"
)

