"""CID 6112 PleuraAnatomyFindingorFeature
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


ANTERIOR_JUNCTION_LINE = CodedConcept(
    value="112088",
    meaning="Anterior junction line",
    scheme_designator="DCM"
)

POSTERIOR_JUNCTION_LINE = CodedConcept(
    value="112089",
    meaning="Posterior junction line",
    scheme_designator="DCM"
)

FISSURE_OF_LUNG = CodedConcept(
    value="T-D051D",
    meaning="Fissure of lung",
    scheme_designator="SRT"
)

