"""CID 6154 EchoPattern
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


ANECHOIC = CodedConcept(
    value="111361",
    meaning="Anechoic",
    scheme_designator="DCM"
)

HYPERECHOIC = CodedConcept(
    value="111362",
    meaning="Hyperechoic",
    scheme_designator="DCM"
)

COMPLEX = CodedConcept(
    value="111363",
    meaning="Complex",
    scheme_designator="DCM"
)

HYPOECHOIC = CodedConcept(
    value="111364",
    meaning="Hypoechoic",
    scheme_designator="DCM"
)

ISOECHOIC = CodedConcept(
    value="111365",
    meaning="Isoechoic",
    scheme_designator="DCM"
)

