"""CID 7273 MRDiffusionModels
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


MONOEXPONENTIAL_DIFFUSION_MODEL = CodedConcept(
    value="113250",
    meaning="Mono-exponential diffusion model",
    scheme_designator="DCM"
)

BIEXPONENTIAL_IVIM_DIFFUSION_MODEL = CodedConcept(
    value="113251",
    meaning="Bi-exponential (IVIM) diffusion model",
    scheme_designator="DCM"
)

KURTOSIS_DIFFUSION_MODEL = CodedConcept(
    value="113252",
    meaning="Kurtosis diffusion model",
    scheme_designator="DCM"
)

GAMMA_DISTRIBUTION_MODEL = CodedConcept(
    value="113253",
    meaning="Gamma distribution model",
    scheme_designator="DCM"
)

STRETCHED_EXPONENTIAL_DIFFUSION_MODEL = CodedConcept(
    value="113254",
    meaning="Stretched exponential diffusion model",
    scheme_designator="DCM"
)

TRUNCATED_GAUSSIAN_DIFFUSION_MODEL = CodedConcept(
    value="113255",
    meaning="Truncated Gaussian diffusion model",
    scheme_designator="DCM"
)

