"""CID 8104 BreastTissueSpecimenTypes
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


SPECIMEN_FROM_BREAST_OBTAINED_BY_CORE_NEEDLE_BIOPSY = CodedConcept(
    value="G-8318",
    meaning="specimen from breast obtained by core needle biopsy",
    scheme_designator="SRT"
)

FROZEN_SECTION_BREAST_SAMPLE = CodedConcept(
    value="G-8339",
    meaning="frozen section breast sample",
    scheme_designator="SRT"
)

SPECIMEN_FROM_BREAST_STEREOTACTICALLY_GUIDED_CORE_NEEDLE_BIOPSY = CodedConcept(
    value="G-8319",
    meaning="specimen from breast, stereotactically guided core needle biopsy",
    scheme_designator="SRT"
)

SEGMENTECTOMY_BREAST_SAMPLE = CodedConcept(
    value="G-833F",
    meaning="segmentectomy breast sample",
    scheme_designator="SRT"
)

BREAST_DUCT_SAMPLE = CodedConcept(
    value="G-8346",
    meaning="breast duct sample",
    scheme_designator="SRT"
)

BREAST_TRUCUT_BIOPSY_SAMPLE = CodedConcept(
    value="G-832D",
    meaning="breast tru-cut biopsy sample",
    scheme_designator="SRT"
)

SPECIMEN_FROM_BREAST_OBTAINED_BY_EXCISION = CodedConcept(
    value="G-8430",
    meaning="specimen from breast obtained by excision",
    scheme_designator="SRT"
)

LUMPECTOMY_BREAST_SAMPLE = CodedConcept(
    value="G-833D",
    meaning="lumpectomy breast sample",
    scheme_designator="SRT"
)

SPECIMEN_FROM_BREAST_BY_INCISIONAL_BIOPSY_OF_BREAST_MASS = CodedConcept(
    value="G-831B",
    meaning="specimen from breast by incisional biopsy of breast mass",
    scheme_designator="SRT"
)

SPECIMEN_FROM_BREAST_OBTAINED_BY_IMAGE_GUIDED_CORE_BIOPSY = CodedConcept(
    value="R-003AC",
    meaning="specimen from breast obtained by image guided core biopsy",
    scheme_designator="SRT"
)

SPECIMEN_FROM_BREAST_OBTAINED_BY_TOTAL_MASTECTOMY = CodedConcept(
    value="G-8311",
    meaning="specimen from breast obtained by total mastectomy",
    scheme_designator="SRT"
)

