"""CID 12250 CardiacUltrasoundCommonLinearMeasurements
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


ROI_INTERNAL_DIMENSION_BY_US = CodedConcept(
    value="59090-1",
    meaning="ROI Internal Dimension by US",
    scheme_designator="LN"
)

ROI_THICKNESS_BY_US = CodedConcept(
    value="59089-3",
    meaning="ROI Thickness by US",
    scheme_designator="LN"
)

DIAMETER = CodedConcept(
    value="M-02550",
    meaning="Diameter",
    scheme_designator="SRT"
)

MAJOR_AXIS = CodedConcept(
    value="G-A193",
    meaning="Major Axis",
    scheme_designator="SRT"
)

CIRCUMFERENCE = CodedConcept(
    value="M-02560",
    meaning="Circumference",
    scheme_designator="SRT"
)

MINOR_AXIS = CodedConcept(
    value="G-A194",
    meaning="Minor Axis",
    scheme_designator="SRT"
)

RADIUS = CodedConcept(
    value="G-A196",
    meaning="Radius",
    scheme_designator="SRT"
)

LENGTH = CodedConcept(
    value="G-D7FE",
    meaning="Length",
    scheme_designator="SRT"
)

