"""CID 7184 AbstractMultidimensionalImageModelAxisDirection
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


SEPTUMWALL_AXIS = CodedConcept(
    value="110865",
    meaning="Septum-Wall Axis",
    scheme_designator="DCM"
)

ANTERIORINFERIOR_AXIS = CodedConcept(
    value="110864",
    meaning="Anterior-Inferior Axis",
    scheme_designator="DCM"
)

APEXBASE_AXIS = CodedConcept(
    value="110863",
    meaning="Apex-Base Axis",
    scheme_designator="DCM"
)

ANTERIORPOSTERIOR_AXIS = CodedConcept(
    value="110862",
    meaning="Anterior-Posterior Axis",
    scheme_designator="DCM"
)

HEADFOOT_AXIS = CodedConcept(
    value="110861",
    meaning="Head-Foot Axis",
    scheme_designator="DCM"
)

LEFTRIGHT_AXIS = CodedConcept(
    value="110860",
    meaning="Left-Right Axis",
    scheme_designator="DCM"
)

