"""CID 10031 CR/DRMechanicalConfiguration
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


TABLE_MOUNT = CodedConcept(
    value="113952",
    meaning="Table Mount",
    scheme_designator="DCM"
)

UPRIGHT_STAND_MOUNT = CodedConcept(
    value="113954",
    meaning="Upright Stand Mount",
    scheme_designator="DCM"
)

UNMOUNTED_DETECTOR = CodedConcept(
    value="113953",
    meaning="Unmounted Detector",
    scheme_designator="DCM"
)

CARM_MOUNT = CodedConcept(
    value="113955",
    meaning="C-Arm Mount",
    scheme_designator="DCM"
)

