"""CID 4210 OphthalmicTomographyAcquisitionDevice
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


REFLECTIONBASED_CORNEAL_TOPOGRAPHER = CodedConcept(
    value="111946",
    meaning="Reflection-based corneal topographer",
    scheme_designator="DCM"
)

INTERFEROMETRYBASED_CORNEAL_TOMOGRAPHER = CodedConcept(
    value="111947",
    meaning="Interferometry-based corneal tomographer",
    scheme_designator="DCM"
)

SCHEIMPFLUG_CAMERA = CodedConcept(
    value="111626",
    meaning="Scheimpflug Camera",
    scheme_designator="DCM"
)

ELEVATIONBASED_CORNEAL_TOMOGRAPHER = CodedConcept(
    value="111945",
    meaning="Elevation-based corneal tomographer",
    scheme_designator="DCM"
)

SCANNING_LASER_POLARIMETER = CodedConcept(
    value="A-00E8C",
    meaning="Scanning Laser Polarimeter",
    scheme_designator="SRT"
)

CONFOCAL_SCANNING_LASER_OPHTHALMOSCOPE = CodedConcept(
    value="A-00E8B",
    meaning="Confocal Scanning Laser Ophthalmoscope",
    scheme_designator="SRT"
)

OPTICAL_COHERENCE_TOMOGRAPHY_SCANNER = CodedConcept(
    value="A-00FBE",
    meaning="Optical Coherence Tomography Scanner",
    scheme_designator="SRT"
)

RETINAL_THICKNESS_ANALYZER = CodedConcept(
    value="R-FAB5A",
    meaning="Retinal Thickness Analyzer",
    scheme_designator="SRT"
)

