"""CID 4204 OphthalmicFilter
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


NO_FILTER = CodedConcept(
    value="111609",
    meaning="No filter",
    scheme_designator="DCM"
)

RED_OPTICAL_FILTER = CodedConcept(
    value="A-010DF",
    meaning="Red optical filter",
    scheme_designator="SRT"
)

BLUEGREEN_OPTICAL_FILTER = CodedConcept(
    value="A-010D8",
    meaning="Blue-green optical filter",
    scheme_designator="SRT"
)

YELLOWGREEN_OPTICAL_FILTER = CodedConcept(
    value="A-010E0",
    meaning="Yellow-green optical filter",
    scheme_designator="SRT"
)

INFRARED_OPTICAL_FILTER = CodedConcept(
    value="A-010DC",
    meaning="Infrared optical filter",
    scheme_designator="SRT"
)

GREEN_OPTICAL_FILTER = CodedConcept(
    value="A-010E2",
    meaning="Green optical filter",
    scheme_designator="SRT"
)

BLUE_OPTICAL_FILTER = CodedConcept(
    value="A-010DA",
    meaning="Blue optical filter",
    scheme_designator="SRT"
)

POLARIZING_OPTICAL_FILTER = CodedConcept(
    value="A-010E1",
    meaning="Polarizing optical filter",
    scheme_designator="SRT"
)

