"""CID 3642 DegreeFindings
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


DECREASED = CodedConcept(
    value="G-A316",
    meaning="Decreased",
    scheme_designator="SRT"
)

SEVERELY_ELEVATED = CodedConcept(
    value="G-A37A",
    meaning="Severely Elevated",
    scheme_designator="SRT"
)

ELEVATED = CodedConcept(
    value="G-A373",
    meaning="Elevated",
    scheme_designator="SRT"
)

NORMAL_RANGE = CodedConcept(
    value="R-40765",
    meaning="Normal Range",
    scheme_designator="SRT"
)

