"""CID 8110 SpecimenSamplingProcedure
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


DISSECTION_WITH_ENTIRE_SPECIMEN_SUBMISSION = CodedConcept(
    value="111726",
    meaning="Dissection with entire specimen submission",
    scheme_designator="DCM"
)

DISSECTION_WITH_REPRESENTATIVE_SECTIONS_SUBMISSION = CodedConcept(
    value="111727",
    meaning="Dissection with representative sections submission",
    scheme_designator="DCM"
)

SMEAR_PROCEDURE = CodedConcept(
    value="P1-0329D",
    meaning="Smear procedure",
    scheme_designator="SRT"
)

CORE_SAMPLING = CodedConcept(
    value="P3-40011",
    meaning="Core sampling",
    scheme_designator="SRT"
)

TOUCH_PREPARATION_PROCEDURE_ = CodedConcept(
    value="P3-4500A",
    meaning="Touch preparation (procedure)",
    scheme_designator="SRT"
)

BLOCK_SECTIONING = CodedConcept(
    value="P3-4000D",
    meaning="Block sectioning",
    scheme_designator="SRT"
)

LASER_MICRODISSECTION = CodedConcept(
    value="P3-40004",
    meaning="Laser microdissection",
    scheme_designator="SRT"
)

DISSECTION = CodedConcept(
    value="P1-01003",
    meaning="Dissection",
    scheme_designator="SRT"
)

BLOCK_SURFACE_RECUT = CodedConcept(
    value="P3-4000E",
    meaning="Block surface recut",
    scheme_designator="SRT"
)

BLOCK_STEP_SECTIONING = CodedConcept(
    value="P3-4000F",
    meaning="Block step sectioning",
    scheme_designator="SRT"
)

