"""CID 3762 AntiarrhythmicAgents
auto-generated by generate_context_groups.py.
"""
from pydicom.sr.value_types import CodedConcept


CLASS_IV_ANTIARRHYTHMIC_AGENT = CodedConcept(
    value="F-618AE",
    meaning="class IV antiarrhythmic agent",
    scheme_designator="SRT"
)

CLASS_I_ANTIARRHYTHMIC_AGENT = CodedConcept(
    value="F-6181B",
    meaning="class I antiarrhythmic agent",
    scheme_designator="SRT"
)

CLASS_III_ANTIARRHYTHMIC_AGENT = CodedConcept(
    value="F-61995",
    meaning="class III antiarrhythmic agent",
    scheme_designator="SRT"
)

CLASS_II_ANTIARRHYTHMIC_AGENT = CodedConcept(
    value="F-61861",
    meaning="class II antiarrhythmic agent",
    scheme_designator="SRT"
)

